### ISSUE TITLE
How to build a windows x86 or linux arm version 

### ISSUE THREAD

**Issue by koolwiki** [klzgrad/naiveproxy#10]
Hi, could you please tell me how to build a windows x86 or linux arm version? Many thanks!

**Comment by klzgrad** [comment]
To wit: how to build Chrome for win32 and or linux arm. I'll start from here https://www.chromium.org/developers/gn-build-configuration#TOC-Overriding-the-CPU-architecture

The flag can be added in here https://github.com/klzgrad/naiveproxy/blob/master/src/build.sh:  `target_cpu="x86"` or `"arm"` or something. I don't know. Haven't tested it myself. Can try it sometime.

But why? I can see why one would want an ARM binary but why x86?

Another problem is Travis and Appveyor et al don't support ARM natively, so it'd be harder to create autobuild recipes.

**Comment by koolwiki** [comment]
Thank you for your prompt reply. I will try to build one. Because one of my computer's OS is win32, so I want a x86 one.

**Comment by koolwiki** [comment]
Another question is that does naive support websocket or CDN? If not, only one or two IP from China connect to the server every day for a long time is abnormal for a web server. It is resonable to suspect it is a proxy server. So the GFW may block the IP of the server.

**Comment by klzgrad** [comment]
Websocket is obsolete. Websocket is basically a worse HTTP/2, a hack piled on top of http1. Just don't do it.

CDNs should be agnostic to the endpoints as long as they use standard protocols. But I don't think CDN proxying is a good idea in general. They are not designed for this type of traffic - they are optimized for 1:N upstream access to user access ratio so a proxy with 1:1 traffic pattern will cost them and they won't like it. It also slows down your traffic. As long as your own servers are online it's not necessary to go through a middleman.

As to the possibility of traffic aggregate analysis as you described, it doesn't really happen, does it? It's all too easy to direct additional traffic to your proxy servers. And it's too hard to decide to block a website on the sole criterion of having access from a single ip without much collateral damage, no?

**Comment by koolwiki** [comment]
Thank you for your explanation. Maybe you are right.

**Comment by klzgrad** [comment]
I built a x86 version: https://ci.appveyor.com/api/buildjobs/6wiio6m2w610okmf/artifacts/naiveproxy--win-x86.zip

See if it works for you.

**Comment by koolwiki** [comment]
It works! Thank you! I have an other question. Can I just use the official caddy excutable file on server but not build it per wiki "https://github.com/klzgrad/naiveproxy/wiki/Server-Setup"?

**Comment by klzgrad** [comment]
You can. The linked wiki is about building Caddy with QUIC support.

**Comment by klzgrad** [comment]
Win32 build is officially supported. If you need Linux ARM somehow let's discuss it next time.

**Comment by koolwiki** [comment]
Thank you very much! I test it today, the speed is very fast.

**Comment by koolwiki** [comment]
It will be wonderful if there is a linux ARM version, so that I can use it on my android phone.
