### ISSUE TITLE
出现了一些ERROR，这是什么原因？

### ISSUE THREAD

**Issue by ysbreh** [klzgrad/naiveproxy#100]
运行时会如果出现如下类似错误，然后速度和稳定性会极速下降很多，是什么原因呢，配置文件有问题吗
...
2020/07/19 08:52:30.194 **ERROR**   http.log.error  http2: stream closed    {"request": {"method": "CONNECT", "uri": "ipv4-c655-sjc002-dev-ix.1.oca.nflxvideo.net:443", "proto": "HTTP/2.0", "remote_addr": "本地ip:34370", "host": "ipv4-c655-sjc002-dev-ix.1.oca.nflxvideo.net:443", "headers": {"Proxy-Authorization": ["Basic =="], "Padding": ["###?'<$*(>;\"*$((XX"]}, "tls": {"resumed": false, "version": 772, "ciphersuite": 4865, "proto": "h2", "proto_mutual": true, "server_name": "域名.com"}}, "duration": 20.4906085}
2020/07/19 08:52:30.195 **ERROR**   http.log.error  http2: stream closed    {"request": {"method": "CONNECT", "uri": "ipv4-c007-lax009-ix.1.oca.nflxvideo.net:443", "proto": "HTTP/2.0", "remote_addr": "本地ip:34370", "host": "ipv4-c007-lax009-ix.1.oca.nflxvideo.net:443", "headers": {"Padding": [")'!*#>#\"!;+?+;;'XXXXXXXXXXXXX"], "Proxy-Authorization": ["Basic =="]}, "tls": {"resumed": false, "version": 772, "ciphersuite": 4865, "proto": "h2", "proto_mutual": true, "server_name": "域名.com"}}, "duration": 14.667224533}
...

**Comment by klzgrad** [comment]
出现错误以后再speedtest.net慢不慢

**Comment by ysbreh** [comment]
> 出现错误以后再speedtest.net慢不慢

之前使用fast.com测速的，前后几次会差距很大。
Speedtest.net测速时会出现ERROR
YouTube会从6Wkbps左右掉到几千甚至没速度，网页也会打开缓慢，但过一会儿会慢慢恢复。
速度不一定与出现ERROR有关，不排除服务器网络不稳定也有一定的原因。
