### ISSUE TITLE
Could you please explain what dose "Padding support is now automatically detected" mean?

### ISSUE THREAD

**Issue by koolwiki** [klzgrad/naiveproxy#102]
Could you please explain what dose "Padding support is now automatically detected" mean? Detect what? Thank you.

**Comment by klzgrad** [comment]
Padding support is now automatically detected by naiveproxy. Detect padding support.

**Comment by koolwiki** [comment]
Is that means padding will be enabled by the forwardproxy server automatically with out any command?

**Comment by klzgrad** [comment]
right
