### ISSUE TITLE
Caddy v2 with naïve fork of forwardproxy 不能访问目标区网

### ISSUE THREAD

**Issue by kousyougi** [klzgrad/naiveproxy#103]
我Server在内网的IP是192.168.0.3，外网路由器开443让Naiveproxy进来。
之前Server端用Caddy 1.04的组合，通过Naiveproxy的socks通道，可以访问Server包括192.168.0.0/24的其他IP。
更新到Caddy v2的组合之后，只要是192.168.0.0/24的设备都通不了。
这个问题有解吗？

谢谢

**Comment by kousyougi** [comment]
刚刚查了forwardproxy的资料，
实在不知道要怎么加 acl allow all 的设定进json里面。
就把forwardproxy/forwardproxy.go里面的192.168.0.0/16这行删除。
误打误撞，重新编译后，目前似乎可以用。

**Comment by klzgrad** [comment]
我看了forwardproxy代码，大概是
```
"handler": "forward_proxy",
...
acl: {
  [{
    subjects: ["192.168.0.0/16"],
    allow: true
  }]
}
```

**Comment by NetHeritage** [comment]
怎么把forwardproxy的配置加进2.x版caddy的caddyfile呢

**Comment by klzgrad** [comment]
Caddy 2的做法是需要有一个模块把Caddyfile翻译成json，这个模块因为forwardproxy的主要功能还未迁移到Caddy 2所以没有实现，所以现在只能用json。
