### ISSUE TITLE
客户端 net.ipv4.tcp_fastopen = 0 时无法连线

### ISSUE THREAD

**Issue by kousyougi** [klzgrad/naiveproxy#104]
伺服器端目前的设定是 net.ipv4.tcp_fastopen = 0。
目前客户端是 net.ipv4.tcp_fastopen = 1 可以连。
如果把客户端设定也改成 net.ipv4.tcp_fastopen = 0 时，naiveproxy会无法连线。

两端都是openwrt 19.07.3 x86-64

这个反应有点奇怪，正常吗？

**Comment by klzgrad** [comment]
https://github.com/klzgrad/naiveproxy/wiki/Parameter-Tuning 说的是不要打开TCP Fast Open。

这个无法连线跟naiveproxy没有什么关系，是更底层的事情
