### ISSUE TITLE
可不可以新增多节点自动切换模式

### ISSUE THREAD

**Issue by kousyougi** [klzgrad/naiveproxy#105]
可不可以新增多节点自动切换模式

策略希望可以设定：
1. 断线后切换下一个节点
2. 时间段内自动切换下一个节点：例如一个节点使用20分到30分间切换
3. 使用量达到一定范围切换下一个节点：例如一个节点使用到200M跟300M间随机切换。

时间段跟使用量希望可以设定上下范围内随机，指定值怕特征太明显。

这是最近手动抗gfw的心得，有可能可以防封锁。之后ipv6越普及，使用者很容易有很多ip可以利用。

**Comment by klzgrad** [comment]
你之前用haproxy https://github.com/klzgrad/naiveproxy/issues/61，我觉得用法挺好啊？重新实现一遍haproxy意义不大

**Comment by kousyougi** [comment]
之前那个haproxy目前用起来没什么问题。但health check一直送测试包出去，证书又都用同一个网域的证书。
如果要仔细抓这种配置的话，这个配置还蛮明显的。

然后又因为haproxy是连不上后被动切换，会有一段时间连不上卡住。如果是naiveproxy这端在被截流前先切换到别的节点，可以避免被截流时卡住的问题。

**Comment by dan2darren** [comment]
术业有专攻,不赞成naive实现自动切换.

推荐使用[balance](https://balance.inlab.net/),以robin round方式自动切换下一个upstream server,使用非常简单

还想要更多功能可以围绕balance写脚本即可

btw,感谢 @klzgrad 写的naiveproxy!

**Comment by klzgrad** [comment]
“在被截流前”这个要怎么判定呢？不好判定

这个功能是很罕见又很难做对的一个东西

**Comment by kousyougi** [comment]
我自己的经验是用一两个小时节点会死三到五分钟。不固定，跟传输量也有关，传输量大时死的比较快。

naiveproxy的目标是伪装成大众化的上网流量。如果a网站连个5到10分钟、b网站连10到20分钟、c网站又连3到5分钟，随机轮来轮去。这样随机切换会比目前naive+haproxy更像普通的上网流量。

突然想到我同时开多个naive，然后在iptable那边设定定时切换，可以接近我要的模式。
但缺点是 1. 切换的时间会太固定 2. 不知道切换过去的naive当下是不是连线正常
这两个缺点好像可以写指令解决，我去测看看能不能增加稳定性。

**Comment by dan2darren** [comment]
> 我自己的经验是用一两个小时节点会死三到五分钟。不固定，跟传输量也有关，传输量大时死的比较快。
> 
> naiveproxy的目标是伪装成大众化的上网流量。如果a网站连个5到10分钟、b网站连10到20分钟、c网站又连3到5分钟，随机轮来轮去。这样随机切换会比目前naive+haproxy更像普通的上网流量。
> 
> 突然想到我同时开多个naive，然后在iptable那边设定定时切换，可以接近我要的模式。
> 但缺点是 1. 切换的时间会太固定 2. 不知道切换过去的naive当下是不是连线正常
> 这两个缺点好像可以写指令解决，我去测看看能不能增加稳定性。

你这越搞越复杂

1. haproxy太重量,不适合
2. 可以单独线程发送类似心跳包的方式检测upstream server的联通性,联不通的直接做标记,不让连就完了
3. 多个naive server的目的主要还是加速, 伪装的话,弄个local ip能直连的海外url的pool,随机随时自动联呗

**Comment by klzgrad** [comment]
一开始没有必要搞得太paranoid，比你更裸奔的人现在也没碰到什么问题。碰到问题再提高防护级别。

**Comment by kousyougi** [comment]
如果有人也在用haproxy的话，
最近到另一个城市旅行，同个省，都是中国电信。发现haproxy开tcp-check的话，很快就会被挡掉。关掉tcp-check一阵子后就正常了。所以有些城市会以这个为挡的条件，有些看起来不会。
