### ISSUE TITLE
Build release for armv7, bcm53xx

### ISSUE THREAD

**Issue by vongoethe** [klzgrad/naiveproxy#106]
Could it be added the version for Netgear R8000 which the target is BCM53XX.
It's a widely used model.
Thank you

**Comment by klzgrad** [comment]
See if the cortex_a9 build in https://github.com/klzgrad/naiveproxy/releases/tag/v84.0.4147.89-2 works.

**Comment by vongoethe** [comment]
It works like a charm
Thank you
