### ISSUE TITLE
Feature Request: Optional Build as a C/C++ library

### ISSUE THREAD

**Issue by TheWanderingCoel** [klzgrad/naiveproxy#109]
Hi klzgrad:
    First of all, thank you for developing another proxy client. The idea that use chrome network stack instead of using go is really like a innovation. I want to ask that if you could provide a option that build as C/C++ library (dynamic or static) so a C/C++ GUI application call directly call the function like ``startNaiveproxy();`` instead of using binary files. For me, currently I'm developing a GUI client with Qt5. I think the use C/C++ library is more conventient that call a binary file and have to terminate it once user choose to disconnect the server. If you think it is too complex, no problem for that. Thanks for reading and considering my advice.

Best Regards,
TheWanderingCoel

**Comment by klzgrad** [comment]
startNaiveproxy() would still create several threads. What is the difference in functionality? I consider not creating an extra process purely cosmetic.

**Comment by TheWanderingCoel** [comment]
> startNaiveproxy() would still create several threads.

It's true, but GUI client can handle them self. Use boolean variable or pointer to determine whether naiveproxy is already started or not. For Qt, personally I use QThread to handle all this. For me, I think the functionality is integration and also user friendly for those GUI applications. User does not have to download extra binary file themsevles. I would still suggest a function that can pass in config file path and start Naiveproxy. Since this is an additional function and also as a library, this does not affect cli version of it.

**Comment by klzgrad** [comment]
> Use boolean variable or pointer to determine whether naiveproxy is already started or not.

You can do the same with process management.

> User does not have to download extra binary file themsevles.

You want to bundle a library. You can do the same with a binary.

> I would still suggest a function that can pass in config file path and start Naiveproxy.

You can create a temporary config file somewhere and start it from there.

**Comment by btwiuse** [comment]
I believe that would involve modifying this part of src/net/BUILD.gn:

https://github.com/klzgrad/naiveproxy/blob/047a828dd95f0605f89ff3bf9298abae6966f4fb/src/net/BUILD.gn#L2366-L2394

You may need to add a target like this, which I haven't tested yet:
```
  shared_library("libnaive") {
    testonly = true
    sources = [
      "tools/naive/naive_connection.cc",
      "tools/naive/naive_connection.h",
      "tools/naive/naive_proxy.cc",
      "tools/naive/naive_proxy.h",
      "tools/naive/naive_proxy_bin.cc",
      "tools/naive/naive_proxy_delegate.h",
      "tools/naive/naive_proxy_delegate.cc",
      "tools/naive/http_proxy_socket.cc",
      "tools/naive/http_proxy_socket.h",
      "tools/naive/redirect_resolver.h",
      "tools/naive/redirect_resolver.cc",
      "tools/naive/socks5_server_socket.cc",
      "tools/naive/socks5_server_socket.h",
    ]

    # TODO(jschuh): crbug.com/167187 fix size_t to int truncations.
    configs += [ "//build/config/compiler:no_size_t_to_int_warning" ]
    deps = [
      ":net",
      "//base",
      "//build/win:default_exe_manifest",
      "//components/version_info:version_info",
      "//url",
    ]
  }
```

**Comment by klzgrad** [comment]
I'll let you know that naiveproxy as a library is only possible in this https://github.com/v2ray/discussion/issues/754#issuecomment-650567745 form.
