### ISSUE TITLE
使用其它工具搭建的https代理都能使用naiveproxy来提升那20%吗

### ISSUE THREAD

**Issue by mixool** [klzgrad/naiveproxy#110]
使用caddy2的forwardproxy是否加成？
或是只要是合规的安全https代理，都能使用naiveproxy来提升那20%？

比如我目前我使用`https://github.com/ginuerzh/gost/releases`搭建了一个带探测防御的https代理，客户端用naiveproxy，是能正常使用的。

**Comment by klzgrad** [comment]
naiveproxy自带一套包长度混淆层，跟gost（一个标准的h2 proxy）互操作就没有这个功能了。

跟gost互操作可能也没有HTTP Fast Open，会多一个RTT。

**Comment by NetHeritage** [comment]
刚试了下，naiveproxy客户端竟然可以连上caddy1+forwardproxy搭建的代理（服务端没有用naiveproxy），这样能获得那20%的好处不？
