### ISSUE TITLE
希望能支持 OpenWrt 原生编译

### ISSUE THREAD

**Issue by 1715173329** [klzgrad/naiveproxy#111]
由于各架构差异以及依赖库等各种问题，希望能支持直接通过
OpenWrt 源码构建出二进制文件，而不是通过下载预编译文件使用。

**Comment by klzgrad** [comment]
为什么

**Comment by 1715173329** [comment]
> 为什么

可以完整支持 openwrt 现有所有架构和适应目标差异
可以解决由于 libraries 版本问题导致的无法使用
通过 openwrt 原生编译更加合理
另外由于 openwrt toolchain 问题，即使是同架构，在不同 target 上也存在差异，亦会导致各种迷之问题，甚至导致无法启动

**Comment by klzgrad** [comment]
你认为怎样才能支持？

**Comment by 1715173329** [comment]
> 你认为怎样才能支持？

如标题所述，支持直接通过 openwrt 源码构建出二进制文件 (Makefile)
openwrt 也有 ninja 等支持，理应问题不大，不过我并不了解 chromium 构建方式

**Comment by klzgrad** [comment]
那你去试一下吧

**Comment by 1715173329** [comment]
> 那你去试一下吧

如上文所述，我并不了解 chromium 构建方法，尤其是有关跨架构构建，曾经尝试过但并未取得效果
如果可以希望您能提供相关文档

**Comment by klzgrad** [comment]
你是否想过你未取得效果是有原因的

**Comment by 1715173329** [comment]
> 你是否想过你未取得效果是有原因的

正如上文所述，我并不了解 chromium 构建方法
基本的 gn 等工具和依赖也有处理，但各种参数确实不了解

**Comment by klzgrad** [comment]
1. 编译需要8G内存
2. 编译时间久
3. 需要把现有编译系统改成gcc
4. 打开了各种人给我报告编译错误的魔盒

**Comment by 1715173329** [comment]
1/2：编译条件满足的，我全新编译不过也就五分钟左右。。。
3：GCC 编译问题，是通过添加 `custom_toolchain="//build/toolchain/linux:clang_mipsel_openwrt"` 这个参数吗？
4：这个确实，但希望您能够提供一点帮助，Makefile 可以由我自己来完成

**Comment by 1715173329** [comment]
目前初步完成了对 x86_64 的支持
![image](https://user-images.githubusercontent.com/22235437/90566324-d91e8e80-e1da-11ea-9c4b-8ca72ab26abf.png)

但是尝试为其他架构编译时出现下面的报错
![image](https://user-images.githubusercontent.com/22235437/90566422-08350000-e1db-11ea-8725-4d189f48c6d0.png)

**Comment by 1715173329** [comment]
目前已经完全做好了，便不多叨饶了。
