### ISSUE TITLE
使用go1.15编译出的caddy文件，运行出错。

### ISSUE THREAD

**Issue by proxysu** [klzgrad/naiveproxy#112]
使用最新版本的go1.15来编译服务端caddy。运行出错，改为go1.14.7编译，运行正常。

**Comment by darhwa** [comment]
这是因为caddy依赖的quic-go尚不支持Go 1.15。只有耐心等待上游解决（lucas-clemente/quic-go#2614）

**Comment by yuchenxi2000** [comment]
quic最新release（v0.18.0）已经支持Golang1.15了，但是klzgrad/forwardproxy依赖的还是旧版本，目前还是得用Golang1.14.7

**Comment by klzgrad** [comment]
跟forwardproxy依赖什么版本并无关系。

用：
```
~/go/bin/xcaddy build HEAD --with github.com/caddyserver/forwardproxy=$PWD/forwardproxy
```
