### ISSUE TITLE
检测NaiveProxy的小小思路，也适用于其他代理

### ISSUE THREAD

**Issue by ghost** [klzgrad/naiveproxy#114]
是的，NaiveProxy解决了TLS in TLS问题，也解决了主动探测、TLS客户端指纹、长度识别的问题。

但是NP有一点很不寻常：正常的浏览器，在其HTTPS连接被终止后，会立即断开连接（不会再尝试重新连接）。

NP在这里很不寻常：它会在断开后尝试重新连接服务器，正常的浏览器会乖乖停下来（来自一个做L7识别的朋友）。

详细一点的话就是：“NaiveProxy在被阻断连线后，正常浏览器应该会重新开始TLS握手和连接，但是NaiveProxy却没有进行任何握手直接开始数据传送。这和浏览器完全不同。更接近于加密代理。”

GFW（启明星辰）现在正在使用这个方法，来判断一个连接是否为加密代理。但目前处于灰度测试阶段（GFW的灰度测试时间很长）。也就是说还没实装。

V2Ray等TLS代理也存在这个问题。

缓解建议是：当检测到连接中断，就在未来的若干分钟内（启明星辰会对一个被阻断的连接观察三到五分钟，且这三到五分钟内是无法连接也ping不通服务器的）不建立任何连接。使其行为“看上去”是一个正常的浏览器和人类，而不是代理。

**Comment by klzgrad** [comment]
基于TLS的代理模仿浏览器是较好的，因为在所有具备TLS栈的软件中，特定浏览器是已知用户最多的，这在类别匿名性上提供了最大的分母。也许有少数机械性的软件生成了更多的流量，但很难有证据论证它的类别匿名性。

不是浏览器装成浏览器未必就是鹦鹉，问题是什么是“不是”。把马的尾巴拿掉不是马，与两个人扮演的马不是马，两个“不是”的性质是不同的。

**Comment by rprx** [comment]
取决于“鹦鹉”的定义。

**Comment by doyouhavebtree** [comment]
> 
> 
> 我测了一下，浏览器里面一个HTTP request在ERR_CONNECTION_REFUSED之后的确不会自动重试。但如果是页面的XHR在同样原因失败之后，浏览器的网络栈并不会阻止后续的XHR产生网络流量。NaiveProxy对比的流量就是有交互的页面，不是Request-Response的页面。所以你做L7识别的朋友应该明确一下，“正常的浏览器”具体指什么。
> 
> 补充一点：对，启明星辰也是老外包了。之前我只说是高校实验室在搞科研，应该加入他一份。不过从项目生命周期的角度来看，战略姿态还是一样的。

根据我和朋友那天粗浅的谈话来看，应该是Request-Response。因为我的朋友提到了这么一件事：

“NaiveProxy在被Reset后，正常浏览器应该会重新开始TLS握手和连接，但是NaiveProxy却没有进行任何握手直接开始数据传送”。

**Comment by doyouhavebtree** [comment]
> 
> 
> 还是没忍住想说几句。
> 
> > NP在这里很不寻常：它会在断开后尝试重新连接服务器，正常的浏览器会乖乖停下来（来自一个做L7识别的朋友）。
> 
> 没仔细研究过，但个人觉得这个行为可能不算罕见，存在基本率问题。一些网站有轮询请求（eg. 微信、Gmail），是否也有会相似的行为呢。
> 
> > 缓解建议是：当检测到连接中断，就在未来的若干分钟内（启明星辰会对一个被阻断的连接观察三到五分钟，且这三到五分钟内是无法连接也ping不通服务器的）不建立任何连接。使其行为“看上去”是一个正常的浏览器和人类，而不是代理。
> 
> 这个缓解策略本质上是鹦鹉（[Houmansadr2013b](https://censorbib.nymity.ch/pdf/Houmansadr2013b.pdf)），这正是两个月前我们反复强调应当避免的，避免鹦鹉也是 NaiveProxy 设计的一个基本思想。

错。

第一段，“具有轮询请求的网站”其实是基于WebSocket通讯来完成轮询等操作。

但WebSocket是HTTP之上的协议，意味着HTTP断开，WebSocket也会一起死。不存在所谓的“继续通讯”。

而第二段缓解措施，作者已经给出了精彩的回复：

**基于TLS的代理模仿浏览器是较好的，因为在所有具备TLS栈的软件中，特定浏览器是已知用户最多的，这在类别匿名性上提供了最大的分母。也许有少数机械性的软件生成了更多的流量，但很难有证据论证它的类别匿名性。

不是浏览器装成浏览器未必就是鹦鹉，问题是什么是“不是”。把马的尾巴拿掉不是马，与两个人扮演的马不是马，两个“不是”的性质是不同的。**

**Comment by rprx** [comment]
记得之前关于鹦鹉的讨论中，有这么一个描述：即使静态特征一致，动态行为上还是会露馅。而这个检测思路无疑针对“动态行为”：把马的尾巴拿掉还是马吗？是。还是正常的马吗？不是。若只放行正常的马，相似程度多高也只是五十步笑百步。

我对 TLS 的看好，更多的是“广泛使用的传输层安全协议”，而不是“浏览器专用协议”（GFW 敢把 TLS 封得只剩 100% 浏览器吗？

**Comment by oasiscifr** [comment]
@rprx 
> 这个检测思路，若仅针对 NaiveProxy 这类尽可能向浏览器靠拢的，可能有一点点作用，但有很大的局限性，上面已经说出来了。
这里还需要打破惯性思维：为什么基于 TLS 的代理就一定要像浏览器？大量的出入境 TLS 流量中，浏览器占比很多吗？存疑。

这个issue首先还是应该先讨论问题是否存在，如果存在再讨论🦜还是混沌吧。
klzgrad提出了有效的问题，现在先听到更多细节才是。

**Comment by rprx** [comment]
> 这个issue首先还是应该先讨论问题是否存在，如果存在再讨论🦜还是混沌吧。
> klzgrad提出了有效的问题，现在先听到更多细节才是。

主要是因为“也适用于其他代理”、“V2Ray等TLS代理也存在这个问题。”，这就是把所有 TLS 代理都认为是模拟浏览器的了。

**Comment by rprx** [comment]
> 这个issue首先还是应该先讨论问题是否存在，如果存在再讨论🦜还是混沌吧。
> klzgrad提出了有效的问题，现在先听到更多细节才是。

补充：这个问题是否存在与是否鹦鹉是**高度相关**的，更多的细节的确是需要的，而更多的细节尚未被提供，讨论鹦鹉也完全未离题。

**Comment by rprx** [comment]
其实仔细对比真实人类操作浏览器的行为，还有更多不寻常，比如从早到晚不断访问同一个域名，还连续几天、几十天。欢迎补充。

（这个域名还可能比较奇怪：注册时间没多久，.xyz 廉价/小众后缀，字母数字混杂之类的，却吸引一个人/一堆人天天看

**Comment by kousyougi** [comment]
> 其实仔细对比真实人类操作浏览器的行为，还有更多不寻常，比如从早到晚不断访问同一个域名，还连续几天、几十天。欢迎补充。
> 
> （这个域名还可能比较奇怪：注册时间没多久，.xyz 廉价/小众后缀，字母数字混杂之类的，却吸引一个人/一堆人天天看

訪問公司的NAS會是這種頻率，而且最近越來越多遠端作業。

**Comment by rprx** [comment]
> 訪問公司的NAS會是這種頻率，而且最近越來越多遠端作業。

对于各种不寻常的行为，总还是能找到对应的场景，但问题是比例、流量多少及与公开信息的匹配程度等，比如我描述的那种域名。

**Comment by littlef0x** [comment]
> 
> 
> 其实仔细对比真实人类操作浏览器的行为，还有更多不寻常，比如从早到晚不断访问同一个域名，还连续几天、几十天。欢迎补充。
> 
> （这个域名还可能比较奇怪：注册时间没多久，.xyz 廉价/小众后缀，字母数字混杂之类的，却吸引一个人/一堆人天天看

It should be noted that **behavior** of a browser and **operation** of a human are different things. Tools like NP should focus only on the former one.

I'm not an expert in network. This is just my understanding based on your discussion. IMO, both browser traffic and reconnection behavior is quite common. But when these characteristics occur on the same connection(i.e. a browser that reconnects **immediately** for **all links** and  **all the time**), it is suspicious. So I think this can be called a vulnerability, at least for those try to pretend themselves as normal browser.

As for the mitigation, I wonder whether load balance is feasible, i.e. when a abnormal cutoff is detected on the client side, swith to another server.

**Comment by darhwa** [comment]
我仔细看了楼主这段话后，怀疑大家被带偏了方向：

> 详细一点的话就是：“NaiveProxy在被阻断连线后，正常浏览器应该会重新开始TLS握手和连接，但是NaiveProxy却没有进行任何握手直接开始数据传送。这和浏览器完全不同。更接近于加密代理。”

这种表述明显是有问题的。naive的TLS连接被阻断了， 怎么可能不重新TLS握手，就直接开始传数据？naive并没有打开TLS 1.3 0-rtt，哪怕是0-rtt，也不能说没有握手啊。只能说，被naive代理的流量，感受不到连接中断，在naive恢复连接后，无缝切换到新连接上，这是有可能的。无论如何，naive的连接被中断了，必然要重新握手建立TLS连接，至于隧道里面代理的连接，外部本身也看不到，是不是TLS都不一定，如何判断有没有重新握手？靠包长度检测么？这是另一个层面的问题了。

**Comment by darhwa** [comment]
> 缓解建议是：当检测到连接中断，就在未来的若干分钟内（启明星辰会对一个被阻断的连接观察三到五分钟，且这三到五分钟内是无法连接也ping不通服务器的）不建立任何连接。使其行为“看上去”是一个正常的浏览器和人类，而不是代理。

这估计是为了模拟人类用户的行为，但也有问题。用户看到网站打不开，难道不会手动刷新页面？人类用户也不会在看到网页打不开后，发愣三到五分钟后才刷新。

**Comment by doyouhavebtree** [comment]
> 
> 
> 我仔细看了楼主这段话后，怀疑大家被带偏了方向：
> 
> > 详细一点的话就是：“NaiveProxy在被阻断连线后，正常浏览器应该会重新开始TLS握手和连接，但是NaiveProxy却没有进行任何握手直接开始数据传送。这和浏览器完全不同。更接近于加密代理。”
> 
> 这种表述明显是有问题的。naive的TLS连接被阻断了， 怎么可能不重新TLS握手，就直接开始传数据？naive并没有打开TLS 1.3 0-rtt，哪怕是0-rtt，也不能说没有握手啊。只能说，被naive代理的流量，感受不到连接中断，在naive恢复连接后，无缝切换到新连接上，这是有可能的。无论如何，naive的连接被中断了，必然要重新握手建立TLS连接，至于隧道里面代理的连接，外部本身也看不到，是不是TLS都不一定，如何判断有没有重新握手？靠包长度检测么？这是另一个层面的问题了。

很好，问题就是在于，NaiveProxy没有重新握手建立TLS连接。而是直接传送加密数据了。

麻烦重新审题。

**Comment by darhwa** [comment]
还是麻烦你先去跟消息来源搞清楚，这个`断线`到底是指什么吧，是真的连线中断了还是只是丢了几个包呢。断线重连TCP端口都会变，Naive不重新TLS握手？那就是Chrome(BoringSSL)的实现有大问题了，呵呵。我不认为会存在这样的bug，因为这在测试中太容易发现：就算Chrome不重新握手，当没断线一样继续发数据，服务器那边会认？Naive的修改也并不涉及到如此底层的机制。

这不是我没有审题，而是我仔细审视题目后找出了里面无法自圆其说需要进一步澄清的地方。

另外，我纠正一下我之前一些的说法：

> 只能说，被naive代理的流量，感受不到连接中断，在naive恢复连接后，无缝切换到新连接上，这是有可能的。

这个也是不可能的。要实现这一点，必然涉及到数据重传。然而重传是TCP负责的， TLS并不管重传。连接中断就说明TCP重传机制没有救回来，TLS这一层就更做不了什么。我只能想到一种情形，被代理的连接感受不到断线，那就是阻断发生在Naive的TLS握手过程中。由于TLS握手还没完成，隧道还没建立，这时无论是CONNECT方法请求还是被代理连接的第一个数据包都处于被阻塞的状态，因此Naive重连不会影响到被代理连接。

**Comment by klzgrad** [comment]
即使不要求实证，这个检测方法在理论上也没有说通，而且也没有可实施的缓解办法。如果有更多信息可以继续讨论。
