### ISSUE TITLE
Naive client connection rotation

### ISSUE THREAD

**Issue by WeidiDeng** [klzgrad/naiveproxy#119]
I use naive client on my raspberry pi as socks proxy. As I check from netstat, local tcp port to the server don't change for hours (The connection to remote server, wiki said there're connection rotation.). This leads to bad performance.

For now, I use a bash script to drop forward_proxy configuration and reenable it through [caddy api](https://caddyserver.com/docs/api). Can you look into it when you have time.

Thank you for the project. Multiplexing tcp connections into one is really helpful.

**Comment by klzgrad** [comment]
> As I check from netstat, local tcp port to the server don't change for hours (The connection to remote server, wiki said there're connection rotation.)

Connection stays alive until you have no more proxy traffic. There is no hard interruption.

> This leads to bad performance.

Why?

> For now, I use a bash script to drop forward_proxy configuration and reenable it through caddy api.

For what?

**Comment by WeidiDeng** [comment]
1. Why?

In my environment, the long connection turn out to be extremely slow (page take many seconds to load). However, access my server is fine (my server has deployed reverse proxy for ubuntu launchpad).

2. For What?

Removing forward_proxy configuration and readding it causes naive client to establish a new connection, and the speed is normal again.

**Comment by klzgrad** [comment]
Try this:
```
while true; do
  naive &
  sleep 600
  pkill naive
done
```
