### ISSUE TITLE
v85.0.4183.83-1版本在官方master下用了所有的方法均因依赖无法下载导致无法编译

### ISSUE THREAD

**Issue by zxlhhyccc** [klzgrad/naiveproxy#121]
![image](https://user-images.githubusercontent.com/45259624/92236853-dc0ec400-eee8-11ea-8660-e565bdca397c.png)

**Comment by klzgrad** [comment]
这句话

> The scripts download tools from Google servers with curl. You may need to set a proxy environment variable for curl, e.g. export ALL_PROXY=socks5h://127.0.0.1:1080.

有没有看到

**Comment by zxlhhyccc** [comment]
> 这句话
> 
> > The scripts download tools from Google servers with curl. You may need to set a proxy environment variable for curl, e.g. export ALL_PROXY=socks5h://127.0.0.1:1080.
> 
> 有没有看到

没有。。。。

**Comment by klzgrad** [comment]
你这个跟下载没有关系

你运行了什么命令
