### ISSUE TITLE
使用Naiveproxy测速时无法得到理想的网络性能。

### ISSUE THREAD

**Issue by felixding** [klzgrad/naiveproxy#122]
理论上说Naiveproxy应该有非常好的网络性能，至少和其它代理软件处于同一水平。但测试结果却相差很大，不知道是哪里出了问题。

测试设置如下：

- Naiveproxy v85.0.4183.83-2，v2ray 4.25.1
- 服务器为Ubuntu 18.04 x64。Naiveproxy使用go 1.14.8编译，用caddy2+forwardproxy。v2ray放在了Nginx后面，用了WebSocket via TLS+Vmess协议
- 客户端为Mac OS 10.15.6，Naiveproxy和v2ray均使用命令行程序

测试结果如下：

v2ray：

![v2ray-tokyo-sg](https://user-images.githubusercontent.com/111456/92320528-0da89c00-f05d-11ea-8555-51798373eca9.png)

Naiveproxy：

![naive-tokyo-sg](https://user-images.githubusercontent.com/111456/92320536-1c8f4e80-f05d-11ea-8d3d-8e727fc98e0f.png)

同一时间段反复切换测试，均得到基本一致的结果。请问可能是什么问题？

**Comment by darhwa** [comment]
图上 Connections 下面显示 Multi，估计是这个原因。

naive 是多路复用的，而 v2ray 是 1:1 的连接模型。这样测出来 naive 显示的是你家到 vps 单个连接的带宽，v2ray 则是多个连接的总带宽。

**Comment by klzgrad** [comment]
我没有认真去在性能上优化，如果性能好也只是偶然。

为了重现你这个，我手搭了一个Caddy前端的V2ray。测得二者单连接的网速性能是一样的，所以跟上面推测是一样的。

Naive在设计理念上是沿袭HTTP/2，认为应该把单连接用好，而不是多连接去不公平竞争带宽。因此在实际网络环境中，在性能上要比多连接劣势。Naive里面有多连接的选项，但我不会告诉你。

除此之外CPU占用率我也看了一眼，CPU还不是网速瓶颈，只有相对意义

* 客户端：Naive 22%, V2ray 45%
* 服务端：Caddy(naive) 10%, Caddy+V2ray 5+10%

**Comment by NetHeritage** [comment]
Naive里面有多连接的选项，但我不会告诉你，哈哈哈哈哈

**Comment by felixding** [comment]
明白了。请问有计划优化吗？

**Comment by fbion** [comment]
学习了

**Comment by XueshiQiao** [comment]
@klzgrad “Naive里面有多连接的选项，但我不会告诉你”  稍微透露一下呗，或者给点线索

**Comment by dongxinb** [comment]
想得到答案的阅读下代码吧，很快就能找到的。
[cheatsheet](https://github.com/klzgrad/naiveproxy/blob/master/src/net/tools/naive/naive_proxy_bin.cc)

**Comment by fbion** [comment]
> 想得到答案的阅读下代码吧，很快就能找到的。
> [cheatsheet](https://github.com/klzgrad/naiveproxy/blob/master/src/net/tools/naive/naive_proxy_bin.cc)

                  "--concurrency=<N>          Use N connections, less secure\n"
是这个吗

**Comment by emiyalee1005** [comment]
> > 想得到答案的阅读下代码吧，很快就能找到的。
> > [cheatsheet](https://github.com/klzgrad/naiveproxy/blob/master/src/net/tools/naive/naive_proxy_bin.cc)
> 
> ```
>               "--concurrency=<N>          Use N connections, less secure\n"
> ```
> 
> 是这个吗

I think yes

**Comment by klzgrad** [comment]
![2020-10-03-103420_3840x2160_scrot](https://user-images.githubusercontent.com/9764056/94981385-799af900-0564-11eb-87c0-c75ceb8150a0.png)
我把concurrency参数的上限删除了，然后设为8，然后测得这个数字。但意义不大，因为单连接性能还是很慢。

删除上限的原因是几个月前电信单连接的限速还是10MB/s，现在变成6MB/s了，竟然使用8个连接才能把水管充满。

我使用kcptun测速“单连接”可以达到20MB/s，这里的确有一些对抗限速的空间。

**Comment by felixding** [comment]
你那里UDP不会遇到运营商的限制吗？

我曾经用TCP PCC的用户空间程序获得非常惊人的下载带宽，它对网络的提速效果是如此显著，以至于我甚至不得不通过确认网卡的流量来验证它的速度。当时BBR还没有发布，可惜后来作者去搞区块链了。

我看了很多TCP拥塞控制协议，基本上都只在服务器端做文章，而完全放弃客户端，这当然是正常的，但是对于Naive或类似的软件，因为两边都是自己控制，如果直接集成拥塞控制是不是会有更好的效果？

**Comment by ysbreh** [comment]
> 我没有认真去在性能上优化，如果性能好也只是偶然。
> 
> 为了重现你这个，我手搭了一个Caddy前端的V2ray。测得二者单连接的网速性能是一样的，所以跟上面推测是一样的。
> 
> Naive在设计理念上是沿袭HTTP/2，认为应该把单连接用好，而不是多连接去不公平竞争带宽。因此在实际网络环境中，在性能上要比多连接劣势。Naive里面有多连接的选项，但我不会告诉你。
> 
> 除此之外CPU占用率我也看了一眼，CPU还不是网速瓶颈，只有相对意义
> 
> * 客户端：Naive 22%, V2ray 45%
> * 服务端：Caddy(naive) 10%, Caddy+V2ray 5+10%

启用多连接有哪些风险？

**Comment by klzgrad** [comment]
浏览器访问一个H/2站点不会使用多连接

**Comment by oit63** [comment]
如klzgrad说的，concurrency最好就保持1，可搭配haproxy做负载均衡配多个节点提速

**Comment by klzgrad** [comment]
Duplicate of https://github.com/klzgrad/naiveproxy/issues/122

测得因为HTTP/2设置的原因导致单连接限速
