### ISSUE TITLE
Non-DNS UDP traffic getting blocked?

### ISSUE THREAD

**Issue by AkiOwO** [klzgrad/naiveproxy#123]
Hi everyone!
It seems like that the firewall of my institution is blocking non-DNS UDP traffic. This makes the usage of programs like Teamspeak3, Steam and Parsec (remote PC-Streaming software) unusable. I am using [Proxifier](https://www.proxifier.com/) to route my traffic through the naive proxy (127.0.0.1:1080) and when I tried to connect to a teamspeak3 server, proxifier showed me the following lines in its log:

[09.07 11:40:51] ts3client_win64.exe *64 - 172.16.2.10:53 DNS-UDP Error:QTYPE is incorrect
[09.07 11:40:54] ts3client_win64.exe *64 - 8.8.8.8:53 DNS-UDP Error:QTYPE is incorrect
[09.07 11:40:57] ts3client_win64.exe *64 - 8.8.4.4:53 DNS-UDP Error:QTYPE is incorrect

Is there a way to get around that restriction? Thanks for your help!

Best Regards

**Comment by klzgrad** [comment]
I'm not familiar with Proxifier, but I don't think UDP is supported here at all.

**Comment by AkiOwO** [comment]
Oh I see.
What would be the best way to route UDP and TCP traffic of my programs through naive?
Are there programs for it? I'm using Windows 10, but I could switch to Linux if that's easier.

Thanks for the help,
Best regards

**Comment by klzgrad** [comment]
Naive doesn't support transporting UDP in TCP. It's not in my design scope. I can't help you here.
