### ISSUE TITLE
qtls.ClientSessionState not compatible with tls.ClientSessionState

### ISSUE THREAD

**Issue by andymc88** [klzgrad/naiveproxy#124]
If anyone runs Caddy + naiveproxy and sees an error, `qtls.ClientSessionState not compatible with tls.ClientSessionState`, it is probably due to golang 1.15.

[https://www.oilandfish.com/posts/naiveproxy-caddy-2.html#1-5](https://www.oilandfish.com/posts/naiveproxy-caddy-2.html#1-5)

Solution is to downgrade to golang 1.14.

**Comment by klzgrad** [comment]
You can solve this by building Caddy from HEAD
```
~/go/bin/xcaddy build HEAD --with github.com/caddyserver/forwardproxy=$PWD/forwardproxy
```

**Comment by lxhao61** [comment]
@klzgrad 
HEAD≠caddy_version？

**Comment by klzgrad** [comment]
HEAD gets you the latest Caddy version from its Github master branch, eh?

**Comment by lxhao61** [comment]
> HEAD从其Github主分支获取最新的Caddy版本，是吗？

@klzgrad 
HEAD means it doesn't?
