### ISSUE TITLE
服务端大量ERR_CONNECTION_CLOSED

### ISSUE THREAD

**Issue by gxind** [klzgrad/naiveproxy#125]
具体使用表现为 chrome打开网页有几率立刻报错显示意外终止，然后极短时间内自动刷新网页又正常显示。
haproxy版本 version 2.0.16。。debian10 apt backport安装
naiveproxy版本 v85.0.4183.83-1
完全按照wiki里面介绍的haproxy方式配置
naiveproxy client--->haproxy--->naiveproxy server
![捕获](https://user-images.githubusercontent.com/43134892/92464540-dfaf8d00-f1ff-11ea-974d-e642f9809d29.PNG)

**Comment by klzgrad** [comment]
建议在服务端tcpdump -ilo port 10000，然后用wireshark看一下是什么情况。仅凭以上信息不足以推断

**Comment by gxind** [comment]
> 建议在服务端tcpdump -ilo port 10000，然后用wireshark看一下是什么情况。仅凭以上信息不足以推断

按操作做了，可是我是个小白，wireshark下看不出问题所在。我把dump文件上传，大佬如果有时间，麻烦分析一下问题所在。

[dump.zip](https://github.com/klzgrad/naiveproxy/files/5191990/dump.zip)

**Comment by gxind** [comment]
> > 建议在服务端tcpdump -ilo port 10000，然后用wireshark看一下是什么情况。仅凭以上信息不足以推断
> 
> 按操作做了，可是我是个小白，wireshark下看不出问题所在。我把dump文件上传，大佬如果有时间，麻烦分析一下问题所在。
> 
> [dump.zip](https://github.com/klzgrad/naiveproxy/files/5191990/dump.zip)

又看了一下。照理说这个回落到naiveproxy server的链接 应该是一个明文的协议。但是在wireshark里面看到了很多标注为tls的链接，而且都显示 ignored unknown record。也许问题在这？

**Comment by klzgrad** [comment]
你能不能试一下 https://github.com/klzgrad/naiveproxy/releases/tag/v85.0.4183.83-3

这个是上次 HAProxy一个bug没有修好 https://github.com/klzgrad/naiveproxy/issues/41#issuecomment-596076624

**Comment by gxind** [comment]
> 你能不能试一下 https://github.com/klzgrad/naiveproxy/releases/tag/v85.0.4183.83-3
> 
> 这个是上次 HAProxy一个bug没有修好 [#41 (comment)](https://github.com/klzgrad/naiveproxy/issues/41#issuecomment-596076624)

谢谢大佬。我在电脑前，收到email第一时间测试了。服务端跑了几页log，目前没看到有错误，网页加载全部正常了。问题应该是解决了。再次感谢。
