### ISSUE TITLE
Error in Running Self-Built Caddy

### ISSUE THREAD

**Issue by GWONGJYULEI** [klzgrad/naiveproxy#126]
Firstly, thank you for developing such a great project!

And when I build and run Caddy v2 with naïve fork of forwardproxy, I met the following problem:(Ubuntu 20 LTS (VMware 16), Go version: 1.15.2)

> panic: qtls.ClientSessionState not compatible with tls.ClientSessionState
> 
> goroutine 1 [running]:
> github.com/lucas-clemente/quic-go/internal/handshake.init.2()
> 	github.com/lucas-clemente/quic-go@v0.17.1/internal/handshake/unsafe.go:26 +0x205

And the following is the log of build, maybe could give you some info:
> ryan@ryan-virtual-machine:~$ ~/go/bin/xcaddy build --with github.com/caddyserver/forwardproxy=$PWD/forwardproxy
> 2020/09/19 20:09:58 [INFO] Temporary folder: /tmp/buildenv_2020-09-19-2009.628721396
> 2020/09/19 20:09:58 [INFO] Writing main module: /tmp/buildenv_2020-09-19-2009.628721396/main.go
> 2020/09/19 20:09:58 [INFO] Initializing Go module
> 2020/09/19 20:09:58 [INFO] exec (timeout=10s): /usr/local/go/bin/go mod init caddy 
> go: creating new go.mod: module caddy
> 2020/09/19 20:09:58 [INFO] Replace github.com/caddyserver/forwardproxy => /home/ryan/forwardproxy
> 2020/09/19 20:09:58 [INFO] exec (timeout=10s): /usr/local/go/bin/go mod edit -replace github.com/caddyserver/forwardproxy=/home/ryan/forwardproxy 
> 2020/09/19 20:09:58 [INFO] Pinning versions
> 2020/09/19 20:09:58 [INFO] exec (timeout=0s): /usr/local/go/bin/go get -d -v github.com/caddyserver/caddy/v2 
> go: downloading github.com/caddyserver/caddy v1.0.5
> go: downloading github.com/caddyserver/caddy/v2 v2.1.1
> go: github.com/caddyserver/caddy/v2 upgrade => v2.1.1
> go: downloading go.uber.org/zap v1.15.0
> go: downloading golang.org/x/crypto v0.0.0-20200622213623-75b288015ac9
> go: downloading github.com/caddyserver/certmagic v0.11.2
> go: downloading go.uber.org/multierr v1.5.0
> go: downloading go.uber.org/atomic v1.6.0
> go: downloading github.com/go-acme/lego/v3 v3.7.0
> go: downloading github.com/klauspost/cpuid v1.3.0
> go: downloading golang.org/x/sys v0.0.0-20200413165638-669c56c373c4
> go: downloading github.com/cenkalti/backoff/v4 v4.0.0
> go: downloading golang.org/x/net v0.0.0-20200625001655-4c5254603344
> go: downloading gopkg.in/square/go-jose.v2 v2.4.0
> go: downloading github.com/miekg/dns v1.1.27
> go: downloading golang.org/x/text v0.3.2
> 2020/09/19 20:10:41 [INFO] Build environment ready
> 2020/09/19 20:10:41 [INFO] Building Caddy
> 2020/09/19 20:10:41 [INFO] exec (timeout=0s): /usr/local/go/bin/go build -o /home/ryan/caddy -ldflags -w -s -trimpath 
> go: downloading github.com/smallstep/truststore v0.9.5
> go: downloading github.com/smallstep/cli v0.14.4
> go: downloading github.com/smallstep/nosql v0.3.0
> go: downloading github.com/smallstep/certificates v0.15.0-rc.1.0.20200506212953-e855707dc274
> go: downloading gopkg.in/natefinch/lumberjack.v2 v2.0.0
> go: downloading github.com/jsternberg/zap-logfmt v1.2.0
> go: downloading github.com/dustin/go-humanize v1.0.1-0.20200219035652-afde56e7acac
> go: downloading github.com/google/cel-go v0.5.1
> go: downloading github.com/go-chi/chi v4.1.2+incompatible
> go: downloading github.com/dgraph-io/badger v1.5.3
> go: downloading github.com/pkg/errors v0.9.1
> go: downloading github.com/dgraph-io/badger/v2 v2.0.1-rc1.0.20200413122845-09dd2e1a4195
> go: downloading github.com/golang/protobuf v1.4.1
> go: downloading google.golang.org/protobuf v1.25.0
> go: downloading github.com/antlr/antlr4 v0.0.0-20200503195918-621b933c7a7f
> go: downloading github.com/libdns/libdns v0.0.0-20200501023120-186724ffc821
> go: downloading github.com/urfave/cli v1.22.2
> go: downloading github.com/yuin/goldmark-highlighting v0.0.0-20200307114337-60d527fdb691
> go: downloading github.com/Masterminds/sprig/v3 v3.1.0
> go: downloading github.com/klauspost/compress v1.10.10
> go: downloading github.com/naoina/toml v0.1.1
> go: downloading google.golang.org/genproto v0.0.0-20200526211855-cb27e3aa2013
> go: downloading github.com/yuin/goldmark v1.1.32
> go: downloading github.com/Masterminds/goutils v1.1.0
> go: downloading github.com/spf13/cast v1.3.1
> go: downloading github.com/samfoo/ansi v0.0.0-20160124022901-b6bd2ded7189
> go: downloading github.com/imdario/mergo v0.3.8
> go: downloading github.com/alecthomas/chroma v0.7.4-0.20200517063913-500529fd43c1
> go: downloading github.com/huandu/xstrings v1.3.1
> go: downloading github.com/dgryski/go-farm v0.0.0-20190423205320-6a90982ecee2
> go: downloading github.com/google/uuid v1.1.1
> go: downloading github.com/lucas-clemente/quic-go v0.17.1
> go: downloading github.com/mitchellh/copystructure v1.0.0
> go: downloading github.com/dgraph-io/ristretto v0.0.2-0.20200115201040-8f368f2f2ab3
> go: downloading github.com/naoina/go-stringutil v0.1.0
> go: downloading github.com/cespare/xxhash v1.1.0
> go: downloading github.com/mitchellh/reflectwalk v1.0.0
> go: downloading github.com/Masterminds/semver v1.4.2
> go: downloading github.com/marten-seemann/qtls v0.9.1
> go: downloading github.com/go-sql-driver/mysql v1.5.0
> go: downloading github.com/francoispqt/gojay v1.2.13
> go: downloading github.com/cheekybits/genny v1.0.0
> go: downloading gopkg.in/yaml.v2 v2.3.0
> go: downloading github.com/marten-seemann/qpack v0.1.0
> go: downloading github.com/cpuguy83/go-md2man v1.0.10
> go: downloading github.com/Masterminds/semver/v3 v3.1.0
> go: downloading github.com/shurcooL/sanitized_anchor_name v1.0.0
> go: downloading go.etcd.io/bbolt v1.3.2
> go: downloading github.com/chzyer/readline v0.0.0-20180603132655-2972be24d48e
> go: downloading github.com/sirupsen/logrus v1.4.2
> go: downloading github.com/cpuguy83/go-md2man/v2 v2.0.0
> go: downloading github.com/dlclark/regexp2 v1.2.0
> go: downloading github.com/rs/xid v1.2.1
> go: downloading github.com/AndreasBriese/bbloom v0.0.0-20190306092124-e2d15f34fcf9
> go: downloading github.com/danwakefield/fnmatch v0.0.0-20160403171240-cbb64ac3d964
> go: downloading github.com/russross/blackfriday v1.5.2
> go: downloading github.com/golang/snappy v0.0.1
> go: downloading google.golang.org/grpc v1.27.1
> go: downloading github.com/manifoldco/promptui v0.3.1
> go: downloading cloud.google.com/go v0.54.0
> go: downloading github.com/russross/blackfriday/v2 v2.0.1
> go: downloading github.com/googleapis/gax-go v2.0.0+incompatible
> go: downloading google.golang.org/api v0.20.0
> go: downloading github.com/juju/ansiterm v0.0.0-20180109212912-720a0952cc2a
> go: downloading github.com/googleapis/gax-go/v2 v2.0.5
> go: downloading github.com/mattn/go-isatty v0.0.12
> go: downloading github.com/mattn/go-colorable v0.1.6
> go: downloading github.com/lunixbochs/vtclean v1.0.0
> go: downloading golang.org/x/oauth2 v0.0.0-20200107190931-bf48bf16ab8d
> go: downloading go.opencensus.io v0.22.3
> go: downloading github.com/google/go-cmp v0.5.0
> go: downloading github.com/golang/groupcache v0.0.0-20200121045136-8c9f03a8e57e
> go: found github.com/caddyserver/forwardproxy in github.com/caddyserver/forwardproxy v0.0.0-00010101000000-000000000000
> go: downloading gopkg.in/square/go-jose.v2 v2.4.1
> go: downloading github.com/cenkalti/backoff/v4 v4.0.2
> go: downloading github.com/miekg/dns v1.1.29
> go: downloading github.com/imdario/mergo v0.3.9
> go: downloading github.com/manifoldco/promptui v0.7.0
> 2020/09/19 20:11:01 [INFO] Build complete: caddy
> 2020/09/19 20:11:01 [INFO] Cleaning up temporary folder: /tmp/buildenv_2020-09-19-2009.628721396

It would be thankful that you could take a look when you are free.

**Comment by klzgrad** [comment]
https://github.com/klzgrad/naiveproxy/issues/112#issuecomment-687846773
https://github.com/klzgrad/naiveproxy/issues/124#issuecomment-688571723
