### ISSUE TITLE
[Feature]能否在caddy1中也引入支持naiveproxy的forwardproxy

### ISSUE THREAD

**Issue by xianren78** [klzgrad/naiveproxy#128]
caddy2由于设置复杂，实际上阻碍了一部分人从caddy1转移到caddy2。有没有可能在caddy1中也引入支持naiveproxy的forwardproxy。

**Comment by klzgrad** [comment]
编译定制caddy1也很复杂 https://github.com/caddyserver/caddy/tree/v1#build

**Comment by ysbreh** [comment]
秋水有编译好的“Caddy v1.0.5 + 插件 forwardproxy 编译版” 自行找一下食用。

**Comment by xianren78** [comment]
> 编译定制caddy1也很复杂 https://github.com/caddyserver/caddy/tree/v1#build

https://github.com/shuxs/caddy
按这个build, 其实不难，build完发布一下，大家就可以分享了

**Comment by klzgrad** [comment]
不能

**Comment by klzgrad** [comment]
Caddy 2可以支持Caddyfile配置forwardproxy了
