### ISSUE TITLE
能否增加一个选项以关闭 redir 模式下的 DNS 服务器

### ISSUE THREAD

**Issue by 1715173329** [klzgrad/naiveproxy#129]
目前如使用 redir 模式，会同时在同端口提供一个 udp DNS 服务器，希望能够添加一个选项以关闭此功能。

**Comment by klzgrad** [comment]
不关闭对你有什么影响

**Comment by 1715173329** [comment]
我计划使用 [ipt2socks](https://github.com/zfl9/ipt2socks) 以支持 udp 通讯，目前的 DNS 服务器会造成端口占用。

**Comment by klzgrad** [comment]
1这里的socks不支持udp，2我没看出来为什么ipt2socks一定要用特定端口

**Comment by 1715173329** [comment]
https://github.com/fw876/helloworld/blob/master/luci-app-ssr-plus/root/etc/init.d/shadowsocksr#L646
以目前的设定是 TCP & UDP 使用同一端口，实在毫无必要单独指定别的 UDP 端口，而这也会使得配置更加复杂

当然，确实，据 zfl9/ipt2socks#13 所述，无法穿透 UDP 流量。

**Comment by klzgrad** [comment]
假如未来naiveproxy支持udp了，这个dns的端口自然会改掉。

我不认为naiveproxy未来会支持udp。udp代理有别的更好的方案，简单如[NaiveVPN](https://gist.github.com/klzgrad/5661b64596d003f61980)都可以实现udp代理功能。
