### ISSUE TITLE
按照教程编译的 caddy v2，使用时报错配置错误

### ISSUE THREAD

**Issue by swordsmile** [klzgrad/naiveproxy#130]
route {
  forward_proxy {
    basicauth user pass
    hide_ip
    hide_via
    probe_resistance secret.com
  }
  file_server { root /var/www/html }
}

报错信息
run: adapting config using caddyfile: parsing caddyfile tokens for 'route': Caddyfile:14 - Error during parsing: unrecognized directive: **forward_proxy**

**Comment by mixool** [comment]
操作了一遍没发现问题，试试再重新编译
支持Caddyfile了，真棒。
自用一键： https://github.com/mixool/across/blob/master/naiveproxy/naiveproxy.sh

**Comment by swordsmile** [comment]
> 操作了一遍没发现问题，试试再重新编译
> 支持Caddyfile了，真棒。
> 自用一键： https://github.com/mixool/across/blob/master/naiveproxy/naiveproxy.sh

谢谢分享，我昨天看到 forwardproxy 插件有代码更新，就重新编译了一下 caddy ，也搞定了。
