### ISSUE TITLE
通过代理无法打开https://www.atrandys.com/

### ISSUE THREAD

**Issue by Biercenter** [klzgrad/naiveproxy#133]
最近偶尔遇到有几个网站无法打开，比如上述的网址。同一个VPS上安装的NaiveProxy和vless，使用环境是leans openwrt + ssr plus。
当设置np代理的时候打不开上述网址，但是换到vless就正常。电脑用qv2ray软件设置np代理也可以正常打开。命令行运行np代理1080端口，尝试用curl通过np代理的1080端口能打开google.com的情况下还是无法打开www.atrandys.com
不知道有没有人遇到相同的问题，谢谢

**Comment by klzgrad** [comment]
看起来，没有
