### ISSUE TITLE
Error in Building Caddy with QUIC-GO

### ISSUE THREAD

**Issue by GWONGJYULEI** [klzgrad/naiveproxy#134]
Hi klzgrad,

I just got a problem in building caddy with quic-go, please reffer to the following:

> lgy@lgy-virtual-machine: git clone -b naive https://github.com/klzgrad/forwardproxy
> Cloning into 'forwardproxy'...
> remote: Enumerating objects: 13, done.
> remote: Counting objects: 100% (13/13), done.
> remote: Compressing objects: 100% (7/7), done.
> remote: Total 254 (delta 6), reused 11 (delta 6), pack-reused 241
> Receiving objects: 100% (254/254), 225.19 KiB | 1.80 MiB/s, done.
> Resolving deltas: 100% (130/130), done.
> lgy@lgy-virtual-machine: git clone -b v0.18.0 https://github.com/lucas-clemente/quic-go
> Cloning into 'quic-go'...
> remote: Enumerating objects: 110, done.
> remote: Counting objects: 100% (110/110), done.
> remote: Compressing objects: 100% (84/84), done.
> remote: Total 29373 (delta 50), reused 51 (delta 25), pack-reused 29263
> Receiving objects: 100% (29373/29373), 10.24 MiB | 2.97 MiB/s, done.
> Resolving deltas: 100% (21992/21992), done.
> Note: switching to 'd764a2574b84509a59257026e4a0e7057775ee8b'.
> 
> You are in 'detached HEAD' state. You can look around, make experimental
> changes and commit them, and you can discard any commits you make in this
> state without impacting any branches by switching back to a branch.
> 
> If you want to create a new branch to retain commits you create, you may
> do so (now or later) by using -c with the switch command. Example:
> 
>   git switch -c <new-branch-name>
> 
> Or undo this operation with:
> 
>   git switch -
> 
> Turn off this advice by setting config variable advice.detachedHead to false
> 
> lgy@lgy-virtual-machine: cd quic-go
> lgy@lgy-virtual-machine:~/quic-go$ git cherry-pick c81eeb8bb855eeba6df52660efd99be6d74e6c87
> 
> *** Please tell me who you are.
> 
> Run
> 
>   git config --global user.email "you@example.com"
>   git config --global user.name "Your Name"
> 
> to set your account's default identity.
> Omit --global to set the identity only in this repository.
> 
> fatal: unable to auto-detect email address (got 'lgy@lgy-virtual-machine.(none)')

Could you please tell me how to deal with this situation?
Thanks a lot.

**Comment by klzgrad** [comment]
Run

git config --global user.email "you@example.com"
git config --global user.name "Your Name"

to set your account's default identity.
Omit --global to set the identity only in this repository.

**Comment by GWONGJYULEI** [comment]
Thank you klzgrad!

After running following commands:
```
git config --global user.email "xxxxxxxxx@gmail.com"
git config --global user.name "xxxxxxxxx"
```

I can go through the build process, please refer to the following:
> lgy@lgy-virtual-machine:\~$ cd quic-go
> lgy@lgy-virtual-machine:\~/quic-go$ git config --global user.email "xxxxxxxxx@gmail.com"
> lgy@lgy-virtual-machine:\~/quic-go$ git config --global user.name "xxxxxxxxx"
> lgy@lgy-virtual-machine:~/quic-go$ git cherry-pick c81eeb8bb855eeba6df52660efd99be6d74e6c87
> [detached HEAD 2c036dc9] add support for the HTTP CONNECT method (#2761)
>  Author: klzgrad <kizdiv@gmail.com>
>  Date: Thu Sep 10 19:05:55 2020 +0800
>  2 files changed, 49 insertions(+), 5 deletions(-)

And I will share my experience of using QUIC with you soon.
Thanks for your help again!
