### ISSUE TITLE
naiveproxy doesn't work, no useful log produced

### ISSUE THREAD

**Issue by NightMachinary** [klzgrad/naiveproxy#138]
I have this in my Caddyfile (I removed the auth to isolate the issue, it was the same with auth enabled):
```
np2.zii.x.ir {
route {
  forward_proxy {
    # basic_auth alice abcabc # {env.NP_PASS0}
    # probe_resistance secret.com
    hide_ip
    hide_via
  }
  # file_server browse {
  #   root {env.HOME}/Downloads
  # }
}
}
```

On the client:
```
naive '--listen=socks://127.0.0.1:1080' '--proxy=https://np2.zii.x.ir' --log
[1015/233212.242259:INFO:naive_proxy_bin.cc(412)] Proxying via https://np2.zii.x.ir
[1015/233212.242791:INFO:naive_proxy_bin.cc(550)] Listening on 127.0.0.1:1080
[1015/233225.770837:INFO:naive_connection.cc(250)] Connection 1 to ipinfo.io:443
[1015/233226.370851:INFO:naive_proxy_delegate.cc(85)] Padding capability of https://np2.zii.x.ir:443 undetected
[1015/233226.371201:INFO:naive_proxy.cc(178)] Connection 1 closed: OK
```

```
❯ curl -x 'socks://127.0.0.1:1080' https://ipinfo.io                                                                        
curl: (7) SOCKS4: Failed receiving connect request ack: Failure when receiving data from the peer

❯ curl -x 'socks5://127.0.0.1:1080' https://ipinfo.io                                                                       
curl: (35) Server aborted the SSL handshake
```

There are no log messages on caddy, either.

```
❯ caddy version
v2.2.1 h1:Q62GWHMtztnvyRU+KPOpw6fNfeCD3SkwH7SfT1Tgt2c=
❯ naive --version                                                                                                         
naive 86.0.4240.75
```

**Comment by klzgrad** [comment]
Can't reproduce.

**Comment by NightMachinary** [comment]
> Can't reproduce.

Any ideas on getting more verbose logs?

**Comment by NightMachinary** [comment]
[**@klzgrad**](https://github.com/klzgrad) commented on [Oct 16, 2020, 2:42 AM GMT+3:30](https://github.com/klzgrad/naiveproxy/issues/138#issuecomment-709637255 "2020-10-15T23:12:30Z - Replied by Github Reply Comments"):
> Can't reproduce.

I tried this on another server, and had the exact same result. I also tried connecting from the first server to the second, and got this:

```
❯ curl -x 'socks5://127.0.0.1:1080' https://ipinfo.io                                                                      
curl: (35) OpenSSL SSL_connect: SSL_ERROR_SYSCALL in connection to ipinfo.io:443
```

PS: Are there any docker containers of naiveproxy?

**Comment by NightMachinary** [comment]
[**@klzgrad**](https://github.com/klzgrad) commented on [Oct 16, 2020, 2:42 AM GMT+3:30](https://github.com/klzgrad/naiveproxy/issues/138#issuecomment-709637255 "2020-10-15T23:12:30Z - Replied by Github Reply Comments"):
> Can't reproduce.

I found the problem; I needed to use `:443, np.zii.x.ir`. I had omitted `:443,`. I think you should add a warning for this, as it is not intuitive.

**Comment by NightMachinary** [comment]
[**@klzgrad**](https://github.com/klzgrad) commented on [Oct 16, 2020, 2:42 AM GMT+3:30](https://github.com/klzgrad/naiveproxy/issues/138#issuecomment-709637255 "2020-10-15T23:12:30Z - Replied by Github Reply Comments"):
> Can't reproduce.

After doing more tests, it seems using env vars is also not supported;

```
    basic_auth alice {env.NP_PASS0} # doesn't work
    # basic_auth alice abcabc # works fine
```

gives:

```
naive '--listen=socks://127.0.0.1:1080' '--proxy=https://alice:hi@np.zii.x.ir' --log
[1016/043740.255007:INFO:naive_proxy_bin.cc(412)] Proxying via https://np.zii.x.ir
[1016/043740.262513:INFO:naive_proxy_bin.cc(550)] Listening on 127.0.0.1:1080
[1016/043744.904530:INFO:naive_connection.cc(250)] Connection 1 to ipinfo.io:443
[1016/043745.655077:INFO:naive_proxy_delegate.cc(85)] Padding capability of https://np.zii.x.ir:443 undetected
[1016/043745.655472:INFO:naive_proxy.cc(178)] Connection 1 closed: ERR_PROXY_AUTH_UNSUPPORTED
```

**Comment by klzgrad** [comment]
Caddy's syntax: `np2.zii.x.ir { stuff only handles requests that matches this host }`

It is logical it wouldn't work for other hosts without :443.

**Comment by dfang** [comment]
Hi, @klzgrad 

> [Browser → Naïve (client)] ⟶ Censor ⟶ [Frontend → Naïve (server)] ⟶ Internet

:443 is used by naive server to handshake with proxied server ?

correct me if i am mistaken

**Comment by xlfjn** [comment]
@klzgrad I think the point that `:443` is mandatory in the address part of the specific [site block](https://caddyserver.com/docs/caddyfile/concepts#structure) should appear in the document. 9228d1e just miss the point.

This requirement is somehow surprising, as users might expect the scope of forward proxy to be contained within a site block with specific matching criteria. This behaviour is also not desirable for users hoping to reject requests with 'Host' headers that do not appear in the configuration.

**Comment by klzgrad** [comment]
It *is* surprising, but I didn't find a less surprising way to put it without explaining a large chunk of complexity in Caddy which is irrelevant to NaiveProxy itself.

**Comment by xlfjn** [comment]
Maybe just saying smoething like "`:443` should appear in the address part of the site block, or the proxy client will only be able to access the configured addresses of the site that runs forwardproxy." is acceptable?
Such problem usually arises when users try to add forwardproxy to their existing Caddyfile. The reduction in frustration caused by non-working software might justify surprises in README document.

**Comment by iugo** [comment]
> It _is_ surprising, but I didn't find a less surprising way to put it without explaining a large chunk of complexity in Caddy which is irrelevant to NaiveProxy itself.

An example can be given. If you do not use port 443, you only need to adjust accordingly:

```
{
  order forward_proxy before file_server
}
:12345, example.com:12345 {
  tls me@example.com
  forward_proxy {
    basic_auth user pass
    hide_ip
    hide_via
    probe_resistance
  }
  file_server {
    root /var/www/html
  }
}
```
