### ISSUE TITLE
QUIC mode software quit: Segmentation fault (core dumped)

### ISSUE THREAD

**Issue by koolwiki** [klzgrad/naiveproxy#14]
If I use QUIC mode, the software quit(the windows version quit too, without any message). HTTPS mode is OK. I run caddy like this: ./caddy -quic -conf=Caddyfile.

root@xxx:~$ naiveproxy/src/out/Release/naive --proxy=quic://user:passwd@example.com --listen=socks://127.0.0.1:1080 --padding=true
Segmentation fault (core dumped)

**Comment by klzgrad** [comment]
You need to build Caddy with QUIC support: https://github.com/klzgrad/naiveproxy/wiki/Caddy-with-QUIC.

I put out a fix that makes it fail in a nicer way.

**Comment by koolwiki** [comment]
The above result was from a Caddy server with QUIC support built by myself.

**Comment by koolwiki** [comment]
I am sorry, I made a mistake. The patch wasn't patched successfully. It works now. Thank you!
