### ISSUE TITLE
chromium代码是怎么同步下来的？

### ISSUE THREAD

**Issue by SoonyangZhang** [klzgrad/naiveproxy#141]
大佬，你好。问个和项目关系不大的问题。我比较关注quic协议。之前需要下载整个chromium代码，同步之后所有的代码大概上百G。通过你这个项目，同步下来的代码，差不多500多M。你的代码你怎么从chromium代码库中同步下来的？就是假如我从chromium编译quic的代码，有什么命令可以达到nativeproxy这个代码库的大小？不知我有没有把自己的问题描述清楚。

**Comment by klzgrad** [comment]
直接下载官方的源码包，tar解压的时候用 https://github.com/klzgrad/naiveproxy/blob/master/tools/include.txt 这个列表过滤一下文件，就算是最小化了。

你可以用官方源码包进行编译，同步代码库可能有太多历史信息导致很大。编译的时候可以用inotifywait这个命令检测有哪些文件是实际涉及的，无关的文件就可以删除了。

**Comment by SoonyangZhang** [comment]
大佬，再问个与您项目无关的问题。我采用你的库，编译Degug（build.sh debug）版本的quic库，编译器会爆出未定义符号问题：例如QuicDispatcher中的OnWriteBlocked，OnConnectionClosed，OnStopSendingReceived. 这个问题如何解决呢？

**Comment by klzgrad** [comment]
我没有碰到过这种情况，考虑是你自己的用法所致。你可以使用ninja的-v选项看clang是怎么调用的

**Comment by dfang** [comment]
@klzgrad 我也顺带问下，不是使用[chroumium network stack](https://www.chromium.org/developers/design-documents/network-stack)吗，那应该只要net文件夹下的, 可是我看到你导入了 android_webview, printing 等等这些貌似和net无关的文件夹了，所以为什么要导入这些？是因为没有这些不能编译成功吗？ include.txt 列表是你试验出来的？

**Comment by klzgrad** [comment]
去仔细看一下具体导入了什么

**Comment by dfang** [comment]
我看不懂cpp，也不了解chromium，纯碎是从src/ 文件名上看的  ^_^

**Comment by XueshiQiao** [comment]
@klzgrad  搭车请教下，如何把 naive 编译为一个独立的 static library? 我尝试改了一下，去掉 bin 里的 main 函数，然后 gn 里使用 static_library("xxx"), 不过编译出来的一些 .a 文件无法在空项目中编译通过，老是提示缺少一些库函数的引用，比如 boringssl 之类的，有没有什么建议呢？

**Comment by dfang** [comment]
可以来个telegram群组吗？clash、trojan 什么的都有

**Comment by klzgrad** [comment]
一般意义上static library本身就不是独立的，你到out/Release目录里能看见不止一个.a文件，合起来才连接成naive文件

你想达到的目的，用shared_library可能更方便一点，但也需要改动代码，才能暴露合理的接口出来

**Comment by XueshiQiao** [comment]
> 一般意义上static library本身就不是独立的，你到out/Release目录里能看见不止一个.a文件，合起来才连接成naive文件
> 
> 
> 
> 你想达到的目的，用shared_library可能更方便一点，但也需要改动代码，才能暴露合理的接口出来

多谢🙏
