### ISSUE TITLE
How to config caddy2 support multisite with naiveproxy forward proxy

### ISSUE THREAD

**Issue by bash99** [klzgrad/naiveproxy#144]
When use below configration

```Caddyfile
:443, proxy.xxx.com {
  tls xxx@xxx.com
  route {
    forward_proxy {
      basic_auth xxx yyy
      hide_ip
      hide_via
      probe_resistance xxx.yyy
    }
    file_server { root /var/www/html }
    encode zstd gzip
  }
}

www.xxx.com {
  tls xxx@xxx.com
  route {
    file_server { root /var/www/www.xxx.com }
    encode zstd gzip
  }
}
```

the second site www.xxx.com is not working, all request goes to :443 config.
But if I remove ":443," part, naiveproxy don't work.

Which is no problem in caddy 1.

**Comment by klzgrad** [comment]
This is not related to naiveproxy. Please read Caddy 2 docs.

**Comment by bash99** [comment]
> 
> 
> This is not related to naiveproxy. Please read Caddy 2 docs.

I mean, without ":443" part, multi site is OK in caddy2; but naiveproxy won't work;
add ":443" part, naiveproxy works.

I guess :443 matched all request to https port, so multi site don't work.

**Comment by dfang** [comment]
Hi, @klzgrad 

> [Browser → Naïve (client)] ⟶ Censor ⟶ [Frontend → Naïve (server)] ⟶ Internet

:443 is used by naive server to handshake with proxied server ?

correct me if i am mistaken
