### ISSUE TITLE
Android Support

### ISSUE THREAD

**Issue by arronyxzhang** [klzgrad/naiveproxy#145]
Thanks for building this tool. Is there any progress on android apps?
I think there's a huge demand for this tool from people who want to use it on Android

**Comment by mixool** [comment]
https://github.com/klzgrad/naiveproxy/issues/45

**Comment by klzgrad** [comment]
You reminded me. I estimate the cost of this piece of work to be more than 100,000 yuan before considering its market demand.

So no, I will stop any plan to implement it in the future.
