### ISSUE TITLE
最新openwrt master下提示错误 

### ISSUE THREAD

**Issue by openips** [klzgrad/naiveproxy#147]
ERROR:ssl_client_socket_impl.cc(960)] handshake failed; returned -1, SSL error code 1, net_error -100
INFO:naive_proxy.cc(177)] Connection 21 closed: ERR_PROXY_CONNECTION_FAILED

之前的系统没这样的提示  账号密码完全正确 配置文件在老版本的系统中一切正常 不知道哪个文件出问题了

![image](https://user-images.githubusercontent.com/47168453/97307472-b4116080-189a-11eb-9a0d-18664f8fd392.png)

**Comment by klzgrad** [comment]
什么信息都没有，把环境交代清楚

**Comment by klzgrad** [comment]
1. 你的naive是从哪下载的
2. 你的openwrt运行在什么硬件上

**Comment by openips** [comment]
1、naive下载地址https://github.com/klzgrad/naiveproxy/releases/download/v86.0.4240.75-1/naiveproxy-v86.0.4240.75-1-linux-x64.tar.xz
2、运行在pve下x64虚拟机
3、更新到最新的系统之后可以用了 我也不太明白怎么回事
