### ISSUE TITLE
最新openwrt master下配合openclash提示错误 

### ISSUE THREAD

**Issue by openips** [klzgrad/naiveproxy#151]
1、naive下载地址https://github.com/klzgrad/naiveproxy/releases/download/v86.0.4240.75-1/naiveproxy-v86.0.4240.75-1-linux-x64.tar.xz
2、运行在pve下x64虚拟机和物理机
3、更新到最新的系统之后可以openclash检测可以通过 但是选择节点后直接报错 导致不可用

ERROR:ssl_client_socket_impl.cc(960)] handshake failed; returned -1, SSL error code 1, net_error -100
INFO:naive_proxy.cc(177)] Connection 21 closed: ERR_PROXY_CONNECTION_FAILED

之前的系统没这样的提示 账号密码完全正确 配置文件在老版本的系统中一切正常 不知道哪个文件出问题了

![image](https://user-images.githubusercontent.com/47168453/99136363-53866f80-265f-11eb-9a32-6d15d28cb656.png)
固件版本：OpenWrt SNAPSHOT r14777-c4ab1b7dd9 / LuCI Master git-20.295.56858-b0fe11f
opkg list-installed
base-files - 233-r14777-c4ab1b7dd9
bash - 5.0-4
bind-client - 9.16.7-1
bind-libs - 9.16.7-1
bnx2-firmware - 20200918-1
busybox - 1.31.1-5
ca-bundle - 20200601-1
ca-certificates - 20200601-1
cgi-io - 2020-10-11-d2907bd1-19
coreutils - 8.32-3
coreutils-nohup - 8.32-3
curl - 7.72.0-2
ddns-scripts - 2.8.2-3
ddns-scripts-cloudflare - 2.8.2-3
ddns-scripts-cnkuai - 2.8.2-3
ddns-scripts-digitalocean - 2.8.2-3
ddns-scripts-freedns - 2.8.2-3
ddns-scripts-godaddy - 2.8.2-3
ddns-scripts-noip - 2.8.2-3
ddns-scripts-nsupdate - 2.8.2-3
ddns-scripts-route53 - 2.8.2-3
ddns-scripts-services - 2.8.2-3
dnsmasq-full - 2.82-7
dropbear - 2020.80-3
e2fsprogs - 1.45.6-1
firewall - 2020-09-05-8c2f9fad-1
frpc - 0.34.0-1
fstools - 2020-10-16-f25ab8a8-1
fwtool - 2019-11-12-8f7fe925-1
getrandom - 2020-10-25-9ef88681-1
giflib-utils - 5.2.1-1
grub2 - 2.04-3
grub2-efi - 2.04-3
hostapd - 2020-06-08-5a8b3662-12
hostapd-common - 2020-06-08-5a8b3662-12
ip-full - 5.8.0-1
iperf3 - 3.7-1
ipset - 7.6-1
iptables - 1.8.4-1
iptables-mod-extra - 1.8.4-1
iptables-mod-tproxy - 1.8.4-1
iw - 5.8-1
jshn - 2020-08-06-9e52171d-1
jsonfilter - 2018-02-04-c7e938d6-1
kernel - 5.4.72-1-bfed297b030f2f532579b01f56fbfcd6
kmod-bnx2 - 5.4.72-1
kmod-button-hotplug - 5.4.72-3
kmod-cfg80211 - 5.4.72+5.8-1-1
kmod-crypto-acompress - 5.4.72-1
kmod-crypto-aead - 5.4.72-1
kmod-crypto-ecb - 5.4.72-1
kmod-crypto-hash - 5.4.72-1
kmod-crypto-manager - 5.4.72-1
kmod-crypto-michael-mic - 5.4.72-1
kmod-crypto-null - 5.4.72-1
kmod-crypto-pcompress - 5.4.72-1
kmod-e1000 - 5.4.72-1
kmod-e1000e - 5.4.72-1
kmod-eeprom-93cx6 - 5.4.72-1
kmod-fs-vfat - 5.4.72-1
kmod-hwmon-core - 5.4.72-1
kmod-i2c-algo-bit - 5.4.72-1
kmod-i2c-core - 5.4.72-1
kmod-igb - 5.4.72-1
kmod-igbvf - 5.4.72-1
kmod-input-core - 5.4.72-1
kmod-ipt-conntrack - 5.4.72-1
kmod-ipt-core - 5.4.72-1
kmod-ipt-extra - 5.4.72-1
kmod-ipt-ipset - 5.4.72-1
kmod-ipt-nat - 5.4.72-1
kmod-ipt-offload - 5.4.72-1
kmod-ipt-tproxy - 5.4.72-1
kmod-iptunnel - 5.4.72-1
kmod-ixgbe - 5.4.72-1
kmod-ixgbevf - 5.4.72-1
kmod-ledtrig-default-on - 5.4.72-1
kmod-ledtrig-heartbeat - 5.4.72-1
kmod-ledtrig-netdev - 5.4.72-1
kmod-ledtrig-timer - 5.4.72-1
kmod-lib-crc-ccitt - 5.4.72-1
kmod-lib-lz4 - 5.4.72-1
kmod-lib-lzo - 5.4.72-1
kmod-libphy - 5.4.72-1
kmod-mac80211 - 5.4.72+5.8-1-1
kmod-mdio - 5.4.72-1
kmod-mii - 5.4.72-1
kmod-nf-conntrack - 5.4.72-1
kmod-nf-conntrack-netlink - 5.4.72-1
kmod-nf-flow - 5.4.72-1
kmod-nf-ipt - 5.4.72-1
kmod-nf-ipt6 - 5.4.72-1
kmod-nf-nat - 5.4.72-1
kmod-nf-reject - 5.4.72-1
kmod-nfnetlink - 5.4.72-1
kmod-nls-base - 5.4.72-1
kmod-nls-cp437 - 5.4.72-1
kmod-nls-cp936 - 5.4.72-1
kmod-nls-iso8859-1 - 5.4.72-1
kmod-nls-utf8 - 5.4.72-1
kmod-phy-realtek - 5.4.72-1
kmod-ppp - 5.4.72-1
kmod-pppoe - 5.4.72-1
kmod-pppox - 5.4.72-1
kmod-pps - 5.4.72-1
kmod-ptp - 5.4.72-1
kmod-r8169 - 5.4.72-1
kmod-random-core - 5.4.72-1
kmod-rt2800-lib - 5.4.72+5.8-1-1
kmod-rt2800-mmio - 5.4.72+5.8-1-1
kmod-rt2800-pci - 5.4.72+5.8-1-1
kmod-rt2800-usb - 5.4.72+5.8-1-1
kmod-rt2x00-lib - 5.4.72+5.8-1-1
kmod-rt2x00-mmio - 5.4.72+5.8-1-1
kmod-rt2x00-pci - 5.4.72+5.8-1-1
kmod-rt2x00-usb - 5.4.72+5.8-1-1
kmod-rtl8821ae - 5.4.72+5.8-1-1
kmod-rtlwifi - 5.4.72+5.8-1-1
kmod-rtlwifi-btcoexist - 5.4.72+5.8-1-1
kmod-rtlwifi-pci - 5.4.72+5.8-1-1
kmod-slhc - 5.4.72-1
kmod-tun - 5.4.72-1
kmod-udptunnel4 - 5.4.72-1
kmod-usb-core - 5.4.72-1
kmod-vmxnet3 - 5.4.72-1
kmod-vxlan - 5.4.72-1
kmod-zram - 5.4.72-1
libatomic1 - 8.4.0-2
libblkid1 - 2.36-2
libblobmsg-json - 2020-08-06-9e52171d-1
libc - 1.1.24-2
libcap - 2.43-1
libcap-bin - 2.43-1
libcap-ng - 0.8-1
libcomerr0 - 1.45.6-1
libcurl4 - 7.72.0-2
libelf1 - 0.179-1
libext2fs2 - 1.45.6-1
libf2fs6 - 1.13.0-1
libgcc1 - 8.4.0-2
libgmp10 - 6.1.2-2
libip4tc2 - 1.8.4-1
libip6tc2 - 1.8.4-1
libipset13 - 7.6-1
libiwinfo-lua - 2020-06-03-2faa20e5-1
libiwinfo20200105 - 2020-06-03-2faa20e5-1
libjson-c5 - 0.15-1
libjson-script - 2020-08-06-9e52171d-1
liblua5.1.5 - 5.1.5-7
liblucihttp-lua - 2019-07-05-a34a17d5-1
liblucihttp0 - 2019-07-05-a34a17d5-1
libmbedtls12 - 2.16.8-1
libmnl0 - 1.0.4-2
libncurses6 - 6.2-1
libnetfilter-conntrack3 - 2018-05-01-3ccae9f5-2
libnettle7 - 3.5.1-2
libnfnetlink0 - 1.0.1-3
libnl-tiny - 2019-10-29-0219008c-1
libnss - 3.57-1
libopenssl-conf - 1.1.1h-1
libopenssl1.1 - 1.1.1h-1
libpcre - 8.44-2
libpthread - 1.1.24-2
libreadline8 - 8.0-1
librt - 1.1.24-2
libsmartcols1 - 2.36-2
libsqlite3-0 - 3330000-1
libss2 - 1.45.6-1
libstdcpp6 - 8.4.0-2
libubox20191228 - 2020-08-06-9e52171d-1
libubus-lua - 2020-10-25-ad0cd117-1
libubus20191227 - 2020-10-25-ad0cd117-1
libuci20130104 - 2020-04-24-ec8d3233-3
libuclient20160123 - 2020-06-17-c6609861-1
libuuid1 - 2.36-2
libuv1 - 1.40.0-1
libwolfssl24 - 4.5.0-stable-2
libxml2 - 2.9.10-2
libxtables12 - 1.8.4-1
logd - 2020-10-25-9ef88681-1
lua - 5.1.5-7
luci - git-20.191.33648-4ddcb36
luci-app-ddns - git-20.276.45020-e478875
luci-app-firewall - git-20.191.33648-4ddcb36
luci-app-frpc - git-20.191.33648-4ddcb36
luci-app-openclash - 0.40.14-beta
luci-app-openvpn - git-20.247.45220-51621a3
luci-app-opkg - git-20.191.33648-4ddcb36
luci-app-smartdns - 1.2020.30
luci-app-upnp - git-20.191.33648-4ddcb36
luci-base - git-20.295.56858-b0fe11f
luci-compat - git-20.202.51826-133a1ae
luci-i18n-base-zh-cn - git-20.300.67438-a759402
luci-i18n-ddns-zh-cn - git-20.297.59209-71a8de9
luci-i18n-firewall-zh-cn - git-20.291.62968-5724756
luci-i18n-frpc-zh-cn - git-20.293.73466-0700063
luci-i18n-openvpn-zh-cn - git-20.295.36544-7d15284
luci-i18n-opkg-zh-cn - git-20.300.67438-a759402
luci-i18n-smartdns-zh-cn - git-20.258.10017-f277058
luci-i18n-upnp-zh-cn - git-20.281.27806-e06c7b6
luci-lib-base - git-20.201.65675-68521fc
luci-lib-ip - git-20.250.76529-62505bd
luci-lib-ipkg - git-20.191.33648-4ddcb36
luci-lib-jsonc - git-20.191.33648-4ddcb36
luci-lib-nixio - git-20.234.06894-c4a4e43
luci-mod-admin-full - git-20.191.33648-4ddcb36
luci-mod-network - git-20.282.02609-6c9a6c3
luci-mod-status - git-20.191.33648-4ddcb36
luci-mod-system - git-20.280.34248-a75ae38
luci-proto-ppp - git-20.191.33648-4ddcb36
luci-proto-vxlan - git-20.191.33648-4ddcb36
luci-theme-bootstrap - git-20.229.69577-258e74c
luci-theme-material - git-20.229.69577-258e74c
miniupnpd - 2.1.20200510-5
mkf2fs - 1.13.0-1
mtd - 26
naiveproxy - 86.0.4240.75-1-3
netifd - 2020-10-22-24ce1eab-1
nspr - 4.29-1
openssl-util - 1.1.1h-1
openwrt-keyring - 2019-07-25-8080ef34-1
opkg - 2020-08-31-cf44c2fe-1
partx-utils - 2.36-2
ppp - 2.4.8.git-2020-10-03-2
ppp-mod-pppoe - 2.4.8.git-2020-10-03-2
procd - 2020-10-25-33b799b9-1
r8169-firmware - 20200918-1
rpcd - 2020-09-18-3fea6559-2
rpcd-mod-file - 2020-09-18-3fea6559-2
rpcd-mod-iwinfo - 2020-09-18-3fea6559-2
rpcd-mod-luci - 20191114
rpcd-mod-rrdns - 20170710
rt2800-pci-firmware - 20200918-1
rt2800-usb-firmware - 20200918-1
rtl8821ae-firmware - 20200918-1
smartdns - 1.2020.30-1
terminfo - 6.2-1
ubox - 2020-10-25-9ef88681-1
ubus - 2020-10-25-ad0cd117-1
ubusd - 2020-10-25-ad0cd117-1
uci - 2020-04-24-ec8d3233-3
uclient-fetch - 2020-06-17-c6609861-1
uhttpd - 2020-10-04-14a3cb42-2
uhttpd-mod-ubus - 2020-10-04-14a3cb42-2
urandom-seed - 2
urngd - 2020-01-21-c7f7b6b6-1
usign - 2020-05-23-f1f65026-1
uwsgi - 2.0.19.1-1
uwsgi-cgi-plugin - 2.0.19.1-1
uwsgi-luci-support - 2.0.19.1-1
uwsgi-syslog-plugin - 2.0.19.1-1
vxlan - 6
wget - 1.20.3-4
wireless-regdb - 2020.04.29-1
wpa-cli - 2020-06-08-5a8b3662-12
wpa-supplicant - 2020-06-08-5a8b3662-12
zlib - 1.2.11-3
zoneinfo-asia - 2020c-1

请大神有时间调查一下 感觉可能是
iptables-mod-extra - 1.8.4-1
引起的问题
这是组新版的openclash需要的依赖。老版本的openclash没有这样的问题
谢谢

**Comment by klzgrad** [comment]
不了解openclash是什么

**Comment by openips** [comment]
问题是 sock5在最新的master版本op下报错

**Comment by klzgrad** [comment]
我认为这不是naive的问题。只有引入了openclash才出现问题的话，应该是openclash的问题。

**Comment by lifansama** [comment]
今天重装openwrt后也遇到了这个问题，但折腾了半天之后又自己好了。
怀疑很可能是fake-ip的问题
