### ISSUE TITLE
[Question] how naive hide what user trying to connect

### ISSUE THREAD

**Issue by dfang** [klzgrad/naiveproxy#152]
Hi, thank you for making this brilliant tool. it works very well. but im trying to learn more details. 

AFAIK, [TLS does not hide the url what u trying to access](https://security.stackexchange.com/questions/7705/does-ssl-tls-https-hide-the-urls-being-accessed), how naive-proxy did this ?

**Comment by dfang** [comment]
oh, i got it

it's ok to expose the frontend url, the content is **encrypted** by tls.

smart guy ！！！

**Comment by dfang** [comment]
which tls version did naive proxy use ？ can i specify it as TLS 1.3 ？

**Comment by klzgrad** [comment]
Naiveproxy is oblivious to TLS version.
