### ISSUE TITLE
编译问题

### ISSUE THREAD

**Issue by fuqiang03** [klzgrad/naiveproxy#154]
https://github.com/klzgrad/naiveproxy/blob/9a508ee49d7ae619ccfa76cb121d2217d12a1390/src/buildtools/third_party/libc%2B%2B/trunk/include/support/musl/xlocale.h#L27

![20201201224857](https://user-images.githubusercontent.com/26851715/100755818-8b473280-3427-11eb-8565-b2b6f44dacd2.png)
内核4.14 gcc7.3-glibc
貌似和什么冲突了

**Comment by klzgrad** [comment]
你在编译某种openwrt环境，但又用glibc？这跟你环境有关系

**Comment by fuqiang03** [comment]
strtoll_l和wcstoll_l是自定义的函数吗  如果是 我修改会有影响吗

**Comment by klzgrad** [comment]
我在问你用什么openwrt环境，不告诉我便无法解决这个问题

**Comment by fuqiang03** [comment]
openwrt 18.06 分支

**Comment by fuqiang03** [comment]
在op的主库下同样的函数也报错了 87.0.4280.66-1版本
![image](https://user-images.githubusercontent.com/26851715/101392286-88a17d00-3900-11eb-9ff4-ec2645708dff.png)

**Comment by klzgrad** [comment]
第三方重新打包的代码我无法支持。如果单独提出在openwrt中支持某个设备，我可以支持。

**Comment by darhwa** [comment]
用get-clang.sh拖下来的clang编译有什么问题，为什么要用gcc？

你不会是在尝试用跑openwrt的arm设备来编译naive吧？

**Comment by fuqiang03** [comment]
@darhwa 
我的是路由器固件arm7构架 因为一开始 编译的时候一直在使用glibc库(openwrt18.06) 这样我可以编译个直接适合的二进制文件 或许可以在压缩下 以便适应我那可怜的路由器空间 发现clang对gcc 的链接貌似有什么问题
![QQ截图20201213225409](https://user-images.githubusercontent.com/26851715/102015361-26c89380-3d96-11eb-9e7d-b9635842755f.png)
