### ISSUE TITLE
建议采用git submodule引入chromium

### ISSUE THREAD

**Issue by proxy-rules** [klzgrad/naiveproxy#155]
目前引入chromium会rebase分支，导致forks代码差异，这样使得难以社区协作，因此建议采用git submodule引入chromium。

https://github.com/klzgrad/naiveproxy/blob/9a508ee49d7ae619ccfa76cb121d2217d12a1390/tools/import-upstream.sh#L28

**Comment by klzgrad** [comment]
使用git submodule则无法以commit的形式组织代码补丁序列。

如果rebase到chromium上游的commit树，则代码库历史会巨大无比，难以管理。现在的做法是每当Chrome发布稳定版，则以该稳定版的扁平源代码作为commit根节点。

如果你有关于社区协作的特定用法，可以提出来看看怎么支持。
