### ISSUE TITLE
讨论：之前某群人发现的Naiveproxy不同于浏览器的行为

### ISSUE THREAD

**Issue by nobtree2333333** [klzgrad/naiveproxy#157]
我就是上次提到NaiveProxy的行为和浏览器不同的那位。

上次我没说清楚我对象跟我提到的那个发现的NaiveProxy的弱点是怎么回事，这次直接说清楚。

NaiveProxy和浏览器的行为不同在于：假设一个浏览器的HTTPS连接被阻断，那么再次和服务器连接时，浏览器会重新开始https握手过程（相当于从零开始重新连接）。

但NaiveProxy在这里表现出了异常：它直接开始发送加密数据，没有握手这个步骤，就好像没有意识到需要重新握手连接。

因此，可以用一个方法检查NaiveProxy：那就是主动的阻断HTTPS连接，然后观察被阻断的连接是否会立即发送加密数据而不是重新连接，如果是立即发送加密数据而非重新开始握手和连接，那就判别为NaiveProxy。

这个检查方法来自于腾讯云那些专门做七层流量识别的人，他们转告给我对象，然后我发到这里的。

**Comment by NetHeritage** [comment]
If using naive to download large files, connections may be temporarily terminated and downloading will fail.  Then user have to resume downloading manually. This phenomenon happened quite offen.
I am not sure  weather this is related to the issue mentioned above. It looks like so.

**Comment by nobtree2333333** [comment]
> If using naive to download large files, connections may be temporarily terminated and downloading will fail.
> This phenomenon happened quite offen. Not sure weather this is related to the mechanism of naive mentioned above.

Translate with deepl

i don't know

If using naive to download large files, connections may be temporarily terminated and downloading will fail.
This phenomenon happened quite offen. Not sure weather this is related to the mechanism of naive mentioned above.

**Comment by klzgrad** [comment]
> 它直接开始发送加密数据，没有握手这个步骤

与事实不符

**Comment by NetHeritage** [comment]
在北京联通、教育网、天津联通、北京电信等不同网络环境下，使用naive代理Firefox Chrome等浏览器下载大于500MB的文件，每次都会中断，不知道是为什么
