### ISSUE TITLE
Nginx instead of caddy

### ISSUE THREAD

**Issue by qana87** [klzgrad/naiveproxy#159]
There are unofficial modules around which can turn nginx into a forward proxy. Also nginx itself can forward traffic on layer 4 with the stream option. Can it be used instead of caddy?

**Comment by klzgrad** [comment]
No, Nginx has very poor support for HTTP/2 proxying.

**Comment by XuuKoo** [comment]
> 
> 
> No, Nginx has very poor support for HTTP/2 proxying.

haproxy怎么样？

**Comment by XuuKoo** [comment]
> 
> 
> No, Nginx has very poor support for HTTP/2 proxying.

haproxy怎么样？

**Comment by klzgrad** [comment]
HAProxy一直都可以 https://github.com/klzgrad/naiveproxy/wiki/HAProxy-Setup

**Comment by kousyougi** [comment]
我最近从caddy换到haproxy了。没有客观测试，但haproxy方案好像比caddy方案快。
