### ISSUE TITLE
windows build error

### ISSUE THREAD

**Issue by omengye** [klzgrad/naiveproxy#16]
error message:
```bash
ERROR at //third_party/protobuf/proto_library.gni:369:15: Only source, header, and object files belong in the sources of a static_library. //out/Release/pyproto/google_apis/gcm/protocol/mcs_pb2.py is not one of the valid types.
    sources = get_target_outputs(":$action_name")
              ^---------------------------------
See //google_apis/gcm/BUILD.gn:78:1: whence it was called.
proto_library("proto") {
^-----------------------
See //BUILD.gn:83:7: which caused the file to be included.
      "//google_apis/gcm:gcm_unit_tests",
      ^---------------------------------
```
the chromium version is 74.0.3729.108 and ninja version is 1.9.0, i use v74.0.3729.108-1 git branch. but when i run ./build.sh i got this error. how to solve this problem? thank you.

**Comment by klzgrad** [comment]
There are binary builds you can use. Otherwise I don't know your setup. In here https://github.com/klzgrad/naiveproxy/blob/master/.appveyor.yml you see exactly how it's built with this error you had.

**Comment by omengye** [comment]
there are something strage about gn. i found the same problem here: https://gn.googlesource.com/gn/+/8730b0feb6b991fa47368566501ab9ccfb453c92.
so i thought that was the problem caused by the version of gn? the master branch of git is using the lasted gn version, so i try to download an older version of gn (https://chrome-infra-packages.appspot.com/p/gn/gn/windows-amd64/+/xrm16qCsJ9iGGUPXV8XZbjylsZPNjPfpMCAPRadEkrQC), then the problem has been fixed. 
thank you for your reply.

**Comment by klzgrad** [comment]
gn has indeed had a breaking change: https://bugs.chromium.org/p/gn/issues/detail?id=77.

I've changed the build script to use the gn version shipped in the release tarball instead of the latest gn.
