### ISSUE TITLE
naiveproxy没有走系统内置的DNS

### ISSUE THREAD

**Issue by ymcoming** [klzgrad/naiveproxy#160]
vps本身不能看netflix非自制剧，所以通过解锁DNS的方式来看netflix，就是把/etc/reslov.conf的dnsname改成专用解锁的IP。

在这种情况下，通过naiveproxy连接后，仍然无法收看非自制剧netflix。而同一个VPS下部署的v2ray则能收看。给人的感觉是naiveproxy绕过了/etc/reslov.conf指定的DNS，所以导致解锁失败。

----------呃，我是在openwrt passwall下测试的。刚才发了贴后，用Qv2ray的naive插件连接，则能看netflix非自制剧。。。说明是passwall下的naive插件有问题。不好意思！

**Comment by ymcoming** [comment]
已解决

**Comment by tefiszx** [comment]
> 已解决

请问是怎么解决openwrt下的DNS解锁netflix的问题的？

**Comment by NeedforGit** [comment]
> 已解决

兄弟你好，请问怎样解决 navieproxy 的 dns解锁网飞的问题？这个问题一直困扰着我，希望兄弟能帮一下忙，感谢！

**Comment by AmberisMyShiba** [comment]
> > 已解决
> 
> 兄弟你好，请问怎样解决 navieproxy 的 dns解锁网飞的问题？这个问题一直困扰着我，希望兄弟能帮一下忙，感谢！

我是用openwrt才会有naive不能dns解锁的问题，解决办法是让naive节点成为上游dns。我不知道你的使用环境是什么，所以我的解决方案不一定适合你。

**Comment by NeedforGit** [comment]
> > > 已解决
> > 
> > 
> > 兄弟你好，请问怎样解决 navieproxy 的 dns解锁网飞的问题？这个问题一直困扰着我，希望兄弟能帮一下忙，感谢！
> 
> 我是用openwrt才会有naive不能dns解锁的问题，解决办法是让naive节点成为上游dns。我不知道你的使用环境是什么，所以我的解决方案不一定适合你。

感谢回复，我用的是 openwrt 上的 passwall.

"解决办法是让naive节点成为上游dns"  这种在 passwall 上好解决吗？

**Comment by AmberisMyShiba** [comment]
> > > > 已解决
> > > 
> > > 
> > > 兄弟你好，请问怎样解决 navieproxy 的 dns解锁网飞的问题？这个问题一直困扰着我，希望兄弟能帮一下忙，感谢！
> > 
> > 
> > 我是用openwrt才会有naive不能dns解锁的问题，解决办法是让naive节点成为上游dns。我不知道你的使用环境是什么，所以我的解决方案不一定适合你。
> 
> 感谢回复，我用的是 openwrt 上的 passwall.
> 
> "解决办法是让naive节点成为上游dns" 这种在 passwall 上好解决吗？

在naive上运行dnsmasq，在passwall上把dns解析IP改为naive节点IP和dnsmasq的监听端口
