### ISSUE TITLE
json配置用户与密码名称改变引起的无法启动问题

### ISSUE THREAD

**Issue by lxhao61** [klzgrad/naiveproxy#161]
采用最新插件编译的服务端，用json配置发现无法启动；改成Caddyfile配置，启动正常。调出Caddyfile自动转换的json文件，发现原json中auth_user改成了auth_user_deprecated，auth_pass改成了auth_pass_deprecated。不知道大神是否恢复原来的名称？

**Comment by zjy7723** [comment]
同样，升级后用原先的json配置文件启动失败，改用Caddyfile配置文件正常。

**Comment by klzgrad** [comment]
请按照上游的安排使用新的json语法。

**Comment by ymcoming** [comment]
deprecated----不推荐使用？那有用户认证新的参数吗？

**Comment by klzgrad** [comment]
上游做这个更改的原因是他要把forwardproxy的认证接入到Caddy标准的认证模块，但是暂时还没有完成
