### ISSUE TITLE
是否支持由op源码主分支编译完成？

### ISSUE THREAD

**Issue by happy201807** [klzgrad/naiveproxy#165]
请问arm64 设备 rk3399的r4s 用helloworld 原生编译二进制可以正常使用吗？
尝试用您预构建的naive替换固件自带的，提示/usr/bin/ read only file system ，请问可以怎么做？

**Comment by klzgrad** [comment]
helloworld 原生编译是什么？我没听说过。

预构建的naive，具体是哪个？

提示/usr/bin/ read only file system，怎么运行的？请帖原始输出，不要转述。
