### ISSUE TITLE
[FR] Use direct connections for sites in specific countries

### ISSUE THREAD

**Issue by NightMachinary** [klzgrad/naiveproxy#167]
Having sth like https://www.v2ray.com/en/configuration/routing.html can be very useful. (I know v2ray itself could be paired with the naive client, but v2ray somehow causes my connections to become much slower, so I am avoiding it at all costs.)

**Comment by klzgrad** [comment]
Maintaining such a list is very hard work. Creating mechanisms that support with such lists involves similar complexity. So you have to demonstrate why this can't be solved with in-browser proxy switching.

**Comment by NightMachinary** [comment]
@klzgrad I debugged my v2ray config, and the problem was with DNS; v2ray could not resolve the DNS names through the socks5 proxy. (It's probably a bug in v2ray.) I am closing the issue, as my v2ray config now works.
