### ISSUE TITLE
Working as a tunnel

### ISSUE THREAD

**Issue by vcarus** [klzgrad/naiveproxy#168]
Thanks for your development. 

There's a little question if I may propose. Is it possible to make NaïveProxy working as a tunnel?

Traffic must be encrypted locally and decrypt on the remote server.
I have a relay server listening on some specific ports.
I'd like to tunnel the traffic on the specific port through NaïveProxy to destination server.

[Browser → Local Proxy(encrypt)] ⟶ Internet ⟶ [Naïve(relay server)] ⟶ Censor ⟶ [Frontend → Naïve(remote server) → Local Proxy(decrypt)] ⟶ Internet

But I can't figure out how to setup the relay server. Hope you might help me. Thanks.

**Comment by klzgrad** [comment]
What kind of protocol comes out of Local Proxy(encrypt)?

**Comment by vcarus** [comment]
Just TCP. 

A self made encryption protocol running on TCP with SM2 algorithm.
It looks suspicious among other normal traffic. So I wonder if I can use NaïveProxy as a tunnel.

**Comment by klzgrad** [comment]
The protocol out of Local Proxy(encrypt) must carry the address of the remote server, so TCP is not enough. Think of something else.

**Comment by vcarus** [comment]
Local Proxy(encrypt) is designed like shadowsocks which can work independently but by another encryption algorithm.
And, the TCP traffic comes with address of the remote server of course.

The problem is whether I can make a NaïveProxy tunnel over it on a relay server. 
Thanks.
