### ISSUE TITLE
Add to Homebrew

### ISSUE THREAD

**Issue by NightMachinary** [klzgrad/naiveproxy#170]
Homebrew works across both Linux and macOS. Having `naive` in Homebrew makes installing and upgrading it a breeze.

**Comment by klzgrad** [comment]
I have no idea how to do it.

**Comment by NightMachinary** [comment]
[**@klzgrad**](https://github.com/klzgrad) commented on [Mar 18, 2021, 6:21 PM GMT+3:30](https://github.com/klzgrad/naiveproxy/issues/170#issuecomment-801992059 "2021-03-18T14:51:28Z - Replied by Github Reply Comments"):
> I have no idea how to do it.

Hmm ... Perhaps just add a self-upgrade function to the binary, where the binary periodically checks Github for new releases, and downloads them? 

I myself have no experience with creating Homebrew packages, but I'll look into it when I have the time.

**Comment by klzgrad** [comment]
Self-upgrade, no. Nothing stops it from self-upgrading into a virus.
