### ISSUE TITLE
建议

### ISSUE THREAD

**Issue by dylanhowl** [klzgrad/naiveproxy#172]
作者你好,我并不是Geek,一直喜欢这个项目的理念.但因为caddy v2与forwardproxy等让小白来安装与配置相对复杂,所以想请求看能否:用lighthttp或其他处理外部请求,后发往后部naiveproxy,这样精简一些东西,可能的话能有一键安装脚本就更好了.
异想天开,作者勿恼!

**Comment by dylanhowl** [comment]
实在喜欢trojan那样,申请个证书放个配置就行了.

**Comment by klzgrad** [comment]
这个项目是实验性的。其他人气更高的项目会更注重易用性。
