### ISSUE TITLE
Help eror build openwrt ramips mipsel24kc

### ISSUE THREAD

**Issue by predators46** [klzgrad/naiveproxy#173]
` ERROR at //build/util/version.gni:73:11 (//build/toolchain/linux:clang_x64): Could not execute interpreter. _result = exec_script("version.py", ^---------- I was trying to execute "/home/ubuntu/uu/staging_dir/hostpkg/bin/python3". See //ui/gl/features.gni:8:1: whence it was imported. import("//build/util/version.gni") ^-------------------------------- See //gpu/command_buffer/client/BUILD.gn:5:1: whence it was imported. import("//ui/gl/features.gni") ^---------------------------- See //third_party/blink/renderer/platform/BUILD.gn:152:5: which caused the file to be included. "//gpu/command_buffer/client:client", ^----------------------------------- ninja: Entering directoryout/Release'
ninja: error: loading 'build.ninja': No such file or directory
Makefile:148: recipe for target '/home/ubuntu/uu/build_dir/target-mipsel_24kc_musl/naiveproxy-89.0.4389.72-1/.built' failed
make[2]: *** [/home/ubuntu/uu/build_dir/target-mipsel_24kc_musl/naiveproxy-89.0.4389.72-1/.built] Error 1 `   `

**Comment by klzgrad** [comment]
It requires python2. Try to provide python2 to the build system.

**Comment by predators46** [comment]
> It requires python2. Try to provide python2 to the build system.

https://github.com/immortalwrt/openwrt-naiveproxy/tree/master/naiveproxy

**Comment by klzgrad** [comment]
I have no idea what this link is meant to tell.

**Comment by 1715173329** [comment]
Python3 is okay...
btw, this package won't work on openwrt 19.07 or lower.
