### ISSUE TITLE
请教这是什么

### ISSUE THREAD

**Issue by NetHeritage** [klzgrad/naiveproxy#174]
![image](https://user-images.githubusercontent.com/588329/112722872-cb866f80-8f46-11eb-8d29-cd230973d169.png)

请教  软件有时候会这样显示  但似乎不影响使用   关掉后重新打开   可能就不这样了
这是为什么呢

**Comment by NetHeritage** [comment]
只在使用https模式时候会出现这种现象  使用quic模式时从没遇到过

**Comment by klzgrad** [comment]
HTTP2服务器的默认设置中对上传带宽限制得比较小，所以在测上行速或者上传大文件的时候有这类问题，但是又不敢去改服务器的设置，因为现在的默认设置是大多数人用的，区分度比较小。
