### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by NetHeritage** [klzgrad/naiveproxy#176]
您好，请问，是否可以给本地socks 5添加验证呢？
（隐约记得之前有人提过，但没找到链接了。）

这个特性，在特定场景下会很有用。

如，在公司的大局域网的某台设备上运行naiveproxy客户端，知道密码的同事可以使用，其他人无法使用。

再如，在国内的VPS上部署naiveproxy客户端，本地设备上的软件直接连接该vps，而无需在本地的电脑或者路由器上运行naiveproxy客户端。
（socks 5是明文的，但现在很多流量都是加密的，旁观者也不太容易观察到传输了什么。）

这个特性预计对naiveproxy本身的安全性和隐蔽性影响也很小。

希望您能考虑！

非常感谢!

**Comment by klzgrad** [comment]
可以

**Comment by klzgrad** [comment]
https://github.com/klzgrad/naiveproxy/issues/33#issuecomment-582342131
https://bugs.chromium.org/p/chromium/issues/detail?id=256785
https://bugzilla.mozilla.org/show_bug.cgi?id=122752

你要介绍一下你准备怎么使用这个功能？

**Comment by NetHeritage** [comment]
确实，Firefox和Chrome目前不支持Socks5密码鉴权，会让这个功能的使用场景大大受限。
但还是有不少软件支持的，如Dropbox、Proxifier、Telegram(Microsoft Store版及iOS版)、WinSCP、Putty…等等。

**Comment by klzgrad** [comment]
https://github.com/klzgrad/naiveproxy/releases/tag/v89.0.4389.72-2

**Comment by NetHeritage** [comment]
感谢大神！
