### ISSUE TITLE
JA3 TLS Fingerprint Inconsistent with Chrome

### ISSUE THREAD

**Issue by Warren772** [klzgrad/naiveproxy#177]
Hello, I may be entirely misunderstanding the concept of the project and if so, I apologize in advance. 

I have the _naiveproxy client_ running and am using the socks5 proxy to connect to the internet. The naiveproxy server is working correctly, as it provides the IP address of the server upon lookup. However, I performed a curl request to retrieve the [JA3 fingerprint of the connection](https://ja3er.com/), and the hash indicated the connection has been made with the curl.

![Curl Request](https://user-images.githubusercontent.com/33537446/115309011-ab0e9700-a139-11eb-8b4d-4252385c106c.PNG)

![JA3 Lookup](https://user-images.githubusercontent.com/33537446/115309031-b235a500-a139-11eb-8ed7-aff305fd40fd.PNG)

Again, from reading the README, I would think that the resulting JA3 fingerprint would result in a hash originating from the Chrome browser, as naiveproxy emulates those signatures.

**Comment by klzgrad** [comment]
Your curl connection is inside a tunnel connection. The tunnel connection has Chrome's ClientHello, but the curl connection has curl's ClientHello. JA3 does not see the tunnel connection. The censor does not see your curl connection.
