### ISSUE TITLE
(redir port) transparent support

### ISSUE THREAD

**Issue by nutinshell** [klzgrad/naiveproxy#18]
It's nice to have it to do transparent redirect `dst -j REDIRECT` on Linux gateway.

**Comment by klzgrad** [comment]
Socks proxying is actually superior than transparent proxy, unless you have use cases where socks proxies can't be used. With socks proxies you can do domain-level routing and you can defer DNS resolution to remote server. With transparent proxying (which implies transport layer shenanigans) you have to do ip-level routing, which is inherently less informative and more cumbersome to maintain, and you have to proxy DNS traffic to remote servers to avoid poisoning, which adds latency.

Realistically this is only necessary for Android but for Android you can't use transparent proxies anyway.

**Comment by nutinshell** [comment]
A transparent proxy is way so good for many devices in LAN, we all love this. In fact, to setup this, just needed to involve several commands in Linux, it's fairly easy. DNS may be an issue, but we all have independent DNS solutions nowadays, besides many ALL-IN-ONE tools support DNS(UDP or DoH) to the remote, maybe you could consider this feature if I don't make a joke:)

So I am happy to see redir port support, to replace current not-so-good-for-performance redir program :)

**Comment by klzgrad** [comment]
The kind of architecture you described (tcp proxy with custom dns) is not suitable for this tool. Doing custom DNS adds latency and this tool tried very hard to reduce latency to minimum. I won't support that architecture.

But adding transparent proxying seems not too hard. Basically a new option `--listen=redir://127.0.0.1:1234` to echo `-j REDIRECT` and to differentiate from `-j TPROXY`. You can add your own whatever DNS server to proxy through this. That is not my business.

What is the bad performance redir program?

**Comment by klzgrad** [comment]
This is added here https://github.com/klzgrad/naiveproxy/releases/tag/v76.0.3809.12-redir.

```
./naive --listen=redir:// --proxy=https://user:pass@myserver.com --log
iptables -t nat -A OUTPUT -p tcp -d $(host -ta example.com | cut -d' ' -f4) -j REDIRECT --to-ports 1080
curl example.com
```

**Comment by nutinshell** [comment]
> What is the bad performance redir program?

famous redsocks(C), many Golang based like Glider, they are suffering in heavy load.

**Comment by nutinshell** [comment]
> ./naive --listen=redir:// --proxy=https://user:pass@myserver.com --log
> iptables -t nat -A OUTPUT -p tcp -d $(host -ta example.com | cut -d' ' -f4) -j REDIRECT --to-ports 1080
> curl example.com

Test failed with `-t nat -A PREROUTING -p tcp -s 10.10.0.0/24 -j REDIRECT --to-ports 1080`, the browser in LAN can't open webpages.

**Comment by nutinshell** [comment]
Another report: by watching youtube 4k, v76 suffering, it appears could only reach 30Mbps,  replace it with v74 binary, could reach 150Mbps+.

**Comment by klzgrad** [comment]
> add --padding and

Truth be told, I haven't used `--padding` for months. It's just an escape hatch which you turn on when shit hits the fan. You can start without it.

> v76 suffering, it appears could only reach 30Mbps

You should try again, because youtube may not be downloading stuff all the time. A better way to measure its performance is a regular download with curl. I'm not seeing major CPU usage different with similar throughput achieved between v74 and v76.

> 150Mbps+

Which service provider has good stuff of this level? I should try it out.

**Comment by nutinshell** [comment]
> You should try again, because youtube may not be downloading stuff all the time. A better way to measure its performance is a regular download with curl. I'm not seeing major CPU usage different with similar throughput achieved between v74 and v76.

Tried many times, very clear different experience in watching youtube,  v76 even could cause lag in 4k 60fps, seems like a throughput issue. Maybe I should try to remove ` --padding` on both sides?

> Which service provider has good stuff of this level? I should try it out.

Are you live in GD? There's a plan called 游戏宽带, it's CN2 powered, highly recommended.

**Comment by nutinshell** [comment]
redir test update: the bandwidth issue only when I use redir port, if I use [3rd redir prog](https://github.com/Dreamacro/clash/) + v76, that's no problem. Kernel is 4.18.

**Comment by klzgrad** [comment]
No. Again, don't use Youtube to test throughput when you're reporting a bug. 

Use curl to test it: `curl -v https://commondatastorage.googleapis.com/chromium-browser-official/chromium-75.0.3770.100.tar.xz`.

I have a fix for a certain bug but I need to see if that is the same bug you were seeing.

**Comment by nutinshell** [comment]
> No. Again, don't use Youtube to test throughput when you're reporting a bug.

Yes, you are right, I should use more rigorous results to report. In fact, I did youtu-dl and curl test too, very significant throughput diff. But much more important is that really affect me watching the f**ing 4K resource :) 

The redir2 version seems fixed this, great! Max throughput accomplished!

BTW, I saw a weird phenomenon in both v74 and v76 redir1

```
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0*   Trying 172.217.24.48...
* TCP_NODELAY set
* Connected to commondatastorage.googleapis.com (172.217.24.48) port 443 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
* Cipher selection: ALL:!EXPORT:!EXPORT40:!EXPORT56:!aNULL:!LOW:!RC4:@STRENGTH
* successfully set certificate verify locations:
*   CAfile: /etc/ssl/cert.pem
  CApath: none
* TLSv1.2 (OUT), TLS handshake, Client hello (1):
} [238 bytes data]
* TLSv1.2 (IN), TLS handshake, Server hello (2):
{ [96 bytes data]
* TLSv1.2 (IN), TLS handshake, Certificate (11):
{ [2840 bytes data]
* TLSv1.2 (IN), TLS handshake, Server key exchange (12):
{ [300 bytes data]
* TLSv1.2 (IN), TLS handshake, Server finished (14):
{ [4 bytes data]
* TLSv1.2 (OUT), TLS handshake, Client key exchange (16):
} [37 bytes data]
* TLSv1.2 (OUT), TLS change cipher, Client hello (1):
} [1 bytes data]
* TLSv1.2 (OUT), TLS handshake, Finished (20):
} [16 bytes data]
* TLSv1.2 (IN), TLS change cipher, Client hello (1):
{ [1 bytes data]
* TLSv1.2 (IN), TLS handshake, Finished (20):
{ [16 bytes data]
* SSL connection using TLSv1.2 / ECDHE-RSA-CHACHA20-POLY1305
* ALPN, server accepted to use h2
* Server certificate:
*  subject: C=US; ST=California; L=Mountain View; O=Google LLC; CN=*.storage.googleapis.com
*  start date: Jun 11 12:44:34 2019 GMT
*  expire date: Sep  3 12:21:00 2019 GMT
*  subjectAltName: host "commondatastorage.googleapis.com" matched cert's "*.googleapis.com"
*  issuer: C=US; O=Google Trust Services; CN=Google Internet Authority G3
*  SSL certificate verify ok.
* Using HTTP2, server supports multi-use
* Connection state changed (HTTP/2 confirmed)
* Copying HTTP/2 data in stream buffer to connection buffer after upgrade: len=0
* Using Stream ID: 1 (easy handle 0x7fbebb80b600)
> GET /chromium-browser-official/chromium-75.0.3770.100.tar.xz HTTP/2
> Host: commondatastorage.googleapis.com
> User-Agent: curl/7.54.0
> Accept: */*
>
* Connection state changed (MAX_CONCURRENT_STREAMS updated)!
< HTTP/2 200
< x-guploader-uploadid: AEnB2UrCm5ucc6OI...dVlDadQpJG7lOg
< expires: Mon, 24 Jun 2019 06:30:51 GMT
< date: Mon, 24 Jun 2019 05:30:51 GMT
< cache-control: public, max-age=3600
< last-modified: Tue, 18 Jun 2019 16:44:34 GMT
< etag: "89e08b5...858a4d8"
< x-goog-generation: 1560....828
< x-goog-metageneration: 1
< x-goog-stored-content-encoding: identity
< x-goog-stored-content-length: 708247700
< content-type: application/x-tar
< x-goog-hash: crc32c=3TNltg==
< x-goog-hash: md5=ieCLW...Fik2A==
< x-goog-storage-class: STANDARD
< accept-ranges: bytes
< content-length: 708247700
< server: UploadServer
< alt-svc: quic=":443"; ma=2592000; v="46,44,43,39"
<
{ [1388 bytes data]
  0  675M    0 2542k    0     0  7207k      0  0:01:35 --:--:--  0:01:35 7203k* TLSv1.2 (OUT), TLS alert, Server hello (2):
} [2 bytes data]
* LibreSSL SSL_read: error:06FFF064:digital envelope routines:CRYPTO_internal:bad decrypt, errno 0
* Failed receiving HTTP2 data
  1  675M    1 10.8M    0     0  15.4M      0  0:00:43 --:--:--  0:00:43 15.4M
* Closing connection 0
* TLSv1.2 (OUT), TLS alert, Client hello (1):
} [2 bytes data]
curl: (56) LibreSSL SSL_read: error:06FFF064:digital envelope routines:CRYPTO_internal:bad decrypt, errno 0
```

wget failed too:

```
2019-06-24 13:31:06 (20.5 MB/s) - Read error at byte 34291712/708247700 (error:1408F119:SSL routines:SSL3_GET_RECORD:decryption failed or bad record mac). Retrying.
```

Is this related to that bug?

**Comment by klzgrad** [comment]
The bug was in both v74 and v76. It is a bug in continuing the leftover buffer when a Write operation finishes writing less than input buffer because the data sink is slower than the data source, and the some data are then sent again incorrectly, which is detected by TLS. This only happens at very high throughput, usually in downloading large files.

Youtube starts with several short connections for data chunks and will stop after its buffer has enough data, so if one of the connections gets this bug it will simply restart the connection with slower throttle and you won't see any errors because of Youtube's buffering. You only see the exact error with curl which transfers all data in a single connection linearly.

Now that this bug is fixed, do you have any performance numbers? Like, bandwidth and CPU usage of this proxy and other redir programs when downloading https://commondatastorage.googleapis.com/chromium-browser-official/chromium-75.0.3770.100.tar.xz.
