### ISSUE TITLE
Web download stuck under "heavy" usage

### ISSUE THREAD

**Issue by CyberLeopard** [klzgrad/naiveproxy#180]
Hi,

Server: Caddy v2 with naïve fork of forwardproxy (latest)
Client: naiveproxy in redir mode (latest)

Sometimes endpoints can't open webpages completely, curl test stuck at below:

> user@linux:/$ curl -o /dev/null google.com
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:--  0:00:12 --:--:--     0

No error in server or client logs. If restart the naiveproxy instance, web page download will back to normal. Connect to the server from another location works, the server should be OK. 

I have done some tests use the script below:

> #!/bin/bash
> 
> THREAD=100
> URL_CHECK="google.com"
> URL_DOWN="https://dl.google.com/dl/android/aosp/redfin-rq2a.210305.006-factory-8c28fafa.zip"
> COUNT=0
> 
> while [[ $COUNT -le $THREAD ]];
> do
>         curl --connect-timeout 10 --max-time 10 -o /dev/null -s "$URL_CHECK"
> 
>         if [[ $? -ne 0 ]]; then
>                 echo "web download failed, max curl thread $COUNT, stop."
>                 exit 0
>         fi
> 
>         curl -o /dev/null --limit-rate 10k -s "$URL_DOWN" &
>         ((COUNT++))
>         echo "thread $COUNT"
>         sleep 1
> 
> done
> 
> echo finished

Test results:

1. Increase concurrency setting in Naiveproxy client will help increase max concurrent curl download instances.
2. Better connection between client and server results in much higher max concurrent curl download instances.

What's the cause of this issue? And what we can do to avoid this, especially when the network between client and server is not good?

Thanks.

**Comment by klzgrad** [comment]
This `--limit-rate 10k` is pathological. If you use one instance of this with anything else, curl will be at 0 bytes/second most of the time because it simply does not naturally go that low. I don't have the energy to answer what negative impact this pathological setup could have on the TCP stack.
