### ISSUE TITLE
请问可以在后续版本里支持armv7的openwrt系统吗？

### ISSUE THREAD

**Issue by nivrrex** [klzgrad/naiveproxy#184]
平时在台式电脑用naiveproxy来fq，感觉很不错，没有多余的功能，用起来很舒服，也很稳定
旁路由用了orangepi（全志H3 armv7 cpu）刷了openwrt系统，想弄透明代理，平时给手机用
但是因为没有这个系统和架构的预编译包，所以没法直接弄，请问能在之后的版本里加入这个系统架构的支持吗？

openwrt sdk在下边的网址：
https://downloads.openwrt.org/releases/19.07.7/targets/sunxi/cortexa7/

**Comment by klzgrad** [comment]
https://github.com/klzgrad/naiveproxy/releases/tag/v90.0.4430.85-7 arm_cortex-a7_neon-vfpv4
