### ISSUE TITLE
Naiveproxy version checker

### ISSUE THREAD

**Issue by xh116** [klzgrad/naiveproxy#186]
I am running naiveproxy as local socks5 server,  and I always try to keep naiveproxy client updated, but when I check the version , it only prints the same main version without the tail. 
however there are several versions at this main version. 
I thought it should give a result like  "naive 90.0.4430.85-10"  ...

<img width="282" alt="version" src="https://user-images.githubusercontent.com/37950502/119271858-000c6400-bc36-11eb-824c-a8f4d1abe5ea.png">

**Comment by klzgrad** [comment]
You don't need to update if the base version doesn't change. The tail number refers to different builds, but they have the same functionalities. Any new or changes in features will be released in the next base version. The only inconvenience is bug fixes won't have a new version. But there aren't many bugs, so maybe make do with this version number.
