### ISSUE TITLE
MacOS build Error

### ISSUE THREAD

**Issue by tormentous** [klzgrad/naiveproxy#187]
ERROR at //build/config/mac/mac_sdk.gni:106:7: Script returned non-zero exit code.
      exec_script("//build/mac/find_sdk.py", find_sdk_args, "list lines")
      ^----------
Current dir: /Users/mcbook/naiveproxy/src/out/Release/
Command: /usr/bin/python /Users/mcbook/naiveproxy/src/build/mac/find_sdk.py --print_sdk_path --print_bin_path 10.15
Returned 1.
stderr:

Traceback (most recent call last):
  File "/Users/mcbook/naiveproxy/src/build/mac/find_sdk.py", line 98, in <module>
    print(main())
  File "/Users/mcbook/naiveproxy/src/build/mac/find_sdk.py", line 81, in main
    raise Exception('No %s+ SDK found' % min_sdk_version)
Exception: No 10.15+ SDK found

See //build/toolchain/mac/BUILD.gn:15:1: whence it was imported.
import("//build/config/mac/mac_sdk.gni")
^--------------------------------------
See //BUILD.gn:49:1: which caused the file to be included.
group("gn_all") {
^----------------

**Comment by tormentous** [comment]
ok I am using an old MacOS SDK 10.3 take note please add 10.5 to build instructions

**Comment by tormentous** [comment]
ok new issue

./build.sh
Done. Made 241 targets from 125 files in 3811ms
ninja: Entering directory `out/Release'
[331/2051] LIBTOOL-STATIC obj/third_party/modp_b64/libmodp_b64.a
FAILED: obj/third_party/modp_b64/libmodp_b64.a 
rm -f obj/third_party/modp_b64/libmodp_b64.a && TOOL_VERSION=1621911411 python ../../build/toolchain/mac/filter_libtool.py /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/libtool -static -D  -o obj/third_party/modp_b64/libmodp_b64.a -filelist obj/third_party/modp_b64/libmodp_b64.a.rsp
error: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/libtool: unknown option character `D' in: -D
Usage: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/libtool -static [-] file [...] [-filelist listfile[,dirname]] [-arch_only arch] [-sacLT] [-no_warning_for_no_symbols]
Usage: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/libtool -dynamic [-] file [...] [-filelist listfile[,dirname]] [-arch_only arch] [-o output] [-install_name name] [-compatibility_version #] [-current_version #] [-seg1addr 0x#] [-segs_read_only_addr 0x#] [-segs_read_write_addr 0x#] [-seg_addr_table <filename>] [-seg_addr_table_filename <file_system_path>] [-all_load] [-noall_load]
[336/2051] CXX obj/third_party/protobuf/protobuf_full/extension_set.o
ninja: build stopped: subcommand failed.

**Comment by klzgrad** [comment]
https://chromium.googlesource.com/chromium/src/+/HEAD/docs/mac_build_instructions.md
