### ISSUE TITLE
Version is consistent with -- version

### ISSUE THREAD

**Issue by bigman-rgb** [klzgrad/naiveproxy#188]
I found that there are many versions in releases, such as 

v90.0.4430.85-10

v90.0.4430.85-7

v90.0.4430.85-6

v90.0.4430.85-4

v89.0.4389.72-2 ，

Unfortunately, for example, it was originally v90.0.4430.85-10, but it turned out to be v90.0.4430.85 through the command naive -- version, which seems to have some problems. I hope that every release version should be consistent with the suffix, which also gives me new hope to add automatic update plug-in function for soft routing.

**Comment by klzgrad** [comment]
The -q part in vx.y.z.w-q is my build number. Change in the -q part does not require you to update.
