### ISSUE TITLE
how to build the Android Binaries?

### ISSUE THREAD

**Issue by tormentous** [klzgrad/naiveproxy#190]
as the title says.

**Comment by klzgrad** [comment]
export EXTRA_FLAGS='target_cpu="arm64" target_os="android"'
./get-clang.sh
./build.sh

**Comment by tormentous** [comment]
> export EXTRA_FLAGS='target_cpu="arm64" target_os="android"

I use macos

from terminal 
cd naiveproxy/src
export EXTRA_FLAGS='target_cpu="arm64" target_os="android"

hang up

**Comment by klzgrad** [comment]
Building on Mac is not supported.
