### ISSUE TITLE
Different conncetion behavior from Chrome

### ISSUE THREAD

**Issue by arm64v8a** [klzgrad/naiveproxy#191]
When naive connects to the server, it creates two connections, A and B.

When A receives 200 OK, naive closes B and continue uses A for proxy.

Connection B always stops at "Change Cipher Spec", without sending any H2 data.

This behavior is different from Chrome, and maybe unique.

**Comment by klzgrad** [comment]
This is called preconnects. Have you tested it with comparable conditions?

**Comment by arm64v8a** [comment]
I didn't know about preconnect.

I tested Chrome's behavior by opening https://mydomain directly.

**Comment by klzgrad** [comment]
Ok, it's not just preconnects but also late binding and connection racing.

Try these:
1. No browsers. `curl --proxy socks5h://127.0.0.1:1080 google.com`: Wireshark sees a single connection.
2. No proxy. `chromium --user-data-dir=$(mktemp -d) https://mydomain/1.txt https://mydomain/2.txt`: Wireshark sees two connections to mydomain, but the second one behaves as you described.

**Comment by arm64v8a** [comment]
2 is confirmed. It somehow works as Chrome's design.

But I still see two connections in test 1  `curl --proxy socks5h://127.0.0.1:1080 google.com`

I also noticed that if I use another naive server of lower latency, there will be single connection.

So as far as I know: 

Both navie and Chrome do this in some conditions (multiple requests at the same time/high latency/...)

It's not very predictable because of late binding and connection racing, so it's hard to distinguish them.

Thanks for answering.

**Comment by klzgrad** [comment]
I did test 1 again and still saw only one connection. If you use the `concurrency` flag it may make 2.

It should be hard to distinguish by design because they share much of the same code base.

**Comment by arm64v8a** [comment]
OK. It doesn't seem to be a bug.
