### ISSUE TITLE
关于import-upstream.sh的使用

### ISSUE THREAD

**Issue by inSilo** [klzgrad/naiveproxy#192]
使用import-upstream.sh 下载和更新chromium，chromium精简了不少，不过在编译期间，有很多依赖报错，需要手动去删除被精简的内容，有没有更快的办法通过脚本自动去除掉被精简的依赖，而不用手动一个一个去删除。

**Comment by inSilo** [comment]
举例：[root@vultrguest src]# ./build.sh
ERROR at //net/BUILD.gn:12:1: Unable to load "/root/naiveproxy-90.0.4430.85-10/src/testing/libfuzzer/fuzzer_test.gni".
import("//testing/libfuzzer/fuzzer_test.gni")
^-------------------------------------------
See //BUILD.gn:58:5: which caused the file to be included.     

需要这种需手动一个一个去删除被精简掉的请求头

**Comment by klzgrad** [comment]
https://github.com/klzgrad/naiveproxy/commit/02c292fa4409419807ca0389b085488a17d270ef

**Comment by inSilo** [comment]
好的
