### ISSUE TITLE
Rasberry Pi 4 BCM2711 illegal instruction

### ISSUE THREAD

**Issue by inSilo** [klzgrad/naiveproxy#193]
I just got a raspberry pie 4B today to test it. Raspberry pie 4B carries a bcm2711, which belongs to quad core cortex-a72 (arm V8) 64 bit SOC @ 1.5 GHz. In principle, Download naiveproxy-v91.0.4472.77-1-openwrt-aarch64_ Cortex-a72.tar.xz, but surprisingly, it doesn't work in the openwrt of raspberry pie 4B. Prompt for “illegal instruction error”. I tried naiveproxy-v91.0.4472.77-1-openwrt-aarch64_ Generic.tar.xz version is executable, I hope it can be improved

```
[0345/093622.412828:INFO:naive_proxy_bin.cc(554)] Listening on 0.0.0.0:1080
[0345/093628.031721:INFO:naive_connection.cc(250)] Connection 1 to www.youtube.com:443
Illegal instruction
```

**Comment by klzgrad** [comment]
Which instruction was illegal? Try https://stackoverflow.com/questions/10354147/find-which-assembly-instruction-caused-an-illegal-instruction-error-without-debu

**Comment by inSilo** [comment]
> Which instruction was illegal? Try https://stackoverflow.com/questions/10354147/find-which-assembly-instruction-caused-an-illegal-instruction-error-without-debu



root@OpenWrt:~# gdb naive /tmp/naive.1622953082.30523.4.core
GNU gdb (GDB) 10.1
Copyright (C) 2020 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
Type "show copying" and "show warranty" for details.
This GDB was configured as "aarch64-openwrt-linux".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<https://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
    <http://www.gnu.org/software/gdb/documentation/>.

--Type <RET> for more, q to quit, c to continue without paging--
For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from naive...
[New LWP 30523]
[New LWP 30526]
[New LWP 30524]
[New LWP 30525]
Core was generated by `naive v.json'.
Program terminated with signal SIGILL, Illegal instruction.
#0  0x0000005563f214dc in aes_hw_set_encrypt_key ()
[Current thread is 1 (LWP 30523)]
(gdb)

**Comment by inSilo** [comment]
> Which instruction was illegal? Try https://stackoverflow.com/questions/10354147/find-which-assembly-instruction-caused-an-illegal-instruction-error-without-debu
目前我所获取的信息，就这么多了。aarch64_ Generic是正常的，但是"aarch64_Cortex-a72"版本却发生了"Illegal instruction"，通过gdb调试发现"aarch64_Cortex-a72"版本出现“#0 0x0000005563f214dc in aes_hw_set_encrypt_key ()”，希望能修复。我会继续跟进该帖。

**Comment by klzgrad** [comment]
Come on, what was the instruction at 0x0000005563f214dc? The link did show how to get it. `layout asm`

**Comment by inSilo** [comment]
> layout asm

```
┌──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┐
│  >0x5563f214dc        add w15, w15, w21                                                                                                                                      │
│   0x5563f214e0        sli v5.4s, v25.4s, #7                                                                                                                                  │
│   0x5563f214e4        add w16, w16, w17                                                                                                                                      │
│   0x5563f214e8        sli v9.4s, v26.4s, #7                                                                                                                                  │
│   0x5563f214ec        add w13, w13, w19                                                                                                                                      │
│   0x5563f214f0        sli v13.4s, v27.4s, #7                                                                                                                                 │
│   0x5563f214f4        add w14, w14, w20                                                                                                                                      │
└──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┘
core LWP 30523 In:                                                                                                                                       L??   PC: 0x5563f214dc 
(gdb) 


```

**Comment by klzgrad** [comment]
The function is aes_hw_set_encrypt_key but the address is inside a chacha function. The signal must have been from somewhere else. But these all seem to relate to crypto instructions.

https://www.raspberrypi.org/forums/viewtopic.php?f=63&t=243410 says BCM2711 has no support for ARMv8 crypto extensions. This might be the cause. But the exact cause is still not pinpointed.

**Comment by klzgrad** [comment]
I think using aarch64_generic for BCM2711 is appropriate in this case because cortex-a72 = aarch64_generic + crypto extensions.
