### ISSUE TITLE
On the problems of different platform speeds

### ISSUE THREAD

**Issue by inSilo** [klzgrad/naiveproxy#196]
I'm Running  on "openwrt", "raspberry pie 4B" and M1 MacBook and testing repeatedly, we found that the speed difference is particularly large. Taking YouTube test as an example, running navieproxy on M1 MacBook is better than that on "x86_ Openwrt "and" raspberry pie 4B "have doubled in speed. Why? 

This is my repeated comparison, and has been tested for many days, the same configuration file, different platforms have great differences in speed

<img width="560" alt="1" src="https://user-images.githubusercontent.com/53564509/121524688-239f1f00-ca2a-11eb-9b2b-5ee0b520f216.png">
The above results are obtained by running M1 MacBook

<img width="547" alt="2" src="https://user-images.githubusercontent.com/53564509/121524905-5ba66200-ca2a-11eb-8b54-ade4885f4873.png">
The above results are obtained by running X86_64 Openwrt

**Comment by klzgrad** [comment]
Youtube tests are meaningless. Use curl to test single thread download speed. Or use top to see its CPU usage. If it is not CPU throttled then it is more related to environmental issues.

**Comment by inSilo** [comment]
> Youtube tests are meaningless. Use curl to test single thread download speed. Or use top to see its CPU usage. If it is not CPU throttled then it is more related to environmental issues.

OK, I'll continue the test
