### ISSUE TITLE
About CMSG_NXTHDR(&msg, cmsg)

### ISSUE THREAD

**Issue by inSilo** [klzgrad/naiveproxy#198]
As for the repair of this warning, it seems that this warning will affect the subsequent construction of the chromium version. For example, the official new stable version 91.0.4472.101 has been successfully built, but I failed to compile it in the 92.0.4515.51 beta version, which is stuck in the following code:

```
[401/2110] CXX obj/base/base/unix_domain_socket.o
../../base/posix/unix_domain_socket.cc:171:51: warning: comparison of integers of different signs: 'unsigned long' and 'long' [-Wsign-compare]
    for (cmsg = CMSG_FIRSTHDR(&msg); cmsg; cmsg = CMSG_NXTHDR(&msg, cmsg)) {
                                                  ^~~~~~~~~~~~~~~~~~~~~~~
../sysroot-build/openwrt/21.02.0-rc2/aarch64_generic/include/sys/socket.h:305:44: note: expanded from macro 'CMSG_NXTHDR'
        __CMSG_LEN(cmsg) + sizeof(struct cmsghdr) >= __MHDR_END(mhdr) - (unsigned char *)(cmsg) \
        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ ^  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
1 warning generated.
```

**Comment by klzgrad** [comment]
Don't preempt the release schedule. Only stable releases are supported. No support for unstable versions.

**Comment by inSilo** [comment]
> Don't preempt the release schedule. Only stable releases are supported. No support for unstable versions.

ok
