### ISSUE TITLE
QA: Is there a minimal example for reusing Chrome's network stack?

### ISSUE THREAD

**Issue by leiless** [klzgrad/naiveproxy#202]
Hi, @klzgrad.

As described in README.md:
> TLS parameter fingerprinting: defeated by reusing Chrome's network stack.

I wonder is there a minimal example for reusing Chrome's network stack? I'm interested in how to get Chrome's network stack working. say, a minimal example would be something like `curl https://icanhazip.com`

Any guidelines or examples are welcome. (Sorry I have mere network knowledge)

**Comment by zhenpingfeng** [comment]
If u want to send a simple request u can check the doc in the code. https://chromium.googlesource.com/chromium/src/+/refs/heads/main/net/url_request/url_fetcher.h

**Comment by klzgrad** [comment]
Cronet is a production grade library that does this. Take a look.

The above link is also an example for minimum API usage of the network stack. It has to be combined with a minimum app build, which you can copy from some example app in //net.

The main thing in naiveproxy is that naiveproxy interfaces with Chrome net stack at connection level but the above links interface with Chrome net stack at request level. So it depends on what level you require from Chrome net stack.

**Comment by leiless** [comment]
Thank you! @zhenpingfeng, @klzgrad.

What's the difference between the connection-level and request-level, the latter one assuming that the connection has been established so you just do your request thing? yet the former(naiveproxy) which handles networking at the connection establishment(as a proxy) level?

**Comment by klzgrad** [comment]
A connection API allows to you perform bidirectional data exchange indefinitely. A request API will have one request and one response, after which it terminates.

**Comment by leiless** [comment]
One more stupid question, since Cronet is part of the Chromium project, why don't you build the naiveproxy atop Cronet?
Does the Cronet is interfacing with the request-level connection?

**Comment by klzgrad** [comment]
Cronet is oriented for requests. It doesn't support WebSocket, so lower level connections would be even harder to support.

Cronet is bundled with Java. Naiveproxy needs to be lightweight.

**Comment by leiless** [comment]
Thanks for your patient replies.
