### ISSUE TITLE
Questions about adding upstream in Caddyfile

### ISSUE THREAD

**Issue by xh116** [klzgrad/naiveproxy#203]
I have two VPSs , all running caddy server with your modified forwardproxy.
One located in Singapore which allow to unblock Netflix bought movies. But speed seems limited less than 10Mb/s when using China telecom. 
Another located in USA, which has stable speed more than 50Mb/s.
So I tried to add `upstream https://sg-user:sg-passwd@sg-url.com` in Caddyfile. 
When I connect to the server in USA, I can get stable speed and unblock the Netflix also. 
 
Is this way still safe (camouflage traffic with strong censorship **resistance** and low **detectability**) ? 

Or any better suggestions?

**Comment by klzgrad** [comment]
This setting routes all traffic from USA server to singapore server. Is this necessary? 

You can create two naiveproxy client instances connected to your two servers and use browser extensions to switch between.

**Comment by xh116** [comment]
Thanks, if there is no safety problem. I will test longer to see if it improves the speed and stability comparing directly connecting to Singapore . 

By the way, 

How I wish one day naiveproxy could support failover with a simple txt config file. 
like gost: 

```
      "ChainNodes": [
        "?peer=peer.txt"
      ]
```


```
strategy        fifo
max_fails       2
fail_timeout    10s
reload          5s
# peers
peer    http2://user:passwd@example1:443
peer    http2://user:passwd@example2:443
peer    http2://user:passwd@example3:443
peer    http2://user:passwd@example4:443
peer    http2://user:passwd@example5:443
```

**Comment by klzgrad** [comment]
"failover" is a form of load balancing. It is best not done in naiveproxy but in haproxy etc.
