### ISSUE TITLE
ERROR:tcp_socket_win.cc(353)] bind() returned an error

### ISSUE THREAD

**Issue by onlyJinx** [klzgrad/naiveproxy#204]
运行软件是报错，用管理员启动cmd也一样，请问是那一步出了问题。

系统：win10
naiveproxy：v91.0.4472.77-1

```

{
  "listen": "socks://127.0.0.1:1080",
  "proxy": "https://xxxxx:xxxxx@xxx.com",
  "log": ""
}

```

![image](https://user-images.githubusercontent.com/21324835/126490090-197604fd-ac43-40b3-9fc5-398c930128a0.png)

![36](https://user-images.githubusercontent.com/21324835/126489905-290d52fc-6efe-406e-b309-03d9ab18ceae.jpg)

**Comment by klzgrad** [comment]
它说是权限问题，我也不是很懂windows 10

**Comment by xh116** [comment]
可能1080被占用了

**Comment by onlyJinx** [comment]
@xh116 
好像不是端口占用？我netstat -ano检查了2000/1999/2020/2021/2033都是没有监听的，但是换了3333就可以了。。不知道啥原因

![屏幕截图 2021-07-21 222258](https://user-images.githubusercontent.com/21324835/126505220-c2fbfd4e-b548-49e4-aa08-7da5d50334bc.jpg)

@klzgrad 我顺便问一下，服务端经常产生这些error，请问是否需要处理，还是不管他啊。

**Comment by klzgrad** [comment]
这些error不需要管，还建议把这种log关了
