### ISSUE TITLE
请问怎么查看服务端当前版本号

### ISSUE THREAD

**Issue by onlyJinx** [klzgrad/naiveproxy#206]
想看下服务端是不是需要更新，但是不知道怎么查看当前版本号，WIKI里也没看到 方法，所以来问一下。
Releases里的好像都是客户端没有服务端？
是不是每次有发布Releases的时候我就需要在服务端重新编译一次？
谢谢。
```
go get -u github.com/caddyserver/xcaddy/cmd/xcaddy
~/go/bin/xcaddy build --with github.com/caddyserver/forwardproxy@caddy2=github.com/klzgrad/forwardproxy@naive
```

**Comment by xh116** [comment]
其实naiveproxy服务端就是caddy  所以`caddy version` 即可

**Comment by onlyJinx** [comment]
那请问是不是只要更新Releases里的客户端即可，服务端的话基本不需要更新？等caddy官方更新我就跟着更新即可？

**Comment by klzgrad** [comment]
naiveproxy对服务端一般没有更新要求，如果对caddy其他功能有要求可以自行评估更新
