### ISSUE TITLE
Issue with building?

### ISSUE THREAD

**Issue by shirshak55** [klzgrad/naiveproxy#207]
```
➜  src git:(master) ./build.sh
Done. Made 260 targets from 130 files in 43ms
ninja: Entering directory `out/Release'
[477/2064] CXX obj/base/base/write_protector.o
FAILED: obj/base/base/write_protector.o 
ccache ../../third_party/llvm-build/Release+Asserts/bin/clang++ -MMD -MF obj/base/base/write_protector.o.d -DPA_PCSCAN_STACK_SUPPORTED -DUSE_SYMBOLIZE -DOFFICIAL_BUILD -D_FILE_OFFSET_BITS=64 -D_LARGEFILE_SOURCE -D_LARGEFILE64_SOURCE -DNO_UNWIND_TABLES -D_GNU_SOURCE -DCR_CLANG_REVISION=\"llvmorg-13-init-10392-gd3676d4b-2\" -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS -D_FORTIFY_SOURCE=2 -D_LIBCPP_ABI_UNSTABLE -D_LIBCPP_DISABLE_VISIBILITY_ANNOTATIONS -D_LIBCXXABI_DISABLE_VISIBILITY_ANNOTATIONS -D_LIBCPP_ENABLE_NODISCARD -D_LIBCPP_HAS_NO_VENDOR_AVAILABILITY_ANNOTATIONS -DCR_LIBCXX_REVISION=8fa87946779682841e21e2da977eccfb6cb3bded -DNDEBUG -DNVALGRIND -DDYNAMIC_ANNOTATIONS_ENABLED=0 -DBASE_IMPLEMENTATION -I../.. -Igen -I../../third_party/abseil-cpp -I../../third_party/boringssl/src/include -fno-delete-null-pointer-checks -fno-ident -fno-strict-aliasing --param=ssp-buffer-size=4 -fstack-protector -fno-unwind-tables -fno-asynchronous-unwind-tables -fPIC -pthread -fcolor-diagnostics -fmerge-all-constants -fcrash-diagnostics-dir=../../tools/clang/crashreports -mllvm -instcombine-lower-dbg-declare=0 -flto=thin -fsplit-lto-unit -fwhole-program-vtables -fcomplete-member-pointers -m64 -march=x86-64 -msse3 -Wno-builtin-macro-redefined -D__DATE__= -D__TIME__= -D__TIMESTAMP__= -Xclang -fdebug-compilation-dir -Xclang . -no-canonical-prefixes -Wall -Wextra -Wimplicit-fallthrough -Wunreachable-code -Wthread-safety -Wextra-semi -Wno-missing-field-initializers -Wno-unused-parameter -Wno-c++11-narrowing -Wno-unneeded-internal-declaration -Wno-undefined-var-template -Wno-psabi -Wno-ignored-pragma-optimize -Wno-implicit-int-float-conversion -Wno-final-dtor-non-final-class -Wno-builtin-assume-aligned-alignment -Wno-deprecated-copy -Wno-non-c-typedef-for-linkage -Wno-max-tokens -fno-omit-frame-pointer -g0 -ftrivial-auto-var-init=pattern -fprofile-instr-use=../../chrome/build/pgo_profiles/chrome-linux-4515-1626533253-34e4718a21d6b148e3c9459b9f213fba5d58ef83.profdata -Wno-profile-instr-unprofiled -Wno-profile-instr-out-of-date -Wno-backend-plugin -fsanitize=cfi-vcall -fsanitize-blacklist=../../tools/cfi/ignores.txt -fsanitize=cfi-icall -fvisibility=hidden -Xclang -add-plugin -Xclang find-bad-constructs -Xclang -plugin-arg-find-bad-constructs -Xclang checked-ptr-as-trivial-member -Xclang -plugin-arg-find-bad-constructs -Xclang check-ipc -Wheader-hygiene -Wstring-conversion -Wtautological-overlap-compare -Wexit-time-destructors -Wshadow -Wglobal-constructors -Wexit-time-destructors -O2 -fdata-sections -ffunction-sections -std=c++14 -fno-trigraphs -Wno-trigraphs -fno-exceptions -fno-rtti -nostdinc++ -isystem../../buildtools/third_party/libc++/trunk/include -isystem../../buildtools/third_party/libc++abi/trunk/include -fvisibility-inlines-hidden -c ../../base/allocator/partition_allocator/starscan/write_protector.cc -o obj/base/base/write_protector.o
../../base/allocator/partition_allocator/starscan/write_protector.cc:105:3: error: unknown type name 'uffdio_writeprotect'
  uffdio_writeprotect wp;
  ^
../../base/allocator/partition_allocator/starscan/write_protector.cc:109:47: error: use of undeclared identifier 'UFFDIO_WRITEPROTECT_MODE_WP'
      (mode == UserFaultFDWPMode::kProtect) ? UFFDIO_WRITEPROTECT_MODE_WP : 0;
                                              ^
../../base/allocator/partition_allocator/starscan/write_protector.cc:110:31: error: use of undeclared identifier 'UFFDIO_WRITEPROTECT'
  PA_PCHECK(-1 != ioctl(uffd, UFFDIO_WRITEPROTECT, &wp));
                              ^
3 errors generated.
[494/2064] CXX obj/base/base/pcscan_internal.o
ninja: build stopped: subcommand failed.
```

**Comment by klzgrad** [comment]
You can either upgrade kernel to >= 5.7, or build with Chrome's sysroot with `EXTRA_FLAGS='target_cpu="x64"'`.

**Comment by shirshak55** [comment]
@klzgrad strange i am using 5.8

`

**Comment by xh116** [comment]
> ```
> ➜  src git:(master) ./build.sh
> Done. Made 260 targets from 130 files in 43ms
> ninja: Entering directory `out/Release'
> [477/2064] CXX obj/base/base/write_protector.o
> FAILED: obj/base/base/write_protector.o 
> ccache ../../third_party/llvm-build/Release+Asserts/bin/clang++ -MMD -MF obj/base/base/write_protector.o.d -DPA_PCSCAN_STACK_SUPPORTED -DUSE_SYMBOLIZE -DOFFICIAL_BUILD -D_FILE_OFFSET_BITS=64 -D_LARGEFILE_SOURCE -D_LARGEFILE64_SOURCE -DNO_UNWIND_TABLES -D_GNU_SOURCE -DCR_CLANG_REVISION=\"llvmorg-13-init-10392-gd3676d4b-2\" -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS -D_FORTIFY_SOURCE=2 -D_LIBCPP_ABI_UNSTABLE -D_LIBCPP_DISABLE_VISIBILITY_ANNOTATIONS -D_LIBCXXABI_DISABLE_VISIBILITY_ANNOTATIONS -D_LIBCPP_ENABLE_NODISCARD -D_LIBCPP_HAS_NO_VENDOR_AVAILABILITY_ANNOTATIONS -DCR_LIBCXX_REVISION=8fa87946779682841e21e2da977eccfb6cb3bded -DNDEBUG -DNVALGRIND -DDYNAMIC_ANNOTATIONS_ENABLED=0 -DBASE_IMPLEMENTATION -I../.. -Igen -I../../third_party/abseil-cpp -I../../third_party/boringssl/src/include -fno-delete-null-pointer-checks -fno-ident -fno-strict-aliasing --param=ssp-buffer-size=4 -fstack-protector -fno-unwind-tables -fno-asynchronous-unwind-tables -fPIC -pthread -fcolor-diagnostics -fmerge-all-constants -fcrash-diagnostics-dir=../../tools/clang/crashreports -mllvm -instcombine-lower-dbg-declare=0 -flto=thin -fsplit-lto-unit -fwhole-program-vtables -fcomplete-member-pointers -m64 -march=x86-64 -msse3 -Wno-builtin-macro-redefined -D__DATE__= -D__TIME__= -D__TIMESTAMP__= -Xclang -fdebug-compilation-dir -Xclang . -no-canonical-prefixes -Wall -Wextra -Wimplicit-fallthrough -Wunreachable-code -Wthread-safety -Wextra-semi -Wno-missing-field-initializers -Wno-unused-parameter -Wno-c++11-narrowing -Wno-unneeded-internal-declaration -Wno-undefined-var-template -Wno-psabi -Wno-ignored-pragma-optimize -Wno-implicit-int-float-conversion -Wno-final-dtor-non-final-class -Wno-builtin-assume-aligned-alignment -Wno-deprecated-copy -Wno-non-c-typedef-for-linkage -Wno-max-tokens -fno-omit-frame-pointer -g0 -ftrivial-auto-var-init=pattern -fprofile-instr-use=../../chrome/build/pgo_profiles/chrome-linux-4515-1626533253-34e4718a21d6b148e3c9459b9f213fba5d58ef83.profdata -Wno-profile-instr-unprofiled -Wno-profile-instr-out-of-date -Wno-backend-plugin -fsanitize=cfi-vcall -fsanitize-blacklist=../../tools/cfi/ignores.txt -fsanitize=cfi-icall -fvisibility=hidden -Xclang -add-plugin -Xclang find-bad-constructs -Xclang -plugin-arg-find-bad-constructs -Xclang checked-ptr-as-trivial-member -Xclang -plugin-arg-find-bad-constructs -Xclang check-ipc -Wheader-hygiene -Wstring-conversion -Wtautological-overlap-compare -Wexit-time-destructors -Wshadow -Wglobal-constructors -Wexit-time-destructors -O2 -fdata-sections -ffunction-sections -std=c++14 -fno-trigraphs -Wno-trigraphs -fno-exceptions -fno-rtti -nostdinc++ -isystem../../buildtools/third_party/libc++/trunk/include -isystem../../buildtools/third_party/libc++abi/trunk/include -fvisibility-inlines-hidden -c ../../base/allocator/partition_allocator/starscan/write_protector.cc -o obj/base/base/write_protector.o
> ../../base/allocator/partition_allocator/starscan/write_protector.cc:105:3: error: unknown type name 'uffdio_writeprotect'
>   uffdio_writeprotect wp;
>   ^
> ../../base/allocator/partition_allocator/starscan/write_protector.cc:109:47: error: use of undeclared identifier 'UFFDIO_WRITEPROTECT_MODE_WP'
>       (mode == UserFaultFDWPMode::kProtect) ? UFFDIO_WRITEPROTECT_MODE_WP : 0;
>                                               ^
> ../../base/allocator/partition_allocator/starscan/write_protector.cc:110:31: error: use of undeclared identifier 'UFFDIO_WRITEPROTECT'
>   PA_PCHECK(-1 != ioctl(uffd, UFFDIO_WRITEPROTECT, &wp));
>                               ^
> 3 errors generated.
> [494/2064] CXX obj/base/base/pcscan_internal.o
> ninja: build stopped: subcommand failed.
> ```

I encountered the same problem when building from Dockerfile. 
there are two ways to solve that: 
1, use ubuntu 21.04  (20.04 not work)
2, run this 
```
EXTRA_FLAGS='target_cpu="x64"' ./get-clang.sh

EXTRA_FLAGS='target_cpu="x64"' ./build.sh
```

**Comment by klzgrad** [comment]
> strange i am using 5.8

The struct definition is from the `linux-libc-dev` package. I think you hadn't updated that package, which is why.

Because this is a minor nuisance and it will get fixed automatically in the next Chrome release, I think I can let it be. Ok?

**Comment by shirshak55** [comment]
no its a upstream issue :)
