### ISSUE TITLE
Build for other platforms and architectures.

### ISSUE THREAD

**Issue by Old-Nukkit** [klzgrad/naiveproxy#208]
Hello.
Can you please provide, how to build Naive for android under Linux? (Arch Linux btw)
I was able to build it for Linux x86_64 without problems but I don't know how to do it for Android or Even ARM.
I also checked build log but couldn't figure it out.

**Comment by klzgrad** [comment]
https://github.com/klzgrad/naiveproxy/blob/master/.github/workflows/build.yml#L160-L200

This should work?
