### ISSUE TITLE
Build a completely static "naive" binary

### ISSUE THREAD

**Issue by Old-Nukkit** [klzgrad/naiveproxy#209]
Hello, is there a way to build a static binary (I mean no interpreter involved)?
I already tried editing BUILD.gn and adding `is_component_build = true` or `config("compiler") { cflags = ["-static"] }`.
Nothing changed and the android build still gives me a shared library or dynamic executable, I need static executable (ELF).
I also tried building chromium from source for Linux and its not getting linked statically either.

**Comment by Old-Nukkit** [comment]
I know, but I need to do it.
But if takes a lot of efforts and its not just a simple config or env variable or something this simple, forget about it I'll just go with shared.
After all, chromium build system is too complex for me.
Thank, best regards.

**Comment by klzgrad** [comment]
It's not about effort and simplicity. I don't see the benefit of doing so. Creating a static binary does not make it more portable, only makes it duplicate libc code.

**Comment by Old-Nukkit** [comment]
Im completely aware of downside and disadvantages of statically linking, but I really need to do it.
It would be Great if you tell me how should I do it.
Thank you for your Patience and replies.

**Comment by klzgrad** [comment]
This is not reasonable.

**Comment by nillcoy** [comment]
Hi, I have a way to build a completely static "naive" binary

This is my patch
[static.txt](https://github.com/klzgrad/naiveproxy/files/7039489/static.txt)

For example:

cd naiveproxy
patch -p0 < static.txt

rm -rf src/out/sysroot-build/openwrt/19.07.7/arm_cortex-a9
cd src
export EXTRA_FLAGS='target_cpu="arm" use_allocator="none" use_allocator_shim=false arm_version=0 arm_cpu="cortex-a9" arm_float_abi="soft" arm_use_neon=false target_os="openwrt" enable_static=true'
export OPENWRT_FLAGS='arch=arm_cortex-a9 release=19.07.7 gcc_ver=7.5.0 target=bcm53xx'
./get-clang.sh
./build.sh

**Comment by Old-Nukkit** [comment]
@nillcoy 
Wow, thank you very much!
I didn't expect that, I almost gave up on naive and was going to use Firefox network stack.
