### ISSUE TITLE
go get命令可能被淘汰

### ISSUE THREAD

**Issue by ArcCal** [klzgrad/naiveproxy#217]
go语言升级到1.17后，go get命令好像要被淘汰了（暂时还可用），文档中的编译方法可能需要更新

**Comment by klzgrad** [comment]
应该怎么更新

**Comment by zhenpingfeng** [comment]
Proposal #40276 added a versioned go install variant that works outside of a module.

https://github.com/golang/go/issues/43684

btw, the version number should be 1.17 instead of 1.7

**Comment by bolucat** [comment]
Simply change `go get -u github.com/caddyserver/xcaddy/cmd/xcaddy` to `go install github.com/caddyserver/xcaddy/cmd/xcaddy@latest` from this commit : https://github.com/caddyserver/xcaddy/commit/83655481bffa4ff2a6a2c811ab0d95478ef084ef

**Comment by klzgrad** [comment]
https://github.com/klzgrad/naiveproxy/commit/4a24dc9329d9cd9841d69889eee6fe882165973f
