### ISSUE TITLE
服务器上，build失败

### ISSUE THREAD

**Issue by luckypoem** [klzgrad/naiveproxy#22]
hi.

[root@host src]# ./build.sh
Done. Made 13176 targets from 1938 files in 19710ms
./build.sh: line 75: ninja: command not found
[root@host src]# which ninja
/usr/bin/which: no ninja in (/root/.cargo/bin:/usr/local/php/bin:/usr/local/nginx/sbin:/usr/local/mysql/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/usr/local/python-3.6.4/bin:/usr/bin/v2ray:/root/bin)
[root@host src]# which ninja-build
/usr/bin/ninja-build
[root@host src]# yum install -y ninja
Loaded plugins: fastestmirror
Loading mirror speeds from cached hostfile
 * base: mirrors.sonic.net
 * elrepo-kernel: repos.lax-noc.com
 * epel: mirrors.sonic.net
 * extras: mirror.keystealth.org
 * updates: sjc.edge.kernel.org
No package ninja available.
Error: Nothing to do
[root@host src]#

没有ninja这个包，如何安装ninja?

**Comment by hvonw** [comment]
https://github.com/ninja-build/ninja
https://github.com/ninja-build/ninja/wiki/Pre-built-Ninja-packages

In your case,
Enable the [Extra Packages for Enterprise Linux (EPEL)](https://fedoraproject.org/wiki/EPEL).
After that: `yum install ninja-build`

**Comment by klzgrad** [comment]
Consider CentOS not supported.

**Comment by luckypoem** [comment]
@hvonw 
现在ninja装好了。
我看到这里的build.sh的内容：https://github.com/klzgrad/naiveproxy/blob/master/src/build.sh
里面牵涉到可执行文件gn，我尝试编译gn:
 git clone https://gn.googlesource.com/gn
cd gn
python build/gen.py
ninja -C out
显示：
ninja: Entering directory `out'
[1/272] CXX src/base/command_line.o
FAILED: src/base/command_line.o 
clang++ -MMD -MF src/base/command_line.o.d -I../src -I. -DNDEBUG -O3 -fdata-sections -ffunction-sections -D_FILE_OFFSET_BITS=64 -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS -pthread -pipe -fno-exceptions -fno-rtti -fdiagnostics-color -Wall -Wextra -Wno-unused-parameter -std=c++17 -c ../src/base/command_line.cc -o src/base/command_line.o
error: invalid value 'c++17' in '-std=c++17'
[2/272] CXX src/gn/general_tool.o
FAILED: src/gn/general_tool.o 
clang++ -MMD -MF src/gn/general_tool.o.d -I../src -I. -DNDEBUG -O3 -fdata-sections -ffunction-sections -D_FILE_OFFSET_BITS=64 -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS -pthread -pipe -fno-exceptions -fno-rtti -fdiagnostics-color -Wall -Wextra -Wno-unused-parameter -std=c++17 -c ../src/gn/general_tool.cc -o src/gn/general_tool.o
error: invalid value 'c++17' in '-std=c++17'
[3/272] CXX src/base/environment.o
FAILED: src/base/environment.o 
clang++ -MMD -MF src/base/environment.o.d -I../src -I. -DNDEBUG -O3 -fdata-sections -ffunction-sections -D_FILE_OFFSET_BITS=64 -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS -pthread -pipe -fno-exceptions -fno-rtti -fdiagnostics-color -Wall -Wextra -Wno-unused-parameter -std=c++17 -c ../src/base/environment.cc -o src/base/environment.o
error: invalid value 'c++17' in '-std=c++17'
ninja: build stopped: subcommand failed.

编译gn失败，问题何在呢？

**Comment by klzgrad** [comment]
https://openwrt.org/docs/techref/targets/start

**Comment by klzgrad** [comment]
https://github.com/klzgrad/naiveproxy/blob/master/src/get-clang.sh#L71

**Comment by briteming** [comment]
运行了get-clang.sh，然后运行build.sh，仍然遇错：
[root@vps src]# ./build.sh
ERROR at //build/timestamp.gni:31:19: Could not execute interpreter.
build_timestamp = exec_script(compute_build_timestamp,
                  ^----------
I was trying to execute "/usr/bin/python2".
See //base/BUILD.gn:34:1: whence it was imported.
import("//build/timestamp.gni")
^-----------------------------
See //ppapi/BUILD.gn:290:5: which caused the file to be included.
    "//base",
    ^-------
[root@vps src]#

如何解决？

**Comment by klzgrad** [comment]
yum install python2

**Comment by briteming** [comment]
[root@vps ~]# which python2
/usr/bin/python2
[root@vps ~]#

vps本身就有python2.
