### ISSUE TITLE
linux-arm 与树莓派1B

### ISSUE THREAD

**Issue by pcteams** [klzgrad/naiveproxy#220]
开发板型号：树莓派1B
因 naiveproxy 明确说明不支持树莓派1B 上的 OpenWrt，故使用树莓派官方 Raspberry Pi OS Lite，文件名：2021-05-07-raspios-buster-armhf-lite.zip

> pi@raspberrypi:~ $ uname -a
> Linux raspberrypi 5.10.60+ #1449 Wed Aug 25 14:59:20 BST 2021 armv6l GNU/Linux

安装 naiveproxy 的 linux-arm 安装包，运行，提示错误信息如下

> pi@raspberrypi:~ $ naive -v
> Segmentation fault

参照不支持树莓派1B 上的 OpenWrt 原因，树莓派1B 的 SoC(bcm2708) 不支持 QADD 指令编译，是不是等同于说树莓派1B 没法使用 naiveproxy 了？

**Comment by klzgrad** [comment]
不支持bcm2708这型平台。QADD只是一个现象，根本原因是这个平台太老了，ARMv6，Chromium不支持它，这里是Chromium的下游，也没有条件支持。
