### ISSUE TITLE
关于naive断流的问题

### ISSUE THREAD

**Issue by Demon-Cat** [klzgrad/naiveproxy#222]
最近更新的这几个版本中,似乎通过naive代理后,当跑大流量比如下载和看视频时,不久(半天甚至数个小时后)，就会出现卡死状态，也就访问不了页面（无法代理），需将naive的进程kill掉，重新启动navie才恢复正常，目前不知道出于什么问题！反正每次出现无法代理kill掉重新开启navie进程又恢复正常了。作者能否测试下相关，或者让我提供些测试也行. 

目前我在mac M1和openwrt上均出现这种情况，每天需要kill掉naive进程，重新打开navie应用才会恢复正常使用

**Comment by learnbilling** [comment]
如果仅仅浏览网页页面，不看视频（大流量的），就不会出现这种情况。目前我怀疑是不是navie程序中进程问题还是？

**Comment by learnbilling** [comment]
以上则是我经过近几个星期测试遇到的问题

**Comment by Nomeqc** [comment]
windows上同样遇到这样的问题。

**Comment by Demon-Cat** [comment]
> windows上同样遇到这样的问题。

看来不止是我遇到该问题，希望作者进一步调查

**Comment by klzgrad** [comment]
重现比较困难。可以先保存日志，--log=123.txt，然后自查。如果日志没有什么信息也可以保存netlog，--log-net-log=xxx.json。

**Comment by Demon-Cat** [comment]
> 重现比较困难。可以先保存日志，--log=123.txt，然后自查。如果日志没有什么信息也可以保存netlog，--log-net-log=xxx.json。

```
[0918/115721.917675:INFO:naive_connection.cc(250)] Connection 1050 to www.google.com:443
[0918/115721.949595:INFO:naive_connection.cc(250)] Connection 1051 to www.google.com:443
[0918/115722.537487:INFO:naive_connection.cc(250)] Connection 1052 to www.google.com:443
[0918/115722.537926:INFO:naive_connection.cc(250)] Connection 1053 to www.google.com:443
[0918/115723.468905:INFO:naive_connection.cc(250)] Connection 1054 to www.google.com:443
[0918/115725.054164:INFO:naive_proxy.cc(183)] Connection 1042 closed: OK
[0918/115725.057274:INFO:naive_proxy.cc(183)] Connection 1044 closed: OK
[0918/115725.067862:INFO:naive_proxy.cc(183)] Connection 1043 closed: OK
```
<img width="1013" alt="CB023562-B5B6-4023-93BB-450DCD139C13" src="https://user-images.githubusercontent.com/90884281/133871828-4d79457b-59a5-43d7-bc8f-35f484234ca0.png">

**Comment by Demon-Cat** [comment]
大流量下载一段时间后，就会出现连接变慢。将naive进程kill掉重启又正常

**Comment by Demon-Cat** [comment]
作者可以尝试连续测试大流量下载一段时间，就会出现我这种情况发生了。

**Comment by Demon-Cat** [comment]
从log查看似乎没发现什么大的问题，但就是大流量下载或者看视频后就会出现网页页面卡死无法访问的状况，只要kiil掉naive进程，重新执行naive又好了。（仅出现于长江时间大流量访问的情况下，且我已经做六大量的测试）

**Comment by Demon-Cat** [comment]
可重现，打开一个youtube视频，我这里打开一个播放自然环境的4k视频https://www.youtube.com/watch?v=4eiCKQkXbfU，然后开启4k播放大概30-40分钟，就可以重现该问题了

**Comment by klzgrad** [comment]
按你的方法播放了2小时，没有发现类似现象。考虑网络环境因素，是否有防火墙，是否有CGNAT。

**Comment by klzgrad** [comment]
naive的确可能在断网重连的时候存在一定问题，但我也没有怎么测到。

**Comment by Demon-Cat** [comment]
> naive的确可能在断网重连的时候存在一定问题，但我也没有怎么测到。

我的环境为电信网络，200兆光纤，但的确出现该问题发生。可能不过网络环境笔记难重现也有可能，但我查看log日志的确看不出什么问题，但的确发生连续大流量视频播放可能导致中途卡住无法代理，需要kill掉重新打开naive'进程才恢复正常。

**Comment by Demon-Cat** [comment]
> windows上同样遇到这样的问题。

而且我发现不止我一个人出现该问题，但由于网络因素问题，这个很难重现也是有可能的。

**Comment by Demon-Cat** [comment]
可能我一天看netflix播放视频量大，所用重现得比较容易（一次半次可能测不出，可连续实验多次）。我不知道四楼的兄台是不是也是播放视频流量大时才导致突然代理中断卡死的现象发生。

**Comment by Demon-Cat** [comment]
目前我怀疑是不是由于连续大流量，运营商QOS掉该连接，直到速度降得非常非常低而导致无法代理。然后重新kill掉naive进程再次打开navie开启新的连接，这时又恢复正常，直到下一次QOS掉又不行了（我的个人思路推测可能没有什么依据，仅供参考）

**Comment by Nomeqc** [comment]
我这边并不是完全断，看youtube的时候 有时候速率突然变成六七百，正常是3万左右，重启客户端后速率恢复正常。

**Comment by Demon-Cat** [comment]
> 同样的情况，并不是完全断，看youtube的时候 有时候速率突然变成六七百，正常是3万左右，重启客户端后速率恢复正常。

是的

**Comment by klzgrad** [comment]
"有时候速率突然变成六七百，正常是3万左右" 这个描述肯定是反映网络环境的问题，带宽挤占或者丢包，跟naive本身关系不大，naive这边不能解决网络环境问题。前面问的是否有CGNAT也没有答复，就是说有没有公网IP，若没有，NAT断开长连接是正常的。另外可以看如果用concurrency选项是否有缓解。
```
{
  "listen": "socks://127.0.0.1:1080",
  "proxy": "https://a:b@c.com",
  "concurrency": "2"
}
```
若还不行可以看v2fly等技术是否效果会更好。

**Comment by Demon-Cat** [comment]
> "有时候速率突然变成六七百，正常是3万左右" 这个描述肯定是反映网络环境的问题，带宽挤占或者丢包，跟naive本身关系不大，naive这边不能解决网络环境问题。前面问的是否有CGNAT也没有答复，就是说有没有公网IP，若没有，NAT断开长连接是正常的。另外可以看如果用concurrency选项是否有缓解。
> 
> ```
> {
>   "listen": "socks://127.0.0.1:1080",
>   "proxy": "https://a:b@c.com",
>   "concurrency": "2"
> }
> ```
> 
> 若还不行可以看v2fly等技术是否效果会更好。

果然，使用量作者的配置之后，今天没断过了

**Comment by Demon-Cat** [comment]
> "有时候速率突然变成六七百，正常是3万左右" 这个描述肯定是反映网络环境的问题，带宽挤占或者丢包，跟naive本身关系不大，naive这边不能解决网络环境问题。前面问的是否有CGNAT也没有答复，就是说有没有公网IP，若没有，NAT断开长连接是正常的。另外可以看如果用concurrency选项是否有缓解。
> 
> ```
> {
>   "listen": "socks://127.0.0.1:1080",
>   "proxy": "https://a:b@c.com",
>   "concurrency": "2"
> }
> ```
> 
> 若还不行可以看v2fly等技术是否效果会更好。

设置concurrency作用是将2条 TCP 连接合并成一条，提高并发能力对吧

**Comment by ArcCal** [comment]
我一直把concurrency设为4

经常连续用OneDrive上传下载好几T的文件

没出现过断流

**Comment by Demon-Cat** [comment]
> 我一直把concurrency设为4
> 
> 经常连续用OneDrive上传下载好几T的文件
> 
> 没出现过断流

数值设置得越大越好，还是？

**Comment by ArcCal** [comment]
> > 我一直把concurrency设为4
> > 
> > 经常连续用OneDrive上传下载好几T的文件
> > 
> > 没出现过断流
> 
> 数值设置得越大越好，还是？

貌似最大就是4

**Comment by klzgrad** [comment]
它的作用是使用几条并发隧道连接来运载上层连接。不影响性能的情况下concurrency越小越好，若不设置默认为1。数值越大，单隧道的流量就相对越容易识别，即越不安全，但越能克服恶劣网络环境对性能的影响。

**Comment by zdfdreamfactory** [comment]
用sagernet，最新版本0.8.1-rc02, naive版本v105，开代理打游戏（分应用代理，部落冲突，皇室战争），游戏中会突然掉线，点重新登陆，一切正常，然后玩一段时间又突然掉线，换成同一个服务器搭建的trojan就不存在这个问题

**Comment by openips** [comment]
关注一下

**Comment by klzgrad** [comment]
Sagernet相比于PC版的确会有更多断线的情况发生，这个问题目前没有人在修复。

PC版断线可以在这里继续提交故障数据。

**Comment by zhyonchen** [comment]
> 用sagernet，最新版本0.8.1-rc02, naive版本v105，开代理打游戏（分应用代理，部落冲突，皇室战争），游戏中会突然掉线，点重新登陆，一切正常，然后玩一段时间又突然掉线，换成同一个服务器搭建的trojan就不存在这个问题

试一下SagerNet的分支[Matsuri](https://github.com/MatsuriDayo/Matsuri)，看看掉线问题有没有改善

**Comment by bbcbbk** [comment]
遇到同样的情况, 大流量观看四十分钟之后没速度, 几个网站测速都只有1M, 服务端caddy下放了个自建speedtest,网页测速没有问题, 排除服务器网络波动, 重启服务端caddy后马上恢复; 同一台服务器此前用vless没遇到过这类情况,

**Comment by homenet6** [comment]
> "有时候速率突然变成六七百，正常是3万左右" 这个描述肯定是反映网络环境的问题，带宽挤占或者丢包，跟naive本身关系不大，naive这边不能解决网络环境问题。前面问的是否有CGNAT也没有答复，就是说有没有公网IP，若没有，NAT断开长连接是正常的。另外可以看如果用concurrency选项是否有缓解。
> 
> ```
> {
>   "listen": "socks://127.0.0.1:1080",
>   "proxy": "https://a:b@c.com",
>   "concurrency": "2"
> }
> ```
> 
> 若还不行可以看v2fly等技术是否效果会更好。

在路由器中用openwrt的passwall插件使用naiveproxy 如何添加这个参数呢，请指导，谢谢

**Comment by q2051839** [comment]
我也是一样的情况 自己搞了半个月也没效果 我试试那个参数{
  "listen": "socks://127.0.0.1:1080",
  "proxy": "https://a:b@c.com",
  "concurrency": "2"
}  过1个小时来汇报结果，正常情况看4K 大概路20-30分钟就会断流，或者看短视频频繁刷新也会断。排除网络问题 同样机器搭建XTLS没有问题昨晚上跑了一夜4K。

**Comment by q2051839** [comment]
每次搭建都有这个警告 是我哪里出了问题
2022/11/15 03:54:37.764	WARN	Caddyfile input is not formatted; run the 'caddy fmt' command to fix inconsistencies	{"adapter": "caddyfile", "file": "Caddyfile", "line": 2}

**Comment by q2051839** [comment]
加上   "concurrency": "2" 命令不能启动了很奇怪，本人是500M联通 WIN10 公网IP段  刚才播放4K视频28分钟断流，其中经过几次明显的减速 。是不是速度太高了造成的ISP限制 如何限速。我youtub都是15万速度起步。经过减速的时候会掉到HD,30000左右，再10分钟左右就 断线了。 昨天使用XTLS看了很久 也是高速下 没出现断流问题。

**Comment by q2051839** [comment]
本人是500M联通 WIN10 公网IP段 刚才播放4K视频28分钟断流，其中经过几次明显的减速 。是不是速度太高了造成的ISP限制 如何设置限速。我youtub都是15万速度起步。经过减速的时候会掉到HD,30000左右，再10分钟左右就 断线了。 昨天使用XTLS看了很久 也是高速下 没出现断流问题。

**Comment by q2051839** [comment]
"concurrency": "2" 本人加上这个语句，实测20分钟就断流了。没有任何改善。我是使用的HC3路由器拨号，TP路由器MESH。网络没有卡顿。宽带也是新拨号过.

**Comment by q2051839** [comment]
在隔壁的V2RAYN 项目组 找到了 似乎修改监听地址127.0.0.1  改成0.0.0.0就可以了。之前搜到过，但是常用的Proxy SwitchyOmega···似乎不能监听0.0.0.0

 暂时用V2N启动SOCK5使用 或者直接在V2N添加自定义。实测2个小时的4K确实没哟断流了。
请研究下原理。本人会坚持使用0.0.0.0的方式，如果24小时没有继续回复就应该是没有断流问题了。

**Comment by zdfdreamfactory** [comment]
> 每次搭建都有这个警告 是我哪里出了问题 2022/11/15 03:54:37.764 WARN Caddyfile input is not formatted; run the 'caddy fmt' command to fix inconsistencies {"adapter": "caddyfile", "file": "Caddyfile", "line": 2}

需要格式化caddy 配置文件，命令：caddy fmt --overwrite 接caddyfile目录

**Comment by q2051839** [comment]
> > 每次搭建都有这个警告是我哪里出了问题 2022/11/15 03:54:37.764 WARN Caddyfile 输入未格式化；运行 'caddy fmt' 命令来修复不一致 {"adapter": "caddyfile", "file": "Caddyfile", "line": 2}
> 
> 需要格式化caddy配置文件，命令：caddy fmt --overwrite接caddyfile目录
是接caddyfile的位置么 我是在 /root/Caddyfile  ，如果执行命令caddy fmt overwrite /root/Caddyfile
就是得到caddy: command not found

**Comment by q2051839** [comment]
> > 每次搭建都有这个警告 是我哪里出了问题 2022/11/15 03:54:37.764 WARN Caddyfile input is not formatted; run the 'caddy fmt' command to fix inconsistencies {"adapter": "caddyfile", "file": "Caddyfile", "line": 2}
> 
> 需要格式化caddy 配置文件，命令：caddy fmt --overwrite 接caddyfile目录

非常感谢 已经没有这个错误了

**Comment by q2051839** [comment]
由于之前一天没有大段的时间看4K （又舍不得流量。）以为断流解决
今天看了一大会4K 关于改为0.0.0.0的方案还是会断流的

**Comment by q2051839** [comment]
本人的断流已经解决
总结：
1.获取了IPV6,
2.使用了1.1.1.1和2606:4700:4700::1111
3.使用了V2RAYN作为启动器并手动添加DNS服务器cloudflare-dns.com,
本人不知道哪条是生效的原因，反正是不断流了。。
经过：
一直服役的H3C路由（不支持IPV6）灰尘起码1厘米高了。。虽然还能在500m的宽带跑出580的速度，估计跑个千兆也有冗余。准备拆下来清清灰，突发奇想用了一直作为MESH使用了TP垃圾路由（500M光纤堪堪跑到500上下）作为主路由并获取了IPV6,然后整个傍晚到现在凌晨4点一次断流都没发生过。有遇到同样断流问题的可是试试获取IPV6或者修改DNS试试。
本人不懂技术。仅供同样被断流困扰的人参考。

**Comment by hedsbj** [comment]
梅林科学上网插件和win10 上的v2rayN都有这个问题，还以为是自己哪里姿势 不对。断流的时候网络是正常的，只要重启插件或是v2rayN就正常了。（开始还以为是节点问题，因为网络ping是完全正常的，我是联通宽带 ，用的是AS9929线路）
感谢作者耗费个人精力不为名利给大家提供了重要的选择。从pptp到openvpn到ss到v2ray到xray到现在naive (hy备份），感谢一众无名英雄。现在路由上用xray vless-grpc（为不方便装 客户端的设备，小流量） 大流量的电脑上用naive，断了重启一下也不麻烦，祝作者和这个小程序 越来越好

**Comment by longbowapache** [comment]
提供一个思路：检查一下是不是naiveproxy客户端到服务器之间的访问经过了其他代理软件（例如采用fake-ip模式的clash），我这边给域名排除在fakeip之外好久没问题了。

**Comment by Robot20200229** [comment]
> "concurrency": "2"

我看twitch也是这样，不知道怎么回事，老是卡住

**Comment by Robot20200229** [comment]
> 提供一个思路：检查一下是不是naiveproxy客户端到服务器之间的访问经过了其他代理软件（例如采用fake-ip模式的clash），我这边给域名排除在fakeip之外好久没问题了。

我现在用的是naiveproxy的win64客户端，用vbs设置开机后台自启动的那种

**Comment by Robot20200229** [comment]
> Sagernet相比于PC版的确会有更多断线的情况发生，这个问题目前没有人在修复。
> 
> PC版断线可以在这里继续提交故障数据。

我用vbs后台自启动三个不同配置文件的win64客户端，用一个客户端看twitch20min不到就卡住，但是有用v2rayn启动，看twitch好像就没卡过，不知道什么原因

**Comment by ssthptfpd** [comment]
确实有断流的情况，我在OPENWRT上面用PASSWALL，然后电视看油管，经常看着就没网络了，然后要进PASSWALL里面重新点应用一次，相当于重连一样，马上就又可以了，已经发生了好多次了，但是你当时不去理会，不继续用，过一段时间，好像又能恢复，因我家里是我老爸在用电视看油管，能看的时候他就看，不能看，他就没看，只有当我在场不能看的时候，我才会进路由去重新点应用连接，所以这个问题很迷，用别的协议的时候，没有这个情况发生。

**Comment by ChenAlien** [comment]
同样有这个问题，症状和上面的老哥都一样。。。目前有什么解决方法吗

**Comment by ChenAlien** [comment]
> 这个问题是不是一直没解决掉……

似乎是解决了，在passwall的日志设置里面，把tcp和udp日志都关掉，后来就没复现过了

**Comment by Aperove** [comment]
> > 这个问题是不是一直没解决掉……
> 
> 
> 
> 似乎是解决了，在passwall的日志设置里面，把tcp和udp日志都关掉，后来就没复现过了

好像解决了，我先留个标记

**Comment by caoailin** [comment]
啥意思 ？ 我也经常出现这问题 我可没用openwrt路由

**Comment by redstoneleo** [comment]
问题现在估计还在，请看我的反馈 https://github.com/MatsuriDayo/nekoray/issues/1221#issuecomment-1980136180

**Comment by segfault-bilibili** [comment]
@klzgrad 
>Sagernet相比于PC版的确会有更多断线的情况发生，这个问题目前没有人在修复。

今天我想到了一个可能的解释：Google 自从 Android 12 开始引入的幽灵进程杀手机制，phantom process killer

https://github.com/MatsuriDayo/NekoBoxForAndroid/issues/693

**Comment by segfault-bilibili** [comment]
这个机制很操蛋，系统全局（而不是分app）限制此等幽灵进程默认最多32个，

而且**与此同时，如果你CPU用多了也一样杀**，这个（在Android 14前都）是无解的。

很操蛋，Android 14开始Google才终于在开发者选项里加了完全关闭这个机制的设置项。

**Comment by segfault-bilibili** [comment]
这里还有回帖提到手机厂商可能先于Google之前就做了这等事情，不过我不能确认这个消息是否准确属实：

https://www.reddit.com/r/androiddev/comments/qmsupb/comment/hjdzkbt/

**Comment by segfault-bilibili** [comment]
刚刚想起来小米（大概）也干了，不然Shadowsocks时代引入的GuardedProcess自动重启是哪来的…

**Comment by zhuhansan666** [comment]
尝试添加 `--insecure-concurrency=<N>` (N >= 1, N 为整数), 允许部分 SSL Error 情况下的连接 试试

**Comment by davidwudv** [comment]
这个问题依然存在，每天都要kill几次naive client

**Comment by ArcCal** [comment]
与其主动kill，不如自动定期重启

**Comment by Aperove** [comment]
openwrt也有这个问题，无解

**Comment by sz2013** [comment]
2026年实测这个问题依旧存在 ：并不是完全断，看youtube的时候 有时候速率突然变成六七百，正常是3万左右，重启客户端后速率恢复正常。

排除服务器和线路问题，因为用其它协议的节点不会出现这种情况

**Comment by w22gb8** [comment]
我几年前也遇到过这个问题，不过最近几年好像没遇到过了，不知是哪里的问题
