### ISSUE TITLE
Build Android on Mac

### ISSUE THREAD

**Issue by tormentous** [klzgrad/naiveproxy#223]
ERROR at //build/toolchain/apple/toolchain.gni:56:3: Duplicate toolchain.
  toolchain(target_name) {
  ^-----------------------
Two or more toolchains write to the same directory:
  //out/Release/clang_x64/

This can be fixed by making sure that distinct toolchains have
distinct names.

See //build/toolchain/gcc_toolchain.gni:106:3: Previous toolchain.
  toolchain(target_name) {

**Comment by Demon-Cat** [comment]
> ERROR at //build/toolchain/apple/toolchain.gni:56:3: Duplicate toolchain.
> toolchain(target_name) {
> ^-----------------------
> Two or more toolchains write to the same directory:
> //out/Release/clang_x64/
> 
> This can be fixed by making sure that distinct toolchains have
> distinct names.
> 
> See //build/toolchain/gcc_toolchain.gni:106:3: Previous toolchain.
> toolchain(target_name) {

如果使用作者的build.sh脚本编译，似乎不会报您这个错误。可能是你传递的gn参数缺失了什么的。

**Comment by klzgrad** [comment]
没有重现方法

**Comment by tormentous** [comment]
git clone --depth 1 https://github.com/klzgrad/naiveproxy.git
cd naiveproxy/src
export ANDROID_HOME=/Users/mcbook/Library/Android/sdk
export ANDROID_NDK_HOME=/Users/mcbook/adt-bundle-mac-x86_64-20140702/sdk/ndk/21.3.6528147
export EXTRA_FLAGS='target_cpu="arm64" target_os="android"'
./get-clang.sh
./build.sh

**Comment by Demon-Cat** [comment]
> git clone --depth 1 https://github.com/klzgrad/naiveproxy.git
> cd naiveproxy/src
> export ANDROID_HOME=/Users/mcbook/Library/Android/sdk
> export ANDROID_NDK_HOME=/Users/mcbook/adt-bundle-mac-x86_64-20140702/sdk/ndk/21.3.6528147
> export EXTRA_FLAGS='target_cpu="arm64" target_os="android"'
> ./get-clang.sh
> ./build.sh

您在mac平台上构建？

**Comment by Demon-Cat** [comment]
请尝试：
git clone --depth 1 https://github.com/klzgrad/naiveproxy.git
cd naiveproxy/src
export ANDROID_HOME=/Users/mcbook/Library/Android/sdk
export ANDROID_NDK_HOME=/Users/mcbook/adt-bundle-mac-x86_64-20140702/sdk/ndk/21.3.6528147

EXTRA_FLAGS='target_cpu="arm64" target_os="android"' ./get-clang.sh
EXTRA_FLAGS='target_cpu="arm64" target_os="android"' ./build.sh

**Comment by Demon-Cat** [comment]
我推荐你在Ubuntu下完成android 的编译，而不是在mac平台上。因为作者的CI也是使用Ubuntu环境中交叉构建的

**Comment by tormentous** [comment]
> 您在mac平台上构建？

Yes 是的

> 请尝试：

192:src tormentous$ git clone --depth 1 https://github.com/klzgrad/naiveproxy.git
Cloning into 'naiveproxy'...
remote: Enumerating objects: 11812, done.
remote: Counting objects: 100% (11812/11812), done.
remote: Compressing objects: 100% (10356/10356), done.
remote: Total 11812 (delta 1399), reused 9572 (delta 1077), pack-reused 0
Receiving objects: 100% (11812/11812), 28.27 MiB | 1.24 MiB/s, done.
Resolving deltas: 100% (1399/1399), done.
Updating files: 100% (11353/11353), done.
192:src tormentous$ cd naiveproxy/src
192:src tormentous$ export ANDROID_HOME=/Users/mcbook/Library/Android/sdk
192:src tormentous$ export ANDROID_NDK_HOME=/Users/mcbook/adt-bundle-mac-x86_64-20140702/sdk/ndk/21.3.6528147
192:src tormentous$ 
192:src tormentous$ EXTRA_FLAGS='target_cpu="arm64" target_os="android"' ./get-clang.sh
+ . ./get-sysroot.sh
+++ uname
++ ARCH=Darwin
+++ which python2
+++ which python
++ PYTHON=/usr/bin/python
+++ /usr/bin/python tools/clang/scripts/update.py --print-revision
++ CLANG_REVISION=llvmorg-13-init-15163-g98033fdc-1
++ eval 'target_cpu="arm64" target_os="android"'
+++ target_cpu=arm64
+++ target_os=android
++ case "$ARCH" in
++ which ccache
++ export CCACHE_SLOPPINESS=time_macros
++ CCACHE_SLOPPINESS=time_macros
++ export CCACHE_BASEDIR=/Users/mcbook/naiveproxy/src/naiveproxy/src
++ CCACHE_BASEDIR=/Users/mcbook/naiveproxy/src/naiveproxy/src
++ export CCACHE_CPP2=yes
++ CCACHE_CPP2=yes
++ CCACHE=ccache
++ WITH_CLANG=Mac
++ USE_DSYMUTIL=y
++ WITH_PGO=mac
++ WITH_GN=mac
++ '[' mac ']'
+++ cat chrome/build/mac.pgo.txt
++ PGO_PATH=chrome-mac-4577-1629902302-845c5352866ea6fc5cbe2c287dcadbea46d358bc.profdata
+ '[' '' -a '!' -d .//lib ']'
+ '[' '' ']'
+ '[' '!' -d third_party/llvm-build/Release+Asserts/bin ']'
+ mkdir -p third_party/llvm-build/Release+Asserts
+ clang_path=clang-llvmorg-13-init-15163-g98033fdc-1.tgz
+ clang_url=https://commondatastorage.googleapis.com/chromium-browser-clang/Mac/clang-llvmorg-13-init-15163-g98033fdc-1.tgz
+ curl https://commondatastorage.googleapis.com/chromium-browser-clang/Mac/clang-llvmorg-13-init-15163-g98033fdc-1.tgz
+ tar xzf - -C third_party/llvm-build/Release+Asserts
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 50.1M  100 50.1M    0     0  1161k      0  0:00:44  0:00:44 --:--:--  594k
+ '[' '' -a '!' -f chrome/android/profiles/afdo.prof ']'
+ '[' mac -a '!' -f chrome/build/pgo_profiles/chrome-mac-4577-1629902302-845c5352866ea6fc5cbe2c287dcadbea46d358bc.profdata ']'
+ mkdir -p chrome/build/pgo_profiles
+ cd chrome/build/pgo_profiles
+ curl --limit-rate 10M -LO https://storage.googleapis.com/chromium-optimization-profiles/pgo_profiles/chrome-mac-4577-1629902302-845c5352866ea6fc5cbe2c287dcadbea46d358bc.profdata
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  146M    0  146M    0     0  1009k      0 --:--:--  0:02:28 --:--:-- 1388k
+ cd ../../..
+ '[' y -a '!' -f tools/clang/dsymutil/bin/dsymutil ']'
+ mkdir -p tools/clang/dsymutil
+ dsymutil_path=dsymutil-llvmorg-13-init-15163-g98033fdc-1.tgz
+ dsymutil_url=https://commondatastorage.googleapis.com/chromium-browser-clang-staging/Mac/dsymutil-llvmorg-13-init-15163-g98033fdc-1.tgz
+ curl https://commondatastorage.googleapis.com/chromium-browser-clang-staging/Mac/dsymutil-llvmorg-13-init-15163-g98033fdc-1.tgz
+ tar xzf - -C tools/clang/dsymutil
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 11.8M  100 11.8M    0     0  1021k      0  0:00:11  0:00:11 --:--:-- 1420k
+ '[' '' -a '!' -f /Users/mcbook/.cargo/bin/sccache.exe ']'
+ '[' '!' -f gn/out/gn ']'
++ grep ''\''gn_version'\'':' DEPS
++ cut '-d'\''' -f4
+ gn_version=git_revision:24e2f7df92641de0351a96096fb2c490b2436bb8
+ mkdir -p gn/out
+ curl -L https://chrome-infra-packages.appspot.com/dl/gn/gn/mac-amd64/+/git_revision:24e2f7df92641de0351a96096fb2c490b2436bb8 -o gn.zip
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   711  100   711    0     0    582      0  0:00:01  0:00:01 --:--:--   582
100  895k  100  895k    0     0   159k      0  0:00:05  0:00:05 --:--:--  206k
+ unzip gn.zip -d gn/out
Archive:  gn.zip
  inflating: gn/out/gn               
  inflating: gn/out/.cipdpkg/manifest.json  
+ rm gn.zip
+ '[' '' -a '!' -d third_party/android_ndk ']'
192:src tormentous$ EXTRA_FLAGS='target_cpu="arm64" target_os="android"' ./build.sh
ERROR at //third_party/zlib/BUILD.gn:339:17: Unable to load "/Users/mcbook/naiveproxy/src/naiveproxy/src/third_party/android_ndk/BUILD.gn".
      deps += [ "//third_party/android_ndk:cpu_features" ]
                ^---------------------------------------

**Comment by Demon-Cat** [comment]
> > 您在mac平台上构建？
> 
> Yes 是的
> 
> > 请尝试：
> 
> 192:src tormentous$ git clone --depth 1 https://github.com/klzgrad/naiveproxy.git
> Cloning into 'naiveproxy'...
> remote: Enumerating objects: 11812, done.
> remote: Counting objects: 100% (11812/11812), done.
> remote: Compressing objects: 100% (10356/10356), done.
> remote: Total 11812 (delta 1399), reused 9572 (delta 1077), pack-reused 0
> Receiving objects: 100% (11812/11812), 28.27 MiB | 1.24 MiB/s, done.
> Resolving deltas: 100% (1399/1399), done.
> Updating files: 100% (11353/11353), done.
> 192:src tormentous$ cd naiveproxy/src
> 192:src tormentous$ export ANDROID_HOME=/Users/mcbook/Library/Android/sdk
> 192:src tormentous$ export ANDROID_NDK_HOME=/Users/mcbook/adt-bundle-mac-x86_64-20140702/sdk/ndk/21.3.6528147
> 192:src tormentous$
> 192:src tormentous$ EXTRA_FLAGS='target_cpu="arm64" target_os="android"' ./get-clang.sh
> 
> * . ./get-sysroot.sh
>   +++ uname
>   ++ ARCH=Darwin
>   +++ which python2
>   +++ which python
>   ++ PYTHON=/usr/bin/python
>   +++ /usr/bin/python tools/clang/scripts/update.py --print-revision
>   ++ CLANG_REVISION=llvmorg-13-init-15163-g98033fdc-1
>   ++ eval 'target_cpu="arm64" target_os="android"'
>   +++ target_cpu=arm64
>   +++ target_os=android
>   ++ case "$ARCH" in
>   ++ which ccache
>   ++ export CCACHE_SLOPPINESS=time_macros
>   ++ CCACHE_SLOPPINESS=time_macros
>   ++ export CCACHE_BASEDIR=/Users/mcbook/naiveproxy/src/naiveproxy/src
>   ++ CCACHE_BASEDIR=/Users/mcbook/naiveproxy/src/naiveproxy/src
>   ++ export CCACHE_CPP2=yes
>   ++ CCACHE_CPP2=yes
>   ++ CCACHE=ccache
>   ++ WITH_CLANG=Mac
>   ++ USE_DSYMUTIL=y
>   ++ WITH_PGO=mac
>   ++ WITH_GN=mac
>   ++ '[' mac ']'
>   +++ cat chrome/build/mac.pgo.txt
>   ++ PGO_PATH=chrome-mac-4577-1629902302-845c5352866ea6fc5cbe2c287dcadbea46d358bc.profdata
> * '[' '' -a '!' -d .//lib ']'
> * '[' '' ']'
> * '[' '!' -d third_party/llvm-build/Release+Asserts/bin ']'
> * mkdir -p third_party/llvm-build/Release+Asserts
> * clang_path=clang-llvmorg-13-init-15163-g98033fdc-1.tgz
> * clang_url=https://commondatastorage.googleapis.com/chromium-browser-clang/Mac/clang-llvmorg-13-init-15163-g98033fdc-1.tgz
> * curl https://commondatastorage.googleapis.com/chromium-browser-clang/Mac/clang-llvmorg-13-init-15163-g98033fdc-1.tgz
> * tar xzf - -C third_party/llvm-build/Release+Asserts
>   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
>   Dload  Upload   Total   Spent    Left  Speed
>   100 50.1M  100 50.1M    0     0  1161k      0  0:00:44  0:00:44 --:--:--  594k
> * '[' '' -a '!' -f chrome/android/profiles/afdo.prof ']'
> * '[' mac -a '!' -f chrome/build/pgo_profiles/chrome-mac-4577-1629902302-845c5352866ea6fc5cbe2c287dcadbea46d358bc.profdata ']'
> * mkdir -p chrome/build/pgo_profiles
> * cd chrome/build/pgo_profiles
> * curl --limit-rate 10M -LO https://storage.googleapis.com/chromium-optimization-profiles/pgo_profiles/chrome-mac-4577-1629902302-845c5352866ea6fc5cbe2c287dcadbea46d358bc.profdata
>   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
>   Dload  Upload   Total   Spent    Left  Speed
>   100  146M    0  146M    0     0  1009k      0 --:--:--  0:02:28 --:--:-- 1388k
> * cd ../../..
> * '[' y -a '!' -f tools/clang/dsymutil/bin/dsymutil ']'
> * mkdir -p tools/clang/dsymutil
> * dsymutil_path=dsymutil-llvmorg-13-init-15163-g98033fdc-1.tgz
> * dsymutil_url=https://commondatastorage.googleapis.com/chromium-browser-clang-staging/Mac/dsymutil-llvmorg-13-init-15163-g98033fdc-1.tgz
> * curl https://commondatastorage.googleapis.com/chromium-browser-clang-staging/Mac/dsymutil-llvmorg-13-init-15163-g98033fdc-1.tgz
> * tar xzf - -C tools/clang/dsymutil
>   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
>   Dload  Upload   Total   Spent    Left  Speed
>   100 11.8M  100 11.8M    0     0  1021k      0  0:00:11  0:00:11 --:--:-- 1420k
> * '[' '' -a '!' -f /Users/mcbook/.cargo/bin/sccache.exe ']'
> * '[' '!' -f gn/out/gn ']'
>   ++ grep ''''gn_version''':' DEPS
>   ++ cut '-d'''' -f4
> * gn_version=git_revision:24e2f7df92641de0351a96096fb2c490b2436bb8
> * mkdir -p gn/out
> * curl -L https://chrome-infra-packages.appspot.com/dl/gn/gn/mac-amd64/+/git_revision:24e2f7df92641de0351a96096fb2c490b2436bb8 -o gn.zip
>   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
>   Dload  Upload   Total   Spent    Left  Speed
>   100   711  100   711    0     0    582      0  0:00:01  0:00:01 --:--:--   582
>   100  895k  100  895k    0     0   159k      0  0:00:05  0:00:05 --:--:--  206k
> * unzip gn.zip -d gn/out
>   Archive:  gn.zip
>   inflating: gn/out/gn
>   inflating: gn/out/.cipdpkg/manifest.json
> * rm gn.zip
> * '[' '' -a '!' -d third_party/android_ndk ']'
>   192:src tormentous$ EXTRA_FLAGS='target_cpu="arm64" target_os="android"' ./build.sh
>   ERROR at //third_party/zlib/BUILD.gn:339:17: Unable to load "/Users/mcbook/naiveproxy/src/naiveproxy/src/third_party/android_ndk/BUILD.gn".
>   deps += [ "//third_party/android_ndk:cpu_features" ]
>   ^---------------------------------------

默认作者的 get-clang 脚本所获取编译构建环境中，安卓似乎仅有在linux环境。请详细查看脚本中 https://chromium.googlesource.com/android_ndk.git/+/refs/heads/main

**Comment by Demon-Cat** [comment]
也就是说你目前在mac平台上构建，它找不到android_ndk原因可以是加载啦Linux版的android_ndk，而不是你所谓的mac平台上的android_ndk

**Comment by tormentous** [comment]
> 也就是说你目前在mac平台上构建，它找不到android_ndk原因可能是加载了Linux版的android_ndk，而不是你所谓的mac平台上的android_ndk.
> 
> 当然，你也可以尝试将adt-bundle-mac-x86_64-20140702/sdk/ndk/21.3.6528147中的内容替换掉third_party/android_ndk 目录中的文件再试试看

我跟着这个
https://github.com/klzgrad/naiveproxy/issues/185

**Comment by Demon-Cat** [comment]
> > 也就是说你目前在mac平台上构建，它找不到android_ndk原因可能是加载了Linux版的android_ndk，而不是你所谓的mac平台上的android_ndk.
> > 当然，你也可以尝试将adt-bundle-mac-x86_64-20140702/sdk/ndk/21.3.6528147中的内容替换掉third_party/android_ndk 目录中的文件再试试看
> 
> 我跟着这个
> #185
> 
> ![Screen Shot 2021-09-18 at 1 50 11 PM](https://user-images.githubusercontent.com/34568349/133877701-07997875-04d2-4253-ab30-114d044e0842.png)
> 
> 192:src tormentous$ EXTRA_FLAGS='target_cpu="arm64" target_os="android"' ./build.sh
> ERROR at //build/toolchain/apple/toolchain.gni:56:3: Duplicate toolchain.
> toolchain(target_name) {
> ^-----------------------
> Two or more toolchains write to the same directory:
> //out/Release/clang_x64/
> 
> This can be fixed by making sure that distinct toolchains have
> distinct names.
> 
> See //build/toolchain/gcc_toolchain.gni:106:3: Previous toolchain.
> toolchain(target_name) {
> ^-----------------------

它看起来貌似 toolchain(target_name) { 重复定义了，这个可能需要作者才能解决

**Comment by Demon-Cat** [comment]
刚查阅了chromium的安卓编译指南，明确指明了安卓不支持在mac或者windows上编译，https://chromium.googlesource.com/chromium/src/+/HEAD/docs/android_build_instructions.md



System requirements
A 64-bit Intel machine running Linux with at least 8GB of RAM. More than 16GB is highly recommended.
At least 100GB of free disk space.
You must have Git and Python installed already.
Most development is done on Ubuntu. Other distros may or may not work; see the Linux instructions for some suggestions.

Building the Android client on Windows or Mac is not supported and doesn't work.

**Comment by Demon-Cat** [comment]
navie是chromium的下游，由于chromium不支持在windows或者mac交叉编译Android 客户端，所以还是老老实实使用Linux环境编译吧

**Comment by klzgrad** [comment]
不支持
