### ISSUE TITLE
Update to  94.0.4606.54

### ISSUE THREAD

**Issue by updater1234** [klzgrad/naiveproxy#224]
upstream has been upgraded to  94.0.4606.54

**Comment by testermania** [comment]
Is udp supported?

**Comment by updater1234** [comment]
The software only supports HTTPS or QUIC. And QUIC is based on UDP protocol.

**Comment by testermania** [comment]
I changed client settings https: to quic:

I get the following error

ERR_QUIC_PROTOCOL_ERROR

**Comment by hdid** [comment]
> Is udp supported?

Socks UDP associate is not supported.
