### ISSUE TITLE
The test shows that QUIC is not supported

### ISSUE THREAD

**Issue by ysbreh** [klzgrad/naiveproxy#226]
HTTP/3 Check a URL ：https://http3check.net/
URL : My url
Caddyfile : 

```
{
  servers {
    protocol {
      experimental_http3
    }
  }
}
:443, My url
tls me@example.com
route {
  forward_proxy {
    basic_auth user pass
    hide_ip
    hide_via
    probe_resistance
  }
  file_server { root /var/www/html }
}
```

Test results ：
    QUIC is not supported
    HTTP/3 is supported
    HTTP/3 Check failed to establish a QUIC connection for all attempts made with the given endpoint. 
What's the reason？

**Comment by klzgrad** [comment]
This is an issue between Caddy and http3check.net.
