### ISSUE TITLE
关于中转naive流量

### ISSUE THREAD

**Issue by Demon-Cat** [klzgrad/naiveproxy#227]
目前有一个需求，就是又一台国外很垃圾的机器（可以看nf），但连接到国内速度简直惨不忍睹（延迟、丢包极高）。目前我想弄一台中转机，来中转naive的流量，请问具体该怎么弄？

**Comment by klzgrad** [comment]
Caddy forwardproxy用upstream选项可以中转，细节自查

**Comment by Demon-Cat** [comment]
> Caddy forwardproxy用upstream选项可以中转，细节自查



上游代理服务器：

```
{
  servers  {
    protocol {
      experimental_http3   #开启 HTTP/3支持
    }
  }
}
:443, server02.example.com
tls /etc/ssl/private/cert.pem /etc/ssl/private/key.pem 
route {
  forward_proxy {
    basic_auth user pass
    hide_ip
    hide_via
    probe_resistance
  }
}
```

中转服务器上，设置上游代理：

```
{
  servers  {
    protocol {
      experimental_http3   #开启 HTTP/3支持
    }
  }
}
:443, server01.example.com
tls /etc/ssl/private/cert.pem /etc/ssl/private/key.pem 
route {
  forward_proxy {
    basic_auth user pass
    hide_ip
    hide_via
    upstream https://user:pass@server02.example.com:443
  }
}
```

意味着上游代理服务器和中转服务器都需要配置不同的域名和证书？还有 forward_proxy 中的 basic_auth、hide_ip、hide_via在中转机中也需要填写对吧？目前在本地navie代理填写了中转的地址 server01.example.com，连接后发现ip地址为上游代理服务器的地址server02.example.com。这意味着上游代理服务器和中转服务器都需要证书认证，我不太清楚会不会影响性能，可能我这种方式设置有些问题。肯请作者指正我的不足之处，万分感谢！
