### ISSUE TITLE
Support Http and Sock Proxy upstream.

### ISSUE THREAD

**Issue by Doimatcuabautroi** [klzgrad/naiveproxy#233]
As the tittle, please support http or sock proxy upstream.
I also have question, if naiveproxy can upstream http or sock proxy. Does it can still camouflage like your architecture: 
([Browser → Naïve client] ⟶ Censor ⟶ [Frontend → Naïve server] ⟶ Internet).
Because I am using some free proxy (http or sock, example: hola proxy, shadowsocks, ultrasurf,...), but I want to upstream all internet traffic through naiveproxy, Im not sure that can still bypass firewall like your architecture, so i opened the issue.

**Comment by klzgrad** [comment]
It does not. There is no camouflage in http or socks transport. HTTP/2/TLS is the basic premise for this.

It is also pointless to run naiveproxy inside another tunnel. There needs to be only one obfuscation layer.
