### ISSUE TITLE
Emulate chrome network stack in node.js/curl

### ISSUE THREAD

**Issue by restyler** [klzgrad/naiveproxy#238]
Hi! I am not sure if naiveproxy is a good fit for my use case, but I decided to ask anyways. I am trying to bypass website scraping protection which apparently detects the tls fingerprint of node.js/curl request and shows 403 error page for such requests, while the exact same request from real browser works fine. Is it possible to use naiveproxy as a proxy for curl utility so the request looks exactly like it was originated from Chrome? thanks in advance.

**Comment by klzgrad** [comment]
Naiveproxy protects against man in the middle attack. It doesn't interfere with end to end traffic. It's easier to program headless Chrome or use selenium for automation.

**Comment by restyler** [comment]
thank you for you reply. headless chrome evaluates js, and this makes it too resource intensive and slow for my use case. I need just a network stack with tls.

**Comment by klzgrad** [comment]
I believe what you are looking for is Cronet's native API: https://source.chromium.org/chromium/chromium/src/+/main:components/cronet/ https://source.chromium.org/chromium/chromium/src/+/main:components/cronet/native/sample/

It exposes C API. Naiveproxy exposes a socks5 network interface but no API. Also Cronet is oriented for request-response transaction while Naiveproxy is oriented for bidirectional traffic.

**Comment by restyler** [comment]
Thank you for your reply, it helped.
