### ISSUE TITLE
Connection Distribution to Multiple Servers

### ISSUE THREAD

**Issue by CyberLeopard** [klzgrad/naiveproxy#239]
Hello,

With a setup of multiple servers and naiveproxy run with multiple connections, I can set some servers as active and some as backup, but traffic may not be distributed as I intended, here are some examples:

1. Some of the active servers go down, naiveproxy connections will go to the rest of the active servers and stay there even after these servers are back online. Result un-balanced distribution between the active servers.
2. All active servers go down, naiveproxy connections will go to the backup servers and stay there even after active servers are back online. 

I can restart naiveproxy to redistribute its connections, but this will interrupt all proxy connections for example downloading, SSH, etc. Is there a way naiveproxy connections close automatically?

Here is how it might work: naiveproxy connection turns to closing/dying stage after some time, during this stage, it will create another connection which accepts new proxy connections, the old naiveproxy connection don't accept new proxy connections and will close after all it's current proxy connections closed.

Any ideas on this will be appreciated. Thank you.

**Comment by klzgrad** [comment]
Seems like the standard use case of a load balancer that supports live update of backend list and priority based balancing. Have you checked haproxy?

I don't understand what the rest is trying to do. It seems to be the job of the load balancing frontend.

**Comment by klzgrad** [comment]
Reopen if you want to continue this discussion.
