### ISSUE TITLE
caddy报错

### ISSUE THREAD

**Issue by blog2020** [klzgrad/naiveproxy#24]
no action found for directive 'forwardproxy' with server type 'http' (missing a plugin?)

**Comment by klzgrad** [comment]
missing a plugin?

Did you download Caddy with the forwardproxy plugin?

**Comment by blog2020** [comment]
原来是没有安装插件，已经可以上网了，感谢。另外请教一下，我的是电信，用ss或者v2ray都被限制在10兆的宽带（我的网络是100M的），油管最高只能到10000Kbps，我是听别人说这个程序可以解决电信Qos的，但是我试了一下，好像并没什么改善，请问这个程序可以解决（或减缓）电信的Qos吗？

**Comment by klzgrad** [comment]
You ask me if this can improve your bandwidth after it didn't. Of course it didn't. In theory it should, because this is https traffic on port 443.
