### ISSUE TITLE
server error log: read: connection reset by peer, client error: read: connection reset by peer

### ISSUE THREAD

**Issue by zdfdreamfactory** [klzgrad/naiveproxy#240]
Latest caddy v2 with klzgrad forwardproxy

Problem:
Sometimes working, sometimes not working

I use quic proxy, not https (tcp blocked by the wall, test with tcping )

caddy server log:
Nov 19 03:31:22 exquisite-hops-2.localdomain caddy[9111]: {"level":"error","ts":1637292682.9433992,"logger":"http.log.error","msg":"stream 152 canceled with error code 268","request":{"remote_addr":"183.3.184.32:45318","proto":"HTTP/3","met>
Nov 19 03:31:38 exquisite-hops-2.localdomain caddy[9111]: {"level":"error","ts":1637292698.2188523,"logger":"http.log.error","msg":"stream 160 canceled with error code 268","request":{"remote_addr":"183.3.184.32:45318","proto":"HTTP/3","met>
Nov 19 03:36:07 exquisite-hops-2.localdomain caddy[9111]: {"level":"error","ts":1637292967.6602,"logger":"http.log.error","msg":"read tcp 64.64.225.180:40254->142.250.101.188:5228: read: connection reset by peer","request":{"remote_addr":"1>
Nov 19 03:39:10 exquisite-hops-2.localdomain caddy[9111]: {"level":"error","ts":1637293150.5709436,"logger":"http.log.error","msg":"read tcp 64.64.225.180:53144->31.13.65.18:443: read: connection reset by peer","request":{"remote_addr":"183>
Nov 19 03:39:10 exquisite-hops-2.localdomain caddy[9111]: {"level":"error","ts":1637293150.8811917,"logger":"http.log.error","msg":"read tcp 64.64.225.180:53146->31.13.65.18:443: read: connection reset by peer","request":{"remote_addr":"183>
Nov 19 03:52:00 exquisite-hops-2.localdomain caddy[9111]: {"level":"error","ts":1637293920.2872381,"logger":"http.log.error","msg":"read tcp 64.64.225.180:34354->172.253.113.188:443: read: connection reset by peer","request":{"remote_addr":>
Nov 19 03:55:25 exquisite-hops-2.localdomain caddy[9111]: {"level":"error","ts":1637294125.866673,"logger":"http.log.error","msg":"timeout: no recent network activity","request":{"remote_addr":"183.3.184.32:47003","proto":"HTTP/3","method":>
Nov 19 04:02:30 exquisite-hops-2.localdomain caddy[9111]: {"level":"error","ts":1637294550.8356872,"logger":"http.log.error","msg":"timeout: no recent network activity","request":{"remote_addr":"183.3.184.32:46871","proto":"HTTP/3","method">
Nov 19 04:13:28 exquisite-hops-2.localdomain caddy[9111]: {"level":"error","ts":1637295208.4722679,"logger":"http.log.error","msg":"read tcp 64.64.225.180:39046->173.194.219.188:5228: read: connection reset by peer","request":{"remote_addr">
Nov 19 04:36:43 exquisite-hops-2.localdomain caddy[9111]: {"level":"error","ts":1637296603.6682992,"logger":"http.log.error","msg":"read tcp 64.64.225.180:58386->142.250.152.188:443: read: connection reset by peer","request":{"remote_addr":>
Nov 19 04:42:04 exquisite-hops-2.localdomain caddy[9111]: {"level":"error","ts":1637296924.6508899,"logger":"http.log.error","msg":"read tcp 64.64.225.180:47862->142.250.141.188:5228: read: connection reset by peer","request":{"remote_addr">
Nov 19 04:51:25 exquisite-hops-2.localdomain caddy[9111]: {"level":"error","ts":1637297485.3522604,"logger":"http.log.error","msg":"timeout: no recent network activity","request":{"remote_addr":"183.3.184.34:42207","proto":"HTTP/3","method">
Nov 19 05:01:15 exquisite-hops-2.localdomain caddy[9111]: {"level":"error","ts":1637298075.6273038,"logger":"http.log.error","msg":"read tcp 64.64.225.180:48094->142.250.141.188:5228: read: connection reset by peer","request":{"remote_addr">
Nov 19 05:09:43 exquisite-hops-2.localdomain caddy[9111]: {"level":"error","ts":1637298583.1462421,"logger":"http.log.error","msg":"stream 8 canceled with error code 268","request":{"remote_addr":"183.3.184.34:43955","proto":"HTTP/3","metho>
Nov 19 05:11:13 exquisite-hops-2.localdomain caddy[9111]: {"level":"error","ts":1637298673.6438606,"logger":"http.log.error","msg":"read tcp 64.64.225.180:48110->142.250.141.188:5228: read: connection reset by peer","request":{"remote_addr">
Nov 19 05:21:09 exquisite-hops-2.localdomain caddy[9111]: {"level":"error","ts":1637299269.6110423,"logger":"http.log.error","msg":"read tcp 64.64.225.180:48124->142.250.141.188:5228: read: connection reset by peer","request":{"remote_addr">
Nov 19 05:44:58 exquisite-hops-2.localdomain caddy[9111]: {"level":"error","ts":1637300698.6618237,"logger":"http.log.error","msg":"timeout: no recent network activity","request":{"remote_addr":"183.3.184.34:42716","proto":"HTTP/3","method">
Nov 19 06:01:06 exquisite-hops-2.localdomain caddy[9111]: {"level":"error","ts":1637301666.8594372,"logger":"http.log.error","msg":"timeout: no recent network activity","request":{"remote_addr":"183.3.184.34:44183","proto":"HTTP/3","method">
Nov 19 06:29:57 exquisite-hops-2.localdomain caddy[9111]: {"level":"error","ts":1637303397.652028,"logger":"http.log.error","msg":"timeout: no recent network activity","request":{"remote_addr":"183.3.184.34:44736","proto":"HTTP/3","method":>
Nov 19 06:44:43 exquisite-hops-2.localdomain caddy[9111]: {"level":"error","ts":1637304283.1719518,"logger":"http.log.error","msg":"timeout: no recent network activity","request":{"remote_addr":"183.3.184.34:42178","proto":"HTTP/3","method">
Nov 19 06:45:49 exquisite-hops-2.localdomain caddy[9111]: {"level":"error","ts":1637304349.3586564,"logger":"http.log.error","msg":"timeout: no recent network activity","request":{"remote_addr":"183.3.184.34:42207","proto":"HTTP/3","method">
Nov 19 06:56:33 exquisite-hops-2.localdomain caddy[9111]: {"level":"error","ts":1637304993.7721198,"logger":"http.log.error","msg":"read tcp 64.64.225.180:50494->74.125.137.188:5228: read: connection reset by peer","request":{"remote_addr":>
Nov 19 06:59:42 exquisite-hops-2.localdomain caddy[9111]: {"level":"error","ts":1637305182.8713548,"logger":"http.log.error","msg":"timeout: no recent network activity","request":{"remote_addr":"183.3.184.34:43965","proto":"HTTP/3","method">
Nov 19 07:00:04 exquisite-hops-2.localdomain caddy[9111]: {"level":"error","ts":1637305204.9169135,"logger":"http.log.error","msg":"timeout: no recent network activity","request":{"remote_addr":"183.3.184.34:42417","proto":"HTTP/3","method">
Nov 19 07:11:14 exquisite-hops-2.localdomain caddy[9111]: {"level":"error","ts":1637305874.4669526,"logger":"http.log.error","msg":"read tcp 64.64.225.180:56550->142.250.112.188:5228: read: connection reset by peer","request":{"remote_addr">
Nov 19 07:21:19 exquisite-hops-2.localdomain caddy[9111]: {"level":"error","ts":1637306479.2922592,"logger":"http.log.error","msg":"timeout: no recent network activity","request":{"remote_addr":"183.3.184.34:42716","proto":"HTTP/3","method">
Nov 19 07:30:01 exquisite-hops-2.localdomain caddy[9111]: {"level":"error","ts":1637307001.0662377,"logger":"http.log.error","msg":"read tcp 64.64.225.180:54086->142.250.141.188:443: read: connection reset by peer","request":{"remote_addr":>
Nov 19 07:36:29 exquisite-hops-2.localdomain caddy[9111]: {"level":"error","ts":1637307389.9317753,"logger":"http.log.error","msg":"read tcp 64.64.225.180:51352->74.125.137.188:5228: read: connection reset by peer","request":{"remote_addr":>
Nov 19 07:44:06 exquisite-hops-2.localdomain caddy[9111]: {"level":"error","ts":1637307846.6352751,"logger":"http.log.error","msg":"read tcp 64.64.225.180:54248->142.250.141.188:443: read: connection reset by peer","request":{"remote_addr":>
Nov 19 07:50:03 exquisite-hops-2.localdomain caddy[9111]: {"level":"error","ts":1637308203.390306,"logger":"http.log.error","msg":"read tcp 64.64.225.180:46466->64.233.171.188:443: read: connection reset by peer","request":{"remote_addr":"1>
Nov 19 08:03:38 exquisite-hops-2.localdomain caddy[9111]: {"level":"error","ts":1637309018.0915787,"logger":"http.log.error","msg":"read tcp 64.64.225.180:52012->74.125.137.188:5228: read: connection reset by peer","request":{"remote_addr":>
Nov 19 08:23:14 exquisite-hops-2.localdomain caddy[9111]: {"level":"error","ts":1637310194.177305,"logger":"http.log.error","msg":"read tcp 64.64.225.180:48020->173.194.204.188:5228: read: connection reset by peer","request":{"remote_addr":>
Nov 19 08:28:12 exquisite-hops-2.localdomain caddy[9111]: {"level":"error","ts":1637310492.6515257,"logger":"http.log.error","msg":"read tcp 64.64.225.180:52418->74.125.137.188:5228: read: connection reset by peer","request":{"remote_addr":>
Nov 19 09:11:39 exquisite-hops-2.localdomain caddy[9111]: {"level":"error","ts":1637313099.7654958,"logger":"http.log.error","msg":"read tcp 64.64.225.180:52926->74.125.137.188:5228: read: connection reset by peer","request":{"remote_addr":>
Nov 19 09:35:59 exquisite-hops-2.localdomain caddy[9111]: {"level":"error","ts":1637314559.9797194,"logger":"http.log.error","msg":"read tcp 64.64.225.180:44546->142.250.101.188:5228: read: connection reset by peer","request":{"remote_addr">
Nov 19 09:36:00 exquisite-hops-2.localdomain caddy[9111]: {"level":"error","ts":1637314560.7314782,"logger":"http.log.error","msg":"read tcp 64.64.225.180:41434->173.194.77.188:443: read: connection reset by peer","request":{"remote_addr":">
Nov 19 09:37:13 exquisite-hops-2.localdomain caddy[9111]: {"level":"error","ts":1637314633.5768712,"logger":"http.log.error","msg":"stream 204 canceled with error code 268","request":{"remote_addr":"183.3.184.34:44554","proto":"HTTP/3","met>
Nov 19 09:48:56 exquisite-hops-2.localdomain caddy[9111]: {"level":"error","ts":1637315336.17316,"logger":"http.log.error","msg":"read tcp 64.64.225.180:44758->142.250.101.188:5228: read: connection reset by peer","request":{"remote_addr":">
Nov 19 09:56:28 exquisite-hops-2.localdomain caddy[9111]: {"level":"error","ts":1637315788.7787921,"logger":"http.log.error","msg":"read tcp 64.64.225.180:44766->142.250.101.188:5228: read: connection reset by peer","request":{"remote_addr">
Nov 19 10:37:20 exquisite-hops-2.localdomain caddy[9111]: {"level":"error","ts":1637318240.235996,"logger":"http.log.error","msg":"read tcp 64.64.225.180:53336->74.125.137.188:5228: read: connection reset by peer","request":{"remote_addr":">
Nov 19 10:47:24 exquisite-hops-2.localdomain caddy[9111]: {"level":"error","ts":1637318844.4564488,"logger":"http.log.error","msg":"read tcp 64.64.225.180:59298->142.250.112.188:5228: read: connection reset by peer","request":{"remote_addr">
Nov 19 10:49:19 exquisite-hops-2.localdomain caddy[9111]: {"level":"error","ts":1637318959.3704162,"logger":"http.log.error","msg":"stream 112 canceled with error code 268","request":{"remote_addr":"183.3.184.34:43495","proto":"HTTP/3","met>
Nov 19 10:50:48 exquisite-hops-2.localdomain caddy[9111]: {"level":"error","ts":1637319048.171408,"logger":"http.log.error","msg":"read tcp 64.64.225.180:53408->74.125.137.188:5228: read: connection reset by peer","request":{"remote_addr":">
Nov 19 10:54:38 exquisite-hops-2.localdomain caddy[9111]: {"level":"error","ts":1637319278.5712004,"logger":"http.log.error","msg":"read tcp 64.64.225.180:53636->74.125.137.188:5228: read: connection reset by peer","request":{"remote_addr":>
Nov 19 11:03:26 exquisite-hops-2.localdomain caddy[9111]: {"level":"error","ts":1637319806.0913184,"logger":"http.log.error","msg":"read tcp 64.64.225.180:45156->142.250.101.188:5228: read: connection reset by peer","request":{"remote_addr">
Nov 19 11:04:55 exquisite-hops-2.localdomain caddy[9111]: {"level":"error","ts":1637319895.3334136,"logger":"http.log.error","msg":"read tcp 64.64.225.180:44884->172.253.63.188:5228: read: connection reset by peer","request":{"remote_addr":>
Nov 19 11:09:21 exquisite-hops-2.localdomain caddy[9111]: {"level":"error","ts":1637320161.2588334,"logger":"http.log.error","msg":"read tcp 64.64.225.180:45250->142.250.101.188:5228: read: connection reset by peer","request":{"remote_addr">
Nov 19 11:13:48 exquisite-hops-2.localdomain caddy[9111]: {"level":"error","ts":1637320428.6514378,"logger":"http.log.error","msg":"timeout: no recent network activity","request":{"remote_addr":"183.3.184.34:41630","proto":"HTTP/3","method">
Nov 19 11:20:39 exquisite-hops-2.localdomain caddy[9111]: {"level":"error","ts":1637320839.4022112,"logger":"http.log.error","msg":"read tcp 64.64.225.180:39028->74.125.137.188:443: read: connection reset by peer","request":{"remote_addr":">
Nov 19 11:21:21 exquisite-hops-2.localdomain caddy[9111]: {"level":"error","ts":1637320881.3876162,"logger":"http.log.error","msg":"read tcp 64.64.225.180:39044->74.125.137.188:443: read: connection reset by peer","request":{"remote_addr":">
Nov 19 11:22:13 exquisite-hops-2.localdomain caddy[9111]: {"level":"error","ts":1637320933.3587356,"logger":"http.log.error","msg":"read tcp 64.64.225.180:54286->74.125.137.188:5228: read: connection reset by peer","request":{"remote_addr":>
Nov 19 11:42:33 exquisite-hops-2.localdomain caddy[9111]: {"level":"error","ts":1637322153.962192,"logger":"http.log.error","msg":"read tcp 64.64.225.180:54938->74.125.137.188:5228: read: connection reset by peer","request":{"remote_addr":">
Nov 19 11:44:26 exquisite-hops-2.localdomain caddy[9111]: {"level":"error","ts":1637322266.0757432,"logger":"http.log.error","msg":"read tcp 64.64.225.180:43380->173.194.77.188:443: read: connection reset by peer","request":{"remote_addr":">

Client (Latest windows client)
[1119/200138.162:INFO:naive_connection.cc(250)] Connection 1180 to chat.google.com:443
[1119/200141.469:INFO:naive_connection.cc(250)] Connection 1181 to chat.google.com:443
[1119/200142.163:INFO:naive_proxy.cc(182)] Connection 1181 closed: ERR_QUIC_PROTOCOL_ERROR
[1119/200142.163:INFO:naive_proxy.cc(182)] Connection 1180 closed: ERR_QUIC_PROTOCOL_ERROR
[1119/200142.163:INFO:naive_proxy.cc(182)] Connection 1179 closed: ERR_QUIC_PROTOCOL_ERROR
[1119/200142.165:INFO:naive_connection.cc(250)] Connection 1182 to chat.google.com:443
[1119/200146.168:INFO:naive_proxy.cc(182)] Connection 1182 closed: ERR_QUIC_PROTOCOL_ERROR
[1119/200154.163:INFO:naive_connection.cc(250)] Connection 1183 to play.google.com:443
[1119/200158.166:INFO:naive_proxy.cc(182)] Connection 1183 closed: ERR_QUIC_PROTOCOL_ERROR
[1119/200202.177:INFO:naive_proxy.cc(182)] Connection 1184 closed: ERR_QUIC_PROTOCOL_ERROR
[1119/200212.197:INFO:naive_connection.cc(250)] Connection 1185 to www.google.com:443
[1119/200214.169:INFO:naive_connection.cc(250)] Connection 1186 to mail.google.com:443
[1119/200214.842:INFO:naive_connection.cc(250)] Connection 1187 to www.google.com:443
[1119/200216.371:INFO:naive_proxy.cc(182)] Connection 1187 closed: ERR_QUIC_PROTOCOL_ERROR
[1119/200216.371:INFO:naive_proxy.cc(182)] Connection 1185 closed: ERR_QUIC_PROTOCOL_ERROR
[1119/200216.371:INFO:naive_proxy.cc(182)] Connection 1186 closed: ERR_QUIC_PROTOCOL_ERROR
[1119/200216.373:INFO:naive_connection.cc(250)] Connection 1188 to www.google.com:443
[1119/200216.374:INFO:naive_connection.cc(250)] Connection 1189 to www.google.com:443
[1119/200216.374:INFO:naive_connection.cc(250)] Connection 1190 to mail.google.com:443
[1119/200220.384:INFO:naive_proxy.cc(182)] Connection 1189 closed: ERR_QUIC_PROTOCOL_ERROR
[1119/200220.384:INFO:naive_proxy.cc(182)] Connection 1188 closed: ERR_QUIC_PROTOCOL_ERROR
[1119/200220.384:INFO:naive_proxy.cc(182)] Connection 1190 closed: ERR_QUIC_PROTOCOL_ERROR
[1119/200220.413:INFO:naive_connection.cc(250)] Connection 1191 to www.google.com:443
[1119/200224.427:INFO:naive_proxy.cc(182)] Connection 1191 closed: ERR_QUIC_PROTOCOL_ERROR
[1119/200224.429:INFO:naive_connection.cc(250)] Connection 1192 to www.google.com:443
[1119/200225.169:INFO:naive_connection.cc(250)] Connection 1193 to mail.google.com:443

**Comment by klzgrad** [comment]
QUIC is not guaranteed to work in adverse network conditions.
