### ISSUE TITLE
关于梅林ARM Cortex A9架构

### ISSUE THREAD

**Issue by emmaki** [klzgrad/naiveproxy#250]
请问目前Releases 版本中，有可支持梅林固件的ARM Cortex A9架构的naiveproxy文件吗？如果没有，如何进行交叉编译可支持的版本？
https://github.com/RMerl/am-toolchains

**Comment by klzgrad** [comment]
https://github.com/klzgrad/naiveproxy/wiki/OpenWrt-Support#asuswrt-merlin
