### ISSUE TITLE
关于前置tls,作为v2ray/xray/trojan-go的tls前置

### ISSUE THREAD

**Issue by ilpl** [klzgrad/naiveproxy#253]
请问有没有可能作为v2ray/xray/trojan-go的tls前置?

例如:
v2ray(trojan)+naiveproxy(tls) ----> server[trojan+tls]
v2ray访问本地naiveproxy监听,naiveproxy添加一层tls再去访问服务器

在不改变服务器的情况下使用naiveproxy作为v2fly的tls前置(v2fly去掉tls).

这样就达到了消除go指纹,并且使用v2ray强大的功能

**Comment by klzgrad** [comment]
多层加密意义不大

而且go指纹还没有成为问题，所以没有人感到这个事情很紧迫
