### ISSUE TITLE
IOS编译问题处理解决整个过程-作者有意添加上？？

### ISSUE THREAD

**Issue by emmaki** [klzgrad/naiveproxy#255]
我尝试指定target_os="ios"，似乎可以正常编译，但链接库时就发生错误了。似乎是链接时找不到stdlib++ 
```
export EXTRA_FLAGS="target_cpu=\"arm64\" target_os=\"ios\" use_allocator=\"none\" use_allocator_shim=false enable_dsyms=false"
```

错误发生在Link：
```
Done. Made 456 targets from 145 files in 1148ms
ninja: Entering directory `out/Release'
[2334/3162] LINK clang_x64/protoc
warning: no debug symbols in executable (-arch x86_64)
[2694/3162] LINK clang_x64/root_store_tool
warning: no debug symbols in executable (-arch x86_64)
[3162/3162] LINK ./naive
FAILED: naive 
TOOL_VERSION=1642467775 ../../build/toolchain/apple/linker_driver.py -Wcrl,strippath,../../../../../../../../Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/strip ../../third_party/llvm-build/Release+Asserts/bin/clang++  -fuse-ld=lld -Wl,--icf=all -Wl,--color-diagnostics -target arm64-apple-ios14.0 -no-canonical-prefixes -Wl,-dead_strip -Wl,-no_data_in_code_info -Wl,-no_function_starts -nostdlib++ -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS15.2.sdk -Wl,-ObjC -Wl,-rpath,@executable_path/Frameworks -L/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS15.2.sdk/usr/lib/swift -L/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/swift/iphoneos -o "./naive" "@./naive.rsp"
ld64.lld: error: undefined symbol: ___gxx_personality_v0
>>> referenced by obj/net/libnet.a(network_change_notifier_mac.o)

ld64.lld: error: undefined symbol: ___cxa_begin_catch
>>> referenced by obj/base/libbase.a(call_with_eh_frame_asm.o)

ld64.lld: error: undefined symbol: ___gxx_personality_v0
>>> referenced by obj/net/libnet.a(network_change_notifier_mac.o)

ld64.lld: error: undefined symbol: ___gxx_personality_v0
>>> referenced by obj/net/libnet.a(network_change_notifier_mac.o)

ld64.lld: error: undefined symbol: ___gxx_personality_v0
>>> referenced by obj/net/libnet.a(network_change_notifier_mac.o)

ld64.lld: error: undefined symbol: ___gxx_personality_v0
>>> referenced by obj/net/libnet.a(network_change_notifier_mac.o)

ld64.lld: error: undefined symbol: ___gxx_personality_v0
>>> referenced by obj/net/libnet.a(network_change_notifier_mac.o)

ld64.lld: error: undefined symbol: ___gxx_personality_v0
>>> referenced by obj/net/libnet.a(network_change_notifier_mac.o)

ld64.lld: error: undefined symbol: ___gxx_personality_v0
>>> referenced by obj/net/libnet.a(network_change_notifier_mac.o)

ld64.lld: error: undefined symbol: ___gxx_personality_v0
>>> referenced by obj/net/libnet.a(network_change_notifier_mac.o)

ld64.lld: error: undefined symbol: ___gxx_personality_v0
>>> referenced by obj/net/libnet.a(network_change_notifier_mac.o)

ld64.lld: error: undefined symbol: ___gxx_personality_v0
>>> referenced by obj/net/libnet.a(network_change_notifier_mac.o)

ld64.lld: error: undefined symbol: ___gxx_personality_v0
>>> referenced by obj/net/libnet.a(network_change_notifier_mac.o)

ld64.lld: error: undefined symbol: ___gxx_personality_v0
>>> referenced by obj/net/libnet.a(network_change_notifier_mac.o)

ld64.lld: error: undefined symbol: ___gxx_personality_v0
>>> referenced by obj/net/libnet.a(network_change_notifier_mac.o)

ld64.lld: error: undefined symbol: ___gxx_personality_v0
>>> referenced by obj/net/libnet.a(network_change_notifier_mac.o)

ld64.lld: error: undefined symbol: ___gxx_personality_v0
>>> referenced by obj/net/libnet.a(network_change_notifier_mac.o)

ld64.lld: error: undefined symbol: ___gxx_personality_v0
>>> referenced by obj/net/libnet.a(network_change_notifier_mac.o)

ld64.lld: error: undefined symbol: ___gxx_personality_v0
>>> referenced by obj/net/libnet.a(network_change_notifier_mac.o)

ld64.lld: error: undefined symbol: ___gxx_personality_v0
>>> referenced by obj/net/libnet.a(network_change_notifier_mac.o)

ld64.lld: error: too many errors emitted, stopping now (use --error-limit=0 to see all errors)
clang++: error: linker command failed with exit code 1 (use -v to see invocation)
Traceback (most recent call last):
  File "/Users/mk/Desktop/tt/naiveproxy/src/out/Release/../../build/toolchain/apple/linker_driver.py", line 341, in <module>
    LinkerDriver(sys.argv).run()
  File "/Users/mk/Desktop/tt/naiveproxy/src/out/Release/../../build/toolchain/apple/linker_driver.py", line 117, in run
    subprocess.check_call(compiler_driver_args, env=env)
  File "/Users/mk/miniforge3/lib/python3.9/subprocess.py", line 373, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['../../third_party/llvm-build/Release+Asserts/bin/clang++', '-fuse-ld=lld', '-Wl,--icf=all', '-Wl,--color-diagnostics', '-target', 'arm64-apple-ios14.0', '-no-canonical-prefixes', '-Wl,-dead_strip', '-Wl,-no_data_in_code_info', '-Wl,-no_function_starts', '-nostdlib++', '-isysroot', '/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS15.2.sdk', '-Wl,-ObjC', '-Wl,-rpath,@executable_path/Frameworks', '-L/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS15.2.sdk/usr/lib/swift', '-L/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/swift/iphoneos', '-o', './naive', '@./naive.rsp']' returned non-zero exit status 1.
ninja: build stopped: subcommand failed.
```

问题解决在二楼上！

**Comment by emmaki** [comment]
我找到原因了，似乎是 在编译 IOS时，chromium自动添加上了 -nostdlib++ 参数。

如果我去掉了参数，则正常编译：
```
../../third_party/llvm-build/Release+Asserts/bin/clang++ -fuse-ld=lld -Wl,--icf=all -Wl,--color-diagnostics -target arm64-apple-ios14.0 -no-canonical-prefixes -Wl,-dead_strip -Wl,-no_data_in_code_info -Wl,-no_function_starts -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS15.2.sdk -Wl,-ObjC -Wl,-rpath,@executable_path/Frameworks -L/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS15.2.sdk/usr/lib/swift -L/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/swift/iphoneos -o ./naive @./naive.rsp
```

**Comment by emmaki** [comment]
想问下，作者能否添加上IOS编译？

**Comment by klzgrad** [comment]
编译完了怎么运行？

https://chromium.googlesource.com/chromium/src/+/main/docs/ios/build_instructions.md#building-for-device

> To be able to build and run Chromium and the tests for devices, you need to have an Apple developer account (a free one will work) and the appropriate provisioning profiles, then configure the build to use them.

> Please refer to the Apple documentation on how to get a code signing identity and certificates. You can check that you have a code signing identity correctly installed by running the following command.

`Apple developer account`和`a code signing identity and certificates`从哪里来？

**Comment by hw-1** [comment]
> 我找到原因了，似乎是 在编译 IOS时，chromium自动添加上了 -nostdlib++ 参数。
> 
> 如果我去掉了参数，则正常Link链接 （这个我在测试时自己指定的Link参数）：
> 
> ```
> ../../third_party/llvm-build/Release+Asserts/bin/clang++ -fuse-ld=lld -Wl,--icf=all -Wl,--color-diagnostics -target arm64-apple-ios14.0 -no-canonical-prefixes -Wl,-dead_strip -Wl,-no_data_in_code_info -Wl,-no_function_starts -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS15.2.sdk -Wl,-ObjC -Wl,-rpath,@executable_path/Frameworks -L/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS15.2.sdk/usr/lib/swift -L/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/swift/iphoneos -o ./naive @./naive.rsp
> ```
> 
> 引起原因是，第124行：https://github.com/klzgrad/naiveproxy/blob/master/src/build/config/c%2B%2B/BUILD.gn#L124 修改内容如下可正常编译：
> 
> ```
> # Make sure we don't link against the system libstdc++ or libc++.
>     if (is_clang) {
> <<<<<<<
>       ldflags += [ "-nostdlib++" ]
> =======
>       if (target_os == "ios") {
>         ldflags += []
>       } else {
>         ldflags += [ "-nostdlib++" ]
>       }
> >>>>>>>
>     } else {
>       # Gcc has a built-in abs() definition with default visibility.
>       # If it was not disabled, it would conflict with libc++'s abs()
>       # with hidden visibility.
>       cflags += [ "-fno-builtin-abs" ]
> 
>       ldflags += [ "-nodefaultlibs" ]
> ```
> 
> GN参数关键设置：target_os="ios" 和 enable_dsyms=false PS：如果不设置enable_dsyms=false，编译时可能会出现 `warning: no debug symbols in executable (-arch x86_64)`
> 
> 正常编译，链接后的IOS arm64 二进制文件：
> 
> ```
> (base) mk@mkdeMacBook-Air src % bash ./build.sh
> Done. Made 456 targets from 145 files in 1210ms
> ninja: Entering directory `out/Release'
> [3162/3162] LINK ./naive
> 
> (base) mk@mkdeMacBook-Air src % file ./out/Release/naive 
> ./out/Release/naive: Mach-O 64-bit executable arm64
> ```
> 
> Chromium 关于IOS编译参考：https://chromium.googlesource.com/chromium/src/+/main/docs/ios/build_instructions.md

编译成 static_library 成功后，加入IOS工程，好多找不到符号，有遇到这个问题吗？

**Comment by klzgrad** [comment]
没有，我没有去试过ios编译

**Comment by arror** [comment]
> > 我找到原因了，似乎是 在编译 IOS时，chromium自动添加上了 -nostdlib++ 参数。
> > 如果我去掉了参数，则正常Link链接 （这个我在测试时自己指定的Link参数）：
> > ```
> > ../../third_party/llvm-build/Release+Asserts/bin/clang++ -fuse-ld=lld -Wl,--icf=all -Wl,--color-diagnostics -target arm64-apple-ios14.0 -no-canonical-prefixes -Wl,-dead_strip -Wl,-no_data_in_code_info -Wl,-no_function_starts -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS15.2.sdk -Wl,-ObjC -Wl,-rpath,@executable_path/Frameworks -L/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS15.2.sdk/usr/lib/swift -L/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/swift/iphoneos -o ./naive @./naive.rsp
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 引起原因是，第124行：https://github.com/klzgrad/naiveproxy/blob/master/src/build/config/c%2B%2B/BUILD.gn#L124 修改内容如下可正常编译：
> > ```
> > # Make sure we don't link against the system libstdc++ or libc++.
> >     if (is_clang) {
> > <<<<<<<
> >       ldflags += [ "-nostdlib++" ]
> > =======
> >       if (target_os == "ios") {
> >         ldflags += []
> >       } else {
> >         ldflags += [ "-nostdlib++" ]
> >       }
> > >>>>>>>
> >     } else {
> >       # Gcc has a built-in abs() definition with default visibility.
> >       # If it was not disabled, it would conflict with libc++'s abs()
> >       # with hidden visibility.
> >       cflags += [ "-fno-builtin-abs" ]
> > 
> >       ldflags += [ "-nodefaultlibs" ]
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > GN参数关键设置：target_os="ios" 和 enable_dsyms=false PS：如果不设置enable_dsyms=false，编译时可能会出现 `warning: no debug symbols in executable (-arch x86_64)`
> > 正常编译，链接后的IOS arm64 二进制文件：
> > ```
> > (base) mk@mkdeMacBook-Air src % bash ./build.sh
> > Done. Made 456 targets from 145 files in 1210ms
> > ninja: Entering directory `out/Release'
> > [3162/3162] LINK ./naive
> > 
> > (base) mk@mkdeMacBook-Air src % file ./out/Release/naive 
> > ./out/Release/naive: Mach-O 64-bit executable arm64
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Chromium 关于IOS编译参考：https://chromium.googlesource.com/chromium/src/+/main/docs/ios/build_instructions.md
> 
> 编译成 static_library 成功后，加入IOS工程，好多找不到符号，有遇到这个问题吗？

请问您是如何编译为 static_library 的呢？期待您的回复。
