### ISSUE TITLE
FireFox访问google报PR_END_OF_FILE_ERROR

### ISSUE THREAD

**Issue by SnowyYANG** [klzgrad/naiveproxy#258]
服务器和客户端应该是配好了的，具体配置下面有。

Firfox浏览器 ：
能上pixiv，用email登录人机验证刷不出来，用twitter登录通过，图片正常显示。
能上GitHub、twitter，能登陆，但是用户头像、twitter图片刷不出来。
Google、wikipedia、YouTube不能上，报PR_END_OF_FILE_ERROR。

非浏览器：
试了下设置系统代理，完全不能用，客户端一直ERR_SOCKS_CONNECTION_FAILED。
Git clone 正常。

我域名在CloudFlare，我已经关掉了CloudFlare的中转代理，并且暂停了CloudFlare，查了域名解析也是直接解析到VPS的。
不知道是不是CloudFlare的问题。

Caddyfile:
```
:443, 域名
tls cert.pem key.pem
route {
  forward_proxy {
    basic_auth 用户名 密码
    hide_ip
    hide_via
    probe_resistance
  }
  file_server { root /var/www/html }
}
```
config.json:
```
{
  "listen": "socks://127.0.0.1:1080",
  "proxy": "https://用户名:密码@域名",
  "log": ""
}
```

**Comment by klzgrad** [comment]
我觉得跟Cloudflare有关，跟naiveproxy无关。ERR_SOCKS_CONNECTION_FAILED就是代理连接失败。如果想细看可以用log-net-log等调试选项。

**Comment by SnowyYANG** [comment]
在CloudFlare以外重新注册了域名，重新配置了服务器和客户端，GitHub可以显示头像了，但是Google和Wikipedia仍然PR_END_OF_FILE_ERROR。

**Comment by SnowyYANG** [comment]
加上了
```
{
  servers {
    protocol {
      experimental_http3
    }
  }
}
```

可以访问Google和Wikipedia了，打扰。

**Comment by SnowyYANG** [comment]
呜呜呜，我什么设置都没改，现在又不行了。Google、YouTube、Wikipedia又报PR_END_OF_FILE_ERROR。这次没用CloudFlare。

**Comment by chinant** [comment]
> 

你的问题解决了嘛? 我这边也是用firefox出现同样问题,用chrome和curl都能正常访问
