### ISSUE TITLE
run naive as shared native lib on android

### ISSUE THREAD

**Issue by Nyxil** [klzgrad/naiveproxy#265]
I'm trying to build naive as shared native lib for android and run it with JNI on android.
I added a JNI method to naive_proxy_bin.cc to call the main method and successfully compiled the project and got binary, the problem is that i cant mark this class (or my own) as shared_library in BUILD.md file, the compile process just normally ends without any error and no binary output (don't know why)

this is my test JNI method inside naive_proxy_bin.cc, compiles without any issue
![1](https://user-images.githubusercontent.com/100045060/154816329-0812398a-1c10-40a3-8a2a-dc6da3d7f967.png)

this is the android log when i do the System.loadLibrary("naive");
![2](https://user-images.githubusercontent.com/100045060/154816345-a62ae048-8962-4cca-94f0-3ddbe6589aad.png)

obviously i cant call the JNI methods because it isnt marked as shared lib method at compile time
![3](https://user-images.githubusercontent.com/100045060/154816371-327160f3-69de-4aa5-8baf-d0a59168b30d.png)

can you give me hint to build it as shared lib including the JNI method ?

**Comment by klzgrad** [comment]
https://source.chromium.org/chromium/chromium/src/+/main:mojo/core/BUILD.gn;l=204?q=%5C%22shared_library%20-file:third_party&ss=chromium%2Fchromium%2Fsrc&start=1
