### ISSUE TITLE
Haproxy配置支持QUIC吗？

### ISSUE THREAD

**Issue by emmaki** [klzgrad/naiveproxy#266]
Haproxy 2.5版本似乎支持配置QUIC，请问能否用于作者的版本？能否测试下？我不太懂haproxy配置。https://www.haproxy.com/blog/announcing-haproxy-2-5/

**Comment by klzgrad** [comment]
要么行，要么不行。如果不行也不会有什么改正的办法，因为这里涉及的问题都很复杂。

这个当然是谁用谁测试。

**Comment by emmaki** [comment]
> 要么行，要么不行。如果不行也不会有什么改正的办法，因为这里涉及的问题都很复杂。
> 
> 这个当然是谁用谁测试。

似乎之前naive可用指定quic版本？现在没有了？

**Comment by emmaki** [comment]
> 要么行，要么不行。如果不行也不会有什么改正的办法，因为这里涉及的问题都很复杂。
> 
> 这个当然是谁用谁测试。

还有决定quic能否正常使用条件是？ 似乎有些服务器上可以，有些不可以，这是什么原因造成的？ 是不是linux需要额外的设置？

**Comment by klzgrad** [comment]
这个我不知道，QUIC很复杂，如果不可以，原因都很难查证。
