### ISSUE TITLE
Cann't run arm version on android

### ISSUE THREAD

**Issue by koolwiki** [klzgrad/naiveproxy#27]
I download the arm version of naive. Copy it into the home folder of termux (terminal app of android). Get some errors as follows when I excute naive.

$ ./naive --h
bash: ./naive: Permission denied
$ chmod 755 naive
$ ./naive --h
bash: ./naive: No such file or directory
$ file naive
naive: ELF 32-bit LSB shared object, ARM, EABI5 version 1 (SYSV), dynamically linked, interpreter /lib/ld-linux-armhf.so.3, for GNU/Linux 3.2.0, BuildID[sha1]=3bca406d6b3aee188485dabb1427130677470768, not stripped
$ ldd naive
libdl.so.2
libpthread.so.0
librt.so.1
libnss3.so
libnssutil3.so
libnspr4.so
libm.so.6
libgcc_s.so.1
libc.so.6
ld-linux-armhf.so.3

**Comment by koolwiki** [comment]
Some one says static build should be work.

**Comment by klzgrad** [comment]
https://wiki.termux.com/wiki/Differences_from_Linux#Termux_uses_Bionic_libc

Chrome does have an Android build. I just didn't bother with it.

**Comment by koolwiki** [comment]
> https://wiki.termux.com/wiki/Differences_from_Linux#Termux_uses_Bionic_libc
> 
> Chrome does have an Android build. I just didn't bother with it.

I tried per this document, but failed again. Could you please build an Android one? That would be awesome.

**Comment by pomhg** [comment]
> > https://wiki.termux.com/wiki/Differences_from_Linux#Termux_uses_Bionic_libc
> > Chrome does have an Android build. I just didn't bother with it.
> 
> I tried per this document, but failed again. Could you please build an Android one? That would be awesome.

Use naive under linux distribution chroot env, it
 works well, such as [](https://github.com/Neo-Oli/termux-ubuntu)

**Comment by koolwiki** [comment]
> > > https://wiki.termux.com/wiki/Differences_from_Linux#Termux_uses_Bionic_libc
> > > Chrome does have an Android build. I just didn't bother with it.
> > 
> > 
> > I tried per this document, but failed again. Could you please build an Android one? That would be awesome.
> 
> Use naive in other linux distribution chroot env, it
> works well. e.g. Termux-Ubuntu.

Could you please tell me what app I should use? Thanks.

**Comment by koolwiki** [comment]
@pomhg Thank you, it works with termux-debian now.

**Comment by klzgrad** [comment]
> Could you please build an Android one?

It's possible, as I mentioned earlier, that Chrome does support building binaries compatible with Android. But it's not very useful to provide a standalone binary without packaging it in a proper apk. I'm not ready to do that yet.
