### ISSUE TITLE
[Feature Request] To add wss mode onto https and quic mode

### ISSUE THREAD

**Issue by diyism** [klzgrad/naiveproxy#271]
I've tested the quic mode and https mode of naiveproxy, 
/usr/bin/naive --listen=socks://127.0.0.1:8085 --proxy=**quic**://[naive username]:[naive password]@[my vps domain]
/usr/bin/naive --listen=socks://127.0.0.1:8085 --proxy=**https**://[naive username]:[naive password]@[my vps domain]
Both of them work very well.

But I want to hide my VPS ip with my home IP, so I try to reverse proxy through cloudflare,
/usr/bin/naive --listen=socks://127.0.0.1:8085 --proxy=**https**://[naive username]:[naive password]@[my vps domain] --host-resolver-rules="MAP [my vps domain] [fastest cloudflare IP]"
It seems it won't work,  I can see "HTTP CONNECT" in the log output.

I understand the cloudflare doesn't pass throught HTTP CONNECT, but it indeed pass through websocket traffic(by enabling it in the Network setting on cloudflare).

Is there any way to add websocket support? We need the 3rd protocol wss (add to quic, https):
/usr/bin/naive --listen=socks://127.0.0.1:8085 --proxy=**wss**://[naive username]:[naive password]@[my vps domain]

**Comment by openips** [comment]
wss was used too normal and too easy to be checked by gfw

**Comment by diyism** [comment]
> wss was used too normal and too easy to be checked by gfw

The chrome and websites use wss very often, so I think it's normal traffic, it's not so distinguishable

**Comment by klzgrad** [comment]
Websocket does not have traffic multiplexing and thus is prone to website fingerprinting and traffic classification, which is the first requirement of this project.
