### ISSUE TITLE
naiveproxy并不会改变tls握手指纹对吧

### ISSUE THREAD

**Issue by yuzd** [klzgrad/naiveproxy#274]
我测试了下
![image](https://dimg04.c-ctrip.com/images/0v55m120009e2ir3t5E1C.png)

发现tls指纹并没有变成chrome的指纹

大佬，tls的握手指纹通过proxy是无法改的对吧。

**Comment by klzgrad** [comment]
测试方法不对。自己想一下

**Comment by yuzd** [comment]
@klzgrad 能否给个keyword 不多就要一个

**Comment by onegithuber** [comment]
有测试成功吗
