### ISSUE TITLE
naiveproxy基于TLS SNI的中转

### ISSUE THREAD

**Issue by Kaze1027** [klzgrad/naiveproxy#275]
我有两台服务器，一台A是GIA线路，质量很好，另一台B是绿云的DC2，电信线路不行但是可以解锁流媒体，我现在两台上面都跑了caddy+forward的naiveproxy，我想请教一下如何在A主机上通过访问特定的SNI来转发流量到B，实现中转。比如A主机上设定a.example.com和b.example.com，B主机上
是braw.example.com，现在通过a.example.com和braw.example.com的443都可以使用naiveproxy协议上网，但是如何实现特定用户（电信）访问b.example.com时A服务器通过TLS SNI功能触发handler的upstream将流量转发到braw.example.com再通过naiveproxy上网，这个过程中会有两次证书认证就会报错，请大佬指点指点。

**Comment by klzgrad** [comment]
我觉得Caddy理应有这个功能，根据SNI控制反向代理上游。但是要用json配置，里面比较复杂 https://caddyserver.com/docs/modules/http.handlers.subroute 请自行研究

**Comment by Kaze1027** [comment]
好的，谢谢大佬指点，我去研究一下，自己对caddy不太熟悉，我慢慢看，多谢指点。

**Comment by Kaze1027** [comment]
您好，我去看过了，但是好像是error路由吗，没看到反代相关内容，是不是意味着这个是使用subroute的error路由来切换，但是我记得caddy的SNI需要使用level 4模块，I4模块里面好像不能用这个
