### ISSUE TITLE
可选客户端提示

### ISSUE THREAD

**Issue by bolucat** [klzgrad/naiveproxy#276]
v2rayN 在最新的版本 [5.16](https://github.com/2dust/v2rayN/releases/tag/5.16) 中添加了 Naiveproxy 的自定义配置文件支持，是否可以考虑在 Readme 中添加 v2rayN 以提示使用者？谢谢

https://github.com/klzgrad/naiveproxy/blob/c647d3d363a117406822bbe0e677218071a6bf7c/README.md?plain=1#L24

**Comment by klzgrad** [comment]
https://github.com/klzgrad/naiveproxy/issues/158
