### ISSUE TITLE
[Idea] Integrate naiveproxy-client and caddy-forward into "go-ipfs p2p forward"

### ISSUE THREAD

**Issue by diyism** [klzgrad/naiveproxy#277]
"ipfs p2p forward" works in go-ipfs v0.12,
but its band width is only 0.5MB/s from Shanghai to South Korea,
while the naiveproxy's band width is 5MB/s for same IPs from Shanghai to South Korea.
(https://github.com/libp2p/go-libp2p/issues/324#issuecomment-1073456410)

"ipfs p2p forward" is very convinient, and "naiveproxy" is very performancy,
so I have the idea to integrate naiveproxy-client and caddy-forward into "go-ipfs p2p forward",
is there any possiblity and reasonbility?

**Comment by klzgrad** [comment]
Naiveproxy provides a regular socks5 proxy. Easiest is to layer ipfs (I don't know its details) over socks5.

**Comment by diyism** [comment]
You're right, I'll try to wrap ipfs node into caddy/naiveproxy server (which listens on 443 udp/tcp): https://github.com/ipfs/go-ipfs/issues/6430
