### ISSUE TITLE
Print Request & Response Details

### ISSUE THREAD

**Issue by anthonyalayo** [klzgrad/naiveproxy#278]
Hey there,

Fantastic project! I think naive proxy is ahead of the game compared to other proxies for getting around TLS fingerprinting restrictions.

With that being said, the logging is a bit lacking. I'm hoping to see request/response headers, query params, and bodies. 
Would it be possible to add logging for this?

Thanks,
Anthony

**Comment by klzgrad** [comment]
There are options to either save NetLog (see chromium docs on how to use it) or save SSL key files and decrypt the traffic in wireshark. See USAGE.txt.
