### ISSUE TITLE
Add http proxy support

### ISSUE THREAD

**Issue by koolwiki** [klzgrad/naiveproxy#28]
After testing, I find out that naive only support socks5 proxy, but don't support http proxy in local. Could you please add http proxy support in local? Thank you.

**Comment by klzgrad** [comment]
What is the use case? Which application can only work with http proxy not socks5?

HTTP proxies are harder to implement correctly.

**Comment by koolwiki** [comment]
Because I found out that http proxy is better for firefox, but I don't know why. Privoxy can tranfer socks5 proxy to http proxy. This would be a solution.

**Comment by klzgrad** [comment]
> http proxy is better for firefox

How?

**Comment by klzgrad** [comment]
If there's a reason that http proxy is actually better for firefox I'll consider it.
