### ISSUE TITLE
如何通过 launchctl 使 naiveproxy 作为服务运行？

### ISSUE THREAD

**Issue by Johnshall** [klzgrad/naiveproxy#287]
RT，我尝试在 macOS Monterey 12.3.1 上以服务的形式运行naiveproxy，并利用launchctl进行管理，以下是我的plist文件
```
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
        <key>KeepAlive</key>
        <true/>
        <key>Label</key>
        <string>com.naive.naiveproxy</string>
        <key>Program</key>
        <string>/Applications/naiveproxy/naive -c /Applications/naiveproxy/config.json</string>
        <key>RunAtLoad</key>
        <true/>
</dict>
</plist>
```
我可以确定 ``/Applications/naiveproxy/naive -c /Applications/naiveproxy/config.json`` 可以正常运行，并且此文件通过检查 ``com.naive.naiveproxy: OK``

但是运行的时候会出现
``Load failed: 5: Input/output error. Try running `launchctl bootstrap` as root for richer errors.``

我不清楚这个问题是如何被产生的，但是它让我很困扰。烦请各位大佬多多指点，不吝赐教！

**Comment by klzgrad** [comment]
`Try running `launchctl bootstrap` as root for richer errors.`

这纯属MacOS问题，我无法回答

**Comment by Johnshall** [comment]
我不会操作 `launchctl bootstrap` ，所以不太清楚如何排除 launchctl 的错误；

这里先提供一个简单的方案：
1. 在 terminal 中用 screen 命令创建一个新 terminal；
2. 运行 naive；
3. 按住 control + A + D 分离终端
4. 放心的关闭 terminal

这样就可以放心的后台运行naive了，缺点是无法开机启动。之后如果有时间还是准备详细了解一下launchctl，并在此追踪进度。

**Comment by Johnshall** [comment]
已解决。

1. 创建 /Users/【用户名】/Library/LaunchAgents/com.klzgrad.naiveproxy.plist
2. 写入下面内容

```xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
    <key>KeepAlive</key>
    <true/>
    <key>Label</key>
    <string>com.klzgrad.naiveproxy</string>
    <key>ProgramArguments</key>
    <array>
        <string>/Applications/naive/naive【naive 可执行文件位置】</string>
        <string>-c</string>
        <string>/Applications/naive/config.json【naive 配置文件位置】</string>
    </array>
    <key>RunAtLoad</key>
    <true/>
</dict>
</plist>
```

4. 启动
```bash
launchctl load com.naive.proxy.plist
```

**Comment by wen-long** [comment]
> 已解决。
> 
> 1. 创建 /Users/【用户名】/Library/LaunchAgents/com.klzgrad.naiveproxy.plist
> 2. 写入下面内容
> 
> ```
> <?xml version="1.0" encoding="UTF-8"?>
> <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
> <plist version="1.0">
> <dict>
>     <key>KeepAlive</key>
>     <true/>
>     <key>Label</key>
>     <string>com.klzgrad.naiveproxy</string>
>     <key>ProgramArguments</key>
>     <array>
>         <string>/Applications/naive/naive【naive 可执行文件位置】</string>
>         <string>-c</string>
>         <string>/Applications/naive/config.json【naive 配置文件位置】</string>
>     </array>
>     <key>RunAtLoad</key>
>     <true/>
> </dict>
> </plist>
> ```
> 
> 3. 启动
> 
> ```shell
> launchctl load com.naive.proxy.plist
> ```

推荐 [LaunchControl](https://www.soma-zone.com/LaunchControl/)。 Mac 必备
