### ISSUE TITLE
Malware Detected?

### ISSUE THREAD

**Issue by AttorneyFan** [klzgrad/naiveproxy#29]
Scaned by Virustotal. Malware Detected?
![20191210170809](https://user-images.githubusercontent.com/588329/70515199-eb3a2e80-1b6f-11ea-9f6a-af1c5951622b.png)

**Comment by klzgrad** [comment]
https://github.com/PKISharp/win-acme/issues/28

Theres very little I can do about it. I did not build the exe personally. Appveyor built it with my recipe. Unless Appveyor is compromised or my within account is compromised, I'm going to trust the built binary. If you have trust issue you can build it yourself on Windows using the appveyor recipe.

**Comment by klzgrad** [comment]
There is nothing left in this issue.
