### ISSUE TITLE
Do not understand the question. User is responsible to set up their own Let's Encrypt cert rotation.

### ISSUE THREAD

**Issue by lls275** [klzgrad/naiveproxy#296]
Do not understand the question. User is responsible to set up their own Let's Encrypt cert rotation.

_Originally posted by @klzgrad in https://github.com/klzgrad/naiveproxy/issues/295#issuecomment-1159699250_

If haproxy can detect that if the certificate expires, it will refuse to connect with naive, which is the safest, otherwise it is quite dangerous like I have been connecting with expired certificate before.

**Comment by lls275** [comment]
haproxy seems to provide verification of certificate validity, https://www.haproxy.com/blog/ssl-client-certificate-management-at-application-level/, but I seem to have problems with the configuration

**Comment by lls275** [comment]
Or add a verification server certificate on naive, if the server certificate expires, it will not connect

**Comment by klzgrad** [comment]
It's not haproxys job to detect cert validity. And client cert is irrelevant here. Any regular https client would reject expired server cert. The problem is with the client.

> like I have been connecting with expired certificate before.

I don't think this happens. Naive client already verifies server cert.

**Comment by lls275** [comment]
> It's not haproxys job to detect cert validity. And client cert is irrelevant here. Any regular https client would reject expired server cert. The problem is with the client.
> 
> > like I have been connecting with expired certificate before.
> 
> I don't think this happens. Naive client already verifies server cert.


Then there may be a problem with the naive server authentication certificate logic. I tested it again today, running a certificate that has expired for 30 days on the server, connecting with naive, it seems that there is no error, and it runs normally
