### ISSUE TITLE
[Enhancement]Optional for custom SNI

### ISSUE THREAD

**Issue by wkksx** [klzgrad/naiveproxy#297]
Dear developer:
hello!
      In some application scenarios, the SNI sent by the client and the "hostname" are inconsistent, for example, in the case of the need for transit server proxy forwarding, the  "hostname" is the name of the transit server, but the SNI is still unchanged, can you add the optional option of custom SNI？
Best regards

**Comment by klzgrad** [comment]
Domain fronting? It will not be supported here.
