### ISSUE TITLE
同时开启socks和http服务

### ISSUE THREAD

**Issue by Fhokud** [klzgrad/naiveproxy#301]
如题，添加这个功能可以方便和诸多工具对接，
例如满足Windows系统代理（使用http）和非浏览器应用（使用socks）的同时使用

**Comment by Johnshall** [comment]
windows系统代理可以用
socks=127.0.0.1
来使用socks代理

**Comment by Fhokud** [comment]
> windows系统代理可以用 socks=127.0.0.1 来使用socks代理

但是浏览器并不会使用，（edge，chrome）

**Comment by klzgrad** [comment]
用privoxy把socks转成http
