### ISSUE TITLE
能否再完善下

### ISSUE THREAD

**Issue by nilxbit** [klzgrad/naiveproxy#305]
刚看到这个issue https://github.com/klzgrad/naiveproxy/issues/303   下来测试了一下

目前如果想同时支持ipv6和ipv4，需要开两个naive
./naive --listen=redir://0.0.0.0:1080
./naive --listen=redir://::1:1080
此时路由器本机ipv4和ipv6都能上网，但是局域网的设备无法ipv6科学上网

然后我又写成这样
./naive --listen=redir://:::1080
此时ipv6行了，但是ipv4又不行了

希望能再完善下，让./naive --listen=redir://:::1080可以同时监听所有ip

**Comment by klzgrad** [comment]
https://github.com/klzgrad/naiveproxy/releases/tag/v104.0.5112.79-4 是否解决问题？

**Comment by nilxbit** [comment]
可以了，现在都可以了

**Comment by kpzhao** [comment]
> 刚看到这个issue #303 下来测试了一下
> 
> 目前如果想同时支持ipv6和ipv4，需要开两个naive ./naive --listen=redir://0.0.0.0:1080 ./naive --listen=redir://::1:1080 此时路由器本机ipv4和ipv6都能上网，但是局域网的设备无法ipv6科学上网
> 
> 然后我又写成这样 ./naive --listen=redir://:::1080 此时ipv6行了，但是ipv4又不行了
> 
> 希望能再完善下，让./naive --listen=redir://:::1080可以同时监听所有ip

请问一下你的iptables是按照usage.txt里面设置的吗?我设置完浏览器访问谷歌和youtube显示无法建立安全连接
