### ISSUE TITLE
跑一段时间流量后会近乎终止流量传输

### ISSUE THREAD

**Issue by iceBear67** [klzgrad/naiveproxy#306]
latest naive with latest caddy fork(forwardproxy).

用一段时间后速度就会明显下降甚至到0b/s
间隔大约三十秒左右会恢复连接，不同的云服务商均有出现这个问题

过一会把具体情况发下来，不知道有没有人遇到过类似的情况

**Comment by wen-long** [comment]
经常遇到，习惯了手动重启。。

**Comment by iceBear67** [comment]
好像没法给出更多信息.....

**Comment by openips** [comment]
断流+1

**Comment by klzgrad** [comment]
没有碰到过，如果有，可能是长连接收到ISP的影响，NAT端口变化之类的

**Comment by openips** [comment]
> 没有碰到过，如果有，可能是长连接收到ISP的影响，NAT端口变化之类的

wan口是公网IP

**Comment by openips** [comment]
@klzgrad  给个思路看看怎么排查 这个问题挺恶心的 每次更新手机APP 流量稍微大一点就出这样的问题

**Comment by klzgrad** [comment]
开一个ssh -o ServerAliveInterval=60然后挂机可以检查长连接是否会被卡住

**Comment by klzgrad** [comment]
间隔大约三十秒左右会恢复连接，这个性质是不一样的，如果短时间遇到很多丢包，TCP拥塞的确会卡住然后缓慢恢复

**Comment by iceBear67** [comment]
我下周放学测一下

**Comment by openips** [comment]
> 开一个ssh -o ServerAliveInterval=60然后挂机可以检查长连接是否会被卡住
试了一下 没有问题 一切正常

>间隔大约三十秒左右会恢复连接，这个性质是不一样的，如果短时间遇到很多丢包，TCP拥塞的确会卡住然后缓慢恢复
使用tcping 监控 一直没有丢包

```
36 responses, 36 ok, 0.00% failed
round-trip min/avg/max = 0.2/0.2/0.7 ms
```

**Comment by openips** [comment]
大概率gfw升级了

**Comment by openips** [comment]
关了吧 我把客户端降级到之前不断流的版本 还是断流了

**Comment by iceBear67** [comment]
会不会就是单纯针对长连接chromium tls的干扰?

**Comment by klzgrad** [comment]
长连接本身就容易受到干扰，如果网络质量不佳就是这样，不需要对长连接专门干扰，要干扰就是直接封ip了

**Comment by 5uy4n9** [comment]
差不多同时间段会偶尔遇到这个问题，最近几天变得更加频繁，在https协议无响应的时候换成quic，或者反过来还可以连接，今天开始变成偶尔会连整个IP都短暂（大约几十秒-1分钟）被封，同时一直连接着的ssh断开，icmp也ping不通

**Comment by openips** [comment]
gfw大发神威了 naive还能扛一阵

**Comment by oit63** [comment]
是偶尔有这个情况，改了进程优先级为实时fifo，看起来要好些。具体如何要再观察
