### ISSUE TITLE
Question: Is there any benefit if NaiveProxy work with the Shadow-TLS?

### ISSUE THREAD

**Issue by GWONGJYULEI** [klzgrad/naiveproxy#310]
Thanks for your great work for this project firstly!
As the subject. If is, could you please share some ideas about how to deploy the Shadow-TLS to work with NaiveProxy?
If not, could you please briefly explain for the reason?
Thanks!

**Comment by klzgrad** [comment]
There is none. ShadowTLS has its flaws, see https://github.com/net4people/bbs/issues/123#issuecomment-1242735733. It's ok to have more choices, but it is not technically necessary to combine them.
