### ISSUE TITLE
How do I chain two naive servers? (forward proxy)

### ISSUE THREAD

**Issue by NightMachinery** [klzgrad/naiveproxy#311]
I need to chain two naive proxy servers:

client -> first naive server -> second naive server -> free internet

How do I do this?

**Comment by klzgrad** [comment]
The second naive server is redundant. Deploy one naive server for the censor crossing path, and the other one with plain http proxy. Caddy forwardproxy has an upstream option that works for this.

**Comment by NightMachinery** [comment]
@klzgrad The problem is that both the client and the first server are in Iran.

**Comment by SaberDoTcodeR** [comment]
@klzgrad with the current network restrictions in Iran the only solution that could bypass is a two-proxy structure that @NightMachinery mentioned.

**Comment by klzgrad** [comment]
> with the current network restrictions in Iran the only solution that could bypass

Bypass what? I can only guess in blind this is some kind of double-censor network and offer suggestions that may or may not address the problem of yours.

It can work in chains. See https://github.com/klzgrad/naiveproxy/blob/master/tests/basic.py#L248, where three instances of naiveproxy are chained together.

Here what you may need is probably:

1. Locally: the first naiveproxy client, `--listen=socks://:1080 --proxy=https://first.relay.com`
2. At the first relay: Caddy forwardproxy with upstream option http://127.0.0.1:8080
3. At the first relay: naiveproxy `--listen=http://:8080 --proxy=https://second.relay.com` (This `--listen=http://` inbound protocol is a minimal implementation that only supports HTTP CONNECT requests)
4. At the second relay: Caddy forwardproxy without upstream option.

I hope this combination works in theory, but I haven't tested it.

**Comment by sae13** [comment]
> The second naive server is redundant. Deploy one naive server for the censor crossing path, and the other one with plain http proxy. Caddy forwardproxy has an upstream option that works for this.

can you make caddy example of first and second server please?

**Comment by klzgrad** [comment]
If you check https://github.com/klzgrad/forwardproxy#caddyfile-syntax-server-configuration you can find ways to use the `upstream` option.

**Comment by KaraRyougi** [comment]
Actually, you don’t need to do that - you can run the following iptables command on first server:

```
sudo iptables -t nat -A PREROUTING -p tcp -m tcp --dport 443 -j DNAT --to-destination <second server ip>
sudo iptables -t nat -A POSTROUTING -d <second server ip> -j MASQUERADE
```
(point your domain name DNS record to first server)

And then enable IPv4 forwarding by adding `net.ipv4.ip_forward=1` in `/etc/sysctl.conf` and run `sudo sysctl -p` to apply the configuration.
