### ISSUE TITLE
[Feature Request] piggyback SNI mode just like Cloak and GoQuiet

### ISSUE THREAD

**Issue by diyism** [klzgrad/naiveproxy#312]
It seems that the two projects of Cloak and GoQuiet implement "fake sni" very differently with other proxy projects.
There are two parameters in Cloak:
1.(client side)ServerName:   the domain you want to make your ISP or firewall think you are visiting.

2.(server side)RedirAddr:  the redirection address when the incoming traffic is not from a Cloak client. Ideally it should be set to a major website allowed by the censor (e.g. www.bing.com)

It's very simple to deploy without exposing my domain and its tls cert.
https://github.com/cbeuw/Cloak/issues/169

And if the GFW blocked the server (and my domain never exposed), we needn't to get a new domain, just need to get a new server IP and change the DNS A record of my domain.

Ref:  https://github.com/cbeuw/GoQuiet#how-it-works
the author mentioned tls session resumption.

**Comment by klzgrad** [comment]
This project tries to create a TLS parrot as authentic as possible. Faking SNI is not hard to detect because the faked certificates and domain names would not match the certificates and IP addresses from the actual sites. Faking it does create an extra dimension of obfuscation, which is in itself useful. But this project is meant as a kind of fallback solution, which will hopefully work when all other solutions fail, even at a higher cost. So cost reduction is less of a consideration here compared to completeness of TLS parroting.

**Comment by diyism** [comment]
Misunderstanding, I think there are 6 methods about SNI break-through here:
1. no-sni: revolter-firefox(https://github.com/revolter-firefox/revolter-firefox),  which get rid of sni information. Obviously, it's weak for break-through, and it's bad for CDN based websites;
2. bad-sni: SNI-Mask(https://github.com/macronut/SNI-Mask), which use invalid fake packets to make firewall ignore the SNI, it will be exposed  after too many connections.
3. fake-sni: LibertyTunnel fake sni mode(https://github-wiki-see.page/m/krlvm/LibertyTunnel/wiki/SNI-Modification), which modify the sni name with GFW-allowed domain name but replace the certificate with self-signed one, it will be exposed if the GFW check the certificate.
4. tunnel-sni: naiveproxy/v2ray/trojan-go, which use a valid sni and cert, but which will expose the user's domain name
5. cloak-sni: cloak plugin for openvpn(https://github.com/cbeuw/Cloak), which use a valid sni and cert, but without using the user's domain name, after successfull hankshake, Cloak use tls session resumption to inject the tls session to proxy network traffic, and if the GFW check the sni and cert, it's a valid sniproxy to redirect to the GFW-allowed website.(ref:  https://github.com/cbeuw/GoQuiet#how-it-works)

**Comment by diyism** [comment]
@tomac4t my fault, the Cloak is not a sniproxy, it just continue the valid tls session to the specified single domain name.(for example www.bing.com)

**Comment by klzgrad** [comment]
Exposing the user's domain name is the design goal, part of the parroting profile that makes the entire setup more authentic. It's not a feature to be able to manipulate SNI, it's a bug.
