### ISSUE TITLE
Padding capability undetected when Tinyproxy as forward proxy 

### ISSUE THREAD

**Issue by amd64v3** [klzgrad/naiveproxy#313]
I setup naiveproxy server following <a href="https://github.com/klzgrad/naiveproxy/wiki/HAProxy-Setup">HAProxy setup</a>, and all configs were the same with that, it can connect Internet normally, but when I checked the naive client output, found padding was undetected, then I change Tinyproxy to naiveproxy binary as forward proxy, it can detect padding, but Tinyproxy is more simpler and easier, can you check it? Here is Tinyproxy's log:

INFO      Sep 27 01:33:45 [6541]: Initializing tinyproxy ...
INFO      Sep 27 01:33:45 [6541]: Reloading config file
INFO      Sep 27 01:33:45 [6541]: Added address [127.0.0.1] to listen addresses.
INFO      Sep 27 01:33:45 [6541]: Disabling transmission of the "Via" header.
INFO      Sep 27 01:33:45 [6541]: listen_sock called with addr = '127.0.0.1'
INFO      Sep 27 01:33:45 [6541]: trying to listen on host[127.0.0.1], family[2], socktype[1], proto[6]
INFO      Sep 27 01:33:45 [6541]: listening on fd [0]
INFO      Sep 27 01:33:45 [6541]: Now running as group "tinyproxy".
INFO      Sep 27 01:33:45 [6541]: Now running as user "tinyproxy".
INFO      Sep 27 01:33:45 [6541]: Setting the various signals.
INFO      Sep 27 01:33:45 [6541]: Creating child number 1 of 10 ...
INFO      Sep 27 01:33:45 [6541]: Creating child number 2 of 10 ...
INFO      Sep 27 01:33:45 [6541]: Creating child number 3 of 10 ...
INFO      Sep 27 01:33:45 [6541]: Creating child number 4 of 10 ...
INFO      Sep 27 01:33:45 [6541]: Creating child number 5 of 10 ...
INFO      Sep 27 01:33:45 [6541]: Creating child number 6 of 10 ...
INFO      Sep 27 01:33:45 [6541]: Creating child number 7 of 10 ...
INFO      Sep 27 01:33:45 [6541]: Creating child number 8 of 10 ...
INFO      Sep 27 01:33:45 [6541]: Creating child number 9 of 10 ...
INFO      Sep 27 01:33:45 [6541]: Creating child number 10 of 10 ...
INFO      Sep 27 01:33:45 [6541]: Finished creating all children.
INFO      Sep 27 01:33:45 [6541]: Starting main loop. Accepting connections.
CONNECT   Sep 27 01:35:16 [6551]: Connect (file descriptor 6): localhost [127.0.0.1]
CONNECT   Sep 27 01:35:16 [6551]: Request (file descriptor 6): CONNECT google.com:80 HTTP/1.1
INFO      Sep 27 01:35:16 [6551]: No upstream proxy for google.com
INFO      Sep 27 01:35:16 [6551]: opensock: opening connection to google.com:80
INFO      Sep 27 01:35:16 [6551]: opensock: getaddrinfo returned for google.com:80
CONNECT   Sep 27 01:35:16 [6550]: Connect (file descriptor 6): localhost [127.0.0.1]
CONNECT   Sep 27 01:35:16 [6550]: Request (file descriptor 6): CONNECT google.com:80 HTTP/1.1
INFO      Sep 27 01:35:16 [6550]: No upstream proxy for google.com
INFO      Sep 27 01:35:16 [6550]: opensock: opening connection to google.com:80
INFO      Sep 27 01:35:16 [6550]: opensock: getaddrinfo returned for google.com:80
CONNECT   Sep 27 01:35:17 [6550]: Established connection to host "google.com" using file descriptor 7.
CONNECT   Sep 27 01:35:17 [6551]: Established connection to host "google.com" using file descriptor 7.
INFO      Sep 27 01:35:17 [6550]: Not sending client headers to remote machine
INFO      Sep 27 01:35:17 [6551]: Not sending client headers to remote machine
CONNECT   Sep 27 01:35:17 [6549]: Connect (file descriptor 6): localhost [127.0.0.1]
CONNECT   Sep 27 01:35:17 [6549]: Request (file descriptor 6): CONNECT www.google.com:443 HTTP/1.1
INFO      Sep 27 01:35:17 [6549]: No upstream proxy for www.google.com
INFO      Sep 27 01:35:17 [6549]: opensock: opening connection to www.google.com:443
INFO      Sep 27 01:35:17 [6549]: opensock: getaddrinfo returned for www.google.com:443
CONNECT   Sep 27 01:35:17 [6549]: Established connection to host "www.google.com" using file descriptor 7.
INFO      Sep 27 01:35:17 [6549]: Not sending client headers to remote machine
CONNECT   Sep 27 01:35:17 [6548]: Connect (file descriptor 6): localhost [127.0.0.1]
CONNECT   Sep 27 01:35:17 [6548]: Request (file descriptor 6): CONNECT www.google.com:443 HTTP/1.1
INFO      Sep 27 01:35:17 [6548]: No upstream proxy for www.google.com
INFO      Sep 27 01:35:17 [6548]: opensock: opening connection to www.google.com:443
INFO      Sep 27 01:35:17 [6548]: opensock: getaddrinfo returned for www.google.com:443
CONNECT   Sep 27 01:35:17 [6548]: Established connection to host "www.google.com" using file descriptor 7.
INFO      Sep 27 01:35:17 [6548]: Not sending client headers to remote machine
CONNECT   Sep 27 01:35:18 [6547]: Connect (file descriptor 6): localhost [127.0.0.1]
CONNECT   Sep 27 01:35:18 [6546]: Connect (file descriptor 6): localhost [127.0.0.1]
CONNECT   Sep 27 01:35:18 [6547]: Request (file descriptor 6): CONNECT www.gstatic.com:443 HTTP/1.1
CONNECT   Sep 27 01:35:18 [6546]: Request (file descriptor 6): CONNECT www.gstatic.com:443 HTTP/1.1
INFO      Sep 27 01:35:18 [6547]: No upstream proxy for www.gstatic.com
INFO      Sep 27 01:35:18 [6546]: No upstream proxy for www.gstatic.com
INFO      Sep 27 01:35:18 [6546]: opensock: opening connection to www.gstatic.com:443
INFO      Sep 27 01:35:18 [6547]: opensock: opening connection to www.gstatic.com:443
INFO      Sep 27 01:35:18 [6547]: opensock: getaddrinfo returned for www.gstatic.com:443
INFO      Sep 27 01:35:18 [6546]: opensock: getaddrinfo returned for www.gstatic.com:443
CONNECT   Sep 27 01:35:18 [6546]: Established connection to host "www.gstatic.com" using file descriptor 7.
CONNECT   Sep 27 01:35:18 [6547]: Established connection to host "www.gstatic.com" using file descriptor 7.
INFO      Sep 27 01:35:18 [6546]: Not sending client headers to remote machine
INFO      Sep 27 01:35:18 [6547]: Not sending client headers to remote machine
ERROR     Sep 27 01:35:19 [6547]: read_buffer: read() failed on fd 6: Connection reset by peer
INFO      Sep 27 01:35:19 [6547]: Closed connection between local client (fd:6) and remote client (fd:7)
CONNECT   Sep 27 01:35:19 [6547]: Connect (file descriptor 6): localhost [127.0.0.1]
CONNECT   Sep 27 01:35:19 [6547]: Request (file descriptor 6): CONNECT content-autofill.googleapis.com:443 HTTP/1.1
INFO      Sep 27 01:35:19 [6547]: No upstream proxy for content-autofill.googleapis.com
INFO      Sep 27 01:35:19 [6547]: opensock: opening connection to content-autofill.googleapis.com:443
INFO      Sep 27 01:35:19 [6547]: opensock: getaddrinfo returned for content-autofill.googleapis.com:443
CONNECT   Sep 27 01:35:19 [6547]: Established connection to host "content-autofill.googleapis.com" using file descriptor 7.
INFO      Sep 27 01:35:19 [6547]: Not sending client headers to remote machine
CONNECT   Sep 27 01:35:19 [6545]: Connect (file descriptor 6): localhost [127.0.0.1]
CONNECT   Sep 27 01:35:19 [6545]: Request (file descriptor 6): CONNECT apis.google.com:443 HTTP/1.1
INFO      Sep 27 01:35:19 [6545]: No upstream proxy for apis.google.com
INFO      Sep 27 01:35:19 [6545]: opensock: opening connection to apis.google.com:443
INFO      Sep 27 01:35:19 [6545]: opensock: getaddrinfo returned for apis.google.com:443
CONNECT   Sep 27 01:35:19 [6545]: Established connection to host "apis.google.com" using file descriptor 7.
INFO      Sep 27 01:35:19 [6545]: Not sending client headers to remote machine
NOTICE    Sep 27 01:35:20 [6541]: Waiting servers (3) is less than MinSpareServers (5). Creating new child.
NOTICE    Sep 27 01:35:25 [6541]: Waiting servers (4) is less than MinSpareServers (5). Creating new child.
ERROR     Sep 27 01:35:25 [6550]: read_buffer: read() failed on fd 6: Connection reset by peer
ERROR     Sep 27 01:35:25 [6548]: read_buffer: read() failed on fd 6: Connection reset by peer
ERROR     Sep 27 01:35:25 [6549]: read_buffer: read() failed on fd 6: Connection reset by peer
ERROR     Sep 27 01:35:25 [6546]: read_buffer: read() failed on fd 6: Connection reset by peer
ERROR     Sep 27 01:35:25 [6545]: read_buffer: read() failed on fd 6: Connection reset by peer
ERROR     Sep 27 01:35:25 [6547]: read_buffer: read() failed on fd 6: Connection reset by peer
INFO      Sep 27 01:35:25 [6547]: Closed connection between local client (fd:6) and remote client (fd:7)
INFO      Sep 27 01:35:25 [6548]: Closed connection between local client (fd:6) and remote client (fd:7)
INFO      Sep 27 01:35:25 [6546]: Closed connection between local client (fd:6) and remote client (fd:7)
INFO      Sep 27 01:35:25 [6549]: Closed connection between local client (fd:6) and remote client (fd:7)
INFO      Sep 27 01:35:25 [6545]: Closed connection between local client (fd:6) and remote client (fd:7)
INFO      Sep 27 01:35:25 [6550]: Closed connection between local client (fd:6) and remote client (fd:7)

Tinyproxy version 1.10.0, Haproxy version  2.2.9,  Running on Debian 11.5

**Comment by klzgrad** [comment]
HAProxy + tinyproxy is more of a poor man's tutorial for people who don't want to install Caddy to set up a realistic HTTP/2 website without appearing as a dedicate proxy server. Tinyproxy is not capable of the padding protocol, just as the text says. The padding is important to reduce traffic analysis effectiveness from packet lengths, so it's recommended to use it.

**Comment by amd64v3** [comment]
Got it, by the way ,there are more 2 questions: 1. If I use naiveproxy binary as forward proxy, should I update it  when naiveproxy update?  2. Does Haproxy support naiveproxy QUIC mode?

**Comment by klzgrad** [comment]
naiveproxy binary behind a reverse proxy frontend only works to unpad the payload. The padding protocol is unlikely to ever change, so it doesn't need update.

Does HAProxy support QUIC, is the question to ask. If it does, naiveproxy may work with it, or not, depending on QUIC interoperatability.
