### ISSUE TITLE
Will Encrypted client hello be supported at both the client and server side?

### ISSUE THREAD

**Issue by showgood163** [klzgrad/naiveproxy#314]
ECH is supported by chromium since v105.

I don't know whether forward proxy of caddy supports ECH.

**Comment by ArcCal** [comment]
借宝地请教一个问题 naiveproxy mac版怎么使用呢

**Comment by klzgrad** [comment]
Does Chromium "support" ECH? https://bugs.chromium.org/p/chromium/issues/detail?id=1091403, https://chromeenterprise.google/intl/en_ca/policies/#EncryptedClientHelloEnabled - there is "the default rollout process".
Does Caddy support ECH? https://github.com/caddyserver/caddy/issues/4221 Not planned yet.

**Comment by klzgrad** [comment]
@ArcCal same way with any other platform

**Comment by showgood163** [comment]
@klzgrad 

So will there be an option for naiveproxy to enable/disable ECH on the client side?
How do I test whether the state of ECH on the server side?

**Comment by klzgrad** [comment]
The "option" is this https://chromeenterprise.google/intl/en_ca/policies/#EncryptedClientHelloEnabled. See also https://github.com/klzgrad/naiveproxy/wiki/Performance-Tuning#chromium with another policy setting.

The server is just Caddy. You should follow Caddy's dev news.

**Comment by showgood163** [comment]
Thanks for the clarification.

I enabled ECH inside the chromium on windows, llinux and android.
With naiveproxy as the proxy, I opened https://tls-ech.dev/ to test whether ECH is enabled.
I got positive results on android. However, on both windows and linux I got negative results.
When no proxy is enabled, I got positive results on both windows and linux.
What could go wrong here?

**Comment by showgood163** [comment]
@tomac4t 

根据https://github.com/net4people/bbs/issues/128，GFW开始审查TLS ClientHello包，并根据审查结果决定对策
这可能意味着naiveproxy client和naiveproxy server中间需要有ECH来阻止审查

至于caddyserver，确实不是naiveproxy能处理的

**Comment by showgood163** [comment]
@tomac4t 

我是希望隧道外有ECH支持的，原因是我连代理的域名都不想让墙看见。
不过你说的关于ECH的现状部分确实有道理，可能我现在提ECH太早了。

**Comment by klzgrad** [comment]
Not planned at this time.
