### ISSUE TITLE
Strip the binary?

### ISSUE THREAD

**Issue by tomac4t** [klzgrad/naiveproxy#32]
I see the binary on the releases is not stripped. Should it add `strip` command on `.travis.yml`? It will save about 2MB space.

**Comment by klzgrad** [comment]
I'm not sure 2MB matters, when the stripped size is still 4MB. The stripped 2MB gets you a minimal debug ability of stack backtrace when the program crashes, which I think is somewhat useful.

**Comment by tomac4t** [comment]
Well, Perhaps it's matter to Openwrt users (I'm not)... But they should have the ability to strip the binary if they need. I will close this issue:-)
