### ISSUE TITLE
443端口被屏蔽，可以添加个非443端口的caddy配置吗？

### ISSUE THREAD

**Issue by Git-Apt** [klzgrad/naiveproxy#321]
我在中文网上找来十几次的非443配置文件全部失败，我想使用非443端口但是不懂caddy的写法，参照您的配置改了几个小时都未能成功，很痛苦，看到的大神可以将配置发出来参考下吗？帮帮我们这种小白吧，真害怕和全世界失去联系。 reverse_proxy 转发网页这种和服务器架个web有什么安全上的区别吗？谢谢啦，在线不关闭网页等待！

**Comment by klzgrad** [comment]
与naiveproxy无关
