### ISSUE TITLE
where i can find binary caddy with forward proxy

### ISSUE THREAD

**Issue by sae13** [klzgrad/naiveproxy#322]
hey hi 
where i can find binary caddy with forward proxy
my vms are in iran and google sanction does not let us download from go repositories

**Comment by klzgrad** [comment]
You can build locally and upload the binary to your VM.

**Comment by KaraRyougi** [comment]
Does NaiveProxy work with cellular data in Iran for you? It seems that TLS-based solutions only work in residential ISPs, not mobile networks.

**Comment by klzgrad** [comment]
https://github.com/klzgrad/forwardproxy/releases/tag/caddy2-naive-20221006
