### ISSUE TITLE
在一些设备上GLIBC库存在问题

### ISSUE THREAD

**Issue by qingmuhy** [klzgrad/naiveproxy#324]
/usr/bin/naive: /lib/aarch64-linux-gnu/libm.so.6: version `GLIBC_2.29' not found (required by /usr/bin/naive)

运行可执行文件会出现如上提示，应该是因为设备的GLIBC库比较老的原因，但因为设备是一些NAS厂商定制的系统，不是很方便升级GLIBC库（互联网上有很多升级后出现问题的情况，因为设备数据比较多，如果重置会比较麻烦，因此不是很敢手动升级。）

`[~] # ldd --version
ldd (GNU libc) 2.23
Copyright (C) 2016 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
Written by Roland McGrath and Ulrich Drepper.
`

希望能在编译的时候考虑一下老库的兼容性。

如果不方便或者麻烦就算了，不管你是否有解决这个问题的打算，都谢谢你看到了这里。：）

**Comment by klzgrad** [comment]
什么发行版

**Comment by qingmuhy** [comment]
Linux QNAP 4.2.8 #1 SMP Sat Oct 1 01:50:16 CST 2022 aarch64 GNU/Linux

**Comment by qingmuhy** [comment]
主要是白NAS，系统都是厂家定制好的，要是Linux系统我就自己升级了。

**Comment by qingmuhy** [comment]
我这么做的目的是为了获得更好的兼容性，在国内外互联的地点使用高伪装性的naiveproxy协议，在国内到终端这一段使用兼容性更好的协议以使用clash等客户端。

因为穷没有国内服务器，最经济实惠的方法就是使用家宽了，但是因为没购入软路由，且硬路由性能较差，因此我倾向于使用docker部署在nas这样性能相对较强的设备上。

**Comment by klzgrad** [comment]
```
$ objdump -T naiveproxy-v106.0.5249.91-1-linux-arm64/naive  | grep GLIBC_2.29
0000000000000000      DF *UND*	0000000000000000 (GLIBC_2.29) pow
0000000000000000      DF *UND*	0000000000000000 (GLIBC_2.29) log
0000000000000000      DF *UND*	0000000000000000 (GLIBC_2.29) exp
```

**Comment by klzgrad** [comment]
https://bugs.chromium.org/p/chromium/issues/detail?id=1309965#c5

**Comment by qingmuhy** [comment]
还想请教一个问题，是否可以在一个客户端配置文件里写入多个代理。比如

{
  "listen": "socks://127.0.0.1:1080",
  "proxy": "https://user:pass@example1.com"
},
{
  "listen": "socks://127.0.0.1:1081",
  "proxy": "https://user:pass@example2.com"
}

**Comment by emmaki** [comment]
> 

完全没有这必要，如果想再开一个则重新开启一个naive进程加载新的socks1081的端口

**Comment by emmaki** [comment]
> 还想请教一个问题，是否可以在一个客户端配置文件里写入多个代理。比如
> 
> { "listen": "socks://127.0.0.1:1080", "proxy": "https://user:pass@example1.com" }, { "listen": "socks://127.0.0.1:1081", "proxy": "https://user:pass@example2.com" }

完全没有这必要，如果想再开一个则重新开启一个naive进程加载新的socks1081的端口

**Comment by emmaki** [comment]
> 我这么做的目的是为了获得更好的兼容性，在国内外互联的地点使用高伪装性的naiveproxy协议，在国内到终端这一段使用兼容性更好的协议以使用clash等客户端。
> 
> 因为穷没有国内服务器，最经济实惠的方法就是使用家宽了，但是因为没购入软路由，且硬路由性能较差，因此我倾向于使用docker部署在nas这样性能相对较强的设备上。

可以在电脑上运行，没必要在nas上运行

**Comment by emmaki** [comment]
> 我这么做的目的是为了获得更好的兼容性，在国内外互联的地点使用高伪装性的naiveproxy协议，在国内到终端这一段使用兼容性更好的协议以使用clash等客户端。
> 
> 因为穷没有国内服务器，最经济实惠的方法就是使用家宽了，但是因为没购入软路由，且硬路由性能较差，因此我倾向于使用docker部署在nas这样性能相对较强的设备上。

弄一台老旧的单口电脑做软路由，完全可行的。如果你家有老旧废弃的笔记本电脑或者其他设施也是不错的选择

**Comment by klzgrad** [comment]
https://github.com/klzgrad/naiveproxy/releases/tag/v106.0.5249.91-2

**Comment by qingmuhy** [comment]
👌

**Comment by klzgrad** [comment]
Fixed.
