### ISSUE TITLE
Q

### ISSUE THREAD

**Issue by emmaki** [klzgrad/naiveproxy#327]
q

**Comment by emmaki** [comment]
可参考https://www.haproxy.com/blog/announcing-haproxy-2-6/，甚至官方提供的demo，https://github.com/haproxytechblog/haproxy-2.6-http3。目前与naive连接解密tls流量是正常的

**Comment by klzgrad** [comment]
用wireshark看一下haproxy与tinyproxy之间是怎么交互的

**Comment by emmaki** [comment]
您能否重现下？
