### ISSUE TITLE
应该如何为本地监听添加验证的

### ISSUE THREAD

**Issue by op69qs** [klzgrad/naiveproxy#33]
本地监听端口(HTTP or socks)添加简单的帐密验证，方便手机使用，比如外网访问家宽部署的端口

还一个是 当有请求进来的时候报错，运行环境是在openwrt arm8的路由上
`NSS_VersionCheck("3.26") failed. NSS >= 3.26 is required. Please upgrade to the latest NSS, and if you still get this error, contact your distribution maintainer.`

**Comment by klzgrad** [comment]
现在还没有这个功能，计划是直接做一个app出来。家庭宽带难道不会有上行带宽小的问题吗？放到云主机上会被查。

现在还没有给openwrt arm编译版本，openwrt跟ubuntu的libc不一样。这个错误说明你安装libnss了吗？

**Comment by op69qs** [comment]
家宽那上传够我一个人用了，libnss3是有的 不过版本好像不够，我是想打包编译的时候能不能把相关库都一并加进去 不然这些 arm mtk平台对应的库安装编译还是比较麻烦

**Comment by klzgrad** [comment]
根据这个页面 https://github.com/openwrt/packages/commits/master/libs/nss/Makefile Openwrt从来没有过低于3.26的libnss，所以问你装的是什么libnss

**Comment by op69qs** [comment]
很早的版本，还一个就是群晖arm版本
不知道是不是
`Version needs section '.gnu.version_r' contains 2 entries:
 Addr: 0x0000000000010720  Offset: 0x010720  Link: 3 (.dynstr)
  000000: Version: 1  File: libnssutil3.so  Cnt: 9
  0x0010:   Name: NSSUTIL_3.12.5  Flags: none  Version: 58
  0x0020:   Name: NSSUTIL_3.21  Flags: none  Version: 57
  0x0030:   Name: NSSUTIL_3.12.3  Flags: none  Version: 56
  0x0040:   Name: NSSUTIL_3.13  Flags: none  Version: 55
  0x0050:   Name: NSSUTIL_3.17.1  Flags: none  Version: 54
  0x0060:   Name: NSSUTIL_3.31  Flags: none  Version: 53
  0x0070:   Name: NSSUTIL_3.24  Flags: none  Version: 52
  0x0080:   Name: NSSUTIL_3.14  Flags: none  Version: 51
  0x0090:   Name: NSSUTIL_3.12  Flags: none  Version: 50
  0x00a0: Version: 1  File: libc.so.6  Cnt: 1
  0x00b0:   Name: GLIBC_2.17  Flags: none  Version: 49`

**Comment by klzgrad** [comment]
OpenWrt只支持19.07

如果你把OpenWrt 19.07装好了，可以再来要一个build

**Comment by klzgrad** [comment]
我调查了一下，Chrome和Firefox都不支持Socks密码鉴权。这个功能实现了也没用。

naive里面的http代理是一个半功能版，不能当一般代理用。
