### ISSUE TITLE
NaiveProxy ignores IPv6 prefix precedence in gai.conf since v104.0.5112.79-2

### ISSUE THREAD

**Issue by random755** [klzgrad/naiveproxy#330]
With `precedence ::ffff:0:0/96  100` in gai.conf, naiveproxy releases since v104.0.5112.79-2 connect to dual stack domains via IPv6 instead of IPv4. Older releases work as intended.

Upstream has been working on enabling the built-in asynchronous DNS client on Linux (see crbug.com/1350321), which does not support parsing `/etc/gai.conf` as of now, but AFAIK it hasn't been flipped in M104. In short, I don't believe there is an upstream behavior change between M103 and M104.

`git range-diff a092302d..v104.0.5112.79-2 ec4214cc..v103.0.5060.53-3` showed that patch `socket: Add RawConnect method` was changed and it looks related. Haven't verified though.

**Comment by klzgrad** [comment]
Chrome almost never used gai.conf for this. https://bugs.chromium.org/p/chromium/issues/detail?id=516305

Unless there is a way to flip resolution order by changing gai.conf before v104.

**Comment by klzgrad** [comment]
https://bugs.chromium.org/p/chromium/issues/detail?id=917418 described the behavior until v103:

> The way our current implementation works:
> * If the first IP address in our list is IPv4, or all the IP addresses are IPv4 or IPv6, just try all the addresses serially. Only try the next IP after connecting to the previous one returned an error.
> * Otherwise, try to connect to them all in order, as above. But if connecting to them all (in order) takes more than 200 milliseconds, create a copy of the address list, with all the IPv4 addresses in font (But that still has the IPv6 addresses), and race trying them all in order against trying all entries in the old list in order.
>
> [...] the current implementation does potentially prefer low-priority IPv4 addresses over earlier IPv6 addresses

The specific code that implements this was

```cpp
  // If the list contains IPv6 and IPv4 addresses, and the first address
  // is IPv6, the IPv4 addresses will be tried as fallback addresses, per
  // "Happy Eyeballs" (RFC 6555).
  bool try_ipv6_connect_with_ipv4_fallback =
      addresses.front().GetFamily() == ADDRESS_FAMILY_IPV6 &&
      !AddressListOnlyContainsIPv6(addresses);
```

This means getaddrinfo() results reordered by /etc/gai.conf could indeed make IPv4 addresses preferred. But this behavior was accidental and never supported.

And a planned behavior was

> There are other options here - make one sub-job only connect to IPv6, and the other only connect to IPv4, for instance

The change was applied in https://chromium-review.googlesource.com/c/chromium/src/+/3617441 (released in v104), which removed the above code and added behaviors towards the original plan and Happy Eyeballs v2 that explicitly starts IPv6 connection first.

So overriding IPv6 precedence via gai.conf cannot be supported. If this behavior is required, `ip6tables -d $ipv6 -j REJECT` would have the same effect, both of which are static configuration and require root to configure.

**Comment by random755** [comment]
Ah, okay. I was misled by #166, thought it is supported and this could be a regression.

Thanks for figuring it out.

Side note: it turns out nowadays IPv6 works good enough, as I've only noticed the change months later, while debugging unrelated problems.
