### ISSUE TITLE
naive proxy的可执行文件无法在arm v5的老路由器上运行吗

### ISSUE THREAD

**Issue by cary-sas** [klzgrad/naiveproxy#332]
你好，
想问一下 naiveproxy-v106.0.5249.91-1-linux-arm 版本的二进制可以在华硕arm v5的路由器上运行吗？ （AC88U AC68U 等等）。
我这边试了一下好像运行不起来呢

**Comment by klzgrad** [comment]
https://github.com/klzgrad/naiveproxy/wiki/OpenWrt-Support#asuswrt-merlin ?

**Comment by klzgrad** [comment]
不必须，socks和redir是独立单独使用的，合在一起有什么作用取决于现场环境
