### ISSUE TITLE
arm64 unused DT entry with Termux

### ISSUE THREAD

**Issue by Fhokud** [klzgrad/naiveproxy#333]
WARNING: linker: Warning: "/data/data/com.termux/files/home/naiveproxy-v106.0.5249.91-2-android-arm64/naive" unused DT entry: unknown processor-specific (type 0x70000001 arg 0x0) (ignoring)

106.0.5249.91-2，106.0.5249.91-1 都无法运行

**Comment by Fhokud** [comment]
改为arm可以正常运行

**Comment by Fhokud** [comment]
安卓12

**Comment by klzgrad** [comment]
`WARNING: linker: Warning: "/data/data/com.termux/files/home/naiveproxy-v106.0.5249.91-2-android-arm64/naive" unused DT entry: unknown processor-specific (type 0x70000001 arg 0x0) (ignoring)` is a warning. It does not mean any error.

This should be an issue specific to Termux. See https://github.com/termux/termux-packages/issues/7789. `termux-elf-cleaner --api-level 24 ./naive` should fix this.

**Comment by Fhokud** [comment]
thank you
