### ISSUE TITLE
请问tls in tls 问题

### ISSUE THREAD

**Issue by lyric2y** [klzgrad/naiveproxy#334]
想请教一个问题，tls in tls 的产生在于 naive 客户端上，还是Caddy服务端上？ 服务端返回的数据，是通过 Application Data的大小来识别tls in tls？

**Comment by klzgrad** [comment]
有什么bug需要解决？这里不做一般性技术教学

**Comment by lyric2y** [comment]
就是对 Opt-in of padding protocol
NaïveProxy clients should interoperate with any regular HTTP/2 proxies unaware of this padding protocol. NaïveProxy servers (i.e. any proxy server capable of the this padding protocol) should interoperate with any regular HTTP/2 clients (e.g. regular browsers) unaware of this padding protocol. 这段话有点不太理解，是不是如果服务端是naive通过listen去监听，那么我虽所在本地就不要用naive了？改成通过浏览器普通https代理连接即可？

**Comment by lyric2y** [comment]
> 有什么bug需要解决？这里不做一般性技术教学

可能我刚才没把具体问题说清楚，实在抱歉，就是首页说明地方我没看懂才提问的

**Comment by klzgrad** [comment]
两边都支持padding，才会使用padding，这叫opt in。这里应该不存在描述不清楚的问题
