### ISSUE TITLE
HAProxy QUIC backend not working

### ISSUE THREAD

**Issue by lyric2y** [klzgrad/naiveproxy#337]
Hello, I have to say that naive now has a very excellent improvement, and the author's hard work. Recently, haproxy has supported QUIC, and supports HTTP2/S and QUIC to access the back-end load service, which means that the back-end service can be an HTTP service based on TCP, from the official repository https://github.com/haproxytechblog/haproxy-2.6-http3 available.

```
global
  log /dev/log local0 info
  pidfile /var/run/haproxy.pid
  stats socket /var/run/haproxy/api.sock mode 660 level admin
  stats timeout 30s
  ssl-load-extra-del-ext
  ssl-load-extra-files key

defaults
  log global
  mode http
  option httplog
  option dontlognull
  timeout connect 10m
  timeout client  10m
  timeout server  10m

frontend mysite
  bind :80
  bind :443  ssl crt /etc/haproxy/certs/foo.com/cert.crt alpn h2

  # enables HTTP/3 over QUIC
  bind quic4@:443 ssl crt /etc/haproxy/certs/foo.com/cert.crt alpn h3

  # Redirects to HTTPS
  http-request redirect scheme https unless { ssl_fc }

  # Switches to the QUIC protocol
  http-response set-header alt-svc "h3=\":443\";ma=2592000;"

  default_backend webservers

backend webservers
  balance roundrobin
  server web1 127.0.0.1:8080 check maxconn 30
```

So I also compiled the HAPROXY version that supports QUIC for the first time, and used a simple HTTP WEB service as the backend of HAPROXY, which performed well.

So I started to move it to forward proxy, I replaced the above webservers with naive as the proxy server.

But it seems to only handle requests from naive client HTTPS, not from QUIC. 
```
# Based on the connection between naive client quic and haproxy quic when naive is the server

root@Haproxy:~# naive --listen=http://127.0.0.1:8080 --log     
[1010/071550.031640:INFO:naive_proxy_bin.cc(418)] Proxying via direct://
[1010/071550.031873:INFO:naive_proxy_bin.cc(558)] Listening on 127.0.0.1:8080
[1010/071552.926987:ERROR:naive_connection.cc(267)] Connection 1 to invalid origin :0
[1010/071552.927015:INFO:naive_proxy.cc(192)] Connection 1 closed: ERR_ADDRESS_INVALID
[1010/071552.927101:ERROR:naive_connection.cc(267)] Connection 2 to invalid origin :0
[1010/071552.927115:INFO:naive_proxy.cc(192)] Connection 2 closed: ERR_ADDRESS_INVALID
[1010/071552.940273:ERROR:naive_connection.cc(267)] Connection 3 to invalid origin :0
[1010/071552.940294:INFO:naive_proxy.cc(192)] Connection 3 closed: ERR_ADDRESS_INVALID
```
But I checked the handshake between them by `--log-net-log=<path> Save NetLog` and found that tls is Normal, it means that naive quic and haproxy work well, that is not the problem, so I consider whether it is a problem with the backend proxy server. Since I'm not familiar with C++, I used GOlang to reproduce, and I also found some ways to do it.

When naive connects to the proxy behind haproxy via https (simple http proxy), its carrier is

```
CONNECT www.google.com:443 HTTP/1.1
host: www.google.com:443
padding: xxxxxxxxxxx
proxy-authorization: xxxxxxxxxxx
```

But when naive connects the proxy behind haproxy via quic (simple http proxy), its carrier is

```
CONNECT HTTP/1.1
host: www.google.com:443
```

Very interesting, the requested resource URI is missing, and padding and proxy-authorization cannot be read under quic.

So I think that since the carrier obtained under golang is different between https and quic, then naive as a server should also be unable to process the client's proxy request due to this behavior.
https://github.com/klzgrad/naiveproxy/blob/master/src/net/tools/naive/naive_connection.cc#L264

**Comment by klzgrad** [comment]
> used GOlang to reproduce

You can use tcpdump or wireshark to capture the loopback traffic between haproxy and the backend and see if the headers (proxy authorization, padding) are deleted. If they are, it would indeed break the setup. The next question would be why they are deleted.

**Comment by lyric2y** [comment]
> > used GOlang to reproduce
> 
> You can use tcpdump or wireshark to capture the loopback traffic between haproxy and the backend and see if the headers (proxy authorization, padding) are deleted. If they are, it would indeed break the setup. The next question would be why they are deleted.

Completely verified my guess. When haproxy and naive are used as proxy servers, the report in wireshark does not have authorization, padding, and the URI is also empty, but it is placed in the host field.
<img width="715" alt="ha_and_haproxy" src="https://user-images.githubusercontent.com/115361755/194834418-378bf57d-c9ba-4e8f-9e55-827577aa3414.png">

**Comment by lyric2y** [comment]
> > used GOlang to reproduce
> 
> You can use tcpdump or wireshark to capture the loopback traffic between haproxy and the backend and see if the headers (proxy authorization, padding) are deleted. If they are, it would indeed break the setup. The next question would be why they are deleted.



> requested resource URI

Is it possible to obtain the requested resource URI instead of obtaining it through the host field?

**Comment by lyric2y** [comment]
But currently it is through QUIC, the naive client and haproxy are in quic transmission, the requestURI is gone, it is transferred to the host field, so I think when naive is used as a server, the original http2 method is not suitable, and should be done to naive Improvement, what does the author think about this?

**Comment by lyric2y** [comment]
I was a little negligent in capturing the packet just now. I will add it. In fact, the padding has been passed on, but it is placed in a different position.

**Comment by lyric2y** [comment]
That is to say, there is a padding field passed by the client to the server, but the location may not be like that of http2. I saw it at the time, and it seems that the author can improve it.

**Comment by lxhao61** [comment]
问题解决了？

**Comment by klzgrad** [comment]
I didn't find a HAProxy build with QUIC enabled and don't have time to build it. So close it for now.
