### ISSUE TITLE
这是怎么回事？

### ISSUE THREAD

**Issue by luckypoem** [klzgrad/naiveproxy#34]

**Comment by tomac4t** [comment]
首先，这个问题和 NaiveProxy 没有关系，下次建议在相关社区提问。
其次，这条日志提供了足够排查的信息了，你的域名为 `np.briten.info`，出错的原因是返回 403 了。那么 443 端口绑定是什么？很显然是 Nginx，而不是 Caddy。请确保 Caddy 申请证书时绑定的是 443 端口。
```
{
  "identifier": {
    "type": "dns",
    "value": "np.briten.info"
  },
  "status": "invalid",
  "expires": "2020-01-24T15:25:28Z",
  "challenges": [
    {
      "type": "tls-alpn-01",
      "status": "invalid",
      "error": {
        "type": "urn:ietf:params:acme:error:unauthorized",
        "detail": "Cannot negotiate ALPN protocol \"acme-tls/1\" for tls-alpn-01 challenge",
        "status": 403
      },
      "url": "https://acme-v02.api.letsencrypt.org/acme/chall-v3/2334755956/QSb4lg",
      "token": "vTiF7g_DMRaa62CBgiTV-5L0x9j5K9nn-FbzylwZEw0",
      "validationRecord": [
        {
          "hostname": "np.briten.info",
          "port": "443",
          "addressesResolved": [
            "104.36.70.71"
          ],
          "addressUsed": "104.36.70.71"
        }
      ]
    }
  ]
}
```

**Comment by luckypoem** [comment]
@tomac4t 
 Caddy 申请证书时,可以不绑定443 端口吗？如果不绑定443 端口，该如何设置？

**Comment by luckypoem** [comment]
@tomac4t 
请把我的域名和vps的ip分别改为mydomain.com和my-vps-ip
谢谢侬

**Comment by tomac4t** [comment]
第一个问题请阅读 https://letsencrypt.org/docs/challenge-types/ 
第二个问题，由于证书透明政策，移除域名没有意义；且你的任何编辑都会在 GitHub 留下记录。LE 社区也希望提问者在报告问题时不会因为所谓的“隐匿性”（并没有）而不透露域名。

**Comment by klzgrad** [comment]
你想藏域名，但是历史删不了。我帮你把这个issue删了，聊胜于无。下次就知道let's encrypt的url里面id也属于可识别信息，不要再失手了。

**Comment by luckypoem** [comment]
@klzgrad 
tks

**Comment by luckypoem** [comment]
@klzgrad 
你这里naiveproxy是跟caddy结合的。如果跟nginx结合，具体怎么操作？

**Comment by klzgrad** [comment]
不支持nginx，因为：nginx与Let's Encrypt的整合比较繁琐，nginx不支持http/2反向代理。

**Comment by luckypoem** [comment]
@klzgrad 

cat ~/caddyfile
mydomain.com:2443
root /var/www/html
tls xyz@some-email.com
forwardproxy {
  basicauth myusername mypassword
  hide_ip
  hide_via
  probe_resistance secret.localhost
  upstream http://127.0.0.1:8080
}

然后，运行：
caddy -http-port 82 -conf ~/caddyfile
这样caddy监听的https端口就由默认的443端口改为了2443，监听的http端口就由默认的80端口改为了82.终于解决令人头痛的监听443端口和80端口的问题。

真是不明白upstream http://127.0.0.1:8080里面的http://127.0.0.1:8080是什么意思？是一个监听vps上的8080端口的http代理服务器程序？
