### ISSUE TITLE
ios 支持吗？

### ISSUE THREAD

**Issue by zanmeipaul** [klzgrad/naiveproxy#340]
ios 支持吗？
我用 Shadowrocket   HTTPS 和 HTTP2  都无法连接，不知道是不是我配置哪些错误

**Comment by klzgrad** [comment]
支持ios的编译和无签名app的运行。不清楚shadowrocket的情况。

**Comment by zanmeipaul** [comment]
@klzgrad   请问哪里有ios的编译和无签名app运行的说明吗？

**Comment by klzgrad** [comment]
https://github.com/klzgrad/naiveproxy/blob/master/.github/workflows/build.yml#L442

**Comment by zanmeipaul** [comment]
@klzgrad 构建是在mac上执行这个脚本  [build.sh](https://github.com/klzgrad/naiveproxy/blob/master/src/build.sh)  吗？  构建的时候该传什么参数吗？

**Comment by zanmeipaul** [comment]
@zydou  我的服务器端配置
`{
 "apps": {
   "http": {
     "servers": {
       "srv0": {
         "listen": [
           ":8080"
         ],
         "routes": [
           {
             "handle": [
               {
                 "auth_user_deprecated": "ceshi",
                 "auth_pass_deprecated": "123456",
                 "handler": "forward_proxy",
                 "hide_ip": true,
                 "hide_via": true,
                 "probe_resistance": {}
               }
             ]
           },
           {
             "handle": [
               {
                 "handler": "reverse_proxy",
                 "headers": {
                   "request": {
                     "set": {
                       "Host": [
                         "{http.reverse_proxy.upstream.hostport}"
                       ],
                       "X-Forwarded-Host": [
                         "{http.request.host}"
                       ]
                     }
                   }
                 },
                 "transport": {
                   "protocol": "http",
                   "tls": {}
                 },
                 "upstreams": [
                   {
                     "dial": ""
                   }
                 ]
               }
             ]
           }
         ],
         "tls_connection_policies": [
           {
             "match": {
               "sni": [
                 ""
               ]
             },
             "certificate_selection": {
               "any_tag": [
                 "cert0"
               ]
             }
           }
         ],
         "automatic_https": {
           "disable": true
         }
       }
     }
   },
   "tls": {
     "certificates": {
       "load_files": [
         {
           "certificate": "/root/a.crt",
           "key": "/root/a.key",
           "tags": [
             "cert0"
           ]
         }
       ]
     }
   }
 }
}`
使用 Shadowrocket 无法连接，请问是我服务端配置问题吗？

**Comment by zydou** [comment]
@zanmeipaul 我对Caddy的json格式的配置不熟, 我是用的Caddyfile格式
```caddy
{
  admin off
  servers :443 {
      protocols h1 h2 h3
  }
  order forward_proxy before file_server
}

:443, www.yourdomain.com {
  tls email@example.com
  forward_proxy {
    basic_auth username password
    hide_ip
    hide_via
    probe_resistance www.digitalocean.com
  }
  file_server {
    root /var/www/html
  }
}
```

**Comment by zydou** [comment]
@zanmeipaul 那你需要让caddy监听在非443端口上并开启tls, 有点复杂, 官方文档在这里: https://caddyserver.com/docs/automatic-https

我看了你的json配置, 你好像是手动配置了一个证书. 我不知道这个证书是不是真实有效的证书. 如果是自签证书的话, 或许你可以试试在shadowrocket的naive节点配置里, 把 [允许不安全] 这个选项打开

**Comment by zydou** [comment]
@Aquarian-Age 我用的caddy自带的证书申请, 按下面这种方式写caddyfile的话, 自动会申请一个域名`www.yourdomain.com`对应的证书.
```caddyfile
{
  admin off
  servers :443 {
      protocols h1 h2 h3
  }
  order forward_proxy before file_server
}

:443, www.yourdomain.com {
  tls email@example.com
  forward_proxy {
    basic_auth username password
    hide_ip
    hide_via
    probe_resistance www.digitalocean.com
  }
  file_server {
    root /var/www/html
  }
}
```

**Comment by maike2019** [comment]
> 支持ios的编译和无签名app的运行。不清楚shadowrocket的情况。

作者您好，我看到Shadowrocket有http2模式和https 模式，两种选项。请问两种不同的配置方式有何区别呢？两种不同的连接方式在速度与安全上有何区别呢？

**Comment by ArcCal** [comment]
这个问题，应该问小火箭作者

> > 支持ios的编译和无签名app的运行。不清楚shadowrocket的情况。
> 
> 作者您好，我看到Shadowrocket有http2模式和https 模式，两种选项。请问两种不同的配置方式有何区别呢？两种不同的连接方式在速度与安全上有何区别呢？

**Comment by maike2019** [comment]
> Shadowrocket可以使用的, 用HTTP2, 不要开[TCP快速打开]和[填充]这两个选项

我在iPhone中，必须打开 填充  才能正常使用。请问大家的配置具体都是如何填写的？
