### ISSUE TITLE
go编译naiveproxy版本的caddy在低内存的服务器上会报错，请问有解决的办法吗

### ISSUE THREAD

**Issue by ffishwy** [klzgrad/naiveproxy#341]
服务器只有256MB内存，go编译naiveproxy版本的caddy会报错
请问有解决的办法吗？

**Comment by Johnshall** [comment]
在本地用 go 交叉编译，或者在[这里](https://github.com/lxhao61/integrated-examples/releases)下载预编译好的caddy。

**Comment by klzgrad** [comment]
https://github.com/klzgrad/forwardproxy/releases/tag/caddy2-naive-20221007

**Comment by ffishwy** [comment]
感谢提供的release版本，自己swap一个文件做虚拟内存也可以编出来了
小内存编译失败的一个解决方法就是使用虚拟内存
