### ISSUE TITLE
warp can't be used

### ISSUE THREAD

**Issue by huahsui** [klzgrad/naiveproxy#344]
When I use cloudfare's warp service, I get the following error

`root@c0d042:~#    ERROR   http.log.error  lookup of github.com failed: lookup github.com on 1.1.1.1:53: read udp 172.16.0.2:47916->1.1.1.1:53: i/o timeout {"request": {"remote_ip": "172.17.0.1", "remote_port": "25384", "proto": "HTTP/2.0", "method": "CONNECT", "host": "github.com:443", "uri": "github.com:443", "headers": {"Padding": [";,!$+><?)&;+;$((XXXXXXXXXXXXXXX"], "Proxy-Authorization": []}, "tls": {"resumed": true, "version": 772, "cipher_suite": 4865, "proto": "h2", "server_name": "xxxx.com"}}, "duration": 10.00352092, "status": 502, "err_id": "2yd8at6qv", "err_trace": "forwardproxy.Handler.dialContextCheckACL (forwardproxy.go:499)"}`

So , can't the naiveproxy server use cloudflare's warp service?

**Comment by klzgrad** [comment]
Don't know. Not a problem of naiveproxy.

**Comment by kylesean** [comment]
@huahsui 可以用的，我用一键脚本安装了 Socks5-WARP 默认给了一个 40000 的端口号 直接在配置文件 forward_proxy 里加一行：upstream socks5://127.0.0.1:40000 ，否则 naiveproxy 节点用不了。
