### ISSUE TITLE
How to use extra-header?

### ISSUE THREAD

**Issue by lyric2y** [klzgrad/naiveproxy#346]
How to use extra-header? `--extra-header="key: 1111\r\n"`, capturing packets via wireshark doesn't seem to work for me

**Comment by lyric2y** [comment]
And if there are multiple extra-headers, how to use writing? Is there a template？

**Comment by klzgrad** [comment]
\r is not escaped in command line. You need `key: value$(printf '\r\n')` with cmdline. Json supports the escaping.

**Comment by lyric2y** [comment]
> \r is not escaped in command line. You need `key: value$(printf '\r\n')` with cmdline. Json supports the escaping.


I tried to attach an age to the request header of the client as a test, but I did not find the request header with age in the packet capture through wireshark, only method, authority, padding and proxy-authoriation. Is there a problem?
```
./naive --listen=socks://0.0.0.0:1080 --proxy=https://user:pass@www.domain.com:443 --log --extra-header="age: 10$(printf '\r\n')" --ssl-key-log-file=ssl-key-log.json
```

**Comment by klzgrad** [comment]
--extra-header**s**

**Comment by lyric2y** [comment]
> --extra-header**s**

thanks.
