### ISSUE TITLE
mac客户端找不到config文件

### ISSUE THREAD

**Issue by erashining** [klzgrad/naiveproxy#35]
Error reading config.json: (1003) File doesn't exist.
logout
Saving session...
...copying shared history...
...saving history...truncating history files...
...completed.

谢谢🙏

**Comment by tomac4t** [comment]
如果指得是文件事实存在，但提示找不到：从 Releases 下载的是打包了config.json，运行 `./naive config.json` 即可；此外，你可能需要注意 config.json 文件的路径。
如果指得是文件不存在：自己建一个，参考 https://github.com/klzgrad/naiveproxy#setup

**Comment by erashining** [comment]
蟹蟹
已经连上啦～

**Comment by UncleUncleWang** [comment]
> 蟹蟹 已经连上啦～

你用啥第三方的客户端来连socks呀
