### ISSUE TITLE
Say goodbye

### ISSUE THREAD

**Issue by lys57** [klzgrad/naiveproxy#351]
Say goodbye

**Comment by lys57** [comment]
上述测试，作者可以复现，并且也会得到相同的结论。我相信这种特征，不用机器学习，肉眼都能观察到了

**Comment by lys57** [comment]
如果机器学习，这种特征真的是非常容易辨识的

**Comment by 2378** [comment]
杞人忧天，担心这个还不如担心：灯塔已正式断供芯片，狗急跳墙砍光缆，届时哥么敢买布上桥吗 :facepunch:

**Comment by klzgrad** [comment]
有些细节不准确，但总体上说得没错，你可以看#1里面的分析。

特征是否明显不能靠直觉判断，因为只有一个正样本，只要存在负样本被错误识别的概率，就不能稳定成为检测的依据。

长度混淆肯定是有比没有更好，至于有了之后，可以继续讨论如何增加混淆的强度。

**Comment by ahn254** [comment]
> 杞人忧天，担心这个还不如担心：灯塔已正式断供芯片，狗急跳墙砍光缆，届时哥么敢买布上桥吗 👊

我不知道你想表达什么意思，但看出来就是秀优越感的

**Comment by ahn254** [comment]
> 有些细节不准确，但总体上说得没错，你可以看#1 里面的分析。
> 
> 特征是否明显不能靠直觉判断，因为只有一个正样本，只要存在负样本被错误识别的概率，就不能稳定成为检测的依据。
> 
> 长度混淆肯定是有比没有更好，至于有了之后，可以继续讨论如何增加混淆的强度。

能否将内层tls大的包拆开？

**Comment by lys57** [comment]
> 有些细节不准确，但总体上说得没错，你可以看#1 里面的分析。
> 
> 特征是否明显不能靠直觉判断，因为只有一个正样本，只要存在负样本被错误识别的概率，就不能稳定成为检测的依据。
> 
> 长度混淆肯定是有比没有更好，至于有了之后，可以继续讨论如何增加混淆的强度。

kFirstPaddings = 8 只能填充和去填充前面8个包吗？ 还有就是内层的tls可以拆包？

**Comment by klzgrad** [comment]
> tls可以拆包

这只是很多种方法中的一种，而且简单分片而不加入额外multiplexing也变化不大。只能说，PR welcome。

**Comment by lys57** [comment]
> > tls可以拆包
> 
> 这只是很多种方法中的一种，而且简单分片而不加入额外multiplexing也变化不大。只能说，PR welcome。

其实我也是在bbs无意中看到一篇才决定自己去抓包调试的。
 https://github.com/net4people/bbs/issues/129#issuecomment-1279693944

**Comment by lys57** [comment]
> 

其实填充我觉得大的包没必要填充，因为我看到了内层的tls的Server Hello、Certificate, Server Key Exchange, Server Hello Done等都被填充了。这两个包本来就很大。所以添加padding相当于仅仅扩充包的系数而已，并且很小的包填充后的大小也是小的。总体padding似乎真的起到了很微小的作用

**Comment by lys57** [comment]
我做了没填充和填充后的对比，基本上通过包的序列大小对比，基本是一致的。所以我感觉padding应该对本来大的包不填充，小的包反而填充。否则填充基本效果真的太小了。

**Comment by klzgrad** [comment]
怎样证明这个长度不会出现在任何浏览器访问网站的流量中？
