### ISSUE TITLE
Would naiveproxy consider implementing some kind of UDP over TCP?

### ISSUE THREAD

**Issue by sora987** [klzgrad/naiveproxy#353]
Since most UDP supported proxy protocols are having serious issues bypassing GFW recently, proxy UDP without getting IP blocked is quite diffcult. Most VOIP services including Discord, Skype and Google Voice all rely on UDP, not to mention online games and P2P softwares. I think the need for a UoT method is quite dire.

I know Sagernet modified naive forwardproxy setup to implement their UoT method, but their method is only available for their Android client. Without binary and documentation I can't see their implementation adopted anywhere else...

Would naiveproxy consider implementing UoT natively? Is there any obstacle or reason for not doing anything about UDP?

Regardless whether there will be a UoT method, thank you for developing this great protocol.

**Comment by klzgrad** [comment]
This is just demonstrating some core ideas and not meant to be useful for everyone. Some feature requests were accepted because they are trivial changes. This is a big feature.

**Comment by klzgrad** [comment]
Now duplicate of #617.
