### ISSUE TITLE
Openwrt客户端可以提供IPK文件吗?

### ISSUE THREAD

**Issue by yishan2019** [klzgrad/naiveproxy#354]
Openwrt客户端可以提供IPK文件吗?

**Comment by ArcCal** [comment]
借宝地请教各位大佬
klzgrad编译好的mac arm64二进制文件，怎么在使用M1和M2的mac上运行

**Comment by ArcCal** [comment]
好像没法通过homebrew安装

**Comment by klzgrad** [comment]
二进制没有依赖，可以直接运行。

openwrt ipk有一些第三方发行版在提供，这里不提供。
