### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by AttorneyFan** [klzgrad/naiveproxy#36]
Naiveproxy is a great project to bypass gfw. It has been running smoothly for months on my VPS.
Thanks for ur work done. 
Does the develop team has any plan to support cdn? Naiveproxy would be unbreakable if can work with cdn.

**Comment by tomac4t** [comment]
Hello @AttorneyFan, 

NaïveProxy use HTTP CONNECT method to established HTTP tunnel. Cloudflare doesn't support that method (as I understand), so you can't use it as reverse proxy. And using a CDN is not good idea: https://github.com/klzgrad/naiveproxy/issues/10#issuecomment-478813442

> CDNs should be agnostic to the endpoints as long as they use standard protocols. But I don't think CDN proxying is a good idea in general. They are not designed for this type of traffic - they are optimized for 1:N upstream access to user access ratio so a proxy with 1:1 traffic pattern will cost them and they won't like it. It also slows down your traffic. As long as your own servers are online it's not necessary to go through a middleman.

**Comment by kousyougi** [comment]
Could you please add udp forward mode?
Like "forward" function of Trojan. and "Dokodemo-door" of V2ray.
I want to make one udp tunnel over naiveproxy.

I dont know why, but the performance of naiveproxy is obviously better than Trojan and V2ray.
Thanks a lot.

**Comment by klzgrad** [comment]
@AttorneyFan I'm not convinced using a CDN is substantially better than without.

@kousyougi In general no. I'm not aware of UDP traffic being interfered with by the GFW except for DNS queries, which can be protected with other means. So it's not necessary to use a specialized anti-censorship solution for UDP traffic.

**Comment by NightMachinary** [comment]
> @AttorneyFan I'm not convinced using a CDN is substantially better than without.
> 
> @kousyougi In general no. I'm not aware of UDP traffic being interfered with by the GFW except for DNS queries, which can be protected with other means. So it's not necessary to use a specialized anti-censorship solution for UDP traffic.

What means are there to protect the DNS queries?

**Comment by klzgrad** [comment]
Socks5 allows domains to be resolved remotely.

**Comment by segfault-bilibili** [comment]
> Socks5 allows domains to be resolved remotely.

However there are situations where apps do not put domain names to the socks5 request header, like, running naive on a router.

There are ways like peeking into HTTP Host header or TLS SNI etc so that the domains will then be known in order to put them into socks5 header - however this relies on peeking into application layer.

**Comment by segfault-bilibili** [comment]
Sorry, I didn't know `redir` option.
