### ISSUE TITLE
您好，能提供chrome-mac-xxx.profdata curl地址

### ISSUE THREAD

**Issue by MINGERTAI** [klzgrad/naiveproxy#360]
由于macOS下必须使用您的naive,您编译好的没有naive二进制文件，下载您的源码编译不了

由于缺少 chrome-mac-5249-1664382991-c20aa63034471953c41867af45e4ab22224b0ebd.profdata

gn-mac-amd64.zip 与 clang-llvmorg-16-init-907-g8b740747-1.tgz 都有了

希望您能提供chrome-mac-5249-1664382991-c20aa63034471953c41867af45e4ab22224b0ebd.profdata下载地址

谢谢

**Comment by klzgrad** [comment]
curl --limit-rate 10M -LO "https://storage.googleapis.com/chromium-optimization-profiles/pgo_profiles/$PGO_PATH"
