### ISSUE TITLE
linux s390x， which pack shall I use？

### ISSUE THREAD

**Issue by biozzl** [klzgrad/naiveproxy#368]
which install pack shall I use？

**Comment by klzgrad** [comment]
It is not currently supported but is possible to support. Please describe your system (hardware, software) to justify why it is an architecture that is worth supporting.

**Comment by biozzl** [comment]
> It is not currently supported but is possible to support. Please describe your system (hardware, software) to justify why it is an architecture that is worth supporting.

I'm using IMB VPS Linux one with Linux version 5.4.0-121-generic (buildd@bos02-s390x-006) (gcc version 9.4.0 (Ubuntu 9.4.0-1ubuntu1~20.04.1)) -Ubuntu SMP
**Below are configurations：**
vendor_id       : IBM/S390
# processors    : 2
bogomips per cpu: 3241.00
max thread id   : 0
features        : esan3 zarch stfle msa ldisp eimm dfp edat etf3eh highgprs te vx vxd vxe gs vxe2 vxp sort dflt sie 
facilities      : 0 1 2 3 4 6 7 8 9 10 12 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 30 31 32 33 34 35 36 37 38 40 41 42 43 44 45 46 47 48 49 50 51 52 53 54 55 57 58 59 60 61 73 74 75 76 77 80 81 82 128 129 130 131 133 134 135 146 147 148 150 151 152 155 156 168
cache0          : level=1 type=Data scope=Private size=128K line_size=256 associativity=8
cache1          : level=1 type=Instruction scope=Private size=128K line_size=256 associativity=8
cache2          : level=2 type=Data scope=Private size=4096K line_size=256 associativity=8
cache3          : level=2 type=Instruction scope=Private size=4096K line_size=256 associativity=8
cache4          : level=3 type=Unified scope=Shared size=262144K line_size=256 associativity=32
cache5          : level=4 type=Unified scope=Shared size=983040K line_size=256 associativity=60
processor 0: version = FF,  identification = 0A18E8,  machine = 8561
processor 1: version = FF,  identification = 0A18E8,  machine = 8561

cpu number      : 0
cpu MHz dynamic : 5200
cpu MHz static  : 5200

cpu number      : 1
cpu MHz dynamic : 5200
cpu MHz static  : 5200
CPU(s):                          2
On-line CPU(s) list:             0,1
Thread(s) per core:              1
Core(s) per socket:              1
Socket(s) per book:              1
Book(s) per drawer:              1
Drawer(s):                       2
NUMA node(s):                    1
Vendor ID:                       IBM/S390
Machine type:                    8561
CPU dynamic MHz:                 5200
CPU static MHz:                  5200
BogoMIPS:                        3241.00
Hypervisor:                      z/VM 7.1.0
Hypervisor vendor:               IBM
Virtualization type:             full
Dispatching mode:                horizontal
L1d cache:                       256 KiB
L1i cache:                       256 KiB
L2d cache:                       8 MiB
L2i cache:                       8 MiB
L3 cache:                        256 MiB
L4 cache:                        960 MiB
NUMA node0 CPU(s):               0,1
Vulnerability Itlb multihit:     Not affected
Vulnerability L1tf:              Not affected
Vulnerability Mds:               Not affected
Vulnerability Meltdown:          Not affected
Vulnerability Mmio stale data:   Not affected
Vulnerability Spec store bypass: Not affected
Vulnerability Spectre v1:        Mitigation; __user pointer sanitization
Vulnerability Spectre v2:        Mitigation; etokens
Vulnerability Srbds:             Not affected
Vulnerability Tsx async abort:   Not affected
Flags:                           esan3 zarch stfle msa ldisp eimm dfp edat etf3eh highgprs te vx vxd vxe gs vxe2 vxp sort dflt sie

**Comment by klzgrad** [comment]
> IBM VPS

What is the nature of this? You need to show there are more than one users who will need the s390x port.

**Comment by biozzl** [comment]
> > IBM VPS
> 
> What is the nature of this? You need to show there are more than one users who will need the s390x port.

This is IBM Linux One platform with over 10 thousand users in there and s390x configration is the only type this platform provide.
I'm link the wesite and description in below：
https://linuxone.cloud.marist.edu/#/index
IBM LinuxONE is an enterprise-grade Linux® server with a unique architecture designed to meet the needs of mission-critical workloads. It brings together IBM’s experience in building sustainable, secure and scalable systems with the openness of the Linux operating system.

**Comment by klzgrad** [comment]
I think what you need is the s390x port of Caddy server, which is built with standard Go cross compile. Naive is client side only.
