### ISSUE TITLE
"/bin/ash: naive: not found" on OpenWRT X86-64

### ISSUE THREAD

**Issue by kousyougi** [klzgrad/naiveproxy#37]
I used OpenWrt 19.07.1_x86-64 at Qemu.
It can run caddy without error by their linux-x64 version.

When I started naiveproxy-linux-x64.
It showed "/bin/ash: naive: not found"

Should I build a OpenWrt Version? Is it difficult?
Please help. Thanks

**Comment by kousyougi** [comment]
I tried to build it.
but still got this message: 

> /bin/ash: naive: not found

Could you please check what i missed?

My openwrt is
"https://downloads.openwrt.org/releases/19.07.1/targets/x86/64/openwrt-sdk-19.07.1-x86-64_gcc-7.5.0_musl.Linux-x86_64.tar.xz"

And I modified the following 2 file. ("get-clang.sh" &"get-openwrt.sh" )
modified this 2 lines on "get-clang.sh"
> ARCH="Linux"
OPENWRT_FLAGS=true

added this to "get-openwrt.sh"

> arch="x86_64"
release="19.07.1"
target="x86"
subtarget="64"
gcc_ver="7.5.0"

Thanks

**Comment by klzgrad** [comment]
OpenWrt uses a different libc from Ubuntu (musl). The error means s working ELF interpreter is not found. The -linux-x64 builds are built for Ubuntus, not OpenWrt.

If you need a real OpenWrt build, tell me the architecture on which you plan to use it, and I'll create a new build.

**Comment by kousyougi** [comment]
Thanks for your reply.
I really need a new OpenWrt build.

I use this architecture:
Official OpenWrt 19.07.1 x86-64 gcc-7.5.0
I thinks it is the most used architecture.

SDK: https://downloads.openwrt.org/releases/19.07.1/targets/x86/64/openwrt-sdk-19.07.1-x86-64_gcc-7.5.0_musl.Linux-x86_64.tar.xz

Thanks a lot.

**Comment by klzgrad** [comment]
You're using it in QEMU, which I consider a test case, not a real workload. What kind of hardware do you use it for?

**Comment by kousyougi** [comment]
I use a small computer ( CPU: intel N3150 ) runing MikroTik RouterOS's KVM.

MikroTik RouterOS:
Architecture Name: x86_64
Version: 6.45.8 (long-term)

My hardware:
CPU: Intel N3150
RAM: 8GB

Thanks

**Comment by klzgrad** [comment]
See naiveproxy-v80.0.3987.87-1-openwrt-x86_64.tar.xz
in https://github.com/klzgrad/naiveproxy/releases/tag/v80.0.3987.87-1.

**Comment by kousyougi** [comment]
It can not work.

I've installed libnss 3.48-1 package on OpenWrt.

show this message on Firefox
> PR_END_OF_FILE_ERROR


on OpenWrt
> root@OpenWrt:/# /etc/naive/./naive /etc/naive/config.json
[0206/103436.329063:ERROR:cert_verify_proc_nss.cc(998)] CERT_PKIXVerifyCert for example.net failed err=-8179
[0206/103436.329992:ERROR:ssl_client_socket_impl.cc(941)] handshake failed; returned -1, SSL error code 1, net_error -202
[0206/103437.323163:ERROR:ssl_client_socket_impl.cc(941)] handshake failed; returned -1, SSL error code 1, net_error -202

and on the server side, I didn't see any package coming from port 443.

**Comment by klzgrad** [comment]
`-8179` means SEC_ERROR_UNKNOWN_ISSUER. Your certificate is not generated correctly.

See "Generate certificates" in https://www.chromium.org/quic/playing-with-quic and https://source.chromium.org/chromium/chromium/src/+/master:docs/linux/cert_management.md.

**Comment by kousyougi** [comment]
I found out that is my mistake. I resolved the wrong domain name before.
It can run well now on my OpenWrt X86-64.
The latency is so low compared with other tools.
Its a really good application. Thanks again.
