### ISSUE TITLE
log报错

### ISSUE THREAD

**Issue by gitcoinkuang** [klzgrad/naiveproxy#370]
网速突然很慢，图片也加载不出来，我就去看了下服务器，有很多以下这些错误，我的域名已经替换成其他的，只看错误，请问这是什么原因？
2022/10/30 08:22:46.917 ERROR   http.log.error  read tcp 10.0.0.37:59488->142.250.157.188:5228: read: connection reset by peer {"request": {"remote_ip": "39.130.79.200", "remote_port": "18509", "proto": "HTTP/2.0", "method": "CONNECT", "host": "mtalk.google.com:5228", "uri": "mtalk.google.com:5228", "headers": {"Padding": ["!*'++$(?(;?*@'&+XXXXXXXX"], "Proxy-Authorization": []}, "tls": {"resumed": false, "version": 772, "cipher_suite": 4865, "proto": "h2", "server_name": "kb.xxxxxxx.buzz"}}, "duration": 7.473231837}

**Comment by klzgrad** [comment]
这个是无关日志
