### ISSUE TITLE
关于文档解读

### ISSUE THREAD

**Issue by ylo235** [klzgrad/naiveproxy#372]
引用如下：

NaïveProxy proxies bidirectional streams through HTTP/2 (or HTTP/3) CONNECT tunnels. The bidirectional streams operate in a sequence of reads and writes of data. The first kFirstPaddings (8) reads and writes in a bidirectional stream after the stream is established are padded in this format:

struct PaddedData {
  uint8_t original_data_size_high;  // original_data_size / 256
  uint8_t original_data_size_low;  // original_data_size % 256
  uint8_t padding_size;
  uint8_t original_data[original_data_size];
  uint8_t zeros[padding_size];
};
padding_size is a random integer uniformally distributed in [0, kMaxPaddingSize] (kMaxPaddingSize: 255). original_data_size cannot be greater than 65535, or it has to be split into several reads or writes.

我对这段似乎不太明白，作者可以介绍下？
The first kFirstPaddings (8) reads and writes in a bidirectional stream after the stream is established are padded in this format。

意思是当建立流后，双向流中前八个包分别进行读取和写入？ 客户端`填充`发往服务端前八个包，然后服务端`去填充`前八个包？

Wiki是否能否更新中文文档？https://github.com/klzgrad/naiveproxy/wiki/%E7%AE%80%E4%BD%93%E4%B8%AD%E6%96%87

**Comment by klzgrad** [comment]
没看出有哪里没说清楚

**Comment by ylo235** [comment]
> 没看出有哪里没说清楚

也就是我的理解是正确的对吧

**Comment by ylo235** [comment]
> 没看出有哪里没说清楚

能否更新wiki的中文版说明？

**Comment by klzgrad** [comment]
不建议翻译这一段
