### ISSUE TITLE
为什么小火箭必须打开填充才能使用

### ISSUE THREAD

**Issue by gitcoinkuang** [klzgrad/naiveproxy#373]
你好，我有几个问题
1、就是这个填充的作用是什么？为什么小火箭必须打开填充才能使用，而PC端配置文件里不加padding也能使用？
2、最近经常浏览网页会出现网络中断的现象，这个是因为网络波动造成的吗？
3、网页图片多会显示不出来，这个怎么改善呢？https代理是单线程，所以并发高就会失败吗？

**Comment by gitcoinkuang** [comment]
调了描述里的性能参数，现在已经飞起了！

**Comment by openips** [comment]
> 调了描述里的性能参数，现在已经飞起了！

哪个参数

**Comment by ylo235** [comment]
> 你好，我有几个问题 1、就是这个填充的作用是什么？为什么小火箭必须打开填充才能使用，而PC端配置文件里不加padding也能使用？ 2、最近经常浏览网页会出现网络中断的现象，这个是因为网络波动造成的吗？ 3、网页图片多会显示不出来，这个怎么改善呢？https代理是单线程，所以并发高就会失败吗？

我就用小火箭连接naive，非常快。 非常给力！奥利给～～～～～干了兄弟们～～。并且小火箭内置cronet内核，复用了chrome的网络栈，非常给力！！奥利给～～

**Comment by klzgrad** [comment]
> 小火箭内置cronet内核，复用了chrome的网络栈

这是什么软件，开源了吗？为什么会产生要到这里来提问的情况？虽然NaiveProxy是弱开源，但是如果引用了代码，应该进行一些反馈，以确保安全问题的更新能及时上下游进行通知。

**Comment by Johnshall** [comment]
> > 小火箭内置cronet内核，复用了chrome的网络栈
> 
> 这是什么软件，开源了吗？为什么会产生要到这里来提问的情况？虽然NaiveProxy是弱开源，但是如果引用了代码，应该进行一些反馈，以确保安全问题的更新能及时上下游进行通知。

是 shadowrocket，闭源。
之前咨询过 shadowrocket 作者，回答到对 naiveproxy 的支持是普通的 HTTPS 代理，因为 chrome 网络栈太过复杂，在 iOS 上实现的工作不值得努力。

**Comment by klzgrad** [comment]
上面有人宣称shadowrocket内置了cronet，是怎么内置的？我这刚把cronet支持删除，因为没有得到反馈有人在用。如果别人要用，cronet有一些修改需要注意。

**Comment by sify29** [comment]
> > > 小火箭内置cronet内核，复用了chrome的网络栈
> > 
> > 
> > 这是什么软件，开源了吗？为什么会产生要到这里来提问的情况？虽然NaiveProxy是弱开源，但是如果引用了代码，应该进行一些反馈，以确保安全问题的更新能及时上下游进行通知。
> 
> 是 shadowrocket，闭源。 之前咨询过 shadowrocket 作者，回答到对 naiveproxy 的支持是普通的 HTTPS 代理或 HTTP/2 代理+内置 TLS 库。因为 chrome 网络栈太过复杂，在 iOS 上实现的工作不值得努力。

native很多接口ios上都没有。但我做过测试，cronet打包成framework到xcode上，是能复用chrome的指纹的，不过我还没找到ios对connect的请求支持，所以中途放弃了。所以目前我只考虑电脑端，并且与go绑定，通过cronet-go前辈的项目学习，大概也有一定的了解。不过我最近打算用cornet去请求websocket，按道理应该可以，但目前似乎还是遇到些问题。

**Comment by sify29** [comment]
> 上面有人宣称shadowrocket内置了cronet，是怎么内置的？我这刚把cronet支持删除，因为没有得到反馈有人在用。如果别人要用，cronet有一些修改需要注意。

ios上需要额外打包成framework，不过接口太少。我已经做过测试了

**Comment by klzgrad** [comment]
想在ios上部署cronet可以参考这几个补丁：

https://github.com/klzgrad/naiveproxy/tree/106.0.5249.91#changes-from-upstream
```
(Cronet) Allow passing in -connect-authority header to override the CONNECT authority field
(Cronet) Disable system proxy resolution and use fixed proxy resolution specified by experimental option proxy_server
(Cronet) Support setting base::FeatureList by experimental option feature_list
(Cronet) Support setting the network isolation key of a stream with -network-isolation-key header
(Cronet) Add certificate net fetcher
(Cronet) Support setting socket limits by experimental option socket_limits
```

**Comment by maike2019** [comment]
是的，我选择HTTP2模式，必须打开 填充才能正常使用。大家都是如何配置的？？
TCP快速打开 和  填充 是什么意思？该如何选择？到底是否要打开呢？我看别人都说只填写地址和端口和user+password，其他不需要填写。 
可我如果不打开  填充  ，我的节点 是无法正常使用的，打开了填充才恢复正常。请问这算什么问题？该如何解决？

**Comment by maike2019** [comment]
楼主所说的调优是指： sudo sysctl -w net.ipv4.tcp_notsent_lowat=16384 吗？
