### ISSUE TITLE
“experimental_http3”: false,报错

### ISSUE THREAD

**Issue by sophauer** [klzgrad/naiveproxy#374]
config json file as followed:
#  /etc/caddy/caddy_server.json
{
  "admin": {
    "disabled": true
  },
  "logging": {
    "sink": {
      "writer": {
        "output": "discard"
      }
    },
    "logs": {
      "default": {
        "writer": {
          "output": "discard"
        }
      }
    }
  },
  "apps": {
    "http": {
      "servers": {
        "srv0": {
          "listen": [
            ":18443"
          ],
          "routes": [
            {
              "handle": [
                {
                  "handler": "subroute",
                  "routes": [
                    {
                      "handle": [
                        {
                          "auth_pass_deprecated": "U",
                          "auth_user_deprecated": "P_75b8B1",
                          "handler": "forward_proxy",
                          "hide_ip": true,
                          "hide_via": true,
                          "probe_resistance": {}
                        }
                      ]
                    },
                    {
                      "match": [
                        {
                          "host": [
                            "server.my999999999.com"
                          ]
                        }
                      ],
                      "handle": [
                        {
                          "handler": "file_server",
                          "root": "/var/www/html",
                          "index_names": [
                            "index.html"
                          ]
                        }
                      ],
                      "terminal": true
                    }
                  ]
                }
              ]
            }
          ],
          **"experimental_http3": false,**
          "tls_connection_policies": [
            {
              "match": {
                "sni": [
                  "server.my999999999.com"
                ]
              }
            }
          ],
          "automatic_https": {
            "disable": true
          }
        }
      }
    },
    "tls": {
      "certificates": {
        "load_files": [
          {
            "certificate": "/root/server.my999999999.com/server.my999999999.com.cer",
            "key": "/root/server.my999999999.com/server.my999999999.com.key"
          }
        ]
      }
    }
  }
}

运行服务端
/usr/bin/caddy run --config /etc/caddy/caddy_server.json

报错
loading http app module: decoding module config: http: json: unknown field “experimental_http3”

去掉
“experimental_http3”: false,
后正常了,但是UDP口开了,被QOS的不要不要的
求教如何正确关闭udp

**Comment by zdfdreamfactory** [comment]
早期caddy版本支持experimental_http3，新版去掉了，新版默认是支持的，caddy的文档链接：https://caddyserver.com/docs/caddyfile/options#protocols

**Comment by zdfdreamfactory** [comment]
> > 早期caddy版本支持experimental_http3，新版去掉了，新版默认是支持的，caddy的文档链接：https://caddyserver.com/docs/caddyfile/options#protocols
> > caddy 2.6版本更新日志: https://github.com/caddyserver/caddy/releases/tag/v2.6.0
> 
> 谢谢指教,不过.我是想把http3给关闭了,因为UDP被QOS的很惨 求指引

参考作者最新的配置文件：
{
        order forward_proxy before file_server
        servers {
                protocols h1 h2
        }
}

如果需要http3，在h2后面加一个h3
