### ISSUE TITLE
 [FATAL] exit status 1

### ISSUE THREAD

**Issue by huixindebaicai** [klzgrad/naiveproxy#375]
An exception occurred in the installation step according to the homepage example. What should I do?

root@XXX:~/go/pkg/mod# ~/go/bin/xcaddy build --with github.com/caddyserver/forwardproxy@caddy2=github.com/klzgrad/forwardproxy@naive
2022/11/02 15:05:25 [INFO] Temporary folder: /tmp/buildenv_2022-11-02-1505.3716246685
2022/11/02 15:05:25 [INFO] Writing main module: /tmp/buildenv_2022-11-02-1505.3716246685/main.go
package main

import (
	caddycmd "github.com/caddyserver/caddy/v2/cmd"

	// plug in Caddy modules here
	_ "github.com/caddyserver/caddy/v2/modules/standard"
	_ "github.com/caddyserver/forwardproxy"
)

func main() {
	caddycmd.Main()
}
2022/11/02 15:05:25 [INFO] Initializing Go module
2022/11/02 15:05:25 [INFO] exec (timeout=10s): /usr/local/go/bin/go mod init caddy 
go: creating new go.mod: module caddy
go: to add module requirements and sums:
	go mod tidy
2022/11/02 15:05:25 [INFO] Replace github.com/caddyserver/forwardproxy => github.com/klzgrad/forwardproxy@naive
2022/11/02 15:05:25 [INFO] exec (timeout=10s): /usr/local/go/bin/go mod edit -replace github.com/caddyserver/forwardproxy=github.com/klzgrad/forwardproxy@naive 
2022/11/02 15:05:25 [INFO] Pinning versions
2022/11/02 15:05:25 [INFO] exec (timeout=0s): /usr/local/go/bin/go get -d -v github.com/caddyserver/caddy/v2 
github.com/caddyserver/caddy/v2 imports
	net/netip: package net/netip is not in GOROOT (/usr/local/go/src/net/netip)
2022/11/02 15:05:31 [FATAL] exit status 1

**Comment by ArcCal** [comment]
可以翻翻本项目的issue，有人问过，有人贡献过解决方法

**Comment by anlythree** [comment]
解决了么？我也遇到了这个问题，，貌似是go缺少net/netip这个包，但是百度不到怎么安装
