### ISSUE TITLE
关于naive服务端对流量的控制

### ISSUE THREAD

**Issue by on4day** [klzgrad/naiveproxy#376]
目前有一个想法：
某个网站的vip会员只有一个，但我和小伙伴用同一个naive服务端。
在流量经过naive时，修改https数据包内容和头，请问各位好汉有什么方式可以实现吗？

**Comment by klzgrad** [comment]
--extra-headers

**Comment by on4day** [comment]
@klzgrad 没太明白，caddy中没有这个参数，能麻烦详细说一下吗？
