### ISSUE TITLE
路由器上用gfwlist方式好像有点问题呢。。。。

### ISSUE THREAD

**Issue by zhangbo8418** [klzgrad/naiveproxy#383]
路由器上用gfwlist方式好像有点问题呢，不用gfwlist模式流量受不鸟。。。我是naiveproxy和路由器的dnsmasq使用gfwlist,但是感觉不稳，有些网站打不开。。。

规则
        ipset -N gfwlist iphash
        iptables -t nat -A PREROUTING -p tcp -m set --match-set gfwlist dst -j REDIRECT --to-port 1080
        iptables -t nat -A OUTPUT -p tcp -m set --match-set gfwlist dst -j REDIRECT --to-port 1080
        # 添加Telegram服务器组
        ipset -A gfwlist 91.108.4.0/22
        ipset -A gfwlist 91.108.8.0/21
        ipset -A gfwlist 91.108.16.0/22
        ipset -A gfwlist 91.108.56.0/22
        ipset -A gfwlist 149.154.160.0/20

gfwlist
        server=/youtu.be/127.0.0.1#53
        ipset=/youtu.be/gfwlist
        server=/youtube.com/127.0.0.1#53
        ipset=/youtube.com/gfwlist
        server=/youtube-nocookie.com/127.0.0.1#53
        ipset=/youtube-nocookie.com/gfwlist
        server=/youtubeeducation.com/127.0.0.1#53
        ipset=/youtubeeducation.com/gfwlist
        server=/youtubegaming.com/127.0.0.1#53
        ipset=/youtubegaming.com/gfwlist
        server=/youtubekids.com/127.0.0.1#53
        ipset=/youtubekids.com/gfwlist

www.youtube.com
<img width="1414" alt="QQ20221105-164435@2x" src="https://user-images.githubusercontent.com/46797568/200112142-e86d1314-76bd-4624-81dd-1ade1cbefac3.png">

youtube.com
<img width="1417" alt="QQ20221105-164454@211" src="https://user-images.githubusercontent.com/46797568/200112158-118c9c5c-d7bf-4675-a5f2-3698546f7d55.png">

播放倒是没问题，就是封面木有
<img width="1415" alt="QQ20221105-164828@2222" src="https://user-images.githubusercontent.com/46797568/200112182-161380f4-f0e8-4f44-b5a5-240448b31d47.png">

**Comment by sify29** [comment]
> 路由器上用gfwlist方式好像有点问题呢，不用gfwlist模式流量受不鸟。。。我是naiveproxy和路由器的dnsmasq使用gfwlist,但是感觉不稳，有些网站打不开。。。
> 
> 规则 ipset -N gfwlist iphash iptables -t nat -A PREROUTING -p tcp -m set --match-set gfwlist dst -j REDIRECT --to-port 1080 iptables -t nat -A OUTPUT -p tcp -m set --match-set gfwlist dst -j REDIRECT --to-port 1080 # 添加Telegram服务器组 ipset -A gfwlist 91.108.4.0/22 ipset -A gfwlist 91.108.8.0/21 ipset -A gfwlist 91.108.16.0/22 ipset -A gfwlist 91.108.56.0/22 ipset -A gfwlist 149.154.160.0/20
> 
> gfwlist server=/youtu.be/127.0.0.1#53 ipset=/youtu.be/gfwlist server=/youtube.com/127.0.0.1#53 ipset=/youtube.com/gfwlist server=/youtube-nocookie.com/127.0.0.1#53 ipset=/youtube-nocookie.com/gfwlist server=/youtubeeducation.com/127.0.0.1#53 ipset=/youtubeeducation.com/gfwlist server=/youtubegaming.com/127.0.0.1#53 ipset=/youtubegaming.com/gfwlist server=/youtubekids.com/127.0.0.1#53 ipset=/youtubekids.com/gfwlist
> 
> [www.youtube.com](http://www.youtube.com) <img alt="QQ20221105-164435@2x" width="1414" src="https://user-images.githubusercontent.com/46797568/200112142-e86d1314-76bd-4624-81dd-1ade1cbefac3.png">
> 
> youtube.com <img alt="QQ20221105-164454@211" width="1417" src="https://user-images.githubusercontent.com/46797568/200112158-118c9c5c-d7bf-4675-a5f2-3698546f7d55.png">
> 
> 播放倒是没问题，就是封面木有 <img alt="QQ20221105-164828@2222" width="1415" src="https://user-images.githubusercontent.com/46797568/200112182-161380f4-f0e8-4f44-b5a5-240448b31d47.png">

设置问题，原因自己找。

**Comment by zhangbo8418** [comment]
> > 路由器上用gfwlist方式好像有点问题呢，不用gfwlist模式流量受不鸟。。。我是naiveproxy和路由器的dnsmasq使用gfwlist,但是感觉不稳，有些网站打不开。。。
> > 
> > 规则 ipset -N gfwlist iphash iptables -t nat -A PREROUTING -p tcp -m set --match-set gfwlist dst -j REDIRECT --to-port 1080 iptables -t nat -A OUTPUT -p tcp -m set --match-set gfwlist dst -j REDIRECT --to-port 1080 # 添加Telegram服务器组 ipset -A gfwlist 91.108.4.0/22 ipset -A gfwlist 91.108.8.0/21 ipset -A gfwlist 91.108.16.0/22 ipset -A gfwlist 91.108.56.0/22 ipset -A gfwlist 149.154.160.0/20
> > 
> > gfwlist server=/youtu.be/127.0.0.1#53 ipset=/youtu.be/gfwlist server=/youtube.com/127.0.0.1#53 ipset=/youtube.com/gfwlist server=/youtube-nocookie.com/127.0.0.1#53 ipset=/youtube-nocookie.com/gfwlist server=/youtubeeducation.com/127.0.0.1#53 ipset=/youtubeeducation.com/gfwlist server=/youtubegaming.com/127.0.0.1#53 ipset=/youtubegaming.com/gfwlist server=/youtubekids.com/127.0.0.1#53 ipset=/youtubekids.com/gfwlist
> > 
> > [www.youtube.com](http://www.youtube.com) <img alt="QQ20221105-164435@2x" width="1414" src="https://user-images.githubusercontent.com/46797568/200112142-e86d1314-76bd-4624-81dd-1ade1cbefac3.png">
> > 
> > youtube.com <img alt="QQ20221105-164454@211" width="1417" src="https://user-images.githubusercontent.com/46797568/200112158-118c9c5c-d7bf-4675-a5f2-3698546f7d55.png">
> > 
> > 播放倒是没问题，就是封面木有 <img alt="QQ20221105-164828@2222" width="1415" src="https://user-images.githubusercontent.com/46797568/200112182-161380f4-f0e8-4f44-b5a5-240448b31d47.png">
> 
> 设置问题，原因自己找。

大佬，给个提示啊。。。

**Comment by klzgrad** [comment]
Not a tech support forum.
