### ISSUE TITLE
Windows11开启hyper-v无法连接

### ISSUE THREAD

**Issue by jideweiwx** [klzgrad/naiveproxy#386]
开启hyper-v后无法连接上网
系统：windows11 22h2
版本：v107.0.5304.87-1
未开启hyper-v
![1](https://user-images.githubusercontent.com/46131498/200165437-f624420b-78d7-4138-84e7-988fed4fe543.png)
开启hyper-v
![2](https://user-images.githubusercontent.com/46131498/200165451-352ab7bf-8e67-40b2-838c-74067de6212a.png)

**Comment by klzgrad** [comment]
跟你的环境配置有关，程序没有bind端口的权限

**Comment by jideweiwx** [comment]
> 跟你的环境配置有关，程序没有bind端口的权限

谢谢！

**Comment by 2378** [comment]
hyperv保留端口的老问题了，重启系统都不见得管用
比如我机器上 一个virtualbox 两个hyperv 
naive端口改到10000以上才不受影响
