### ISSUE TITLE
naiveproxy服务端的出口能配置为走socks5吗？

### ISSUE THREAD

**Issue by crazypeace** [klzgrad/naiveproxy#387]
naiveproxy服务端的出口能配置为走socks5吗？
这样的话，naiveproxy的出口部分可以借用v2ray的路由模块实现一些特殊需要。

**Comment by klzgrad** [comment]
你试了吗

**Comment by crazypeace** [comment]
大佬，我都没看到 naive 服务器端哪里可以配置出口啊。

**Comment by klzgrad** [comment]
能，看文档

**Comment by ArcCal** [comment]
可以的
我就是这么干的

**Comment by ArcCal** [comment]
至少有两种方法可以实现你要的效果

**Comment by crazypeace** [comment]
我看到 naive的caddy有个" serve_pac        /secret-proxy.pac "这里面应该可以指定 SOCKS 代理
请教，你说的两种方法， 还有什么方法？

**Comment by ArcCal** [comment]
https://allinfa.com/naiveproxy-caddy.html

看美博园的这个帖子

**Comment by crazypeace** [comment]
你说的这篇帖子里哪里讲到 naiveproxy 对接v2ray了？

**Comment by crazypeace** [comment]
我今天尝试让Naive服务端(Caddy)使用pac文件走SOCKS代理，失败。
1. pac文件内容
```
function FindProxyForURL(url, host) {
  return "SOCKS 127.0.0.1:1080";
}
```
2. Caddyfile修改
```
{
  order forward_proxy before file_server
}
:14443, npp.tzzhu.gq:14443 {
  tls e16d9cb045d8@gmail.com
  forward_proxy {
    basic_auth e16d9cb045d8 e16d9cb045d8
    hide_ip
    hide_via
    probe_resistance
    serve_pac /etc/caddy/s5out.pac #多加了这一行
  }
  file_server {
    root /var/www/html
  }
}
```
3. V2Ray增加Socks5的inbound
```
{
  "tag": "proxy",
  "port": 1080,
  "listen": "127.0.0.1",
  "protocol": "socks",
  "sniffing": {
    "enabled": true,
    "destOverride": [
      "http",
      "tls"
    ]
  },
  "settings": {
    "auth": "noauth",
    "udp": false
  }
}
```
4. V2Ray增加路由设置
```
{
     "type": "field",
     "outboundTag": "socks5-warp",  
     "domain": ["geosite:cn"]  
},
```

测试结果:
1. 通过Naive节点访问 ipw.cn 显示IP为VPS的IP, v2ray access.log中无记录
2. 通过`curl  -x 'SOCKS://127.0.0.1:1080' ipw.cn` 访问 ipw.cn, v2ray access.log中有记录
```
2022/11/24 14:47:18 tcp:127.0.0.1:40776 accepted tcp:106.55.75.123:80 [socks5-warp]
```

**Comment by Btu2023V** [comment]
可以参考以下文章：
https://libertyleadingnetwork.blogspot.com/2022/10/naiveproxy.html
https://zelikk.blogspot.com/2022/11/naiveproxy-socks5-v2ray-cn-ip-domain-route.html
