### ISSUE TITLE
v107.0.5304.87-2 在Merlin上报错 Bus error

### ISSUE THREAD

**Issue by Abderrian** [klzgrad/naiveproxy#392]
v107.0.5304.87-1 可以在Merlin上正常运行。v107.0.5304.87-2报错 Bus error 。
v107.0.5304.87-2 是不是因为开启了PartitionAlloc需要最新版本的OpenWrt？

**Comment by klzgrad** [comment]
> Bus error

缺少错误信息。请勿用自然语言翻译错误信息。

**Comment by Abderrian** [comment]
![01](https://user-images.githubusercontent.com/46275041/201343816-340b3993-e52a-4d02-a297-4ffffc64f875.png)

**Comment by klzgrad** [comment]
需要`strace ./naive config.json`的信息

**Comment by nilxbit** [comment]
我用的openwrt-aarch64_cortex-a53-static在Merlin上也不能运行了

**Comment by nilxbit** [comment]
调试结果跟这个issue差不多 https://github.com/klzgrad/naiveproxy/issues/369
都是partition_alloc::DecommitSystemPages(），
madvise(0x33c08000, 16384, MADV_DONTNEED) = -1 ENOSYS (Function not implemented)

我把https://github.com/klzgrad/naiveproxy/blob/516aa668e218809ab9c68b685e4f9a0320a3eed2/src/base/allocator/partition_allocator/page_allocator_internals_posix.h#L364
注释掉PA_PCHECK(0 == madvise(ptr, length, MADV_DONTNEED));就能运行

不知道大佬有没有更好的解决方法

**Comment by klzgrad** [comment]
#369 是 trap，不是Bus error，不能说明是同一个问题

**Comment by klzgrad** [comment]
Trap的问题看 https://github.com/klzgrad/naiveproxy/releases/tag/v107.0.5304.87-3 有没有解决


Bus error是什么原因目前还不清楚

**Comment by nilxbit** [comment]
我的问题解决了

**Comment by klzgrad** [comment]
也可以使用ulimit -c unlimited生成一个core，上传

**Comment by Abderrian** [comment]
v107.0.5304.87-3可以正常运行了。
