### ISSUE TITLE
caddy log "status": 421

### ISSUE THREAD

**Issue by winds365** [klzgrad/naiveproxy#393]
caddy日志
`
2022/11/12 14:04:49.877	error	http.log.access.log3	handled request	{"request": {"remote_ip": "1.1.1.1", "remote_port": "50809", "proto": "HTTP/2.0", "method": "CONNECT", "host": "149.154.175.53:80", "uri": "149.154.175.53:80", "headers": {"Padding": ["#'*\"!)>;*?'!),;)XXXXXXXXXXXXXXX"], "Proxy-Authorization": []}, "tls": {"resumed": false, "version": 772, "cipher_suite": 4865, "proto": "h2", "server_name": "example.com"}}, "user_id": "", "duration": 0.000026866, "size": 0, "status": 421, "resp_headers": {"Server": ["Caddy"], "Alt-Svc": ["h3=\":4443\"; ma=2592000"]}}
`
caddy配置
`
:4443, example.com {
  tls example.com.cer example.com.key
  forward_proxy {
    basic_auth aaa ccc
    hide_ip
    hide_via
    probe_resistance
  }
  file_server {
    root /var/www/html
  }
}
`
客户端配置
`{
  "listen": "socks://0.0.0.0:10801",
  "proxy": "https://aaa:ccc@example.com:4443",
  "log": ""
}`
浏览器可以正常访问https://example.com:4443

**Comment by winds365** [comment]
caddy配置去掉strict_sni_host on解决

**Comment by sorz** [comment]
It turns out that `strict_sni_host` is [automatically turned on](https://caddyserver.com/docs/caddyfile/options#strict-sni-host) if TLS client auth is ever enabled on any site. 

Workaround:

In global config:

```
servers {
    strict_sni_host insecure_off
}
```

In the sites with mTLS, I did something likes:

```
@not_cloudflare {
  not expression {tls_client_subject} == "CN=origin-pull.cloudflare.net,OU=Origin Pull,O=Cloudflare\\, Inc.,L=San Francisco,ST=California,C=US"
}
error @not_cloudflare 421
```
to prevent domain fronting.
