### ISSUE TITLE
将dns请求分流到naive时出现断流问题

### ISSUE THREAD

**Issue by kmb21y66** [klzgrad/naiveproxy#395]
目前我的全部流量通过arm64软路由透明代理进入xray，分流设置为tcp流量直接分流进入naive，udp流量通过链式代理进入代理服务器所在的vless（最外层是naive），然而该设置启动后不久naive就出现断流问题，经测试只要分流dns流量无论是使用tcp请求直接进入naive还是udp经过vless封装后进入naive都会导致断流，naive客户端日志显示Connection closed: ERR_TIMED_OUT，而将dns协议分流至其他协议的其他服务器后naive断流大幅减少，concurrency选项无缓解。使用的DNS服务器是adguardhome，每次解析域名时会并发请求2个上游dns服务器。
为了方便观察，接下来的日志对应的架构均是通过链式代理进入代理服务器所在的vless（也就是日志中的127.0.0.1:55555）
客户端：naive 107.0.5304.87
[服务端配置](https://paste.ubuntu.com/p/2J5qfqTZRr)
[客户端配置](https://paste.ubuntu.com/p/fC7tty35qm)
[客户端日志](https://paste.ubuntu.com/p/f93xq485KJ)
[客户端网络日志](https://github.com/kmb21y66/dnf44k2ky2cg756p/raw/main/net.zip)
[服务端日志](https://paste.ubuntu.com/p/kDGYq6ThVt)

**Comment by qiangliu8183** [comment]
链接打不开

**Comment by kmb21y66** [comment]
> 链接打不开

谢谢，已修改

**Comment by klzgrad** [comment]
看起来是环境配置问题，这里无法解决
