### ISSUE TITLE
守护进程问题

### ISSUE THREAD

**Issue by dhslegen** [klzgrad/naiveproxy#397]
按教程一步一步来，直接执行没有问题，如下图

<img width="470" alt="image" src="https://user-images.githubusercontent.com/37139487/201628998-21ad2998-57d3-4e0c-b9ca-3fb2e67eac72.png">

<img width="967" alt="image" src="https://user-images.githubusercontent.com/37139487/201630456-47903270-2d6a-4a9f-b4da-337e5f426af7.png">

但创建守护进程访问就异常了，如下图

<img width="156" alt="image" src="https://user-images.githubusercontent.com/37139487/201631323-15443da1-a8ff-415d-889b-ae0a69d685ee.png">
<img width="641" alt="image" src="https://user-images.githubusercontent.com/37139487/201631044-e01a949a-8bd5-4a01-9651-15436897c94a.png">

```
OpenSSL: error:14077438:SSL routines:SSL23_GET_SERVER_HELLO:tlsv1 alert internal error
Unable to establish SSL connection.
```

配置文件如下：
```
{
       order forward_proxy before file_server
       http_port  800
       https_port 4430
}
:4430, mydomain.com {
        tls mydomain@163.com
        forward_proxy {
                basic_auth sd sdfsdgsd
                hide_ip
                hide_via
                probe_resistance
        }
        file_server {
                root /www/wwwroot/www.mydomain.com
        }
}
```

/etc/systemd/system/caddy.service 如下：
```
[Unit]
Description=Caddy
Documentation=https://caddyserver.com/docs/
After=network.target network-online.target
Requires=network-online.target

[Service]
User=caddy
Group=caddy
ExecStart=/usr/bin/caddy run --environ --config /etc/caddy/Caddyfile
ExecReload=/usr/bin/caddy reload --config /etc/caddy/Caddyfile
TimeoutStopSec=5s
LimitNOFILE=1048576
LimitNPROC=512
PrivateTmp=true
ProtectSystem=full
AmbientCapabilities=CAP_NET_BIND_SERVICE

[Install]
WantedBy=multi-user.target
```
请教各位大佬如何解决，谢谢

**Comment by dhslegen** [comment]
据我进一步观察，守护进程的caddy不会自动申请https证书或使用已有的证书，不知这是不是系统的问题

**Comment by klzgrad** [comment]
这个是caddy使用问题，与这里无关
