### ISSUE TITLE
本人的断流已经解决

### ISSUE THREAD

**Issue by q2051839** [klzgrad/naiveproxy#398]
本人的断流已经解决
总结：
1.获取了IPV6,
2.使用了1.1.1.1和2606:4700:4700::1111
3.使用了V2RAYN作为启动器并手动添加DNS服务器cloudflare-dns.com,
本人不知道哪条是生效的原因，反正是不断流了。。
经过：
一直服役的H3C路由（不支持IPV6）灰尘起码1厘米高了。。虽然还能在500m的宽带跑出580的速度，估计跑个千兆也有冗余。准备拆下来清清灰，突发奇想用了一直作为MESH使用了TP垃圾路由（500M光纤堪堪跑到500上下）作为主路由并获取了IPV6,然后整个傍晚到现在凌晨4点一次断流都没发生过。有遇到同样断流问题的可是试试获取IPV6或者修改DNS试试。
本人不懂技术。仅供同样被断流困扰的人参考。

**Comment by openips** [comment]
大流量试试 小流量一样不断

**Comment by Stormdd** [comment]
小火箭断流怎么解决。。
连的HTTP/2协议
TG刷20分钟左右的视频直接断网，需要关闭VPN重新打开才能连上代理
而且小火箭使用naiveproxy开启代理后有一个延迟时间，马上打开google是无网络的，需要重复刷新很多次后才正常
