### ISSUE TITLE
SSL证书校验错误问题

### ISSUE THREAD

**Issue by Jinnrry** [klzgrad/naiveproxy#399]
背景：第一次部署，使用了自签名证书。部署完毕后才知道Naive不能用自签名证书。于是去签发了一个letsencrypt证书。替换证书以后使用windos naive客户端连接正常使用。但是android SagerNet客户端和openwrt SSR plus 中均报错`[1119/140143.514065:ERROR:ssl_client_socket_impl.cc(996)] handshake failed; returned -1, SSL error code 1, net_error -101`

怀疑是NaiveProxy内部有缓存，android上面重装了应用，开关飞行模式，重启手机，均无法解决。 openwrt上面重启Naiveproxy进程，无法解决

**Comment by Jinnrry** [comment]
检查了很多遍，3端的配置文件完全一致。都是ssh连进去看的config文件，3端的naiveproxy版本也都是一样的。但是始终只用windows客户端可用

**Comment by Jinnrry** [comment]
检查了我域名的根证书，Windows 、 openwrt 、 Android这3端都是信任的。实在找不到哪里有问题了

**Comment by EthanSha** [comment]
naive可以自签的,config.json里面 tls项
```json:
{
    "tls": {
        "certificates": {
            "automate": [
                "xxxx.domain.xxx"
            ]
        }
    }
}
```

**Comment by Jinnrry** [comment]
> naive可以自签的,config.json里面 tls项
> 
> ```
> {
>     "tls": {
>         "certificates": {
>             "automate": [
>                 "xxxx.domain.xxx"
>             ]
>         }
>     }
> }
> ```

多谢提醒。我现在没用自签证书了，android 和 openwrt上面死活连不上，只有windows上面可以用，找不到原因

**Comment by klzgrad** [comment]
跟系统的Root CA信任有关，Let's Encrypt更换证书链可能在系统中缺少intermediate CA的信任，这个时候一般会去即时下载该intermediate CA的证书，如果下载失败则无法验证末端信任。需要结合前面的日志和NetLog查看此问题。

**Comment by Jinnrry** [comment]
> 跟系统的Root CA信任有关，Let's Encrypt更换证书链可能在系统中缺少intermediate CA的信任，这个时候一般会去即时下载该intermediate CA的证书，如果下载失败则无法验证末端信任。需要结合前面的日志和NetLog查看此问题。

重新做了一个实验

step 1、win11环境中，使用正常

step 2、使用该系统的WSL开了一个ubuntu系统，ubuntu里面开启naiveproxy，然后连接失败。

ubuntu中测试结果

```
curl -x socks5://127.0.0.1:1080 https://www.baidu.com
curl: (35) OpenSSL SSL_connect: Connection reset by peer in connection to www.baidu.com:443
```
此时naiveproxy日志

```
[1119/183832.552731:INFO:naive_proxy_bin.cc(419)] Proxying via https://v.xxxx.com
[1119/183832.556055:INFO:naive_proxy_bin.cc(564)] Listening on 127.0.0.1:1080
[1119/183915.637818:INFO:naive_connection.cc(273)] Connection 1 to 39.156.66.14:443
[1119/183916.192534:ERROR:cert_issuer_source_aia.cc(135)] AiaRequest::OnFetchCompleted got error -101
[1119/183916.192644:ERROR:cert_verify_proc_builtin.cc(670)] CertVerifyProcBuiltin for v.xxxxx.com failed:
----- Certificate i=0 (CN=v.xxxx.com) -----
ERROR: No matching issuer found


[1119/183916.194096:ERROR:ssl_client_socket_impl.cc(982)] handshake failed; returned -1, SSL error code 1, net_error -202
[1119/183916.194222:INFO:naive_proxy.cc(192)] Connection 1 closed: ERR_PROXY_CERTIFICATE_INVALID
```

**Comment by Jinnrry** [comment]
> 那基本就是中间证书的问题了…

那这有啥办法修复吗？ 除了换证书？

**Comment by Jinnrry** [comment]
> `net_error -101`是因为取回中间证书时被RST打断了（日志没贴全）。如果是caddy生成的证书，只能自行处理证书了（我没用caddy，不知道为什么会缺失中间证书，可能是它的缺陷。自行把中间证书加上去。）…如果是使用certbot/acme.sh第三方工具生成的，使用生成的fullchain.pem。

我手动把我的证书放到系统证书里面去，现在能用了

**Comment by Jinnrry** [comment]
> > `net_error -101`是因为取回中间证书时被RST打断了（日志没贴全）。如果是caddy生成的证书，只能自行处理证书了（我没用caddy，不知道为什么会缺失中间证书，可能是它的缺陷。自行把中间证书加上去。）…如果是使用certbot/acme.sh第三方工具生成的，使用生成的fullchain.pem。
> 
> 我手动把我的证书放到系统证书里面去，现在能用了

但是android上面依然用不了。我猜是安卓现在不信任用户证书，只信任系统根证书

**Comment by klzgrad** [comment]
fullchain的意思是caddy提供给客户端的证书应该包含中间CA的证书，这样客户端就不需要另行获取该中间CA的证书。怎样生成这种证书请自行查询。

**Comment by kzklot** [comment]
> 感谢两位的解答，我换了证书提供商，重装签了一个证书，现在能用了

換了那個供應的? 謝

**Comment by Jinnrry** [comment]
> > 感谢两位的解答，我换了证书提供商，重装签了一个证书，现在能用了
> 
> 換了那個供應的? 謝

用的阿里云的证书。确实是中间证书缺失导致的。你可以google搜索“证书链检查”，有很多在线工具可以直接检查，如果检查出来是这个问题，找中间证书补齐工具一下就行了
