### ISSUE TITLE
UDP穿透不了Socks5

### ISSUE THREAD

**Issue by kousyougi** [klzgrad/naiveproxy#40]
區網的電腦做TPROXY透明代理，TCP可以正常連出去。但UDP發出去都沒有回應。無法nslookup。

平台是OpenWrt X86-64，NaiveProxy架的Socks5，
用ipt2socks當作橋梁做純TPROXY透明代理。
發現TCP可以透明代理過去。UDP透明代理無回應。
交叉比對其他的Socks5搭配ipt2socks可以讓UDP穿透過去。

我目前用 https-dns-proxy 把DNS查詢流量轉成TCP直接送到NavieProxy的Socks5，使用尚不受影響。

謝謝

**Comment by tomac4t** [comment]
之前已经回复过你了：https://github.com/klzgrad/naiveproxy/issues/36#issuecomment-582331812

**Comment by klzgrad** [comment]
`--listen=redir://:1080`会在udp 1080端口上开放一个域名解析器，你可以试一试

**Comment by kousyougi** [comment]
謝謝
我試了，現在可以正常透明代理上網。反應時間很好。

**Comment by klzgrad** [comment]
澄清一下，我说的这个用法设计中只需要iptables规则，不需要ipt2socks和https-dns-proxy这些额外的组件。

这样：
```
iptables -A POSTROUTING ... -p tcp -m multiport --dports 80,443 -j REDIRECT --to-ports 1080
iptables -A POSTROUTING ... -p udp --dport 53 -j REDIRECT --to-ports 1080
./naive --listen=redir://0.0.0.0:1080 --proxy=...
```

但是这个1080端口dns解析出来是假的地址，一般没问题，可能在重启的前后有短暂缓存的问题
