### ISSUE TITLE
go build github.com/lucas-clemente/quic-go: /usr/local/go/pkg/tool/linux_amd64/compile: signal: terminated

### ISSUE THREAD

**Issue by hiifeng** [klzgrad/naiveproxy#402]
Hello, my go version is 1.19.3. When building with the following command, an error is prompted.

root@ifeng:~# go version
go version go1.19.3 linux/amd64

root@ifeng:~# ~/go/bin/xcaddy build --with github.com/caddyserver/forwardproxy@caddy2=github.com/klzgrad/forwardproxy@naive
......
go: downloading github.com/spaolacci/murmur3 v1.1.0
go: downloading github.com/golang/groupcache v0.0.0-20210331224755-41bb18bfe9da
go: downloading github.com/googleapis/enterprise-certificate-proxy v0.0.0-20220520183353-fd19c99a87aa
2022/11/24 03:08:44 [INFO] exec (timeout=0s): /usr/local/go/bin/go build -o /root/caddy -ldflags -w -s -trimpath
go build github.com/lucas-clemente/quic-go: /usr/local/go/pkg/tool/linux_amd64/compile: signal: terminated
2022/11/24 03:08:49 [INFO] Cleaning up temporary folder: /tmp/buildenv_2022-11-24-0306.4090021060
2022/11/24 03:08:49 [FATAL] exit status 1

Can you give me some hints from the error message? thanks

**Comment by klzgrad** [comment]
I guess it was killed for oom.
