### ISSUE TITLE
Android client won't connect and says ERR_PROXY_CONNECTION_FAILED

### ISSUE THREAD

**Issue by NuLL3rr0r** [klzgrad/naiveproxy#403]
I've tested the same server and configuration on both Linux and Android. My Linux client connects and works, while on Android I get ERR_PROXY_CONNECTION_FAILED for every connection attempt. I've run directly from Termux with/without sudo and also the SagerNet plugin. None of them work and I see in the logs the ERR_PROXY_CONNECTION_FAILED error.

**Comment by Nyxil** [comment]
I can confirm that naive doesn't work on android with the following error

**Comment by klzgrad** [comment]
Can't repro; insufficient info for feedback
