### ISSUE TITLE
能静态编译一个mips64的么？

### ISSUE THREAD

**Issue by zhangbo8418** [klzgrad/naiveproxy#405]
能静态编译一个mips64的么？我想把它- 弄到er-4上试试😊

**Comment by klzgrad** [comment]
不能，big endian的平台都不支持

**Comment by zhangbo8418** [comment]
> 不能，big endian的平台都不支持

是啥原因呢？mips64的用octeon工具链也不行么？https://archive.openwrt.org/chaos_calmer/15.05.1/octeon/generic/

**Comment by klzgrad** [comment]
https://github.com/klzgrad/naiveproxy/wiki/OpenWrt-Support Chrome does not support big-endian
