### ISSUE TITLE
About Caddy v1.x QUIC PATCH

### ISSUE THREAD

**Issue by triggered96** [klzgrad/naiveproxy#406]
Looking for a patch on https://github.com/klzgrad/naiveproxy/wiki/Caddy-with-QUIC . The reason is that I have a very special environment and can only use caddy 1.0 (please don’t ask why, I am also very helpless in special environments ). At present, I want to seek the QUIC PATCH of caddy v1.0 or v0.x, but the author deleted it, please release it. At present, I have used the old version of naive in one end environment.

It is also due to some reason in the environment, and it is particular.

**Comment by triggered96** [comment]
I also know that Caddy v1.x is too old, but I really encountered a special environment, so I beg to release the deleted wiki. https://github.com/klzgrad/naiveproxy/wiki/Caddy-with-QUIC

**Comment by klzgrad** [comment]
I don't know. You can download the wiki as a git repo and check for history. Otherwise I never created any patch for caddy.
