### ISSUE TITLE
请问有什么办法在本地编译？ 我把代码放到本地，然后在本地编译 caddy

### ISSUE THREAD

**Issue by crazypeace** [klzgrad/naiveproxy#408]
大佬！fork了你的forwardproxy，然后自己改了点代码。
然后用
`~/go/bin/xcaddy build --with github.com/caddyserver/forwardproxy@caddy2=github.com/crazypeace/forwardproxy@naive`
去编译，但是好像获取不到我刚刚提交的代码。
请问有什么办法在本地编译？ 我把代码放到本地，然后在本地编译 caddy

**Comment by klzgrad** [comment]
https://github.com/caddyserver/xcaddy#custom-builds
