### ISSUE TITLE
Run Caddy as a daemon

### ISSUE THREAD

**Issue by hiifeng** [klzgrad/naiveproxy#409]
Hi all, I see that the condition to run Caddy as a daemon contains systemctl --version >= 232. (https://github.com/klzgrad/naiveproxy/wiki/Run-Caddy-as-a-daemon)
My server operating system is CentOS 7, systemctl version is 219.The Caddy daemon is also running fine.
When the systemctl version is lower than 232, what problems will the Caddy daemon process have during operation? thanks

**Comment by klzgrad** [comment]
I cannot answer systemd support questions.
