### ISSUE TITLE
为何要一直使用naiveproxy最新版本?

### ISSUE THREAD

**Issue by phyzhenli** [klzgrad/naiveproxy#413]
我没有学过计算机网络的内容，手册说要一直使用naiveproxy最新版本，我有点不太理解原因。

因为我测试即使naiveproxy的版本和chrome的版本**不同**也可以work。

保持最新版本应该是保持naiveproxy的版本和chrome的版本**一致**吧？而不是单纯使用最新版本naiveproxy？

**Comment by klzgrad** [comment]
周期性更新版本有助于改善功能性能，应对变化，保持与chrome一致。
