### ISSUE TITLE
如何升级或者更新服务器的版本了

### ISSUE THREAD

**Issue by wazzx** [klzgrad/naiveproxy#415]
谢谢[klzgrad](https://github.com/klzgrad)做出来如此好的项目，我这边目前也搭建成功了，但是目前更新到108了我搭建的时候服务器是107那如何更新了
还是只要再执行一下
```
go install github.com/caddyserver/xcaddy/cmd/xcaddy@latest
~/go/bin/xcaddy build --with github.com/caddyserver/forwardproxy@caddy2=github.com/klzgrad/forwardproxy@naive
```
这个代码就可以了吗，我的配置文件`/etc/caddy/Caddyfile`还需要更改吗！
然后再执行`caddy run`和`caddy start`吗
逻辑不清楚，还望见谅谢谢开发者thx

**Comment by klzgrad** [comment]
不需要更新caddy
