### ISSUE TITLE
http.log.error	http2: stream closed

### ISSUE THREAD

**Issue by willia444** [klzgrad/naiveproxy#417]
感谢大佬所做的一切。
请教一下racknerd的vps上 ubuntu20.04 ubuntu22.04 debian11 ./caddy run 一切正常，但一旦有连接就会报以下错误，使用起来时断时续。同样的操作在其他主机商就没有问题，请问有可能是什么地方出了问题呢？

2022/12/05 04:02:55.647	ERROR	http.log.error	http2: stream closed	{"request": {"remote_ip": "123.174.86.148", "remote_port": "58498", "proto": "HTTP/2.0", "method": "CONNECT", "host": "i.ytimg.com:443", "uri": "i.ytimg.com:443", "headers": {"Accept-Encoding": ["identity"], "User-Agent": ["nghttp2/1.39.2"], "Proxy-Authorization": []}, "tls": {"resumed": false, "version": 772, "cipher_suite": 4865, "proto": "h2", "server_name": "www.test.xyz"}}, "duration": 11.533225384}

**Comment by ayanami-desu** [comment]
你的域名，本地ip都泄露了。

**Comment by openips** [comment]
赶快该日志吧 删了也行

**Comment by glieselab** [comment]
> 你的域名，本地ip都泄露了。

谢谢关心，那些都改过了，并非真实的。

**Comment by willia444** [comment]
> 你的域名，本地ip都泄露了。

谢谢关心，那些都改过了，并非真实的。

**Comment by ayanami-desu** [comment]
> > 你的域名，本地ip都泄露了。
> 
> 谢谢关心，那些都改过了，并非真实的。

我的服务器也是racknerd，使用一段时间后就连不上，重启客户端就又正常。这种问题之前issues里有人提过，好像没什么办法

**Comment by willia444** [comment]
> 

好的，谢谢

**Comment by willia444** [comment]
> > > 你的域名，本地ip都泄露了。
> > 
> > 
> > 谢谢关心，那些都改过了，并非真实的。
> 
> 我的服务器也是racknerd，使用一段时间后就连不上，重启客户端就又正常。这种问题之前issues里有人提过，好像没什么办法

好的，谢谢

**Comment by klzgrad** [comment]
stream closed不是一个错误
