### ISSUE TITLE
It is diffcult to reboot openwrt with naiveproxy

### ISSUE THREAD

**Issue by csquya** [klzgrad/naiveproxy#419]
I think it's my fault, but I do not know how to fix it.
I download naiveproxy for openwrt and unzip it, then copy it to my route.
I sipmplely run it by a script when openwrt boot.
However, when I reboot openwrt on GUI, my route can not reboot as expected.
I have to ssh into route to find out the pid of naviveproxy and kill it, then the "reboot" order I gave before will continue to proceed.
Any suggestion？ 
Or is there any ipk install package and luci to use the naiveproxy? Thanks.

有没有openwrt的安装包和设置界面，以及如何更优雅地自启动和关闭？ 谢谢大家。

**Comment by klzgrad** [comment]
报告意思不清
