### ISSUE TITLE
./caddy run --config /etc/caddy/Caddyfile 只绑定到ipv6地址 

### ISSUE THREAD

**Issue by VirtumartOz** [klzgrad/naiveproxy#421]
google搜了下 增加了bind 0.0.0.0但没效果 

/etc/caddy/Caddyfile：

:8443, www.xxxx.com
bind 0.0.0.0
tls aaaa@126.com
route {
  forward_proxy {
    basic_auth me me
    hide_ip
    hide_via
    probe_resistance
  }
  file_server {
        root /var/www/html
        }
}

netstat -tlnp|grep 443 输出：
[root@racknerd-a39015 ~]# netstat -tlnp|grep 443
tcp6       0      0 :::443                  :::*                    LISTEN      6381/./caddy
tcp6       0      0 :::8443                 :::*                    LISTEN      6381/./caddy

**Comment by VirtumartOz** [comment]
问题解决了

**Comment by CharlesCCC** [comment]
@VirtumartOz 请问怎么解决的?
