### ISSUE TITLE
ERR_QUIC_PROTOCOL_ERROR error

### ISSUE THREAD

**Issue by howxcheng** [klzgrad/naiveproxy#426]
使用quic就会报错 ERR_QUIC_PROTOCOL_ERROR，查询日志是TLS握手错误（TIMEOUT），且在caddy端debug根本没有收到请求，用http3check查询了下发现HTTP3支持但QUIC不支持，换了nginx-quic反而HTTP3和QUIC都支持，感觉是服务端的问题

**Comment by klzgrad** [comment]
这个只能自己debug

**Comment by toshiya14** [comment]
出现过一样的问题，QUIC 用不了，但是 https 可以。
检查一下防火墙是不是只放行了 TCP:443 。
QUIC 使用的底层是 UDP，所以 UDP:443 也需要放行。
