### ISSUE TITLE
handshake failed; returned -1, SSL error code 1, net_error -101

### ISSUE THREAD

**Issue by NadiaGarcia6** [klzgrad/naiveproxy#427]
Hi

There has been strong censorship in Iran and NaiveProxy official client gets this error "handshake failed; returned -1, SSL error code 1, net_error -101" and we cannot use it anymore.
However, ShadowRocket client does not have any problems to connect to the NaiveProxy server as it uses uTLS.

Do you have any plans to add uTLS feature?

Regards,

![image](https://user-images.githubusercontent.com/119847856/207239509-5d9882e0-c36a-4c37-9df0-b37a24cc3154.png)

**Comment by klzgrad** [comment]
It is not possible to add utls here.
