### ISSUE TITLE
if # in the password, naiveproxy does not work

### ISSUE THREAD

**Issue by tuhailong** [klzgrad/naiveproxy#429]
1. if # in the password, naiveproxy does not work, such as Navie_#_Proxy
2. Navie_^_Proxy works well

**Comment by shenlijun** [comment]
@好像也不行

**Comment by klzgrad** [comment]
True, but not a bug.

**Comment by SodaWithoutSparkles** [comment]
does quoting it works?

    basic_auth alice "Navie_#_Proxy"
