### ISSUE TITLE
403 forbidden

### ISSUE THREAD

**Issue by apcac** [klzgrad/naiveproxy#430]
when i try the command 
it shows me this line of errors  at the end 

        google.golang.org/genproto/protobuf/field_mask: google.golang.org/genproto@v0.0.0-20220617124728-180714bec0ad: reading https://proxy.golang.org/google.golang.org/genproto/@v/v0.0.0-20220617124728-180714bec0ad.zip: 403 Forbidden
2022/12/16 17:55:33 [FATAL] exit status 1

**Comment by mahdimoh1** [comment]
hi thre is this issue, what can i di ?
