### ISSUE TITLE
Bridge native proxy?

### ISSUE THREAD

**Issue by usefss** [klzgrad/naiveproxy#432]
I know this maybe not the place to ask this, but is there any way to bridge naiveproxy? like the bridge option in [https://www.v2ray.com/en/configuration/reverse.html](v2ray)? and if so is there any step by step and clear documentation to configure naiveproxy with it?

**Comment by klzgrad** [comment]
Could not understand the question.

**Comment by usefss** [comment]
@klzgrad I mean if we can have any of these with naiveproxy and any documentation related to these: 
```
Traffic flow with bridge server:
    Client =(stable connection with internal network)=> bridge naiveproxy server(internal server with more resilient network provider) =(more stable connection with outside world than normal mobile ISPs)=> upstream naiveproxy server
Or even better with an internal CDN infrastructure([!390](https://github.com/klzgrad/naiveproxy/issues/390)):
    Client =(best route and best node)=> CDN infra ==> upstream naiveproxy server
```
As if you ask yourself what a normal client will achieve with this setup there are two points: 
1. Connections bridged internally have more stability than normal ISPs
2. Islamic republic of Iran has been using internet kill switch on normal ISPs often, although not using this kill switch on most of data centers
And thank you for contributing to freedom of internet.

**Comment by klzgrad** [comment]
Naiveproxy proxy can accept inbound protocols including socks5 and http connect. The inbound socks5 can be password protected. It can send outbound protocols including sock5 and https. These are the available elements that can be used to create proxy chains.
