### ISSUE TITLE
How to build aarch64 openwrt version?

### ISSUE THREAD

**Issue by maskedeken** [klzgrad/naiveproxy#44]
don't know how to cross compile using ninja

**Comment by maskedeken** [comment]
I built the binary successfully using openwrt-sdk-19.07.1-armvirt-64_gcc-7.5.0_musl.Linux-x86_64 as sysroot-build, but when I ran it on openwrt, it said:

-ash: ./naive: not found

and ldd said:
/lib/ld-linux-aarch64.so.1 (0xffff91533000)
libnss3.so => /usr/lib/libnss3.so (0xffff91041000)
libnssutil3.so => /usr/lib/libnssutil3.so (0xffff91006000)
libnspr4.so => /usr/lib/libnspr4.so (0xffff90fc0000)
libgcc_s.so.1 => /lib/libgcc_s.so.1 (0xffff90f9e000)
libc.so => /lib/ld-linux-aarch64.so.1 (0xffff91533000)
libplc4.so => /usr/lib/libplc4.so (0xffff90f8a000)
libplds4.so => /usr/lib/libplds4.so (0xffff90f77000)

**Comment by klzgrad** [comment]
A openwrt x86_64 build was add using these two changes: https://github.com/klzgrad/naiveproxy/commit/349b4e4531219c6869a7d79e75f424c9018cc03d https://github.com/klzgrad/naiveproxy/commit/f7ce953587a058ed7828fec988dcd779619a58f5 if you can figure it out. I'll get around to add this build by weekend.

**Comment by maskedeken** [comment]
> 
> 
> A openwrt x86_64 build was add using these two changes: [349b4e4](https://github.com/klzgrad/naiveproxy/commit/349b4e4531219c6869a7d79e75f424c9018cc03d) [f7ce953](https://github.com/klzgrad/naiveproxy/commit/f7ce953587a058ed7828fec988dcd779619a58f5) if you can figure it out. I'll get around to add this build by weekend.

got it, thanks a lot. I can build it and ran it on arm64 openwrt now

**Comment by klzgrad** [comment]
Did you make this change? 

```diff
diff --git a/src/get-openwrt.sh b/src/get-openwrt.sh
index 0ce461c01..4378e7bc3 100755
--- a/src/get-openwrt.sh
+++ b/src/get-openwrt.sh
@@ -23,8 +23,8 @@ for flag in ALL_NONSHARED ALL_KMODS ALL SIGNED_PACKAGES; do
 done
 make oldconfig
 make
-full_root=staging_dir/toolchain-${arch}_gcc-${gcc_ver}_musl
-cp -r staging_dir/target-${arch}_musl/usr $full_root
+full_root=staging_dir/toolchain-*_gcc-${gcc_ver}_musl
+cp -r staging_dir/target-*_musl/usr $full_root
```

I found the path for armvirt is `toolchain-aarch64_generic_gcc-7.5.0_musl`, which was unexpected.

**Comment by klzgrad** [comment]
The build for openwrt arm64 is uploaded to https://github.com/klzgrad/naiveproxy/releases/tag/v80.0.3987.87-2.

Report again if this build doesn't work.
