### ISSUE TITLE
服务端配置好了，客户端无法翻墙

### ISSUE THREAD

**Issue by nonconformistqi** [klzgrad/naiveproxy#441]
服务端配置好了：
:443, example.com
tls youremail@example.com
route {
  forward_proxy {
    basic_auth yourname pass
    hide_ip
    hide_via
    probe_resistance
  }
   reverse_proxy https://example2.com {
    header_up Host {upstream_hostport}
  }
}

电脑打开网址，可以正常访问反向代理的网站，但是naive客户端连接后，无法正常上网。
请问有大神遇到类似问题吗？
我有另一个服务器，配置和这个一样就是网址不同，能正常上网。

**Comment by nonconformistqi** [comment]
有没有可能是tls申请证书出现问题

**Comment by zedifen** [comment]
可以看下 caddy 输出的日志提示了什么

**Comment by nonconformistqi** [comment]
请问查看日志的代码是什么，caddyfile比较简单，没有写日志输出的路径

**Comment by nonconformistqi** [comment]
systemd 启动 caddy没有报错，我下载了和网站模板，
:443, example.com
tls youremail@example.com
route {
  forward_proxy {
    basic_auth yourname pass
    hide_ip
    hide_via
    probe_resistance
  }
  file_server {
    root /var/www/html 
  }
}
网站可以正常访问，但是还是无法翻墙

**Comment by zedifen** [comment]
~~首先假设应用中的 Caddyfile 是改掉了 example.com 的~~

查看日志的话得看这个 caddy 是怎么运行的，如果是按照仓库 Wiki 里面的方法配了 systemd，那就可以用 `journalctl -xeu caddy.service` 看看；当然方法不唯一，用 `man` 看看用法或者 Google 一下都是可以的

**Comment by nonconformistqi** [comment]
Dec 31 05:02:40 443.tk caddy[1297]: {"level":"info","ts":1672480960.0252683,"msg":"using provided configuration","config_file":"/etc/caddy/Caddyfile","config_adapter":""}
Dec 31 05:02:40 443.tk caddy[1297]: {"level":"info","ts":1672480960.0298138,"logger":"admin","msg":"admin endpoint started","address":"localhost:2019","enforce_origin":false,"origins":["//l>
Dec 31 05:02:40 443.tk caddy[1297]: {"level":"info","ts":1672480960.0305731,"logger":"http","msg":"server is listening only on the HTTPS port but has no TLS connection policies; adding one >
Dec 31 05:02:40 443.tk caddy[1297]: {"level":"info","ts":1672480960.0309107,"logger":"http","msg":"enabling automatic HTTP->HTTPS redirects","server_name":"srv0"}
Dec 31 05:02:40 443.tk caddy[1297]: {"level":"info","ts":1672480960.0305712,"logger":"tls.cache.maintenance","msg":"started background certificate maintenance","cache":"0xc0000e5810"}
Dec 31 05:02:40 443.tk caddy[1297]: {"level":"info","ts":1672480960.0331984,"logger":"tls","msg":"cleaning storage unit","description":"FileStorage:/root/.local/share/caddy"}
Dec 31 05:02:40 443.tk caddy[1297]: {"level":"info","ts":1672480960.0335844,"logger":"http","msg":"enabling HTTP/3 listener","addr":":443"}
Dec 31 05:02:40 443.tk caddy[1297]: {"level":"info","ts":1672480960.0340705,"msg":"failed to sufficiently increase receive buffer size (was: 208 kiB, wanted: 2048 kiB, got: 416 kiB). See ht>
Dec 31 05:02:40 443.tk caddy[1297]: {"level":"info","ts":1672480960.034472,"logger":"http.log","msg":"server running","name":"srv0","protocols":["h1","h2","h3"]}
Dec 31 05:02:40 443.tk caddy[1297]: {"level":"info","ts":1672480960.0341303,"logger":"tls","msg":"finished cleaning storage units"}
Dec 31 05:02:40 443.tk caddy[1297]: {"level":"info","ts":1672480960.0348885,"logger":"http.log","msg":"server running","name":"remaining_auto_https_redirects","protocols":["h1","h2","h3"]}
Dec 31 05:02:40 443.tk caddy[1297]: {"level":"info","ts":1672480960.0351565,"msg":"autosaved config (load with --resume flag)","file":"/root/.config/caddy/autosave.json"}
Dec 31 05:02:40 443.tk caddy[1297]: {"level":"info","ts":1672480960.0352817,"msg":"serving initial configuration"}
Dec 31 05:02:40 443.tk systemd[1]: Started Caddy.

**Comment by nonconformistqi** [comment]
看日志好像没什么问题，example.com改成了自己的域名，而且可以正常访问。

**Comment by nonconformistqi** [comment]
问题解决了，客户端proxy用quic，可以上网，之前是https，
至于为什么要这样还等各位大神解答

**Comment by nonconformistqi** [comment]
今天找到了错误日志

**Comment by nonconformistqi** [comment]
网站可以正常访问，443blog.cf,用cloudflare做的dns解析

**Comment by zedifen** [comment]
刚刚看了一下, 我这边的 Caddyfile 是这么写的:

```
{
  order forward_proxy before file_server
}
:443, my.example.com {
  tls me@example.com
  forward_proxy {
    basic_auth username password
    hide_ip
    hide_via
    probe_resistance
  }
  file_server {
    browse
    root /path/to/files
  }
}
```

Cloudflare DNS 没点小云朵, 如果开了的话可以关了试试 ?

**Comment by nonconformistqi** [comment]
cloudflare 没有开启cdn, Caddyfile应该没问题，因为网站可以访问。真的搞不懂哪里出问题了。
另一个vps配置一模一样，https代理没问题，但这个 vps只能用quic代理。
