### ISSUE TITLE
用手机流量可以正常连接,但是使用家庭宽带连不上

### ISSUE THREAD

**Issue by aquawius** [klzgrad/naiveproxy#444]
手机使用流量可以连接,电脑使用手机流量提供的热点可以连接,但是手机或电脑使用家庭宽带(移动和联通都试过,而且跨省测得)就出现不能正常连接的情况,(有少数时间家庭宽带可以正常连接).

能讨论下是运营商什么地方出现了限制或者说为什么会出现这种情况
下面是服务端配置
```
:443, fuck**********network.com
tls exap@exap.com
route {
 forward_proxy {
   basic_auth user_exp password
   hide_ip
   hide_via
   probe_resistance
  }
 reverse_proxy https://xxxxxxx.com {
   header_up  Host  {upstream_hostport}
   header_up  X-Forwarded-Host  {host}
  }
}
```

客户端: 
电脑: v2rayN + naiveproxy
手机: SagerNet + naive插件
协议都用的https

**Comment by aquawius** [comment]
我认为我这个问题可能和 #441 和 #443 的issue有关联

**Comment by ArcCal** [comment]
reverse_proxy 反代的是什么网站

Caddy反向代理敏感网站，会导致服务器很短时间内被封，在caddy 1时代就已经这样了

**Comment by aquawius** [comment]
> reverse_proxy 反代的是什么网站
> 
> Caddy反向代理敏感网站，会导致服务器很短时间内被封，在caddy 1时代就已经这样了

是一个带有国内备案的cloudreve站点

**Comment by aquawius** [comment]
还有一个值得说明的点,就是当代理不能正常连接的时候,访问域名,伪装的站点的可以正常的访问的

**Comment by aquawius** [comment]
不清楚为什么,现在家宽又能访问了,服务器那边一点没动.
