### ISSUE TITLE
v2rayN V6.0 Bug汇报

### ISSUE THREAD

**Issue by Highnoon8X** [klzgrad/naiveproxy#445]
1、点击“检查更新”“v2rayN”后，会检测并提示下载5.39版本；
2、对于NaiveProxy节点，会提示在文件夹 (D:\V2rayN\bin\naiveproxy) 下未找到Core文件 (文件名:xray, wxray, wv2ray, v2ray)，请下载后放入文件夹，下载地址: https://github.com/klzgrad/naiveproxy/releases，原压缩包里以包含Core文件，但仍无法正常启动，替换为官方版本后，仍报错无法启动。

**Comment by Bryan2333** [comment]
这个Bug应该提交到v2rayN那里

**Comment by zedifen** [comment]
所以 V2RayN 的无法找到 V2Ray Core 的问题，为什么会提到 Naïve Proxy 这边来？ 🤔

**Comment by zedifen** [comment]
我觉得一个可能的临时解决方案：可以尝试另行手动运行 Naïve Proxy，并建立一个 V2Ray 到 Naïve Proxy 侦听端口的 SOCKS 出站

**Comment by Highnoon8X** [comment]
> 这个Bug应该提交到v2rayN那里

提交错了，应该是放到V2rayN那里，不过V2rayN6.1版本之后，这个问题已经修复了。
