### ISSUE TITLE
Add HTTP/3 support

### ISSUE THREAD

**Issue by SodaWithoutSparkles** [klzgrad/naiveproxy#453]
Please add support for HTTP/3. Caddy server supports it, but the forward proxy plugin does not. Neither does the naive fork of forward proxy does. This may cause slowdowns as it tries to upgrade to HTTP/3 but failed, then fallback to HTTP/2. 

A test for HTTP/3 can be found at https://cloudflare-quic.com/

**Comment by klzgrad** [comment]
What do you mean it's not supported? https://github.com/klzgrad/forwardproxy/blob/naive/forwardproxy.go#L337

**Comment by SodaWithoutSparkles** [comment]
> This plugin enables Caddy to act as a forward proxy, with support for **HTTP/2.0 and HTTP/1.1 requests**. HTTP/2.0 will usually improve performance due to multiplexing.

Client ←HTTP/3→ Caddy ←**HTTP/2**→ Server

So the connection between client and caddy is HTTP/3, thats fine. This issue aims to address that the naive fork of forward proxy does not support HTTP/3 requests. Since the issue page of your fork of forward proxy is missing, I think it would be best to post the issue here.

**Comment by klzgrad** [comment]
> cause slowdowns as it tries to upgrade to HTTP/3 but failed, then fallback to HTTP/2

Who slows down? This is not how http/3 works. It does not fall back to h2 with slowdown.

The data link between caddy and upstream should be fairly reliable and low latency. H3 offers minimal benefit for this case.

**Comment by Lippiece** [comment]
Is this still relevant? Does this mean h3 is not supported with naive in the chain?
