### ISSUE TITLE
关于redir远程dns解锁失效的问题

### ISSUE THREAD

**Issue by triggered96** [klzgrad/naiveproxy#454]
naive 在 redir 模式下（本地），本地会先发出一个 DNS question（发一个 IP Packet），获取要连接的服务器的 IP 地址，然后naive直接向这个 IP 地址发起连接」。例如：
```
[0117/030858.793274:INFO:naive_connection.cc(272)] Connection 12 to 154.128.125.119:443
```
然而，如果远程代理服务器搭建了dns解锁流媒体，这种方式就会失效。

但如果 naive 在 http 模式下（本地），naive connection是携带有域名的。这意味远程代理服务器会获取到该域名，然后走dns流媒体解锁劫持。
```
[0117/030858.793274:INFO:naive_connection.cc(272)] Connection 12 to www.netflix.com:443
```

由于分流的实现依赖于 DNS，因此，当代理客户端与代理服务端之间通过 某种协议 建立隧道以后，必须传入域名而不是 IP，才能触发远端服务器的 DNS 解析行为、从而实现将流媒体部分请求分流给 SNI 代理服务器。反之，如果代理客户端传入的不是域名而是 IP，那么远端服务器则不需要进行 DNS 解析直接对该 IP 发起连接、无法实现分流。作者能否改进redir 模式，通过域名进行传递？ 

该功能似乎比较常用，毕竟现在到手的VPS原生解锁流媒体服务的少之又少，只能借助于dns解锁。naive 在本地 http 监听模式下，远程代理服务器dns流媒体解锁是正常的。但如果通过redir方式实现全局域网设备透明代理，就出现问题了。

**Comment by triggered96** [comment]
引入  https://blog.skk.moe/post/how-proxy-client-cause-netflix-unlock-to-fail/

由于分流的实现依赖于 DNS，因此，当代理客户端与代理服务端之间通过 某种协议 建立隧道以后，必须传入域名而不是 IP，才能触发远端服务器的 DNS 解析行为、从而实现将流媒体部分请求分流给 SNI 代理服务器。反之，如果代理客户端传入的不是域名而是 IP，那么远端服务器则不需要进行 DNS 解析直接对该 IP 发起连接、无法实现分流。

根据这个思路，我们就可以找到 DNS 解锁失效的两种可能原因：一种是流媒体的客户端的实现方式。流媒体的客户端可能内置了 DNS 解析、并在 DNS 解析完成后直接向 IP 发起 TCP 连接，代理客户端就无从得知连接的原始域名，那么就会将 IP 而不是域名发送给位于远端服务器上的代理服务端；另一种是代理客户端的实现。Clash 和 Surge 等代理客户端是可以将域名发送给远端服务器的，但是有一些代理客户端，在完成了 DNS 解析以后，并不会反推 TCP 连接的域名、而是直接将 IP 发送给远端服务器。
---------------------
本文著作权归作者 Sukka 所有。本文采用 CC BY-NC-SA 4.0 许可协议，商业转载请联系作者获得授权，非商业转载请注明出处。
作者：Sukka
来源：简析代理客户端导致的远端服务器流媒体 DNS 解锁失效的可能原因 | Sukka's Blog
链接：https://blog.skk.moe/post/how-proxy-client-cause-netflix-unlock-to-fail/

**Comment by triggered96** [comment]
实现：
代理客户端有以下几种方式反查 TCP 连接的域名：
通过 HTTP / SOCKS 方式接入代理客户端的，可以直接获取封装在 HTTP / SOCKS 中的域名
使用代理客户端提供的 redir 和 TUN 的，代理客户端可以通过截获 DNS question 反推 TCP 连接的目标域名

本文著作权归作者 Sukka 所有。本文采用 CC BY-NC-SA 4.0 许可协议，商业转载请联系作者获得授权，非商业转载请注明出处。
作者：Sukka
来源：简析代理客户端导致的远端服务器流媒体 DNS 解锁失效的可能原因 | Sukka's Blog
链接：https://blog.skk.moe/post/how-proxy-client-cause-netflix-unlock-to-fail/

**Comment by triggered96** [comment]
如果naive 在 redir 模式下（本地），通过截获 DNS question 反推 TCP 连接的目标域名，就好了

**Comment by xgmq** [comment]
naive 的 redir模式下有fakedns的功能，把DNS解析設定到udp:1080就可以了，這個方案還比較快。

如果你要分流的話，增加netflix在dnsmasq.conf的範例，1080 port 就是你 redir 設定的 port：

server=/fast.com/127.0.0.1#1080
server=/netflix.ca/127.0.0.1#1080
server=/netflix.com/127.0.0.1#1080
server=/netflix.net/127.0.0.1#1080
server=/netflixinvestor.com/127.0.0.1#1080
server=/netflixtechblog.com/127.0.0.1#1080
server=/nflxext.com/127.0.0.1#1080
server=/nflximg.com/127.0.0.1#1080
server=/nflximg.net/127.0.0.1#1080
server=/nflxsearch.net/127.0.0.1#1080
server=/nflxso.net/127.0.0.1#1080
server=/nflxvideo.net/127.0.0.1#1080
server=/netflixdnstest0.com/127.0.0.1#1080
server=/netflixdnstest1.com/127.0.0.1#1080
server=/netflixdnstest2.com/127.0.0.1#1080
server=/netflixdnstest3.com/127.0.0.1#1080
server=/netflixdnstest4.com/127.0.0.1#1080
server=/netflixdnstest5.com/127.0.0.1#1080
server=/netflixdnstest6.com/127.0.0.1#1080
server=/netflixdnstest7.com/127.0.0.1#1080
server=/netflixdnstest8.com/127.0.0.1#1080
server=/netflixdnstest9.com/127.0.0.1#1080
server=/netflixdnstest10.com/127.0.0.1#1080
server=/netflix.com.edgesuite.net/127.0.0.1#1080

然後 
建議順便把dnsmasq的緩存關閉。
cache-size=0
實測幾乎是沒出現連線錯誤過，速度也很快。

倒是通過代理解析真實的dns首次連結都很卡，各種握手搭配干擾可能要等五到十秒鐘才能把頁面打開。使用smartdns之類的工具緩存常訪問的網站會好一點，但serve-expired之後如果ip不同了，會卡更久。

**Comment by triggered96** [comment]
> naive 的 redir模式下有fakedns的功能，把DNS解析設定到udp:1080就可以了，這個方案還比較快。
> 
> 如果你要分流的話，增加netflix在dnsmasq.conf的範例，1080 port 就是你 redir 設定的 port：
> 
> server=/fast.com/127.0.0.1#1080 server=/netflix.ca/127.0.0.1#1080 server=/netflix.com/127.0.0.1#1080 server=/netflix.net/127.0.0.1#1080 server=/netflixinvestor.com/127.0.0.1#1080 server=/netflixtechblog.com/127.0.0.1#1080 server=/nflxext.com/127.0.0.1#1080 server=/nflximg.com/127.0.0.1#1080 server=/nflximg.net/127.0.0.1#1080 server=/nflxsearch.net/127.0.0.1#1080 server=/nflxso.net/127.0.0.1#1080 server=/nflxvideo.net/127.0.0.1#1080 server=/netflixdnstest0.com/127.0.0.1#1080 server=/netflixdnstest1.com/127.0.0.1#1080 server=/netflixdnstest2.com/127.0.0.1#1080 server=/netflixdnstest3.com/127.0.0.1#1080 server=/netflixdnstest4.com/127.0.0.1#1080 server=/netflixdnstest5.com/127.0.0.1#1080 server=/netflixdnstest6.com/127.0.0.1#1080 server=/netflixdnstest7.com/127.0.0.1#1080 server=/netflixdnstest8.com/127.0.0.1#1080 server=/netflixdnstest9.com/127.0.0.1#1080 server=/netflixdnstest10.com/127.0.0.1#1080 server=/netflix.com.edgesuite.net/127.0.0.1#1080
> 
> 然後 建議順便把dnsmasq的緩存關閉。 cache-size=0 實測幾乎是沒出現連線錯誤過，速度也很快。
> 
> 倒是通過代理解析真實的dns首次連結都很卡，各種握手搭配干擾可能要等五到十秒鐘才能把頁面打開。使用smartdns之類的工具緩存常訪問的網站會好一點，但serve-expired之後如果ip不同了，會卡更久。

您这种思路不错。但我还得考虑别的代理软件整合，比如v2和trojan，它们似乎都支持反查 TCP 连接的域名。

**Comment by xgmq** [comment]
> 
> 您这种思路不错。但我还得考虑别的代理软件整合，比如v2和trojan，它们似乎都支持反查 TCP 连接的域名。

你都要開v2了。乾脆把naiveproxy客戶端設成socks server。然後在v2裡面接上naiveproxy的socks，做那些複雜的整合。
這樣你只要用心研究v2的整合設定就好了。而且v2對各種複雜的方案比較成熟了。

**Comment by triggered96** [comment]
> 

这种方案我尝试过，的确可以。不过能少一层尽量少一层比较好。😁

**Comment by xgmq** [comment]
> 这种方案我尝试过，的确可以。不过能少一层尽量少一层比较好。😁

如果能少一層盡量少一層的話，就不要嗅探所有流量來查dns吧。

直接用udpspeeder多拉一條udp通道到vps查詢dns？
要整合其他代理就用iptables配ipset。這樣最省資源。而且互相獨立。

**Comment by triggered96** [comment]
> server=/fast.com/127.0.0.1#1080
> server=/netflix.ca/127.0.0.1#1080
> server=/netflix.com/127.0.0.1#1080
> server=/netflix.net/127.0.0.1#1080
> server=/netflixinvestor.com/127.0.0.1#1080
> server=/netflixtechblog.com/127.0.0.1#1080
> server=/nflxext.com/127.0.0.1#1080
> server=/nflximg.com/127.0.0.1#1080
> server=/nflximg.net/127.0.0.1#1080
> server=/nflxsearch.net/127.0.0.1#1080
> server=/nflxso.net/127.0.0.1#1080
> server=/nflxvideo.net/127.0.0.1#1080
> server=/netflixdnstest0.com/127.0.0.1#1080
> server=/netflixdnstest1.com/127.0.0.1#1080
> server=/netflixdnstest2.com/127.0.0.1#1080
> server=/netflixdnstest3.com/127.0.0.1#1080
> server=/netflixdnstest4.com/127.0.0.1#1080
> server=/netflixdnstest5.com/127.0.0.1#1080
> server=/netflixdnstest6.com/127.0.0.1#1080
> server=/netflixdnstest7.com/127.0.0.1#1080
> server=/netflixdnstest8.com/127.0.0.1#1080
> server=/netflixdnstest9.com/127.0.0.1#1080
> server=/netflixdnstest10.com/127.0.0.1#1080
> server=/netflix.com.edgesuite.net/127.0.0.1#1080

经过测试，发现您所提供的方案似乎有点问题。，比如将与ipset工作：
```
[0117/090229.499144:ERROR:naive_connection.cc(248)] Connection 10 to unresolved name for 100.64.0.33
[0117/090229.823874:ERROR:naive_connection.cc(248)] Connection 11 to unresolved name for 100.64.0.33
[0117/090229.847233:ERROR:naive_connection.cc(248)] Connection 12 to unresolved name for 100.64.0.33
[0117/090229.873325:ERROR:naive_connection.cc(248)] Connection 13 to unresolved name for 100.64.0.33
[0117/090229.990099:ERROR:naive_connection.cc(248)] Connection 14 to unresolved name for 100.64.0.33
[0117/090230.542792:ERROR:naive_connection.cc(248)] Connection 15 to unresolved name for 100.64.0.4
[0117/090230.740745:ERROR:naive_connection.cc(248)] Connection 16 to unresolved name for 100.64.0.4
[0117/090230.816254:ERROR:naive_connection.cc(248)] Connection 17 to unresolved name for 100.64.0.4
[0117/090230.829534:ERROR:naive_connection.cc(248)] Connection 18 to unresolved name for 100.64.0.4
[0117/090230.847229:ERROR:naive_connection.cc(248)] Connection 19 to unresolved name for 100.64.0.33
[0117/090231.905740:ERROR:naive_connection.cc(248)] Connection 20 to unresolved name for 100.64.0.4
[0117/090231.931973:ERROR:naive_connection.cc(248)] Connection 21 to unresolved name for 100.64.0.4
[0117/090249.363608:ERROR:naive_connection.cc(248)] Connection 22 to unresolved name for 100.64.0.4
[0117/090315.521867:ERROR:naive_connection.cc(248)] Connection 25 to unresolved name for 100.64.0.36
```

您如何解决？ 分流
```
    0     0 REDIRECT   tcp  --  *      *       0.0.0.0/0            0.0.0.0/0            match-set netflix dst redir ports 1235
    2   128 RETURN     all  --  *      *       0.0.0.0/0            0.0.0.0/0            match-set over_wan_ac dst
  130  8028 OVERWALL_WAN_FW  all  --  *      *       0.0.0.0/0            0.0.0.0/0            ! match-set china_v4 dst
```

**Comment by xgmq** [comment]
我看你解析出來都是100.64.0.0 表示你正在用fakedns。那你連ipset都不用用了。直接加一行
iptables -t nat -A PREROUTING -p tcp -d 100.64.0.0/10 -j REDIRECT --to-ports 1080
這樣所有奈飛的流量解析出來都在 100.64.0.0/10 範圍裡，然後都會被導到 1080 port。

**Comment by triggered96** [comment]
> 我看你解析出來都是100.64.0.0 表示你正在用fakedns。那你連ipset都不用用了。直接加一行 iptables -t nat -A PREROUTING -p tcp -d 100.64.0.0/10 -j REDIRECT --to-ports 1080 這樣所有奈飛的流量解析出來都在 100.64.0.0/10 範圍裡，然後都會被導到 1080 port。 導到1080 port之後，那些假ip會自動還原為domain name發到vps去，由你的vps去解析ip。

这个我知道，但是 naive 有时会返回 Connection 25 to unresolved name for 100.64.0.xx，导致奈飞无法继续访问

**Comment by xgmq** [comment]
我寫仔細一點好了

dnsmasq.conf：
server=/netflix.com/127.0.0.1#1080 # netflix 向 udp:1080查詢
server=/google.com/127.0.0.1#1081 # google 向 udp:1081查詢


naiveproxy要執行兩個：

{
  "listen": "redir://0.0.0.0:1080",
  "proxy": "https://user:password@vps1.domain.com:443",
  "resolver-range": "100.64.0.0/16"
}

{
  "listen": "redir://0.0.0.0:1081",
  "proxy": "https://user:password@vps2.domain.com:443",
  "resolver-range": "100.65.0.0/16"
}

防火牆要新增兩個規則：
iptables -t nat -A PREROUTING -p tcp -d 100.64.0.0/16 -j REDIRECT --to-ports 1080
iptables -t nat -A PREROUTING -p tcp -d 100.65.0.0/16 -j REDIRECT --to-ports 1081

這樣你的系統只需要能執行naiveproxy，dnsmasq跟iptables都是路由器內建的，不需要再安裝其他依賴。是最精簡的方案。

**Comment by triggered96** [comment]
> 我寫仔細一點好了
> 
> dnsmasq.conf： server=/netflix.com/127.0.0.1#1080 # netflix 向 udp:1080查詢 server=/google.com/127.0.0.1#1081 # google 向 udp:1081查詢
> 
> naiveproxy要執行兩個：
> 
> { "listen": "redir://0.0.0.0:1080", "proxy": "https://user:password@vps1.domain.com:443", "resolver-range": "100.64.0.0/16" }
> 
> { "listen": "redir://0.0.0.0:1081", "proxy": "https://user:password@vps2.domain.com:443", "resolver-range": "100.65.0.0/16" }
> 
> 防火牆要新增兩個規則： iptables -t nat -A PREROUTING -p tcp -d 100.64.0.0/16 -j REDIRECT --to-ports 1080 iptables -t nat -A PREROUTING -p tcp -d 100.65.0.0/16 -j REDIRECT --to-ports 1081
> 
> 這樣你的系統只需要能執行naiveproxy，dnsmasq跟iptables都是路由器內建的，不需要再安裝其他依賴。是最精簡的方案。

我试试看

**Comment by xgmq** [comment]
> > 我看你解析出來都是100.64.0.0 表示你正在用fakedns。那你連ipset都不用用了。直接加一行 iptables -t nat -A PREROUTING -p tcp -d 100.64.0.0/10 -j REDIRECT --to-ports 1080 這樣所有奈飛的流量解析出來都在 100.64.0.0/10 範圍裡，然後都會被導到 1080 port。 導到1080 port之後，那些假ip會自動還原為domain name發到vps去，由你的vps去解析ip。
> 
> 这个我知道，但是 naive 有时会返回 Connection 25 to unresolved name for 100.64.0.xx，未解析的域名（找不到该域名与虚构解析结果之间的映射关系），导致奈飞无法继续访问。

會不會是你dns開了緩存？naiveproxy裡正常有ip跟domain name的對應表。
naiveproxy找不到ip跟domain name 對應的紀錄。

你的naiveproxy重開的時候，DNS都要清一下緩存。

**Comment by triggered96** [comment]
> > > 我看你解析出來都是100.64.0.0 表示你正在用fakedns。那你連ipset都不用用了。直接加一行 iptables -t nat -A PREROUTING -p tcp -d 100.64.0.0/10 -j REDIRECT --to-ports 1080 這樣所有奈飛的流量解析出來都在 100.64.0.0/10 範圍裡，然後都會被導到 1080 port。 導到1080 port之後，那些假ip會自動還原為domain name發到vps去，由你的vps去解析ip。
> > 
> > 
> > 这个我知道，但是 naive 有时会返回 Connection 25 to unresolved name for 100.64.0.xx，未解析的域名（找不到该域名与虚构解析结果之间的映射关系），导致奈飞无法继续访问。
> 
> 會不會是你dns開了緩存？naiveproxy裡正常有ip跟domain name的對應表。 naiveproxy找不到ip跟domain name 對應的紀錄。
> 
> 你的naiveproxy重開的時候，DNS都要清一下緩存。

嗯嗯

**Comment by triggered96** [comment]
> > > 我看你解析出來都是100.64.0.0 表示你正在用fakedns。那你連ipset都不用用了。直接加一行 iptables -t nat -A PREROUTING -p tcp -d 100.64.0.0/10 -j REDIRECT --to-ports 1080 這樣所有奈飛的流量解析出來都在 100.64.0.0/10 範圍裡，然後都會被導到 1080 port。 導到1080 port之後，那些假ip會自動還原為domain name發到vps去，由你的vps去解析ip。
> > 
> > 
> > 这个我知道，但是 naive 有时会返回 Connection 25 to unresolved name for 100.64.0.xx，未解析的域名（找不到该域名与虚构解析结果之间的映射关系），导致奈飞无法继续访问。
> 
> 會不會是你dns開了緩存？naiveproxy裡正常有ip跟domain name的對應表。 naiveproxy找不到ip跟domain name 對應的紀錄。
> 
> 你的naiveproxy重開的時候，DNS都要清一下緩存。

似乎还是有问题， 之前我也尝试过fakedns。我已经把dnsmasq的缓存大小设置为0，但还是会出现Connection 25 to unresolved name for 。 

我感觉还是从程序上进行改进比较好

**Comment by klzgrad** [comment]
讨论结束了
