### ISSUE TITLE
PC端客户端连接wifi时无法链接，连接手机热点时可以正常访问

### ISSUE THREAD

**Issue by schumacher267** [klzgrad/naiveproxy#458]
如题，有几个现象：
1. 家中的PC端在wifi环境下使用客户端无法连接网络，浏览器标签页一直显示加载中。
2. 手机客户端是安卓，SagerNet，可以正常访问网络。
3. 家中的PC端在手机热点的环境下使用客户端时是可以正常访问google等网络，且速度正常。
4. 公司的PC端可以正常使用客户端访问到google等网络。

请问会是网络的问题吗？如果是的话，要如何规避呢？我尝试在PC端使用quic协议，发现完全不行，如下是我客户端的caddy file配置。请问是哪里出错了吗？

{
    "admin": {
        "disabled": true
    },
    "logging": {
        "sink": {
            "writer": {
                "output": "discard"
            }
        },
        "logs": {
            "default": {
                "writer": {
                    "output": "discard"
                }
            }
        }
    },
    "apps": {
        "http": {
            "servers": {
                "srv0": {
                    "listen": [
                        ":443"
                    ],
                    "routes": [
                        {
                            "handle": [
                                {
                                    "handler": "forward_proxy",
                                    "hide_ip": true,
                                    "hide_via": true,
                                    "auth_user_deprecated": "name",
                                    "auth_pass_deprecated": "password",
                                    "probe_resistance": {
                                        "domain": ""
                                    }
                                }
                            ]
                        },
                        {
                            "match": [
                                {
                                    "host": [
                                        "example.com",
                                        "www.example.com"
                                    ]
                                }
                            ],
                            "handle": [
                                {
                                    "handler": "file_server",
                                    "root": "/var/www/html"
                                }
                            ],
                            "terminal": true
                        }
                    ],
                    "tls_connection_policies": [
                        {
                            "match": {
                                "sni": [
                                    "example.com",
                                    "www.example.com"
                                ]
                            }
                        }
                    ]
                }
            }
        },
        "tls": {
            "automation": {
                "policies": [
                    {
                        "subjects": [
                            "example.com",
                            "www.example.com"
                        ],
                        "issuers": [
                            {
                                "email": "youremail@example.com",
                                "module": "acme"
                            }
                        ]
                    }
                ]
            }
        }
    }
}

**Comment by crazypeace** [comment]
如果 同一个节点，有的客户端可以使用，而有的不行，那说明问题不在节点上。
你的PC在使用wifi的时候，你测试一下网络环境能不能访问到你的节点的IP 或者伪装域名？

**Comment by crazypeace** [comment]
你可以使用这个方法测试一下你的客户端配置文件 以及你的服务端配置 有没有问题
https://zelikk.blogspot.com/2022/12/naive-proxy-troubleshoot.html

**Comment by zedifen** [comment]
对, 请运用控制变量法, 这应该是中国大陆义务教育阶段要求掌握的技能.

对于每个环境, 先测试能否连接到 VPS 上; URL 测试比较准确:

- 如果 VPS 已经配置了 Naive Proxy, 那么在浏览器中 (不经过代理) 访问对应的域名能够正常打开网页就说明配置没有问题, 再查看日志, 如果没有相关提示, `forward_proxy` 也应该正常工作;
- 如果还没有配置 Naive Proxy, 则可以临时使用比如 Node.js 的 `http-server`, 启动一个 HTTP 服务器, 用于调试.

如果出现无法访问的问题, 则可能是 IP 或域名被墙. 

1. 域名被墙: 比如购买并使用的域名之前被 GFW 屏蔽过. 先测试不使用域名, 直接通过 IP 能否访问到主机. 如果可以, 则说明域名被墙, 请考虑更换域名;
1. IP 被墙: 给 VPS 换个 IP 试试.

解决完服务器端的问题之后:

考虑到某些运营商存在 QoS 限制的可能, 对于每个环境, 尝试分别使用 HTTPS 和 QUIC 协议连接到服务器, 选择可以使用的协议进行连接.

根据提到的情况, 可以列一个表格:

<table>
<tr><td>客户端\网络环境</td><td>家庭WiFi</td><td>公司网络</td><td>移动数据(手机热点)</td></tr>
<tr><td>PC</td><td>QUIC: ❌ HTTPS: ❔</td><td>QUIC: ❔HTTPS: ✅</td><td>QUIC: ❔HTTPS: ✅</td></tr>
<tr><td>Phone</td><td>QUIC: ❔ HTTPS: ❔</td><td>QUIC: ❔HTTPS: ❔</td><td>QUIC: ❔HTTPS: ✅</td></tr>
</table>

由于不确定 Phone 在家庭 WiFi 下的访问性 (只提到可以访问), 所以不能断定是家庭 WiFi 的问题.

可以尝试完善这个表格, 以便观察可能存在问题的地方.

**Comment by zedifen** [comment]
另外, 请使用 Markdown 的代码块语法标记 JSON, 命令行输出, 或者可能出现的代码, 这可以使其中的空白得到保留, 便于阅读; 并尽可能标记出语言种类, 以便它们能够被正确高亮.

语法类似如下:

<pre><code>```json
{
  "name": "John Doe",
  "age": "23"
}
```</code></pre>

在一些项目中, 包含不规范的代码块的 Issue 或 Pull Request 可能会被直接关闭.

对于 JSON, 建议以良好的缩进进行展示. 在 Google 上搜索 "JSON Formatter" 即能得到提供 JSON 格式化功能的网站.

给出的 JSON 格式化如下:

```json
{
  "admin":{
    "disabled":true
  },
  "logging":{
    "sink":{
      "writer":{
        "output":"discard"
      }
    },
    "logs":{
      "default":{
        "writer":{
          "output":"discard"
        }
      }
    }
  },
  "apps":{
    "http":{
      "servers":{
        "srv0":{
          "listen":[
            ":443"
          ],
          "routes":[
            {
              "handle":[
                {
                  "handler":"forward_proxy",
                  "hide_ip":true,
                  "hide_via":true,
                  "auth_user_deprecated":"name",
                  "auth_pass_deprecated":"password",
                  "probe_resistance":{
                    "domain":""
                  }
                }
              ]
            },
            {
              "match":[
                {
                  "host":[
                    "example.com",
                    "www.example.com"
                  ]
                }
              ],
              "handle":[
                {
                  "handler":"file_server",
                  "root":"/var/www/html"
                }
              ],
              "terminal":true
            }
          ],
          "tls_connection_policies":[
            {
              "match":{
                "sni":[
                  "example.com",
                  "www.example.com"
                ]
              }
            }
          ]
        }
      }
    },
    "tls":{
      "automation":{
        "policies":[
          {
            "subjects":[
              "example.com",
              "www.example.com"
            ],
            "issuers":[
              {
                "email":"youremail@example.com",
                "module":"acme"
              }
            ]
          }
        ]
      }
    }
  }
}
```

**Comment by klzgrad** [comment]
Can't reproduce.
