### ISSUE TITLE
捐给大佬能不能交朋友 ๑乛v乛๑

### ISSUE THREAD

**Issue by Qlmuby** [klzgrad/naiveproxy#459]
![xDItQuUFu5](https://user-images.githubusercontent.com/55885455/215798238-8e5b8aa4-69a2-4bba-9bcf-88c95fb72ecd.png)
三大域之一啊，在对的人手里才能发挥出价值，大佬你要不要？

**Comment by hiifeng** [comment]
如果我是你，无偿捐出。
如果我是作者，我会在项目介绍里增加一个鸣谢，感谢热心网友Qlmuby，***，***等对项目发展提供的帮助。

**Comment by Qlmuby** [comment]
> 如果我是你，无偿捐出。 如果我是作者，我会在项目介绍里增加一个鸣谢，感谢热心网友Qlmuby，***，***等对项目发展提供的帮助。

对啊，我就是想无偿捐给大佬，感谢klzgrad大佬和Naive项目的贡献。

**Comment by ArcCal** [comment]
大佬肯定不会要的。
本项目的slogan是Make a fortune quietly。

**Comment by ayanami-desu** [comment]
> 
> 本项目的slogan是Make a fortune quietly。

naive，悄悄发财，原来真的是膜啊

**Comment by 2378** [comment]
@Qlmuby  dynadot用PayPal支付， 是不是只能从PayPal余额扣除，不能从银行卡扣除， 以前买过一次付款没成功， 再没这家买了

**Comment by Qlmuby** [comment]
> @Qlmuby dynadot用PayPal支付， 是不是只能从PayPal余额扣除，不能从银行卡扣除， 以前买过一次付款没成功， 再没这家买了

可以用支付宝啊，币种选择RMB就可以用支付宝支付了

**Comment by klzgrad** [comment]
Have a nice day.
