### ISSUE TITLE
Please support the release version of the freebsd operating system

### ISSUE THREAD

**Issue by right0808** [klzgrad/naiveproxy#461]
Please support the release version of the freebsd operating system.
thank you very much.

**Comment by Chilledheart** [comment]
It should be straightforward if you can build it from a live freebsd os.
For cross-compiling, you can start with sysroot: http://ftp.freebsd.org/pub/FreeBSD/releases/amd64/13.0-RELEASE/base.txz

**Comment by klzgrad** [comment]
Duplicate of #433.
