### ISSUE TITLE
Unable to Connect to Voice Channel on Discord using Naiveproxy

### ISSUE THREAD

**Issue by jyogyou** [klzgrad/naiveproxy#464]
Description:
I have been using Naiveproxy as a proxy to connect to Discord and use voice channels. However, I have been experiencing connection issues where the voice channel keeps disconnecting and reconnecting, and I am unable to pinpoint the source of the problem. This issue is not limited to Discord, as I have encountered the same problem with SagerNet and my OpenWrt router. I am unsure how to resolve this issue and would appreciate any help in troubleshooting and resolving this problem.

Thank you.

**Comment by Bryan2333** [comment]
try quic

**Comment by jyogyou** [comment]
> 

QUIC protocol still cannot traverse UDP full-cone NAT.
