### ISSUE TITLE
建议写清楚Dowload的是客户端，server部分注明需要编译，而且一般vps需要编译很久

### ISSUE THREAD

**Issue by fannwong001** [klzgrad/naiveproxy#468]
给的配置例子里面tls后面不是example.com，那是email地址，而且连最基本的证书路径也没有给。要么就建议人们去用一键脚本，否则浪费很多时间。

**Comment by artiga033** [comment]
xcaddy编译的时间不就是一个正常go项目的编译时间吗？不是很长。

> 那是email地址，而且连最基本的证书路径也没有给
Caddy最早就是以[自动HTTPS](https://caddyserver.com/docs/automatic-https)闻名的，要么给email自动签发，要么指定证书，只能二选一。

以上，我赞同写清楚 client 和 server 的区别，不过你提到的配置问题其实都能在[Caddy文档](https://caddyserver.com/docs/caddyfile/directives/tls#syntax)找到答案。

**Comment by klzgrad** [comment]
naive.exe 既是client，也是server。server前端可以是caddy，也可以不是caddy。
这个项目不支持一键脚本。请改用其他方案。

**Comment by fannwong001** [comment]
> xcaddy编译的时间不就是一个正常go项目的编译时间吗？不是很长。
> 
> 
> 
> > 那是email地址，而且连最基本的证书路径也没有给
> 
> 
> 
> Caddy最早就是以[自动HTTPS](https://caddyserver.com/docs/automatic-https)闻名的，要么给email自动签发，要么指定证书，只能二选一。
> 
> 
> 
> 以上，我赞同写清楚 client 和 server 的区别，不过你提到的配置问题其实都能在[Caddy文档](https://caddyserver.com/docs/caddyfile/directives/tls#syntax)找到答案。
> 
> 

有很多不了解caddy的，我只对nginx熟悉，一开始就把他给的配置放到一个config.json文件中，谁知道他是根据后缀名来读取不同格式的，而且也没有给出好的提示。然后用json格式配置证书路径、转发到nginx又是相当麻烦。

**Comment by fannwong001** [comment]
> naive.exe 既是client，也是server。server前端可以是caddy，也可以不是caddy。
> 
> 这个项目不支持一键脚本。请改用其他方案。

速度挺不错的。但是描述确实容易让人误解。

**Comment by fannwong001** [comment]
> naive.exe 既是client，也是server。server前端可以是caddy，也可以不是caddy。 这个项目不支持一键脚本。请改用其他方案。

大哥，你说的”“naive.exe 既是client，也是server”“？？我试过了naive就是客户端！当server是当客户端的server监听socks5或者http！

**Comment by ArcCal** [comment]
看来是不知道怎么当server

怎么当server可以参加美博园的文章

**Comment by fannwong001** [comment]
> 

你试过吗？他写的那个其实就是客户端啊，即使他写成服务，实际是做http代理服务，看一下--help也没有啊

**Comment by ArcCal** [comment]
> > 
> 
> 
> 
> 你试过吗？他写的那个其实就是客户端啊，即使他写成服务，实际是做http代理服务，看一下--help也没有啊

看美博园的文章就知道作者在说什么啦

**Comment by fannwong001** [comment]
> 

你说的是这个吗？https://allinfa.com/naiveproxy-caddy.html
里面的naive server（第十一条）是这样的：
{
"listen": "http://127.0.0.1:8080",
"padding": true
}
这个启动起来就是个http代理啊大哥
