### ISSUE TITLE
How to build mips Padavan version?

### ISSUE THREAD

**Issue by op69qs** [klzgrad/naiveproxy#47]
How to cross compile for mips Padavan version?
I build Padavan toolchain, but how to build naive use that

**Comment by klzgrad** [comment]
I don't know how to customize Padavan. libnss is also required and I don't know how to build libnss in Padavan. And it is not updated since 2018. Is it even maintained?

**Comment by vcarus** [comment]
Padavan is still the one of the most widely used router firmwares today, especially in China. Maintained on https://github.com/hanwckf/rt-n56u  
Sorry I don't know how to compile stuff. Just hope maybe there's a chance to have padavan verison of naiveproxy. 
Thanks.

**Comment by klzgrad** [comment]
It doesn't inspire my confidence that it is still using 3.4 kernel https://github.com/hanwckf/rt-n56u/tree/master/trunk/linux-3.4.x
