### ISSUE TITLE
Functional requirements: set the specified DNS query

### ISSUE THREAD

**Issue by triggered96** [klzgrad/naiveproxy#470]
Can you add a function to allow naive to query by setting the specified DNS to avoid the system layer. I know that chrome browser has this function. And I also saw that chromium has a corresponding api.
```
{
  "listen": "socks://127.0.0.1:1080",
  "proxy": "https://user:pass@domain.example",
  "dns":     "8.8.8.8",
  "log": ""
}
```

**Comment by ArcCal** [comment]
这个功能不错，期待

**Comment by klzgrad** [comment]
Question not clear. Which DNS query goes to where?

**Comment by triggered96** [comment]
> Question not clear. Which DNS query goes to where?

The chrome browser supports dns settings. As long as the socks proxy is used, as long as dns is set, query records will be made through the dns.

**Comment by klzgrad** [comment]
Naive looks up domain.example once at startup and does not look up other domain names later. In the example, who should send dns queries to 8.8.8.8?

**Comment by triggered96** [comment]
I seem to understand what you mean. But I use this kind of remote server, such as deploying on vps (ha+naive), 8.8.8.8 is an example. Avoid system dns queries.

**Comment by triggered96** [comment]
Another problem is `--host-resolver-rules="MAP proxy.example.com 1.2.3.4"`, it seems to be only applicable to proxy ip, specifying other such as *.openai.com will not work.
`--host-resolver-rules="MAP proxy.example.com 1.2.3.4, MAP *.openai.com 1.4.5.6, MAP xxxx.com 2.3.4.6"`

**Comment by klzgrad** [comment]
Answer this precisely: who should send dns queries to 8.8.8.8?

Afaik, naive does not.

**Comment by triggered96** [comment]
> Answer this precisely: who should send dns queries to 8.8.8.8?
> 
> Afaik, naive does not.


When the request passed by the client is a domain name instead of an ip, does the vps need to resolve the domain name into an ip, and then naive access the ip and the target website? And I don't want to query through the system level, but query through the dns specified by naive and return the resolved ip.

**Comment by triggered96** [comment]
Example,  Enter chrome://settings/privacy in the Chrome browser and press Enter.
Scroll to the bottom and click on "Advanced."
Under "Privacy and security," in the "Security" section, click on "Use a preset DNS server address."
Enter the IP address of the DNS server you want to use or select an existing DNS server list.
Click "Save" to save your changes.
Note that this method only affects DNS resolution in the Chrome browser.

**Comment by klzgrad** [comment]
> When the request passed by the client is a domain name instead of an ip, does the vps need to resolve the domain name into an ip, and then naive access the ip and the target website?

Domain names in proxy requests are all resolved remotely.
