### ISSUE TITLE
how would one pass ssl_config_for_origin (application_settings)

### ISSUE THREAD

**Issue by hasnat** [klzgrad/naiveproxy#478]
I am trying to access via server config, tls application_settings; alps ones, connected to ssl `SSL_add_application_settings`

is there way to pass config for this via config.json e.g. `ssl_config_for_origin.protos.h2.application_settings`; or am I understanding/mixing chromium-net/naiveproxy config wrong,

**Comment by klzgrad** [comment]
Why would you want this?

**Comment by hasnat** [comment]
Sorry for not adding references 

https://github.com/WICG/client-hints-infrastructure/blob/main/reliability.md#first-load-with-updated-server

Basically to add in accept_ch alps application_settings on h2/3 servers.

**Comment by hasnat** [comment]
Another ref supporting alps: (Nginx+borinssl) https://github.com/nginx/nginx/commit/54ff39c2f1d56c144f74e8605103bb29a2825596

**Comment by triggered96** [comment]
> 另一个支持 alps 的 ref：（Nginx+borinssl）[https://github.com/amtunlimited/BoringNginx ](https://github.com/amtunlimited/BoringNginx) [nginx/nginx@ 54ff39c](https://github.com/nginx/nginx/commit/54ff39c2f1d56c144f74e8605103bb29a2825596)

How to build it? Please give a specific plan.

**Comment by hasnat** [comment]
@klzgrad 
alps relvant bits would be use of `SSL_add_application_settings` passing per server a custom accept_ch
https://github.com/search?q=repo%3Aklzgrad%2Fnaiveproxy%20SSL_add_application_settings&type=code
https://github.com/nginx/nginx/commit/54ff39c2f1d56c144f74e8605103bb29a2825596#diff-cb8550d376ac709bf295d4989ad9d5214ce815b00da0ce232997e7f83d773394R925

@triggered96 
Dockerfile there is complete enough for steps needed, fetch appropriate commits as submoduled in repo.

**Comment by klzgrad** [comment]
> passing per server a custom accept_ch

Why?

**Comment by hasnat** [comment]
> > passing per server a custom accept_ch
> 
> 
> 
> Why?

To get appropriate client hints for upstreams on first request. Since this is linked to origin; for now am ignoring ssl handshaked clients which end up visiting multiple origins on same session.

**Comment by klzgrad** [comment]
I know what is accept_ch and what are client hints. But you have not answered my question.

If the answer remains the current form, my answer is it is not supported.

**Comment by hasnat** [comment]
Apologies if I haven't answered to "why?". Unsure what the exact question was. 
Ok for this to be not supported. Still love the naiveproxy👍

**Comment by klzgrad** [comment]
What is the use case, what is the relevance to circumvention. You can't ask for support for a particular implementation without justifying its user value.

**Comment by hasnat** [comment]
Use case is getting model client hints on first request. Not waiting on 2nd request. Only alps would allow that. Since it's supported in chromium and other ssl items e.g. Cert/key,timeouts etc are part of config why not also make tls application setting available to be configured.

**Comment by klzgrad** [comment]
> getting model client hints on first request

This is not a use case. This is the implementation you use to support a use case. And the use case is still not answered.

**Comment by hasnat** [comment]
> > getting model client hints on first request
> 
> This is not a use case. This is the implementation you use to support a use case. And the use case is still not answered.

apologies, yes; usecase is to leverage more than just sec-ch-ua-mobile in client-hints e.g. viewport/memory/wow64.. and respond with appropriate page+assets back, minimise serving of wrong assets on first page loads. 
Since our default asset set is desktop, this makes certain devices first page load costly + plenty wrong/to be redundant assets. Very next page then loads right assets but is treated as initial page load slowing things down.

**Comment by klzgrad** [comment]
Then the use case is irrelevant to circumvention because naiveproxy tunnels traffic but does not load page assets.
