### ISSUE TITLE
naiveproxy 怎么进行中继？

### ISSUE THREAD

**Issue by ysbreh** [klzgrad/naiveproxy#48]
本地网络 -> serverA ->serverB ->Global Internet

**Comment by klzgrad** [comment]
Local: naive --listen=... --proxy=https://serverA

serverA: caddy with upstream http://serverB

serverB: any forward proxy

**Comment by ysbreh** [comment]
> Local: naive --listen=... --proxy=https://serverA
> 
> serverA: caddy with upstream http://serverB
> 
> serverB: any forward proxy

Caddyfile：

domain1.net
{
root /var/www/html1
tls Email
forwardproxy {
basicauth user1 pass1
hide_ip
hide_via
probe_resistance
upstream http://127.0.0.1:1080
}
}
domain2.net
{
root /var/www/html2
tls Email
forwardproxy {
basicauth user2 pass2
hide_ip
hide_via
probe_resistance
upstream http://serverB
}
}

Configure the second Web site does not work

**Comment by klzgrad** [comment]
这个是你服务器上配置代理的问题，跟naive无关。
