### ISSUE TITLE
请教各位。在redir模式下，将udp 53端口的请求转发到 1080端口，nslookup为什么返回的是100.64.0.0地址

### ISSUE THREAD

**Issue by 82kg** [klzgrad/naiveproxy#481]
naive 使用 redir模式启动，在1080端口。

把dns流量转发到1080
iptables -t nat -A PREROUTING -p udp --dport 53 -j REDIRECT --to-ports 1080

nslookup google.com 192.168,2.89  返回 100.64.0.1

再添加 iptables -t nat -A PREROUTING -p tcp -d 100.64.0.0/10 -j REDIRECT  --to-ports 1080

nslookup www.google.com 192.168,2.89  返回 100.64.0.2

不知道怎么操作了。

**Comment by klzgrad** [comment]
如果不知道怎么用，可以不用，不影响其他功能。
