### ISSUE TITLE
自己编译的时候，怎么更换Chromium的版本

### ISSUE THREAD

**Issue by lp123sun** [klzgrad/naiveproxy#483]
naiveproxy现在使用的Chromium版本是111.0.5563.64，Chromium最新的版本是111.0.5563.111，怎么样可以使用111.0.5563.111自己编译呢？
有操作步骤或者教程么？

**Comment by lp123sun** [comment]
有没有可能增加一个EDGE的呢？

**Comment by klzgrad** [comment]
编译不同版本希望得到什么？

**Comment by lp123sun** [comment]
希望能在第一时间与新版本Chromium同步，希望和其他用naiveproxy的Chromium版本不一样

**Comment by klzgrad** [comment]
> 第一时间与新版本Chromium同步

有什么特殊需求？

> 希望和其他用naiveproxy的Chromium版本不一样

为什么？

**Comment by lp123sun** [comment]
naiveproxy更新Chromium版本频率并不高，每个Chromium大版本，基本上是固定的小版本吧。
一般用户安装chrome，带自动更新，很快就更新到新版本的chrome了。

**Comment by klzgrad** [comment]
看https://github.com/klzgrad/naiveproxy/blob/master/tools/import-upstream.sh 了解升级过程

**Comment by lp123sun** [comment]
> 看https://github.com/klzgrad/naiveproxy/blob/master/tools/import-upstream.sh 了解升级过程

修改了CHROMIUM_VERSION文件，生成的releases文件，好像就文件名是最新的，编译的代码好像还是旧的。
