### ISSUE TITLE
DNS resolving issue on Android if AAAA record is absent 

### ISSUE THREAD

**Issue by segfault-bilibili** [klzgrad/naiveproxy#484]
Sorry, I'm not sure whether it's appropriate to submit this issue here. It's actually a problem encountered with naive-plugin of SagerNet.

When connecting to a naive caddy server from some IPv4-only network, it seems that both A record and AAAA record have to be present.

Otherwise, the connection cannot be established normally. I cannot see any A query or response in Wireshark, what I can see is just AAAA queries and corresponding AAAA response (which contains only queries but not answers) replied by local carrier DNS server. This problem at least persists for some time.

**Comment by klzgrad** [comment]
Not an issue for here. Check the DNS server or resolver.
