### ISSUE TITLE
文档改进建议

### ISSUE THREAD

**Issue by kj54321** [klzgrad/naiveproxy#485]
1. 按文档安装时需要编译，乞丐版vps非常耗时，且会OOM Signal: killed process finished with exit code 1
，建议提供binary文件.
2. caddy配置文件未提供 自用SSL 证书样例，建议添加 自签名/已有证书方案.

**Comment by klzgrad** [comment]
https://github.com/klzgrad/naiveproxy/commit/12a6ba324f8bc147f3f7ba299e9264e68d2d1a25
