### ISSUE TITLE
question: differences between server hosting methods?

### ISSUE THREAD

**Issue by H4M5TER** [klzgrad/naiveproxy#487]
There mentioned 3 methods in the wiki:

1. standalone `naive` (behind any frontend)
2. `caddy` with modified `forwardproxy` plugin can be use since v84
3. no `naive` but `tinyproxy` is used in the [HAProxy Setup](https://github.com/klzgrad/naiveproxy/wiki/HAProxy-Setup) section.

I also found that the [sing-box](https://github.com/SagerNet/sing-box) support the naive inbound ([not outbound](https://sing-box.sagernet.org/faq/#naive-outbound)).
Is that means the client part is the main functionality of naive which simulates the chromium network stack and the server part only does the authentication?
I'm lack of prior knowledge. Any explanation will be appreciated.

**Comment by H4M5TER** [comment]
Another question:
Is it needed to configure SSL for the caddy (nginx/haproxy/...) before the naive?

**Comment by klzgrad** [comment]
standalone naive has traffic padding but no probe resistance.
caddy with modified forwardproxy has probe resistance and traffic padding.
haproxy has probe resistance but no padding.
tinyproxy had neither.

> configure SSL for the caddy (nginx/haproxy/...) before the naive?

what?

**Comment by H4M5TER** [comment]
Thank you for the detailed explanations.

Is `probe resistance` means redirect the traffic to mask site?

For `configure SSL`, I was tring to say `configure TLS` but mistaked the word.
When making TLS connections, it needs a recognized certificate.
And I need a domain to get a recognized certificate from CA.
Should I replace the `example.org` to a domain I owned and configured DNS?

This seems to be a weird question. Where is wrong?

**Comment by klzgrad** [comment]
> probe resistance

https://www.usenix.org/conference/foci20/presentation/frolov

> Should I replace the example.org to a domain I owned and configured DNS?

Yes, this is required in the naiveproxy architecture.
