### ISSUE TITLE
Blocked by chat.openai.com

### ISSUE THREAD

**Issue by mabodofutk** [klzgrad/naiveproxy#489]
Using naiveproxy can not access chat.openai.com starting today. VPS located in US.
Confirmed the website is fine and another vpn (not naiveproxy) can access it.
Screenshot:
![img](https://i.328888.xyz/2023/04/04/ib9bUZ.jpeg)
The masked ip address is indeed the vps's ip so proxy is ok.

**Comment by ArcCal** [comment]
显然不是chatgpt的问题

**Comment by zedifen** [comment]
I'd suggest people think twice before raising questions, which means that please keep the control variables when you think that there may be a issue and are about to submit it to naiveproxy.
