### ISSUE TITLE
 naiveproxy能否拒绝浏览器ip直连？

### ISSUE THREAD

**Issue by WROIATE** [klzgrad/naiveproxy#490]
naiveproxy的caddy配置需要监听:443端口，但是这样的话caddy不会校验host头，导致用户可直接通过ip连接服务器的站点（这种情况服务器是会返回证书的，证书中包含了域名信息）
naiveproxy理论上也是标准的https请求吗？我在删除caddy的:443后只保留example.com的配置，是无法连接的

**Comment by klzgrad** [comment]
监听:443是为了兼容forwardproxy插件。如果要检查host，可能要用JSON配置。我没有研究过，不知道。
