### ISSUE TITLE
kMaxPaddingSize = 255

### ISSUE THREAD

**Issue by diwenx** [klzgrad/naiveproxy#491]
Is there a reason for limiting the size of padding to a maximum of 255 bytes? If the purpose is to mask the inner TLS handshakes and prevent TLS over TLS detection, I am uncertain whether a padding scheme ranging from 0 to 255 bytes accomplishes that goal. For instance, even after padding, a Clienthello record is still significantly distinct from a Serverhello record, as their original sizes could differ by several thousand bytes.

I may be overlooking some aspect, such as potential performance issues or segmentation concerns. So I would appreciate any insights into why a padding range of [0, 255] is selected as default.

Thanks!

**Comment by klzgrad** [comment]
It's a basic, better than nothing padding scheme. Size under 255 requires only one byte to encode. It's easier to code.

Some randomness can already increase classification difficulty substantially. I was waiting to see if higher strength padding is needed in this space but apparently hasn't been the case.

Check the readme for more design rationale. It's a good thing to reinvent many easy to implement and varying padding schemes, even if imperfect.

**Comment by klzgrad** [comment]
Recent user reports indicate some more capable censorship systems are able to detect the padding format currently used. I will try to replace the current padding scheme in the near future.
