### ISSUE TITLE
The difference between sing-box and naiveproxy

### ISSUE THREAD

**Issue by U201413497** [klzgrad/naiveproxy#492]
What is the difference between naiveproxy implemented by sing-box and yours? For example, will traffic characteristics be more likely to be blocked?

**Comment by klzgrad** [comment]
https://github.com/SagerNet/sing-box/blob/dev-next/inbound/naive.go can be considered an equivalent to the server side backend https://github.com/klzgrad/forwardproxy. It has no equivalent to naive.exe the client side. It does not have a front end, thus is prone to active probing, or it may be implying the user needs set up a front end by themselves.
