### ISSUE TITLE
proxy配置https协议无效

### ISSUE THREAD

**Issue by DG9Jww** [klzgrad/naiveproxy#493]
在客户端配置文件如下：
```
{
  "listen": "socks://127.0.0.1:1080",
  "proxy": "https://username:password666@example.top"
}
```

然后怎么连都没用，在服务端查看端口情况：
![image](https://user-images.githubusercontent.com/84201009/231402330-a0b9e205-af25-46a5-8caa-6fac7c7eb3a1.png)
发现，caddy都是监听的IPv6（大家都这样吗？），于是我又把客户端proxy改成 quic协议，现在才可正常使用
```
{
  "listen": "socks://127.0.0.1:1080",
  "proxy": "quic://username:password666@example.top"
}
```

而且小火箭无论如何都连不上，只能在pc端配置socks代理

求助，哪里搞错了吗

**Comment by klzgrad** [comment]
不是一个bug，请自查。
