### ISSUE TITLE
SOCKS5 over HTTP/2?

### ISSUE THREAD

**Issue by Lingxi-Li** [klzgrad/naiveproxy#497]
SOCKS5 is versatile, supporting proxying both TCP and UDP traffic. Wonder whether it is a good idea to tunnel SOCKS5 in HTTP/2. Would this cause some outstanding traffic signature even with HTTP/2 pipelining and multiplexing? Or if we do this, it is no longer a *naive* proxy anymore?

**Comment by klzgrad** [comment]
You want to tunnel the payload of SOCKS5 in H2. Socks5 over H2 is pure overhead.

**Comment by Lingxi-Li** [comment]
Proxy is inherently connection oriented. There should be no way to tunnel connection-less UDP payload over a connection-oriented proxy without overhead.

On a second thought, the idea of SOCKS5 over H2 indeed does not make much sense. It invalidates the UDP nature and defeats the original motivation of the app to pick UDP. That said to proxy UDP in a meaningful way, the proxy protocol should be based on UDP as well with certain overhead to establish association/connection like SOCKS5 does.
