### ISSUE TITLE
Use HTTP/2 for local CONNECT inbounds

### ISSUE THREAD

**Issue by Lingxi-Li** [klzgrad/naiveproxy#498]
naiveproxy config is as below.

~~~
{
  "listen": "http://0.0.0.0:8080",
  "log": ""
}
~~~

I noticed that local HTTP CONNECT inbounds are using HTTP 1.1 not HTTP/2. Wonder whether it is possible to use HTTP/2 for these CONNECT inbounds so that client like browser only maintains a single connection to naiveproxy. Or is this something to be done on client side?

**Comment by klzgrad** [comment]
> browser only maintains a single connection to naiveproxy

Extra complexity for no gain.
