### ISSUE TITLE
Still release updates for SagerNet plugin?

### ISSUE THREAD

**Issue by Lingxi-Li** [klzgrad/naiveproxy#499]
I see latest doc has replaced SagerNet with [NekoBox](https://github.com/MatsuriDayo/NekoBoxForAndroid) for Android client. Will you keep releasing SagerNet plugin or we need to migrate to NekoBox to sync latest Chrome network stack on Android client?

**Comment by klzgrad** [comment]
NeboBox seems to be the successor to Matsuri which is a fork of SagerNet. Naive works as a plugin in these three UI apps, and can be updated separately from the apps. You don't have to migrate if the UI app still works but I imagine the dev would welcome you upgrade so it's easier to maintain.

I'll look into the release schedule for naive plugin.
