### ISSUE TITLE
"redir" support on Windows

### ISSUE THREAD

**Issue by Lingxi-Li** [klzgrad/naiveproxy#500]
I think the way "redir" works is similar to that of [mitmproxy transparent proxying](https://docs.mitmproxy.org/stable/howto-transparent/#transparent-proxying). That is, naive needs to talk to iptables to get the original destination IP and port. Two questions then follow.

1. "redir" is not currently supported on Windows, right?
2. If so, could naive support it by using [WinDivert](https://github.com/basil00/Divert) like [mitmproxy did](https://github.com/mitmproxy/mitmproxy/blob/main/mitmproxy/platform/windows.py)?

**Comment by klzgrad** [comment]
> naive needs to talk to iptables to get the original destination IP and port

It doesn't. It does very simple things:

https://github.com/klzgrad/naiveproxy/blob/900f316fde0c9b0d6aa08750b955b64bc23da9bf/src/net/tools/naive/naive_connection.cc#L233-L237

> using [WinDivert](https://github.com/basil00/Divert)

Too much complexity. naive.exe is just a single file, portable. This is better handled in a GUI client. Ask v2rayN or nekoray for ideas?

**Comment by Lingxi-Li** [comment]
Make sense. naive better remains simple and dedicated.
