### ISSUE TITLE
openwrt编译错误

### ISSUE THREAD

**Issue by wlk3773208** [klzgrad/naiveproxy#501]
openwrt环境，aarch64平台，错误如下：
touch /home/a/lede/build_dir/target-aarch64_generic_musl/naiveproxy-113.0.5672.62-1/.built_check
MAKEFLAGS="" /home/a/lede/staging_dir/host/bin/ninja  -j1 -C "/home/a/lede/build_dir/target-aarch64_generic_musl/naiveproxy-113.0.5672.62-1/src/out/Release" naive
ninja: Entering directory `/home/a/lede/build_dir/target-aarch64_generic_musl/naiveproxy-113.0.5672.62-1/src/out/Release'
ninja: error: loading 'build.ninja': No such file or directory
make[3]: *** [Makefile:116: /home/a/lede/build_dir/target-aarch64_generic_musl/naiveproxy-113.0.5672.62-1/.built] Error 1
make[3]: Leaving directory '/home/a/lede/feeds/small/naiveproxy'
time: package/feeds/small/naiveproxy/compile#0.14#0.03#0.17
    ERROR: package/feeds/small/naiveproxy failed to build.
make[2]: *** [package/Makefile:116: package/feeds/small/naiveproxy/compile] Error 1

**Comment by klzgrad** [comment]
这个日志不是这里的代码产生的，无法支持
