### ISSUE TITLE
偶尔断连，大佬进来看下情况

### ISSUE THREAD

**Issue by noahge** [klzgrad/naiveproxy#506]
客户端用的openwrt的passwall，手机上用的小火箭，这两种方式，包括不同的网络都试了，在断连的时候均连不上。情况如下，服务器端口未被封，caddy伪装的网站正常访问，感觉上只是forwardproxy失败了，服务器日志正常，错误也都是steam close或者client disconnect，出现故障后，短则几分钟，长则几小时，均可自行恢复。如果排查的话，从什么方面入手呢？

**Comment by remox** [comment]
+1

**Comment by sunlewuyou** [comment]
同样的情况，使用的v2rayN，出现明显变慢疑似断流时重启v2rayN中的节点服务又可恢复正常。

**Comment by ArcCal** [comment]
+1

**Comment by sunlewuyou** [comment]
@klzgrad caddy错误日志：

**Comment by fannwong001** [comment]
+1，近来很频繁，停用2小时以上会有这种情况，但是有时候没有，一台连不上时同一个wifi里的都连不上了，换成另一个移动网络连接没问题。感觉是长时间不使用时，客户端发送的心跳包导致的，此时客户端ip+服务端ip端口被墙，建议客户端长时间不用时可以自动断开连接。

**Comment by zhangbo8418** [comment]
我的443端口今早嘎了。。。哎。。。

**Comment by zhangbo8418** [comment]
感觉是因为这玩意儿更新导致的443被嘎，更新后启动有问题。。。Trace/breakpoint trap   (core dumped)

**Comment by TosakaRinYes** [comment]
反馈+1
使用时有v2rayN+naive时有断连现象，出现频率为几分钟-几小时不等，已经关闭了v2rayN的日志和naive的日志
切换到另一台服务器可以重新连上，不过一会儿后会继续断连，情况和上面描述的一样

**Comment by oit63** [comment]
看来上周是都有这种情况，但是这几天没有遇到了，或许是gfw在测试什么策略

**Comment by fannwong001** [comment]
> 看来上周是都有这种情况，但是这几天没有遇到了，或许是gfw在测试什么策略

现在是没有了，也没有升级。

**Comment by ArcCal** [comment]
+1

**Comment by U201413497** [comment]
+1,并且最近遇到手机流量无法使用，连接wifi就能使用。应该是不同的运营商有不同限制了。

**Comment by klzgrad** [comment]
https://github.com/klzgrad/naiveproxy/releases/tag/v114.0.5735.91-4test

增加了一个基本的大包拆小的策略，看看是否会产生变化。

**Comment by os9sur** [comment]
> https://github.com/klzgrad/naiveproxy/releases/tag/v114.0.5735.91-4test
> 
> 增加了一个基本的大包拆小的策略，看看是否会产生变化。

速度明显慢了很多

**Comment by HouCoder** [comment]
同样的问题，隔一段时间就断流，然后莫名其妙的过一会就又恢复过来了

**Comment by hsz0707** [comment]
The GFW (Great Firewall of China) has added a field, but its meaning is unknown.

**Comment by XiaoanHi** [comment]
https://github.com/caddyserver/caddy/issues/3896#issuecomment-1267575088 疑似Go的问题

**Comment by klzgrad** [comment]
No actionable information.

**Comment by m2acgi** [comment]
联通 naiveproxy 443 端口干扰严重，电信暂时正常。

**Comment by cloudzhong** [comment]
> 联通 naiveproxy 443 端口干扰严重，电信暂时正常。

我现在也是这个情况，我手机联通的，大部分时间连不上。家里电信连的上，手机用shadowsocks
