### ISSUE TITLE
大佬能否编译mac m系列芯片的包

### ISSUE THREAD

**Issue by liwei19920307** [klzgrad/naiveproxy#508]
苹果M系类处理的mac直接跑arm64的是有问题的

**Comment by ArcCal** [comment]
作者发布的预编译的naiveproxy-**-mac-arm64.tar.xz就可以泡在M芯片的mac上

**Comment by liwei19920307** [comment]
> 作者发布的预编译的naiveproxy-**-mac-arm64.tar.xz就可以泡在M芯片的mac上

找到了 版本太多了 被隐藏了 感谢
