### ISSUE TITLE
Using a self-signed certificate on Linux can result in SSL handshake failures. 

### ISSUE THREAD

**Issue by renjunbujin** [klzgrad/naiveproxy#509]
`[0513/065253.742659:ERROR:ssl_client_socket_impl.cc(992)] handshake failed; returned -1, SSL error code 1, net_error -213`

Web pages that use the certificate can be opened without any issues in the Chrome browser, and it works on macOS.

**Comment by klzgrad** [comment]
Any MITM can inject a forged self-signed certificate and there is no way to ensure your connection is secure if self-signed certificates are allowed in any way.
