### ISSUE TITLE
Question about FakeDNS implementation

### ISSUE THREAD

**Issue by Lingxi-Li** [klzgrad/naiveproxy#510]
naive implements a FakeDNS server in "redir" mode. This is fine for TCP connections that will be proxied. But what about UDP that are not proxied? DNS answer is used by host for both TCP and UDP outbounds. If UDP use fake IP and go direct outbound, they will fail. Wonder how naive handles this.

My thought on this is UDP should go to the proxy as well. For UDP inbounds, the proxy resolves the real IP, amends the packet (re-computes checksum if necessary) by replacing fake IP with real one, and finally puts to direct outbound.

**Comment by klzgrad** [comment]
UDP is not supported at all.
