### ISSUE TITLE
有办法级联代理吗

### ISSUE THREAD

**Issue by zhouxiong100** [klzgrad/naiveproxy#511]
有办法级联代理吗，比如从client->Server1->Server2->google.com

**Comment by yjw0628** [comment]
万能方法： 用 nginx 直接做个端口转发

**Comment by klzgrad** [comment]
Caddy forwardproxy有一个upstream的选项，可以实现你的需求

**Comment by univerioiln233** [comment]
upstream socks5h:127.0.0.1:23456

**Comment by zhouxiong100** [comment]
https://github.com/caddyserver/forwardproxy
