### ISSUE TITLE
[Question] Choosing between file_server and reverse_proxy in Caddyfile for camouflaging

### ISSUE THREAD

**Issue by alphajoza** [klzgrad/naiveproxy#512]
For camouflaging naiveproxy, in your example `Caddyfile`, you've used `file_server` to serve a sample html website (at `/var/www/html`). There are other examples in web that are using `reverse_proxy` to a known website (for example www.bing.com) for that purpose.

excerpt:
```
reverse_proxy  www.bing.com  {
   header_up  Host  {upstream_hostport}
   header_up  X-Forwarded-Host  {host}
  }
```

Given the nature and design goals of NaïveProxy, which one is more preferable?

**Comment by klzgrad** [comment]
Use your own blog, or e commerce websites as the front. Reverse proxying to bing.com creates a failed parrot: there is no change bing.com actually appears on your IP address.
