### ISSUE TITLE
简单写了个桌面客户端，会长期维护

### ISSUE THREAD

**Issue by topoge** [klzgrad/naiveproxy#514]
https://github.com/topoge/NgX/releases

主要是将naive二进制包装了一下配合clash.Meta支持规则和TUN模式

**Comment by triggered96** [comment]
> https://github.com/topoge/NgX/releases
> 
> 主要是将naive二进制包装了一下配合clash.Meta支持规则和TUN模式

代码能开源吗？

**Comment by klzgrad** [comment]
好

合并到 https://github.com/klzgrad/naiveproxy/issues/158
