### ISSUE TITLE
修改etc/hosts无法生效问题

### ISSUE THREAD

**Issue by xx-li** [klzgrad/naiveproxy#515]
### 环境
- vps: Linux yellow-hat-2.localdomain 4.9.0-12-amd64 #1 SMP Debian 4.9.210-1 (2020-01-20) x86_64
- client: Openwrt -- Psswall

### 问题
修改vps的`etc/hosts`， 添加一行`'172.31.255.2 chat.openai.com'`，执行ping后可以看到hosts修改已经生效。但是通过client代理访问时，vps本地`etc/hosts`的设置无法生效，请问我应该如何处理，让naiveproxy代理时，特定的域名走特定的IP进行访问？

**Comment by klzgrad** [comment]
client访问时，进行这个域名解析动作的是caddy server，应该重启caddy才能让服务器上的hosts生效

**Comment by xx-li** [comment]
我已经重启了vps，还是不行。 不知道是不是passwall把dns这块接管了，就没有走到caddy的域名解析？
