### ISSUE TITLE
Are there ways to support multiple users with Naiveproxy?

### ISSUE THREAD

**Issue by mshigemoto** [klzgrad/naiveproxy#517]
Thank you for sharing your great work.
I tried Naiveproxy. it works great.

I have a question. Does Naiveproxy support multiple users?
Multi-user is possible according to the description on the following page of your forwardproxy.
https://github.com/klzgrad/forwardproxy

However, with naiveproxy, I made the following settings. But I get an error as "_Error during parsing: Multi-user basicauth is not supported_".

```
   forward_proxy {
     basic_auth user1 pass1
     basic_auth user2 pass2
     hide_ip
     hide_via
     probe_resistance
   }
```

Q1
Are there ways to support multiple users with Naiveproxy?

Q2
If HAPROXY is used for authentication as frontend, will the anonymity of naiveproxy be kept?

Thank you.

**Comment by klzgrad** [comment]
Multi auth is being worked here https://github.com/caddyserver/forwardproxy/pull/99

Haproxy is fine with multi auth, but it needs a padding layer.

**Comment by mshigemoto** [comment]
Thank you for your responce!

**Comment by android1122** [comment]
你好，请问同一个forward_proxy可以设置不同用户对应不同的配置？

**Comment by mshigemoto** [comment]
＞你好，请问同一个forward_proxy可以设置不同用户对应不同的配置？

多用户支持目前正在准备中。 我们必须等待它的出版。

**Comment by zedifen** [comment]
One may want to discuss about further updates under #587.

**Comment by klzgrad** [comment]
Multiple auth is fixed here https://github.com/klzgrad/forwardproxy/releases/tag/v2.7.6-naive
