### ISSUE TITLE
support openwrt riscv64 arch?

### ISSUE THREAD

**Issue by MoetaYuko** [klzgrad/naiveproxy#518]
Recently, openwrt master branch introduced a new riscv64 architecture: https://github.com/openwrt/openwrt/blob/main/target/linux/sifiveu/Makefile, and the SDK is available at https://downloads.openwrt.org/snapshots/targets/sifiveu/generic/openwrt-sdk-sifiveu-generic_gcc-12.3.0_musl.Linux-x86_64.tar.xz

However, compiling naiveproxy against the SDK results in:
```
2023-05-29T21:59:35.4764501Z ERROR at //base/allocator/partition_allocator/partition_alloc.gni:22:3: Assertion failed.
2023-05-29T21:59:35.4764945Z   assert(false, "Unknown CPU: $current_cpu")
2023-05-29T21:59:35.4765418Z   ^-----
2023-05-29T21:59:35.4765629Z Unknown CPU: riscv64
```

Is it possible to enable compilation for riscv64?

**Comment by MoetaYuko** [comment]
Just to note, the error I reported above is fixed by https://github.com/chromium/chromium/commit/a140a4bc5d48356c78ab860c7c5426d2d1b41492 but there are a bunch of other errors, which means riscv64 support has not been fully merged into chromium yet.

**Comment by klzgrad** [comment]
No rushing here. It will be supported when upstreams support it

**Comment by klzgrad** [comment]
https://github.com/klzgrad/naiveproxy/releases/tag/v115.0.5790.166-1
