### ISSUE TITLE
ERR_CONNECTION_ABORTED

### ISSUE THREAD

**Issue by univerioiln233** [klzgrad/naiveproxy#519]
ERR_CONNECTION_ABORTED      ERR_CONNECTION_RESET
Firefox113.0.1 :network :SOCKS Host :Proxy DNS when using SOCKS v5=√;Enable DNS over HTTPS=×
config: network.dns.http3_echconfig.enabled=disable    network.http.http3.priority=disable

**Comment by klzgrad** [comment]
Can't understand
