### ISSUE TITLE
Does naiveproxy compatible with apache?

### ISSUE THREAD

**Issue by qingfengshi** [klzgrad/naiveproxy#52]
I read the wiki of naiveproxy and got that Caddy can work with naiveproxy. However, I have had apache2 server, does the naiveproxy compatible with apache2? Do you have any guide for this configuration?

**Comment by klzgrad** [comment]
The question to be asked is: Does Apache support HTTP/2 reverse proxying to HTTP/1.1? 

https://httpd.apache.org/docs/trunk/mod/mod_proxy_http2.html says no.

In a simplified setup, does Apache support HTTP/2 CONNECT forward proxying? Probably no.

**Comment by qingfengshi** [comment]
OK, thank you for your answer. 

Why does the naiveproxy not use HTTP/2? Will you update it to support HTTP/2 in future?
