### ISSUE TITLE
Naiveproxy with Haproxy, How can we set padding layer? 

### ISSUE THREAD

**Issue by mshigemoto** [klzgrad/naiveproxy#520]
You replied to me "Haproxy is fine with multi auth, but it needs a padding layer."
https://github.com/klzgrad/naiveproxy/issues/517

Does this mean that Haproxy needs to set padding option?
After looking through the Haproxy manual, I couldn't find a way to set the padding.

I would be happy to receive your advice.

In addition, the backend is NGINX, and Haproxy was successfully set up. However, Haproxy did not work with Naiveproxy even though I configured Naiveproxy on the same port.

**Comment by klzgrad** [comment]
> You can also use NaiveProxy as the forward proxy: nohup ./naive --listen=http://127.0.0.1:8080 &. Although as a proxy server it only works together with Naive client, not directly with the browser (only HTTPS works).

https://github.com/klzgrad/naiveproxy/wiki/HAProxy-Setup

**Comment by mshigemoto** [comment]
Thanks for the reply. Forgive my misunderstanding. I want to try it.
