### ISSUE TITLE
建立连接后无法访问内网地址？

### ISSUE THREAD

**Issue by ChainZeaxion** [klzgrad/naiveproxy#522]
如题
成功连接后，可通过中转访问网络
但无法访问server所在内网？
如果可以打开，请指明如何开启。

**Comment by klzgrad** [comment]
修改forwardproxy的acl设置

**Comment by ChainZeaxion** [comment]
> 修改forwardproxy的acl设置

                {
                  "handler": "subroute",
                  "routes": [
                    {
                      "handle": [
                        {
                          "auth_user_deprecated": "Zeaxion",
                          "auth_pass_deprecated": "cX153246",
                          "handler": "forward_proxy",
                          "hide_ip": true,
                          "hide_via": true,
                          "probe_resistance": {

                          }
                        }
                      ]
                    },


我这个配置上，怎么添加上呢

**Comment by zedifen** [comment]
How about referring to [the repo of naïveproxy's modified version of forwardproxy](https://github.com/klzgrad/forwardproxy)? It seems to have description on supported directives.
