### ISSUE TITLE
How to use it with js/go scripts to spoof tls/h2 fingerprint?

### ISSUE THREAD

**Issue by xsfunc** [klzgrad/naiveproxy#524]
I run naive with listen params.
Then I use it as proxy in my go script

```go
func proxy() {
	proxy, _ := url.Parse("http://192.168.1.207:1080") // naive listen address:port
	h := &http.Client{Transport: &http.Transport{Proxy: http.ProxyURL(proxy)}}
	r, err := h.Get(h2FingerUrl)
	if err != nil {
		log.Fatal(err)
	}
	defer r.Body.Close()
	io.Copy(os.Stdout, r.Body)
}
```
When I send request to check my http2 fingerprint, it not changed to chrome's fingerprint. Why it doesn't work?

Maybe you know tools where I can use chromium stack as proxy? For example I send to it req params (path, headers, cookie) and then It sends request with chromium cipher suits and h2 settings like chrome? Like Playwright/puppeteer but only to send requests.

**Comment by bjin** [comment]
what you need is a MITM proxy(which will decrypt and re-encrypt https traffic), instead of a proxyserver like naiveproxy

**Comment by klzgrad** [comment]
This is not supported right now. There is a plan to do it so other circumvention tools can reuse this feature but it is low priority.
