### ISSUE TITLE
SOCKS监听 CURL可以连接但是fifrefox不行

### ISSUE THREAD

**Issue by Riverboat8865** [klzgrad/naiveproxy#525]
我的系统是ubuntu20.04,本机网络设置系统代理http:127.0.0.1:10809， socks:127.0.0.1:10808。客户端配置如下：
```
{
  "listen": "socks://127.0.0.1:10808",
  "proxy": "https://XXXX:YYY@ZZZ.COM",
  "log": "error.log"
}
```

使用系统代理，firefox无法连接网络，显示
>The proxy server is refusing connections

error.log显示

>[0611/102445.798903:INFO:naive_proxy_bin.cc(561)] Listening on 127.0.0.1:10808

尝试手动设置代理，也不行。可是telegram手动设置socks proxy可以连接;命令行curl socks5也可以成功

```
curl --socks5 127.0.0.1:10808 google.com
<HTML><HEAD><meta http-equiv="content-type" content="text/html;charset=utf-8">
<TITLE>301 Moved</TITLE></HEAD><BODY>
<H1>301 Moved</H1>
The document has moved
<A HREF="http://www.google.com/">here</A>.
</BODY></HTML>
```
切换到http模式，设置"listen": "http://127.0.0.1:10809"。fifrefox可以正常浏览网页。

不知道哪里出了问题。

**Comment by Riverboat8865** [comment]
解决了，因为我同时设置了一个http proxy,浏览器优先使用http，但是不存在这个http proxy, socks proxy也不起作用。
请问有没有办法同时在config里面添加http和socks5 proxy。

**Comment by klzgrad** [comment]
现在没有办法，除了运行两个实例。
以后可以思考是否能支持。

**Comment by Riverboat8865** [comment]
> 

还有一个小问题， 我naiveproxy client -v查看版本号只有v114.0.5735.91， github上tag有 
v114.0.5735.91-3，v114.0.5735.91-2。这样一来无法自动比较，可否考虑把版本号命名规则更加标准化？ -

**Comment by klzgrad** [comment]
Duplicate of #526.
