### ISSUE TITLE
疑似Naiveproxy 被检测到并被阻止

### ISSUE THREAD

**Issue by sunlewuyou** [klzgrad/naiveproxy#527]
在运营商racknerd主机上部署了差不多个把月，前两天突然发现手机app上用于测试vpn连接的网址：http://cp.cloudflare.com/ 不通了，但是能连上vpn，google、youtube也都能访问，但是看油管视频明显卡顿缓冲要过好几秒甚至十几秒，所以抓包查看原因，发现打开一个视频时就有很多TCP重传包：
![image](https://github.com/klzgrad/naiveproxy/assets/19728435/0b151420-fcaf-4299-aa9c-8c073c1e736d)
以及更多的RST包：
![image](https://github.com/klzgrad/naiveproxy/assets/19728435/dbb4c2cf-7d74-48a3-9a7b-51878e6b065c)
现在只有racknerd上的是这种情况，别家主机上用了半年多了都正常。也是奇了怪了，还请各位大佬帮忙分析分析此类现象是什么原因导致的，或者指点一下方法自己如何去进一步判断是否是主机商的问题或是其他因素导致。谢谢！
@klzgrad

**Comment by klzgrad** [comment]
如果会用wireshark，在tcp连接的两端同时使用tcpdump保存流量，然后对比一下是否存在插入的tcp包。插入是指一方没有发出但是另外一方收到了。如果是中间人插入的包，一个常见特征是ttl与上下文不一致，但不保证会有这个特征。

**Comment by NirvanaKV** [comment]
RackNerd除了洛杉矶都是ColoCrossing机房的机器，访问Google很可能要人机验证

洛杉矶是MultaCom机房，一般不用人机验证，不过他家洛杉矶VPS涨价了，可以看看CloudCone，也是MC机房，更便宜点
