### ISSUE TITLE
请问如何在CONFIG.JSON中加入参数.

### ISSUE THREAD

**Issue by odesky** [klzgrad/naiveproxy#528]
您好.
 请问如何在CONFIG.JSON加入--host-resolver-rules="MAP proxy.example.com 1.2.3.4"这此参数?

**Comment by odesky** [comment]
{
      "listen": "...",
      "proxy": "...",
     "host-resolver-rules" : "MAP proxy.example.com 1.2.3.4"
 }

**Comment by Hearing-Loss** [comment]
您好，大佬我想请教一下您是怎么做转发的。我在中转机上用firewalld做端口转发，然后客户端配置里面加了"host-resolver-rules": MAP proxy.example.com IP地址"。proxy里面的端口也换成中转机对应的接收端口了，但我这种方法仍然无法连通。想问问您是用什么方法转发的。

**Comment by odesky** [comment]
> 您好，大佬我想请教一下您是怎么做转发的。我在中转机上用firewalld做端口转发，然后客户端配置里面加了"host-resolver-rules": MAP proxy.example.com IP地址"。proxy里面的端口也换成中转机对应的接收端口了，但我这种方法仍然无法连通。想问问您是用什么方法转发的。

=============================
您好,首先我不是大佬.我也是小白.
我的Naiveproxy是用sing-box实现的,不知会不会有什么影响.

firewalld做端口转发这一点你自己操作吧. 这个应该会吧.
我是用IPTABLES做的.

首先你需要确保你不做转发的情况下,可以使用NAIVE.
中转机: 1.1.1.1:88
落地机: abc.com:999  (原abc.com域名解析地址为: 2.2.2.2)
   ---中转机需要将 88端口的TCP(或所有流量)转发到 abc.com:999这里.


那么客户端CONFIG中则是:
{
"listen": "socks://127.0.0.1:8888",
"proxy": "https://user:password@abc.com:88/",     //注意这里的端口是中转机使用的端口.
"host-resolver-rules" : "MAP abc.com 1.1.1.1"        //这里是指把abc.com的IP改写为1.1.1.1
}

以上是我的个人理解.如有误导请见谅.
