### ISSUE TITLE
报Jun 25 00:14:24 instance-20230621-1837 caddy[31244]: {"level":"error","ts":1687652064.7104986,"logger":"http.log.error","msg":"stream 308 canceled  by remote with error code 268",这个错误。

### ISSUE THREAD

**Issue by KENAN1412** [klzgrad/naiveproxy#529]
环境：Ubuntu arm64
配置了quic，socks转发，用的是singbox
通过systemctl status caddy看到报
Jun 25 00:14:24 instance-20230621-1837 caddy[31244]: {"level":"error","ts":1687652064.7104986,"logger":"http.log.error","msg":"stream 308 canceled
 by remote with error code 268",错误，但是还能fq。这要不要管
![图片](https://github.com/klzgrad/naiveproxy/assets/77651819/8bf3add7-0a93-4d28-a2a7-87aa73661263)

**Comment by klzgrad** [comment]
不管
