### ISSUE TITLE
Any plan for supporting openwrt-armv7?

### ISSUE THREAD

**Issue by XueshiQiao** [klzgrad/naiveproxy#53]

**Comment by klzgrad** [comment]
Armv7 is too broad a concept. Choose an architecture from https://openwrt.org/docs/techref/targets/start.

Also, if you want a new build you need to prove there are actual users for it.

**Comment by XueshiQiao** [comment]
Thanks for you reply, I have a Linksys Router which is running on armv7 architecture, but I don't know whether or not other people have the same request as me.

I bought a Raspberry Pi one or two days ago, and I run navie proxy on it perfectly, so it's not necessay for me to run naive proxy on my router.
