### ISSUE TITLE
使用caddy v1配置多个naiveproxy节点时，同一端口时出现只有第一个能使用的问题。

### ISSUE THREAD

**Issue by U201413497** [klzgrad/naiveproxy#532]
caddy v1的配置文件如下：
test1.com:443  {
    gzip
    timeouts none
    tls /path/test1.com/certificate.crt /path/test1.com/private.key 
    forwardproxy {
      basicauth user1 password1 
      hide_ip
      hide_via
      probe_resistance secert.localhost
      upstream http://127.0.0.1:8080
    }
	proxy / https://example.com
}
test2.com:443  {
    gzip
    timeouts none
    tls /path/test2.com/certificate.crt /path/test2.com/private.key 
    forwardproxy {
      basicauth user2 password2  
      hide_ip
      hide_via
      probe_resistance secert.localhost
      upstream http://127.0.0.1:8080
    }
	proxy / https://example.com
}
 
naive监听8080端口，使用的是caddy v1,配置两个域名分别为test1.com和test2.com，同时在443端口，此时两个网站都能打开显示example.com，但是只有test1.com能作为naive节点连接上，test2.com连接显示ssl证书错误，无法使用。如果test2.com的端口从443改为8443，就可以在8443上正常使用naive节点。
我在其他博客上看到caddy多网站配置，https://marsgrid.com/post/a08_caddy/，我的配置都443端口应该也是没问题的，请问一下如何处理。难道是caddy v1版本的basicauth只能在第一个网站时起作用？

**Comment by klzgrad** [comment]
Caddy v1是不支持的用法
