### ISSUE TITLE
iOS 编译问题

### ISSUE THREAD

**Issue by arror** [klzgrad/naiveproxy#534]
期望是 naive 暴露启动、关闭接口，编译成 .a 静态库，并非编译为可执行文件。
打包静态库无需苹果开发者账号，测试可交给使用者。
目前对这个项目是如何编译，以及如何编译为静态库知之甚少，大佬可否指明方向😃

**Comment by klzgrad** [comment]
方向就在现在的编译步骤里面，如果想要可以自己改改
