### ISSUE TITLE
Caddy reports: " tls: first record does not look like a TLS handshake "

### ISSUE THREAD

**Issue by os9sur** [klzgrad/naiveproxy#535]
This bug occurs **only when using Caddy to automatically obtain the certificate**, but the website works fine,
but client's naiveproxy cannot handshake with the server, which is strange.

When I try to access Google from the client with naiveproxy, 
the caddy on the server reports this error: "tls: first record does not look like a TLS handshake"

However, when I set caddy to manually specify the certificates ,naiveproxy works fine.

Thank you for your excellent work!!!
Hope you take a look at this issue when you have time.

**Comment by klzgrad** [comment]
Don't know how to reproduce

**Comment by os9sur** [comment]
> Don't know how to reproduce

If the issue cannot reproduced then it should be a problem with my configuration file. 

After I modified the Caddyfile like this: 
":443, example.com {..." --> ":443, www.example.com, example.com {..."

It works fine now!

I should learn Caddy more carefully instead of applying the example mechanically.

Thank you again for your excellent technical ability and hard work!!!
