### ISSUE TITLE
[Request] Support for Gl.iNet OpenWRT devices

### ISSUE THREAD

**Issue by BaiqingL** [klzgrad/naiveproxy#54]
The Gl.iNet portable routers are pretty popular in use for travel.
I am using the GL-AR750S router and it is running LuCI openwrt-18.06
The output of uname -a is:
Linux GL-AR750S 4.9.120 #0 Thu Aug 16 07:51:15 2018 mips GNU/Linux

Could there please be client support on this platform?
Thanks!

**Comment by klzgrad** [comment]
OpenWrt 19.07+ is required for support.

After that we can discuss adding a build for mips 74kc.

**Comment by BaiqingL** [comment]
It seems like it does have OpenWRT 19.07+
https://openwrt.org/toh/gl.inet/gl-ar750s

**Comment by klzgrad** [comment]
I just recalled MIPS is not supported. Sorry, the main reason is Chrome is not supposed on big-endian platforms, especially in BoringSSL.

This cannot be supported.
