### ISSUE TITLE
Padding capability of XXX undetected

### ISSUE THREAD

**Issue by eightclawfisher** [klzgrad/naiveproxy#541]
服务端的操作系统是Alpine Linux 3.18
服务端是按照首页的介绍编译的，用的配置文件如下：
`{
	"apps": {
	  "http": {
		"servers": {
		  "srv0": {
			"listen": [":443"],
			"routes": [{
			  "handle": [{
				"handler": "forward_proxy",
				"hide_ip": true,
				"hide_via": true,
				"auth_user": "iamusername",
				"auth_pass": "iampassword",
				"probe_resistance": {}
			  }]
			}, {
			  "match": [{"host": ["www.aabbcc.top", "www.aabbcc.top"]}],
			  "handle": [{
				"handler": "file_server",
				"root": "/var/www/html"
			  }],
			  "terminal": true
			}],
			"tls_connection_policies": [{
			  "match": {"sni": ["www.aabbcc.top", "www.aabbcc.top"]}
			}]
		  }
		}
	  },
	  "tls": {
		"automation": {
		  "policies": [{
			"subjects": ["www.aabbcc.top", "www.aabbcc.top"],
			"issuer": {
			  "email": "admin@aabbcc.top",
			  "module": "acme"
			}
		  }]
		}
	  }
	}
  }`

客户端是最新的：
`#naive --listen="socks://192.168.1.1:1010" --proxy='https://iamusername:iampassword@www.aabbcc.top' --log
[0723/234045.156180:INFO:naive_proxy_bin.cc(419)] Proxying via https://www.aabbcc.top
[0723/234045.156679:INFO:naive_proxy_bin.cc(554)] Listening on 192.168.1.1:1010
[0723/234045.425807:INFO:naive_connection.cc(251)] Connection 1 to edge.microsoft.com:443
[0723/234046.227376:INFO:naive_proxy_delegate.cc(86)] Padding capability of https://www.aabbcc.top:443 undetected
[0723/234046.227523:INFO:naive_proxy.cc(182)] Connection 1 closed: ERR_TUNNEL_CONNECTION_FAILED
`

请问是什么原因？谢谢！

**Comment by eightclawfisher** [comment]
https://github.com/klzgrad/naiveproxy/releases/latest downloaded from here, it's running fine. 
 build from source will not work:
go install github.com/caddyserver/xcaddy/cmd/xcaddy@latest
~/go/bin/xcaddy build --with github.com/caddyserver/forwardproxy@caddy2=github.com/klzgrad/forwardproxy@naive

**Comment by klzgrad** [comment]
是用户的配置问题
