### ISSUE TITLE
无法以 HTTP 方式监听 80 端口

### ISSUE THREAD

**Issue by KanakoMikami** [klzgrad/naiveproxy#542]
`GURL` 在处理 HTTP URL 的时候，即使显式指定端口为 80，也会被当成默认端口去掉。

https://github.com/klzgrad/naiveproxy/blob/4b250049af5b887a500937e32d06ae5a163592ff/src/net/tools/naive/naive_proxy_bin.cc#L262-L272

此时这里的 `url.port()` 为空串，导致默认的 8080 端口被保留。

**Comment by klzgrad** [comment]
https://github.com/klzgrad/naiveproxy/releases/tag/v115.0.5790.166-1
