### ISSUE TITLE
config.json cann't work

### ISSUE THREAD

**Issue by eightclawfisher** [klzgrad/naiveproxy#543]
it is running fine with the command "naive '--listen=socks://192.168.1.1:1010' '--proxy=https://httpsuser:httppassword@xxx.xxx.xxx' --log ", but fail with the config.json:
{
  "listen": "socks://192.168.1.1:1010",
  "proxy": "https://httpsuser:httppassword@xxx.xxx.xxx",
  "log": "/var/log/naiveproxy.log"
}
the error log: [0727/074313.926800:INFO:naive_proxy.cc(182)] Connection 2 closed: ERR_TUNNEL_CONNECTION_FAILED

what is cause of this issue?

**Comment by klzgrad** [comment]
Not enough information.
