### ISSUE TITLE
[建议] 希望forwardproxy可以实现监听两个不同参数的域名

### ISSUE THREAD

**Issue by lushangkan** [klzgrad/naiveproxy#544]
caddy无法在两个不同的站点中分别添加forward_proxy，只能通过给站点添加多个域名

但有时需要配置两个站点和两套不同的配置

比如我可能需要一个站点直连，另一个添加upstream参数来连接上游代理（比如cloudflare warp）

有没有办法可以实现这种效果？非常感谢！

**Comment by klzgrad** [comment]
Caddy已经运行在远端了，不理解为什么还要域名路由。

这个需求应该去Caddy提。
