### ISSUE TITLE
Question : Connect to Server with IP

### ISSUE THREAD

**Issue by privatesupport** [klzgrad/naiveproxy#545]
Is it possible to connect to server with IP (+ SNI header) instead of domain?

Something like this : 

`{
    "proxy": "https://user:pass@ip:port",
    "extra-header": "host:domain.tld"
}`

I test this config but I get SSL Error.

**Comment by klzgrad** [comment]
See Chrome's documentation about `--host-resolver-rules` to map domain name to addresses.
