### ISSUE TITLE
naiveproxy配置导致caddy无法使用多域名

### ISSUE THREAD

**Issue by liwei19920307** [klzgrad/naiveproxy#546]
服务器caddy有多个域名的需求，但是只要配置了naiveproxy就没法正常使用，因为naiveproxy的写法是全局的导致配置其他域名caddy报错

Caddyfile 配置如下

```yaml
:443, aaa.com
route {
        forward_proxy {
                basic_auth admin password
                hide_ip
                hide_via
                probe_resistance
        }
        file_server {
        root /srv
        }
}

bbb.com {
        reverse_proxy http://127.0.0.1:1080
        encode gzip
}
```

bbb.com的域名配置后就报错 caddy 无法正常启动报

```
Did you mean to define a second site? If so, you must use curly braces around each site to separate their configurations.
```

**Comment by liwei19920307** [comment]
> 看上去配置文件写法有问题

没问题 去掉bbb.com的配置 caddy正常启动 客户端可以正常代理

**Comment by ArcCal** [comment]
这里已经说的很清楚啦
Did you mean to define a second site? If so, you must use curly braces around each site to separate their configurations.

每一个site的配置文件需要用{}括起来，类似这样：
:443, aaa.com {
        route {
        forward_proxy {
                basic_auth admin password
                hide_ip
                hide_via
                probe_resistance
        }
        file_server {
        root /srv
        }
}
}


bbb.com {
        reverse_proxy http://127.0.0.1:1080
        encode gzip
}


另外需要在全局设置里加上
order forward_proxy before reverse_proxy

**Comment by liwei19920307** [comment]
> 这里已经说的很清楚啦 Did you mean to define a second site? If so, you must use curly braces around each site to separate their configurations.
> 
> 每一个site的配置文件需要用{}括起来，类似这样： :443, aaa.com { route { forward_proxy { basic_auth admin password hide_ip hide_via probe_resistance } file_server { root /srv } } }
> 
> bbb.com { reverse_proxy http://127.0.0.1:1080 encode gzip }
> 
> 另外可能需要在全局设置里加上： order forward_proxy before reverse_proxy

感谢 可以了 之前试过加括号 但是我把443也去掉了 客户端日志没看到错 但是代理无效 所以443必须有 没搞懂为啥不能去443

**Comment by klzgrad** [comment]
Caddy使用问题

**Comment by Angel0726** [comment]
> 这里已经说的很清楚啦 Did you mean to define a second site? If so, you must use curly braces around each site to separate their configurations.
> 
> 每一个site的配置文件需要用{}括起来，类似这样： :443, aaa.com { route { forward_proxy { basic_auth admin password hide_ip hide_via probe_resistance } file_server { root /srv } } }
> 
> bbb.com { reverse_proxy http://127.0.0.1:1080 encode gzip }
> 
> 另外可能需要在全局设置里加上： order forward_proxy before reverse_proxy

order forward_proxy before reverse_proxy加到哪里
