### ISSUE TITLE
Error when using naive with sing-box

### ISSUE THREAD

**Issue by catcheru** [klzgrad/naiveproxy#548]
software version:
naive 114.0.5735.91
sing-box version 1.3.5
    Environment: go1.20.6 darwin/amd64
    Tags: with_gvisor,with_quic,with_wireguard,with_utls,with_reality_server,with_clash_api
    CGO: enabled

naive config:
{
  "listen": "socks://127.0.0.1:1080",
  "proxy": "https://user:passwd@domain.com",
  "log": "/Users/xxx/Documents/Proxy/naive/log"
}

The main part of sing-box config:
    "inbounds": [
        {
            "type": "tun",
            "tag": "tun-in",
            "inet4_address": "172.19.0.1/30",
            "inet6_address": "fdfe:dcba:9876::1/126",
            "auto_route": true,
            "strict_route": false,
            "stack": "system",
            "sniff": true,
            "sniff_override_destination": false
        }
    ],
    "outbounds": [
        {
          "type": "socks",
            "server": "127.0.0.1",
            "server_port": 1080,
            "udp_over_tcp": {
                "enabled": true,
                "version": 2
            },
            "tag": "proxy"
        },
        {
            "type": "direct",
            "tag": "direct"
        },
        {
            "type": "block",
            "tag": "block"
        },
        {
            "type": "dns",
            "tag": "dns-out"
        }
    ]

problems:
The software worked fine the first time opened it, but after terminated it with ctrl-c, I got an error when I opened naive and sing-box again.

[0809/211122.425779:ERROR:socket_posix.cc(93)] CreatePlatformSocket() failed: Too many open files (24)
[0809/211122.426948:ERROR:ssl_client_socket_impl.cc(978)] handshake failed; returned -1, SSL error code 1, net_error -100
[0809/211122.429274:ERROR:socket_posix.cc(93)] CreatePlatformSocket() failed: Too many open files (24)
[0809/211122.429533:ERROR:ssl_client_socket_impl.cc(978)] handshake failed; returned -1, SSL error code 1, net_error -100
[0809/211122.429820:ERROR:ssl_client_socket_impl.cc(978)] handshake failed; returned -1, SSL error code 1, net_error -100

**Comment by klzgrad** [comment]
https://vyspiansky.github.io/2021/06/22/too-many-open-files-error-on-macos/

**Comment by catcheru** [comment]
It worked. Thanks.
