### ISSUE TITLE
速度非常快，但是5分钟后又非常慢（网页都打不开），如此循环

### ISSUE THREAD

**Issue by dota2heqiuzhi** [klzgrad/naiveproxy#549]
网络环境：成都联通千兆
梯子：腾讯云香港服务器，速度上限200Mbps，按照官方文档搭建
客户端：openwrt passwall naiveproxy

目前的问题：比如我现在看youtube视频，非常快（测试200Mbps可以拉满，延迟100ms以内），但是看到5分钟的样子，网速就变得非常慢（虽然慢，但不会完全断开，开一个网页都要5~10s那种，延迟2s以上）。
有没有大佬可以提供排查思路，到底是联通网络的问题（比如限制我访问我的CVM），还是腾讯云服务器的问题（IP之前用xray被封过，现在又自己好了。我试过换IP，都是申请的新IP都是40开头的，内地访问不了。我现在的IP是119开头，只要不出问题，延时是很低的）？
日常需求就是Google和youtube，稳定就行。 求大佬指导！

谢谢！

目前我还有一个备用梯子（腾讯云新加坡轻量云服务器），安装的xray，不会出现这个问题。

**Comment by tarvfx** [comment]
用国内公司的云服务器翻墙容易被风控吧？

**Comment by dota2heqiuzhi** [comment]
> 用国内公司的云服务器翻墙容易被风控吧？

风控的后果是咋样？ 就类似我这种情况，限制网速之类的？

**Comment by klzgrad** [comment]
五分钟重启一次会有什么效果？

Xray默认没有多路复用。

看看是不是机房限制长连接

**Comment by dota2heqiuzhi** [comment]
> 五分钟重启一次会有什么效果？
> 
> Xray默认没有多路复用。
> 
> 看看是不是机房限制长连接

请问大佬，请问重启的意思是在服务器上每五分钟caddy restart一下吗？

**Comment by U201413497** [comment]
情况差不多，
网络环境：武汉电信300M。
梯子：cloudcone服务器，千兆，搭建的naive,采用的是caddy v1
客户端：armbian系统直接运行naive，S805的CPU，监听socks5和http，客户端版本https://github.com/klzgrad/naiveproxy/releases/download/v115.0.5790.166-1/naiveproxy-v115.0.5790.166-1-linux-arm.tar.xz

看油管视频很快，几分钟后卡几秒。然后过几分钟又卡几秒。一直重复。之前没出现这情况。

**Comment by 2378** [comment]
真猛，直连腾讯云，我最多DD后拿来落地。btw，都被封过一次了，没让你写保证书？

**Comment by dota2heqiuzhi** [comment]
> 情况差不多， 网络环境：武汉电信300M。 梯子：cloudcone服务器，千兆，搭建的naive,采用的是caddy v1 客户端：armbian系统直接运行naive，S805的CPU，监听socks5和http，客户端版本https://github.com/klzgrad/naiveproxy/releases/download/v115.0.5790.166-1/naiveproxy-v115.0.5790.166-1-linux-arm.tar.xz
> 
> 看油管视频很快，几分钟后卡几秒。然后过几分钟又卡几秒。一直重复。之前没出现这情况。

试过xray之类的不？   我感觉应该不是协议的问题，是服务器或者运营商的问题

**Comment by dota2heqiuzhi** [comment]
> 真猛，直连腾讯云，我最多DD后拿来落地。btw，都被封过一次了，没让你写保证书？

没有。我就翻个墙看看资料，不做坏事，写啥保证书····
之前xray 1、2年都很稳定，某一天突然发现梯子用不了，ping了下才知道IP被封了。
后面试过套cloudflare的免费CDN，但是速度很慢，自选出来的IP也基本上被限制访问了，感觉不是长久之计。  
这才了解了一下naiveproxy，结果又出现过几分钟网速非常低的问题····

**Comment by 2378** [comment]
这种情况来naive討論，意义不大，个人猜测是ISP的策略，就像之前江苏、河南移动断全球一样

**Comment by crapthings** [comment]
换成113那个版本现在没问题了

**Comment by crapthings** [comment]
体验了一阵，还是有这个问题
