### ISSUE TITLE
合并 命令行和配置文件中的配置

### ISSUE THREAD

**Issue by rsp4jack** [klzgrad/naiveproxy#554]
例如：
```jsonc
// config.json
{
  "listen": "socks://127.0.0.1:1080",
  "proxy": "https://google.com"
}
```
然后：
```
naive --listen socks://0.0.0.0:10808
```
此时 naive 的确会监听 `0.0.0.0:10808`，但没有将请求代理出去。这是因为命令行覆盖了 proxy 的设置，即使命令行中没有指定 proxy。

解决方法是先尝试从配置文件读取配置，然后用命令行参数覆盖设置。

**Comment by klzgrad** [comment]
命令行和config.json不是覆盖的关系，是二选一的关系，覆盖会造成不必要的复杂性
