### ISSUE TITLE
Possibility to use different network interfaces for incoming and outgoing connections

### ISSUE THREAD

**Issue by kolyadin** [klzgrad/naiveproxy#559]
I have a linux server with two WAN connections:

1. Home internet provider (interface enp2s0)
2. 4g/lte modem (interface mv0)

So i need naive proxy listen port on enp2s0 and route traffic via mv0.
As a result final website must see public ip of mv0.

It will be nice if naive will have cli options like this:

./naive --listen=http://192.168.2.100:43150 --einterface=192.168.4.100

Can you provide any working solutions for such task?

**Comment by klzgrad** [comment]
Routing is not performed inside an application. It is performed in the kernel.

With namespace: https://superuser.com/questions/271915/route-the-traffic-over-specific-interface-for-a-process-in-linux

Or you can add a manual route `ip route add $server_ip via $mv0_gateway_ip` to control the routing for a single target IP.
