### ISSUE TITLE
Adaptation for GUI frontend

### ISSUE THREAD

**Issue by BaiqingL** [klzgrad/naiveproxy#56]
There seems to be quite a lot of code that could be removed and slimmed down. I am currently trying to write a Qt5 cross platform fronted for this project and it is taking a while to properly hook together things. In the future when this project evolves, the readability of the code base would be really important for further improvements. Can I suggest an effort to clean up the current code base before progressing to other things?

**Comment by BaiqingL** [comment]
Nevermind, I was looking at a bunch of random code that doesn't seem to be used in any way. It's probably referenced and I just don't notice these things.

**Comment by klzgrad** [comment]
It's a valid question. The current project structured is optimized for minimal maintenance, not minimal code size. You can check the list of files included: https://github.com/klzgrad/naiveproxy/blob/master/tools/include.txt.

It's possible to remove more unused code, but that will make the above list larger. Considering it's not a small list, I'd prefer not to do this kind of microoptimization. 

As for the GUI there is one that I know of: https://github.com/ExcitedCodes/NaiveGUI.

It's possible to do it properly within the Chromium project structure. It contains everything you'll need to build a GUI. But for a third-party GUI the best is to use the binary as is.

**Comment by KevinZonda** [comment]
I'm also developing a GUI client called [NaiveSharp](https://github.com/KevinZonda/NaiveSharp)

**Comment by BaiqingL** [comment]
> I'm also developing a GUI client called [NaiveSharp](https://github.com/KevinZonda/NaiveSharp).

Cool 😄! 
Are there any plans to make it cross platform in the future?

**Comment by KevinZonda** [comment]
> > I'm also developing a GUI client called [NaiveSharp](https://github.com/KevinZonda/NaiveSharp).
> 
> Cool !
> Are there any plans to make it cross platform in the future?

Exactly no. But you may be insterered in Qv2ray, it has naiveproxy plugin support and crossplatform.

**Comment by klzgrad** [comment]
This issue can be merged into #158 now.
