### ISSUE TITLE
Is it possible to share same QUIC port 443 with nginx?

### ISSUE THREAD

**Issue by mingwiki** [klzgrad/naiveproxy#560]
## Why I need that:

I use nginx(ngx_stream_ssl_preread_module) as traffic router and enabled both https/443(and quic/443 reuseport) already;

For h2, caddy naiveproxy server works nice, but for h3, caddy use QUIC/7777 port as default, so when I visit somesite.com:443, quic won't works it's only h2.

## Question:

Is that possible to share same QUIC port 443 with nginx? Or forward naiveproxy QUIC traffic?

### nginx stream config

```
server {
  listen        443;
  proxy_pass    $upstream;
  ssl_preread   on;
}
map $ssl_preread_protocol $upstream {
  "TLSv1.3"     $name;
  "TLSv1.2"     $name;
}
map $ssl_preread_server_name $name {
  somesite.com   caddy;
  default       default_server;
}
upstream caddy {
  server        0.0.0.0:7777;
}
```

### Caddyfile

```
{
        order forward_proxy before route
        admin off
        auto_https off
}

:7777 {
        tls /cert/xx.pem /cert/xx.key {
                ciphers TLS_AES_128_GCM_SHA256
                alpn h2 h3
        }

        forward_proxy {
                basic_auth username passwd
                hide_ip
                hide_via
                probe_resistance
        }

        @host {
                host example.com
        }
        route @host {
                reverse_proxy https://example.com {   
                        header_up Host {upstream_hostport}
                        header_up X-Forwarded-Host {host}
                }
        }
}
```

**Comment by klzgrad** [comment]
https://http3-explained.haxx.se/en/h3/h3-altsvc

Does Nginx return the Alt-Svc header from an HTTP/2 request to the 443 port? If not, you need to figure out how to make it do that.

**Comment by mingwiki** [comment]
Yes, but nginx response Alt-Svc header is 7777, in fact only h2/443 works. I don't know how to make a proxy by nginx.

by the way, I try to use nginx reverse proxy naive as a http service directly, it don't works too: 

1. disable caddy tls
2. proxy_pass http://naive in nginx server location

`order forward_proxy before route`

Caddy do works with route and https://example.com works perfect in http3. but forward_proxy never works, it says 400, and naive client will send many requests to check it again and again every seconds.

**Comment by klzgrad** [comment]
Does ngx_stream_ssl_preread_module support HTTP/3 at all? https://serverfault.com/questions/1102835/tls-passthrough-non-terminating-https-reverse-proxy-load-balancer-for-http-3

In either case, Nginx needs to advertise Alt-Svc: h3=":443" and rewrites any Alt-Svc headers between its backends.

**Comment by mingwiki** [comment]
ngx_stream_ssl_preread_module do support http3, it's simple SNI router before httpserver.

Please check it on my site with F12:

4fm.top is my main and fallback site:

![image](https://github.com/klzgrad/naiveproxy/assets/7548568/f807b102-2fbd-4e8a-8c49-0d5c84bd7e09)

www.4fm.top is naiveproxy server:

![image](https://github.com/klzgrad/naiveproxy/assets/7548568/54e07933-fd00-4d19-9033-40d6763f565b)

So how to use make the proxyserver works on quic/443?
