### ISSUE TITLE
Does fallback website(reverse_proxy) influence the speed of naiveproxy

### ISSUE THREAD

**Issue by yyuurrii34** [klzgrad/naiveproxy#563]
Used to try this in my caddyfile(config for caddy):

reverse_proxy  https://demo.cloudreve.org  {
   header_up  Host  {upstream_hostport}
   header_up  X-Forwarded-Host  {host}
  }

no I substitute them with the line following:
reverse_proxy  localhost:8000
(I build some simple website on local port 8000)

it turned out that,when i was using outer website as the fallback,it **always gave me about 50ms more delay** **whether or not** the Naiveproxy were functioned(used as proxy/no fallback) or used as normal caddy server(used as web server/fallback).

**Comment by klzgrad** [comment]
> **whether or not** the Naiveproxy were functioned

Then it should be not a naiveproxy problem.
