### ISSUE TITLE
使用naive之后就无法解锁gpt 

### ISSUE THREAD

**Issue by Jack-bin183** [klzgrad/naiveproxy#565]
切换到同一个vps的trojan/vmess协议则可以解锁gpt，这是什么原因？
在服务器curl的结果
root@host:~# curl https://chat.openai.com/cdn-cgi/trace
fl=466f49
h=chat.openai.com
ip=2001:470:4807:3518::cae7
ts=1694537481.276
visit_scheme=https
uag=curl/7.81.0
colo=SJC
sliver=none
http=http/2
loc=US
tls=TLSv1.3
sni=plaintext
warp=off
gateway=off
rbi=off
kex=X25519

在客户端curl的结果
fl=619f132
h=chat.openai.com
ip=64.64.x.x
ts=1694537647.351
visit_scheme=https
uag=Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/116.0.0.0 Safari/537.36
colo=LAX
sliver=010-tier1
http=http/2
loc=US
tls=TLSv1.3
sni=plaintext
warp=off
gateway=off
rbi=off
kex=X25519

太奇怪了，求解

2001:470:4807:3518::cae7这个是bwg官方用来解锁gpt的ipv6代理

**Comment by zedifen** [comment]
I think we might also like to know how your configured the server to use the bwg-provided proxy IP?

**Comment by klzgrad** [comment]
提交bug的格式：
```
重现方法：
预期结果：
实际结果：
```

**Comment by wxwxwwxxx** [comment]
可能和DNS有关系。不同的协议和设置下，DNS的来源是有区别的

**Comment by klzgrad** [comment]
缺乏信息

**Comment by klzgrad** [comment]
Duplicate of #577
