### ISSUE TITLE
naiveproxy-v117.0.5938.44-1-openwrt-arm_cortex-a7_neon-vfpv4-static.tar.xz可能有错误

### ISSUE THREAD

**Issue by yqqtws** [klzgrad/naiveproxy#566]
我用的是华硕路由器rx-ax56u, 以前用openwrt-arm_cortex-a7_neon-vfpv4-static都是没有任何问题的，但是这次版本naiveproxy-v117.0.5938.44-1不能运行。

**Comment by klzgrad** [comment]
Duplicate of #564.
