### ISSUE TITLE
修改etc/hosts无法在naiveproxy下生效

### ISSUE THREAD

**Issue by xx-li** [klzgrad/naiveproxy#571]
### 环境
- vps: Linux yellow-hat-2.localdomain 4.9.0-12-amd64 #1 SMP Debian 4.9.210-1 (2020-01-20) x86_64
- client: Openwrt -- Psswall

### 问题
修改vps的`etc/hosts`， 添加一行`'172.31.255.2 chat.openai.com'`，在vps上执行ping后可以看到hosts修改已经生效。但是通过client代理访问时，hosts修改未生效，请问我应该如何处理，让naiveproxy代理时，特定的域名走特定的IP进行访问？
之前怀疑是caddy server的问题，已经重启了vps，还是不行。

同时看到有人提类似问题：https://github.com/klzgrad/naiveproxy/issues/565

**Comment by orangeByte** [comment]
+1
我也遇到了这个问题

**Comment by klzgrad** [comment]
https://github.com/caddyserver/caddy/issues/3518#issuecomment-649817452

**Comment by klzgrad** [comment]
Duplicate of #577
