### ISSUE TITLE
clash重定向导致naiveproxy出问题,求解

### ISSUE THREAD

**Issue by ChuLiqiang** [klzgrad/naiveproxy#574]
计划用clash当透明代理,配置本地naiveproxy后。在clash中配置naiveproxy发布的socket5代理全部正常。
但是在启动iptables的流量重定向后,naiveproxy报socket连接错误。最终定位是下面的防火墙脚本导致。能帮忙看下什么原因吗?

iptables -t nat -A PREROUTING -p tcp --dport 22 -j ACCEPT
iptables -t nat -A PREROUTING -p tcp --dport 53 -j ACCEPT
iptables -t nat -A PREROUTING -p udp --dport 53 -j ACCEPT
iptables -t nat -A PREROUTING -d 192.168.5.24 -p tcp --dport 80 -j ACCEPT
iptables -t nat -A PREROUTING -p tcp --dport 3000 -j ACCEPT
iptables -t nat -A PREROUTING -p tcp -j REDIRECT --to-ports 7892
iptables -t nat -A PREROUTING -p udp -j REDIRECT --to-ports 7892

报错日志[1011/164705.814382:INFO:naive_proxy.cc(197)] Connection 220 closed: ERR_SOCKS_CONNECTION_FAILED

**Comment by openips** [comment]
直接配置sock节点就可以了 没必要防火墙转发

**Comment by ChuLiqiang** [comment]
> 直接配置sock节点就可以了 没必要防火墙转发

这个是旁路由，用防火墙劫持流量到clash的。

**Comment by klzgrad** [comment]
这个环境配置不属于naiveproxy的问题

**Comment by ChuLiqiang** [comment]
> 这个环境配置不属于naiveproxy的问题
不是naiveproxy的问题
