### ISSUE TITLE
使用naive节点无法访问ChatGPT的172.31.255.2代理

### ISSUE THREAD

**Issue by Doublefire-Chen** [klzgrad/naiveproxy#577]
#572 
一模一样的情况，搬瓦工dc06机房的vps，在小鸡上用脚本测试，显示解锁，但是用naiveproxy代理到本地就不能解锁
大概率与搬瓦工解锁ChatGPT的方式有关，搬瓦工的小鸡在访问ChatGPT时会走搬瓦工内部的代理172.31.255.2，我猜是我们使用naiveproxy时小鸡没有走172.31.255.2代理，如果小鸡走172.31.255.2代理，出口地址是一个ipv6地址，而我在手机上用naiveproxy上访问ChatGPT，返回的就是小鸡自己的ipv4地址，提示无法访问。
<img width="699" alt="Screenshot 2023-10-17 at 11 15 29" src="https://github.com/klzgrad/naiveproxy/assets/72138342/b2440dd1-4cf5-4830-92b9-f4e563d72351">
![439411697506865_ pic](https://github.com/klzgrad/naiveproxy/assets/72138342/be005d9a-8a2d-43dd-9bbb-45ce53768428)

**Comment by Doublefire-Chen** [comment]
https://www.v2ex.com/t/950954
v2ex上也有人出现了一样的情况

**Comment by Doublefire-Chen** [comment]
前面说的有点问题，172.31.255.2好像就是搬瓦工小鸡的DNS地址，但是不知道他做的什么操作，可以让出口地址变为V6
<img width="534" alt="Screenshot 2023-10-17 at 11 33 24" src="https://github.com/klzgrad/naiveproxy/assets/72138342/aac4afdd-d5c1-455a-8e7a-577725aac4ae">
<img width="815" alt="Screenshot 2023-10-17 at 11 37 26" src="https://github.com/klzgrad/naiveproxy/assets/72138342/7f8496b9-15de-4606-a3b9-dc2b92133151">

**Comment by klzgrad** [comment]
没有正确配置Caddyfile

https://github.com/klzgrad/forwardproxy#access-control

```
Default policy:

acl {  
    deny 10.0.0.0/8 127.0.0.0/8 172.16.0.0/12 192.168.0.0/16 ::1/128 fe80::/10  
    allow all  
}  
```

`172.31.255.2` 是默认deny的地址之一。需要添加`allow 172.31.255.2`

**Comment by Doublefire-Chen** [comment]
> 没有正确配置Caddyfile
> 
> https://github.com/klzgrad/forwardproxy#access-control
> 
> ```
> Default policy:
> 
> acl {  
>     deny 10.0.0.0/8 127.0.0.0/8 172.16.0.0/12 192.168.0.0/16 ::1/128 fe80::/10  
>     allow all  
> }  
> ```
> 
> `172.31.255.2` 是默认deny的地址之一。需要添加`allow 172.31.255.2`

@klzgrad 大佬，您好，我根据您的提示修改了配置如下，还是无法访问ChatGPT，和之前一样，会返回小鸡的ipv4地址并提示无法访问，不过可以访问openai官网。请问是哪里出问题了？
```
:443, my_domain
tls admin@my_domain
route {
	forward_proxy {
		basic_auth username password
		hide_ip
		hide_via
		probe_resistance
		acl {
			allow 172.31.255.2
		}
	}
	reverse_proxy 127.0.0.1:1234 {
		#伪装网址
		header_up Host {upstream_hostport}
	}
}
```

**Comment by klzgrad** [comment]
allow 172.16.0.0/12

**Comment by Doublefire-Chen** [comment]
> allow 172.16.0.0/12

更改并重启caddy后，还是没有效果，和以前一样，我自己再琢磨琢磨吧，谢谢大佬的辛苦付出。

**Comment by littlefattywong** [comment]
关闭chrome的quic就可以了

**Comment by Doublefire-Chen** [comment]
> 关闭chrome的quic就可以了

感谢回复，刚刚试了下，这个方法对我不适用，没有效果

**Comment by jiangnanan** [comment]
我的环境，机器  还有VPS和你的一模一样，然后按这方法设置了一下就可以了 就一个参数  acl {
			allow 172.31.255.2
		}

**Comment by Doublefire-Chen** [comment]
> 我的环境，机器 还有VPS和你的一模一样，然后按这方法设置了一下就可以了 就一个参数 acl { allow 172.31.255.2 }

@jiangnanan 谢谢你的提醒，我刚刚又回去试了一遍，我知道为啥我之前没有成功了。
我之前在尝试作者 @klzgrad  的建议添加 acl { allow 172.31.255.2 }以及acl { allow 172.16.0.0/12 }没有效果，于是我就把这个allow给注释掉了。
后来在根据 @littlefattywong 的建议关闭quic去测试，因为我没有放行内网地址，所以还是没有效果。
刚刚我取消注释并关闭quic后，成功了。
不需要allow 172.16.0.0/12，allow 172.31.255.2就够用了。
感谢三位 @klzgrad @littlefattywong @jiangnanan （排名不分先后）的热心帮助，互联网因为你们而精彩，谢谢。
此issue到此正式close

**Comment by ArcCal** [comment]
或许可以试试warp解锁，在caddyfile的forword字段添加一句：upstream socks5://127.0.0.1:40000

**Comment by ArcCal** [comment]
关于warp的设置，可以参考：https://chirpset.com/t/topic/463

这个方法也是看你们的讨论想到的

**Comment by ArcCal** [comment]
这个方法好处和弊端都很明显，好处是可以解锁chatgpt和一些流媒体
坏处是，这样做流量被全部导入warp，（在特定情况下）可能拖慢网速，也可能增加openai、google弹出人机验证的可能
是否选用，可以自己斟酌

**Comment by ArcCal** [comment]
关于acl有两个疑问：
一、acl列表支持什么格式的

二、规则数量有无要求

我的forward proxy配置部分如下：
forward_proxy {
		basic_auth xxxx yyyy
		hide_ip
		hide_via
		probe_resistance
		acl {  
			deny_file /etc/caddy/chinaip.txt
		}
	}

chinaip.txt就是一个个IP段（用https://raw.githubusercontent.com/Loyalsoldier/clash-rules/release/cncidr.txt转来的），类似这样：
1.0.1.0/24
1.0.2.0/23
1.0.8.0/21
1.0.32.0/19
1.1.0.0/24
1.1.2.0/23
1.1.4.0/22
1.1.8.0/21
1.1.16.0/20
1.1.32.0/19
1.2.0.0/23
1.2.4.0/22
1.2.8.0/21
1.2.16.0/20
……


测试发现，acl规则似乎没有生效，通过代理依然可以访问墙内的常见服务（微信、bilibili、淘宝、腾讯视频、百度）等（更多的没有测试）

**Comment by godmaycrying** [comment]
> 没有正确配置Caddyfile
> 
> https://github.com/klzgrad/forwardproxy#access-control
> 
> ```
> Default policy:
> 
> acl {  
>     deny 10.0.0.0/8 127.0.0.0/8 172.16.0.0/12 192.168.0.0/16 ::1/128 fe80::/10  
>     allow all  
> }  
> ```
> 
> `172.31.255.2` 是默认deny的地址之一。需要添加`allow 172.31.255.2`

请问如何在json文件配置？

**Comment by jkddw** [comment]
非常感谢，瓦工折腾一天终于解决了，我之前是相反，chatgpt手机可以访问，电脑死活不行，加了一行acl {
allow 172.31.255.2
}就行了，不需要弄quic

**Comment by FZelin** [comment]
我使用 config.json 来运行的
请问该在什么位置，如何配置 acl {allow 172.31.255.2}
```json
{
 "apps": {
   "http": {
     "servers": {
       "srv0": {
         "listen": [
           ":443"   
         ],
         "routes": [
           {
             "handle": [
               {
                 "auth_user_deprecated": "user1",
                 "auth_pass_deprecated": "123456",
                 "handler": "forward_proxy",
                 "hide_ip": true,
                 "hide_via": true,
                 "probe_resistance": {}
               }
             ]
           },
           {
             "handle": [
               {
                 "auth_user_deprecated": "user2",
                 "auth_pass_deprecated": "456789",
                 "handler": "forward_proxy",
                 "hide_ip": true,
                 "hide_via": true,
                 "probe_resistance": {}
               }
             ]
           },
           {
             "handle": [
               {
                 "handler": "reverse_proxy",
                 "headers": {
                   "request": {
                     "set": {
                       "Host": [
                         "{http.reverse_proxy.upstream.hostport}"
                       ],
                       "X-Forwarded-Host": [
                         "{http.request.host}"
                       ]
                     }
                   }
                 },
                 "transport": {
                   "protocol": "http",
                   "tls": {}
                 },
                 "upstreams": [
                   {
                     "dial": "pan.test.com:443"
                   }
                 ]
               }
             ]
           }
         ],
         "tls_connection_policies": [
           {
             "match": {
               "sni": [
                 "www.test.com"
               ]
             },
             "certificate_selection": {
               "any_tag": [
                 "cert0"
               ]
             }
           }
         ],
         "automatic_https": {
           "disable": true
         }
       }
     }
   },
   "tls": {
     "certificates": {
       "load_files": [
         {
           "certificate": "/root/.local/share/caddy/certificates/acme-v02.api.letsencrypt.org-directory/www.test.com/www.test.com.crt",
           "key": "/root/.local/share/caddy/certificates/acme-v02.api.letsencrypt.org-directory/www.test.com/www.test.com.key",
           "tags": [
             "cert0"
           ]
         }
       ]
     }
   }
 }
}
```
