### ISSUE TITLE
能否更改clang和gn的獲取方式？

### ISSUE THREAD

**Issue by triggered96** [klzgrad/naiveproxy#579]
默認情況下，CLANG_REVISION 的版本是根據 tools/clang/scripts 中的設置而確定的，你可以在這個連結找到相關的代碼：https://github.com/klzgrad/naiveproxy/blob/master/src/get-sysroot.sh#L6。

但在 macOS M1 機器上，third_party/llvm-build/Release+Asserts 的版本確實是 x86 架構的，這個情況可以在以下連結找到：https://github.com/klzgrad/naiveproxy/blob/master/src/get-clang.sh#L14-L19。

你也提到 @Chilledheart 似乎提供了一個解決方案，你可以在這個提交中找到相關信息：https://github.com/Chilledheart/naiveproxy/commit/92704e91270b971fbed8041aa3a3e4382fc6be8b。

希望這樣的重新組織對你有所幫助。如果你需要更多的信息或有其他問題，請隨時提出。

**Comment by Chilledheart** [comment]
上游从某个版本开始一直提供arm64版本的clang、gn以及profile data（对的，和x64不同），只需要修改下载和编译脚本就可以。

我一直都是在m1下用原生clang和gn 编译所需的arm64版本naiveproxy。

**Comment by Chilledheart** [comment]
You can try this branch to see if it works for you: https://github.com/Chilledheart/naiveproxy/tree/support_arm64_mac
