### ISSUE TITLE
Can't run on OpenWRT x86_64

### ISSUE THREAD

**Issue by koolwiki** [klzgrad/naiveproxy#58]
The openwrt was downloaded from here.
http://firmware.koolshare.cn/LEDE_X64_fw867/

root@Openwrt:~# opkg install libnss libatomic1                                                                                                                          
Package libnss (3.51-1) installed in root is up to date.                                                                                                                
Package libatomic1 (8.4.0-2) installed in root is up to date.                                                                                                           

root@Openwrt:~# ./naive -h  
Error relocating /usr/lib/libnspr4.so: secure_getenv: symbol not found      

root@Openwrt:~# ldd naive                                                                                                                                               
        /lib/ld-musl-x86_64.so.1 (0x7fb77bfb0000)                                                                                                                       
        libnss3.so => /usr/lib/libnss3.so (0x7fb77ba30000)                                                                                                              
        libnssutil3.so => /usr/lib/libnssutil3.so (0x7fb77ba02000)                                                                                                      
        libnspr4.so => /usr/lib/libnspr4.so (0x7fb77b9ca000)                                                                                                            
        libc.so => /lib/ld-musl-x86_64.so.1 (0x7fb77bfb0000)                                                                                                            
        libplc4.so => /usr/lib/libplc4.so (0x7fb77b9c3000)                                                                                                              
        libplds4.so => /usr/lib/libplds4.so (0x7fb77b9be000)                                                                                                            
        libgcc_s.so.1 => /lib/libgcc_s.so.1 (0x7fb77b9aa000)                                                                                                            
Error relocating /usr/lib/libnspr4.so: secure_getenv: symbol not found

**Comment by klzgrad** [comment]
First reaction
```
root@OpenWrt:~# opkg install libnss
Installing libnss (3.48-2) to root...
Downloading http://downloads.openwrt.org/releases/19.07.2/packages/x86_64/packages/libnss_3.48-2_x86_64.ipk
Installing zlib (1.2.11-3) to root...
Downloading http://downloads.openwrt.org/releases/19.07.2/packages/x86_64/base/zlib_1.2.11-3_x86_64.ipk
Installing libsqlite3-0 (3310100-1) to root...
Downloading http://downloads.openwrt.org/releases/19.07.2/packages/x86_64/packages/libsqlite3-0_3310100-1_x86_64.ipk
Installing nspr (4.24-1) to root...
Downloading http://downloads.openwrt.org/releases/19.07.2/packages/x86_64/packages/nspr_4.24-1_x86_64.ipk
Configuring nspr.
Configuring zlib.
Configuring libsqlite3-0.
Configuring libnss.
root@OpenWrt:~/naiveproxy-v80.0.3987.87-3-openwrt-x86_64# ./naive -h
Usage: naive { OPTIONS | config.json }

Options:
-h, --help                 Show this message
--version                  Print version
--listen=<proto>://[addr][:port]
                           proto: socks, http
                                  redir (Linux only)
--proxy=<proto>://[<user>:<pass>@]<hostname>[:<port>]
                           proto: https, quic
--padding                  Use padding
--host-resolver-rules=...  Resolver rules
--resolver-range=...       Redirect resolver range
--log[=<path>]             Log to stderr, or file
--log-net-log=<path>       Save NetLog
--ssl-key-log-file=<path>  Save SSL keys for Wireshark

root@OpenWrt:~/naiveproxy-v80.0.3987.87-3-openwrt-x86_64# ldd naive
	/lib/ld-musl-x86_64.so.1 (0x7f610662b000)
	libnss3.so => /usr/lib/libnss3.so (0x7f61060ab000)
	libnssutil3.so => /usr/lib/libnssutil3.so (0x7f610607d000)
	libnspr4.so => /usr/lib/libnspr4.so (0x7f6106045000)
	libc.so => /lib/ld-musl-x86_64.so.1 (0x7f610662b000)
	libplc4.so => /usr/lib/libplc4.so (0x7f610603e000)
	libplds4.so => /usr/lib/libplds4.so (0x7f6106039000)
	libgcc_s.so.1 => /lib/libgcc_s.so.1 (0x7f6106025000)

```

**Comment by klzgrad** [comment]
I don't think I can do anything here. You may need to ask the vendor of this firmware.

**Comment by koolwiki** [comment]
> First reaction
> 
> ```
> root@OpenWrt:~# opkg install libnss
> Installing libnss (3.48-2) to root...
> Downloading http://downloads.openwrt.org/releases/19.07.2/packages/x86_64/packages/libnss_3.48-2_x86_64.ipk
> Installing zlib (1.2.11-3) to root...
> Downloading http://downloads.openwrt.org/releases/19.07.2/packages/x86_64/base/zlib_1.2.11-3_x86_64.ipk
> Installing libsqlite3-0 (3310100-1) to root...
> Downloading http://downloads.openwrt.org/releases/19.07.2/packages/x86_64/packages/libsqlite3-0_3310100-1_x86_64.ipk
> Installing nspr (4.24-1) to root...
> Downloading http://downloads.openwrt.org/releases/19.07.2/packages/x86_64/packages/nspr_4.24-1_x86_64.ipk
> Configuring nspr.
> Configuring zlib.
> Configuring libsqlite3-0.
> Configuring libnss.
> root@OpenWrt:~/naiveproxy-v80.0.3987.87-3-openwrt-x86_64# ./naive -h
> Usage: naive { OPTIONS | config.json }
> 
> Options:
> -h, --help                 Show this message
> --version                  Print version
> --listen=<proto>://[addr][:port]
>                            proto: socks, http
>                                   redir (Linux only)
> --proxy=<proto>://[<user>:<pass>@]<hostname>[:<port>]
>                            proto: https, quic
> --padding                  Use padding
> --host-resolver-rules=...  Resolver rules
> --resolver-range=...       Redirect resolver range
> --log[=<path>]             Log to stderr, or file
> --log-net-log=<path>       Save NetLog
> --ssl-key-log-file=<path>  Save SSL keys for Wireshark
> 
> root@OpenWrt:~/naiveproxy-v80.0.3987.87-3-openwrt-x86_64# ldd naive
> 	/lib/ld-musl-x86_64.so.1 (0x7f610662b000)
> 	libnss3.so => /usr/lib/libnss3.so (0x7f61060ab000)
> 	libnssutil3.so => /usr/lib/libnssutil3.so (0x7f610607d000)
> 	libnspr4.so => /usr/lib/libnspr4.so (0x7f6106045000)
> 	libc.so => /lib/ld-musl-x86_64.so.1 (0x7f610662b000)
> 	libplc4.so => /usr/lib/libplc4.so (0x7f610603e000)
> 	libplds4.so => /usr/lib/libplds4.so (0x7f6106039000)
> 	libgcc_s.so.1 => /lib/libgcc_s.so.1 (0x7f6106025000)
> ```

Thank you for your quick reply. May be some bugs in the firmware cause this problem. I tried the official firmware and it works well.
