### ISSUE TITLE
同dae兼容存在问题，希望适配

### ISSUE THREAD

**Issue by ChuLiqiang** [klzgrad/naiveproxy#581]
大鹅反馈curl 本机兼容有问题，能帮忙兼容一下吗？
https://github.com/daeuniverse/dae/blob/main/docs/en/proxy-protocols.md

**Comment by klzgrad** [comment]
描述不清

**Comment by ChuLiqiang** [comment]
> 描述不清

crul -x socks代理有问题。

**Comment by ChuLiqiang** [comment]
> 描述不清

大鹅那边反馈，大鹅和naiveproxy部署在一起的时候。naiveproxy socks代理无法正常使用。

**Comment by ChuLiqiang** [comment]
> 描述不清

最新版测试兼容，可以关掉了

**Comment by ChuLiqiang** [comment]
> You should close it by yourself.

done
