### ISSUE TITLE
[ERROR 400 ] address  IP地址 too many colons in address

### ISSUE THREAD

**Issue by U201413497** [klzgrad/naiveproxy#582]
caddy版本 v1.0.5
debian 版本12
naive 版本[naiveproxy-v118.0.5993.65-1-linux-x64.tar.xz](https://github.com/klzgrad/naiveproxy/releases/download/v118.0.5993.65-1/naiveproxy-v118.0.5993.65-1-linux-x64.tar.xz)

caddy的日志报[ERROR 400 ] address IP地址: too many colons in address。
请教这是什么问题呢

**Comment by ArcCal** [comment]
已经弃用的旧版cadyy……

**Comment by klzgrad** [comment]
不支持caddy v1
