### ISSUE TITLE
Multi-Site Config Caddyfile with Naive Proxy Functionality

### ISSUE THREAD

**Issue by Aocro** [klzgrad/naiveproxy#584]
Hello, I want to express my gratitude for your incredible work! I have been exploring the usage of Naive Proxy for my projects, while working with Naive Proxy, I encountered difficulties in finding an existing multi-site config Caddyfile that incorporates the Naive Proxy functionality. 

So I have developed my own multi-site config Caddy file with Naive Proxy functionality. I believe that sharing this configuration can benefit the community and make it easier for users to configure with multiple sites.

Here is my `docker-compose.yml` file
```docker-compose.yml
version: "3"

services:
  caddy:
    image: pocat/naiveproxy:latest
    container_name: caddy
    environment:
      - TZ=Asia/Shanghai
      - PATH=/etc/naiveproxy/Caddyfile
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./data/caddy/config:/etc/naiveproxy
      - ./data/caddy/html:/var/www/html
      - ./data/caddy/log:/var/log/caddy
    restart: always

  example:
    image: example/example
    container_name: example
    depends_on:
      - caddy
    restart: unless-stopped
```

and `Caddyfile`
```Caddyfile
{
	admin off
	log {
		output file /var/log/caddy/access.log
		level INFO
	}
}

:443 naiveproxy.example.org {
	tls your_email@here
	route {
		forward_proxy {
			basic_auth username password
			hide_ip
			hide_via
			probe_resistance secret-xxxxxxxxsite.com
		}
	}

	file_server {
		root /var/www/html
	}
}

site1.example.org {
	tls your_email@here
	reverse_proxy service1:8080
}

site2.example.org {
	tls your_email@here
	@websockets {
		header Connection *Upgrade*
		header Upgrade websocket
	}
	reverse_proxy @websockets service2:8080
}
```

If there are any potential faults or improvements that you come across in this configuration, I would greatly appreciate your feedback. Thank you for your attention to this matter.

**Comment by ArcCal** [comment]
route {
		forward_proxy {
			basic_auth username password
			hide_ip
			hide_via
			probe_resistance secret-xxxxxxxxsite.com
		}
	}

	file_server {
		root /var/www/html
	}

这里貌似不太对？ route括起来的应该是两个功能吧，不然就没必要route了？这里route{}之内只有forwardproxy
