### ISSUE TITLE
How can I use ip address to connect to a naiveproxy server?

### ISSUE THREAD

**Issue by huangsida** [klzgrad/naiveproxy#585]
When my domain became unavaliable, I tried to use ip address to connect to a naiveproxy server. On IOS, I use shadowrocket, and it works fine. But on PC, when I use ip address to connect to the naive server through the naiveproxy client, the connection can't be established. 
(naive version 118.0.5993.65)
[1101/204918.063836:ERROR:cert_verify_proc_builtin.cc(676)] CertVerifyProcBuiltin for xxx.xxx.xxx.xxx(IP addr) failed:
----- Certificate i=0 (CN=xxx.xxx.com.) -----
ERROR: Time is after notAfter
[1101/204918.064784:ERROR:ssl_client_socket_impl.cc(985)] handshake failed; returned -1, SSL error code 1, net_error -200
[1101/204918.065147:INFO:naive_proxy.cc(192)] Connection 6 closed: ERR_PROXY_CERTIFICATE_INVALID
 
My question is, how to disable the handshake in the source code? Thanks.

**Comment by huangsida** [comment]
Modify naive_proxy.cc , That's it!
//  server_ssl_config_.ignore_certificate_errors =
//      session_->params().ignore_certificate_errors;
//  proxy_ssl_config_.ignore_certificate_errors =
//      session_->params().ignore_certificate_errors;

    server_ssl_config_.ignore_certificate_errors = true;

    proxy_ssl_config_.ignore_certificate_errors = true;

**Comment by ArcCal** [comment]
用--host-resolver-rules="MAP www.goooooooooooooooogle.com 14.23.67.56"参数或者修改hosts文件解决
如：
naive --host-resolver-rules="MAP www.goooooooooooooooogle.com 14.23.67.56" --listen=socks://0.0.0.0:1080 --proxy=https://user:pass@www.goooooooooooooooogle.com --log

**Comment by huangsida** [comment]
> 用--host-resolver-rules="MAP [www.goooooooooooooooogle.com](http://www.goooooooooooooooogle.com) 14.23.67.56"参数或者修改hosts文件解决 如： naive --host-resolver-rules="MAP [www.goooooooooooooooogle.com](http://www.goooooooooooooooogle.com) 14.23.67.56" --listen=socks://0.0.0.0:1080 --proxy=https://user:pass@www.goooooooooooooooogle.com --log

I have tried this method on my Ubuntu, but it doesn't work. Luckly, I found a solution:
Modify the source code src/net/tools/naive/naive_proxy.cc  68-71
server_ssl_config_.ignore_certificate_errors =
      session_->params().ignore_certificate_errors;
  proxy_ssl_config_.ignore_certificate_errors =
      session_->params().ignore_certificate_errors;
---->
    server_ssl_config_.ignore_certificate_errors = true;
    proxy_ssl_config_.ignore_certificate_errors = true;
I have sent a email to the author, and ask him to add a switch. I can only compile it on my Ubuntu. It is too hard for me to compile it for windows and Android.

**Comment by klzgrad** [comment]
There is no security if certificate errors are ignored.

**Comment by huangsida** [comment]
I see.  But it can be used as an emergency way to connect to the vps with domain problems. It will be OK if the vps server is controlled by ourself.

**Comment by klzgrad** [comment]
https://devops.stackexchange.com/questions/19/how-do-i-include-my-internal-ca-certificate-to-validate-ssl-exchanges-in-chef

Supports loading your own CA from SSL_CERT_FILE or SSL_CERT_DIR
