### ISSUE TITLE
How to run navieproxy client on Win7?

### ISSUE THREAD

**Issue by i-Libra** [klzgrad/naiveproxy#588]
It seems windows client build cannot run on win7 system. Could I find any previous build which can run on win7?

**Comment by klzgrad** [comment]
Windows 7 and 8.1 are not supported.

**Comment by xiaopangzi13140** [comment]
@klzgrad  请问naiveproxy-v106.0.5249.91-3-win-x64.zip win7可以用吗？

**Comment by Chilledheart** [comment]
> @klzgrad 请问naiveproxy-v106.0.5249.91-3-win-x64.zip win7可以用吗？

你可以试试我写的yass [支持win7的64位版本](https://github.com/Chilledheart/yass/releases/download/1.9.1/yass-mingw-winxp-release-x86_64-1.9.1-system-installer.exe) , [支持windows xp sp3的32位版本](https://github.com/Chilledheart/yass/releases/download/1.9.1/yass-mingw-winxp-release-i686-1.9.1-system-installer.exe) 后者需要安装 [vc2010运行时](https://download.microsoft.com/download/1/6/5/165255E7-1014-4D0A-B094-B6A430A6BFFC/vcredist_x86.exe)

**Comment by Chilledheart** [comment]
yass is a naiveproxy-compatible gui client for windows: [windows 7 64-bit client installer](https://github.com/Chilledheart/yass/releases/download/1.9.1/yass-mingw-winxp-release-x86_64-1.9.1-system-installer.exe) or [windows xp sp3 32-bit installer](https://github.com/Chilledheart/yass/releases/download/1.9.1/yass-mingw-winxp-release-i686-1.9.1-system-installer.exe) [(require vc 2010 runtime)][vs2010_x86] or [windows 11 arm64 installer](https://github.com/Chilledheart/yass/releases/download/1.9.1/yass-mingw-release-aarch64-1.9.1-system-installer.exe)

[vs2010_x86]: https://download.microsoft.com/download/1/6/5/165255E7-1014-4D0A-B094-B6A430A6BFFC/vcredist_x86.exe

**Comment by PastelArtist** [comment]
在这里下载Windows 7 and Windows 8.1适用的版本：https://github.com/PastelArtist/naiveproxy-for-Windows-7-and-Windows-8.1/releases
编译自项目源码naiveproxy-v109.0.5414.74分支源码，纯老系统上自用，不放心可在www.virustotal.com上扫描病毒。

**Comment by PastelArtist** [comment]
@xiaopangzi13140 Windows 7到Windows 10都可以正常使用。根据https://github.com/klzgrad/naiveproxy/wiki/%E7%AE%80%E4%BD%93%E4%B8%AD%E6%96%87#%E8%87%AA%E8%A1%8C%E7%BC%96%E8%AF%91指南自行编译，Windows 7和Windows 8.1最高支持naiveproxy v109.0.5414.74版本。
[naiveproxy-v109.0.5414.74-1-x64-windows7+.zip](https://github.com/klzgrad/naiveproxy/files/15366192/naiveproxy-v109.0.5414.74-1-x64-windows7%2B.zip)
[naiveproxy-v109.0.5414.74-2-x64-windows7+.zip](https://github.com/klzgrad/naiveproxy/files/15366193/naiveproxy-v109.0.5414.74-2-x64-windows7%2B.zip)

**Comment by klzgrad** [comment]
不允许第三方发布未经验证的二进制。

保持老版本持久运行与naiveproxy的设计原则是背道而驰的。

Windows 7/8的用户应该使用其它的工具，不要使用naiveproxy。
