### ISSUE TITLE
是否可以做一个可以整合编译的openwrt的分支

### ISSUE THREAD

**Issue by openips** [klzgrad/naiveproxy#589]
固件安装完毕后再下载安装naiveproxy太麻烦了
https://github.com/xiaorouji/openwrt-passwall-packages/tree/main/naiveproxy
这里有可以整合编译到openwrt固件的版本 就是里面的客户端太老了
能否官方维护一个方便整合编译 
谢谢

**Comment by klzgrad** [comment]
不能
这里不具有openwrt的使用和测试条件
应该向https://github.com/xiaorouji/openwrt-passwall-packages提交代码
