### ISSUE TITLE
About the multiplexing feature in NaïveProxy

### ISSUE THREAD

**Issue by floating-cat** [klzgrad/naiveproxy#59]
Hi,

I have read most part of this project documentation, and I try to learn the design of this project. But I am still not clear about the multiplexing part of the NaïveProxy.

From my understanding (may incorrect), the NaïveProxy opens a TLS connection for each hostname and multiplex the same hostname request in one connection. But it won't multiplex different hostname requests in a TLS connection. Am' I understand it correctly?

If yes, does the current NaïveProxy multiplexing have any difference from V2Ray's WS+TLS or Trojan?
If I use V2Ray with socks5 for Chrome, the Chrome would also multiplex the same hostname request in one TLS connection (The Chrome open a TCP tunnel to the remote server, and use HTTP/2 in it).

Could you shed me some light about this? Thanks.

**Comment by klzgrad** [comment]
NaiveProxy is basically a H2 tunnel. HTTP/2 has multiplexing built in.

**Comment by floating-cat** [comment]
Thanks for your information.
