### ISSUE TITLE
Too many connection reset by peer

### ISSUE THREAD

**Issue by bluemiaomiao** [klzgrad/naiveproxy#593]
```
"gateway.discord.gg:443", "headers": {"User-Agent": ["Go-http-client/1.1"], "Proxy-Authorization": [], "Proxy-Connection": ["Keep-Alive"]}, "tls": {"resumed": false, "version": 772, "cipher_suite": 4865, "proto": "", "server_name": "xx.com"}}, "duration": 0.428774118}
2023/11/13 12:22:48.215 ERROR   http.log.error  read tcp 10.0.0.4:50086->162.159.133.234:443: read: connection reset by peer    {"request": {"remote_ip": "117.119.77.138", "remote_port": "5726", "client_ip": "117.119.77.138", "proto": "HTTP/1.1", "method": "CONNECT", "host": "gateway.discord.gg:443", "uri": "gateway.discord.gg:443", "headers": {"User-Agent": ["Go-http-client/1.1"], "Proxy-Authorization": [], "Proxy-Connection": ["Keep-Alive"]}, "tls": {"resumed": false, "version": 772, "cipher_suite": 4865, "proto": "", "server_name": "xx.com"}}, "duration": 0.310195828}
2023/11/13 12:23:28.397 ERROR   http.log.error  read tcp 10.0.0.4:34508->52.177.138.113:443: read: connection reset by peer     {"request": {"remote_ip": "117.119.77.138", "remote_port": "5730", "client_ip": "117.119.77.138", "proto": "HTTP/1.1", "method": "CONNECT", "host": "in.appcenter.ms:443", "uri": "in.appcenter.ms:443", "headers": {"User-Agent": ["Go-http-client/1.1"], "Proxy-Authorization": [], "Proxy-Connection": ["Keep-Alive"]}, "tls": {"resumed": false, "version": 772, "cipher_suite": 4865, "proto": "", "server_name": "xx.com"}}, "duration": 5.41121713}
2023/11/13 12:23:49.147 ERROR   http.log.error  read tcp 10.0.0.4:34874->162.159.133.234:443: read: connection reset by peer    {"request": {"remote_ip": "117.119.77.138", "remote_port": "5734", "client_ip": "117.119.77.138", "proto": "HTTP/1.1", "method": "CONNECT", "host": "gateway.discord.gg:443", "uri": "gateway.discord.gg:443", "headers": {"User-Agent": ["Go-http-client/1.1"], "Proxy-Authorization": [], "Proxy-Connection": ["Keep-Alive"]}, "tls": {"resumed": false, "version": 772, "cipher_suite": 4865, "proto": "", "server_name": "xx.com"}}, "duration": 0.313427757}
2023/11/13 12:23:49.973 ERROR   http.log.error  read tcp 10.0.0.4:57440->162.159.135.234:443: read: connection reset by peer    {"request": {"remote_ip": "117.119.77.138", "remote_port": "5735", "client_ip": "117.119.77.138", "proto": "HTTP/1.1", "method": "CONNECT", "host": "gateway.discord.gg:443", "uri": "gateway.discord.gg:443", "headers": {"User-Agent": ["Go-http-client/1.1"], "Proxy-Authorization": [], "Proxy-Connection": ["Keep-Alive"]}, "tls": {"resumed": false, "version": 772, "cipher_suite": 4865, "proto": "", "server_name": "xx.com"}}, "duration": 0.294418644}
2023/11/13 12:24:00.208 ERROR   http.log.error  read tcp 10.0.0.4:41040->52.96.111.98:443: read: connection reset by peer       {"request": {"remote_ip": "117.119.77.138", "remote_port": "5737", "client_ip": "117.119.77.138", "proto": "HTTP/1.1", "method": "CONNECT", "host": "outlook.office.com:443", "uri": "outlook.office.com:443", "headers": {"User-Agent": ["Go-http-client/1.1"], "Proxy-Authorization": [], "Proxy-Connection": ["Keep-Alive"]}, "tls": {"resumed": false, "version": 772, "cipher_suite": 4865, "proto": "", "server_name": "xx.com"}}, "duration": 0.315871464}
2023/11/13 12:24:21.591 ERROR   http.log.error  read tcp 10.0.0.4:37676->204.79.197.200:443: read: connection reset by peer     {"request": {"remote_ip": "117.119.77.138", "remote_port": "5751", "client_ip": "117.119.77.138", "proto": "HTTP/1.1", "method": "CONNECT", "host": "bing.com:443", "uri": "bing.com:443", "headers": {"User-Agent": ["Go-http-client/1.1"], "Proxy-Authorization": [], "Proxy-Connection": ["Keep-Alive"]}, "tls": {"resumed": false, "version": 772, "cipher_suite": 4865, "proto": "", "server_name": "xx.com"}}, "duration": 0.278814696}
2023/11/13 12:24:21.611 ERROR   http.log.error  read tcp 10.0.0.4:37690->204.79.197.200:443: read: connection reset by peer     {"request": {"remote_ip": "117.119.77.138", "remote_port": "5752", "client_ip": "117.119.77.138", "proto": "HTTP/1.1", "method": "CONNECT", "host": "cn.bing.com:443", "uri": "cn.bing.com:443", "headers": {"User-Agent": ["Go-http-client/1.1"], "Proxy-Authorization": [], "Proxy-Connection": ["Keep-Alive"]}, "tls": {"resumed": false, "version": 772, "cipher_suite": 4865, "proto": "", "server_name": "xx.com"}}, "duration": 0.283721691}
2023/11/13 12:24:22.378 ERROR   http.log.error  read tcp 10.0.0.4:37702->204.79.197.200:443: read: connection reset by peer     {"request": {"remote_ip": "117.119.77.138", "remote_port": "5755", "client_ip": "117.119.77.138", "proto": "HTTP/1.1", "method": "CONNECT", "host": "bing.com:443", "uri": "bing.com:
top - 12:29:02 up  1:38,  1 user,  load average: 0.05, 0.04, 0.00
```

Caddyfile:

```caddyfile
{
  admin off
  order forward_proxy before file_server
}

:443, xx.com {
  tls admin@xx.com
  forward_proxy {
    basic_auth xx xx
    hide_ip
    hide_via
    probe_resistance
  }
  file_server {
    root /var/www/html
  }
}
```

Clash YAML:

```yaml
proxies:
- name: US East(Mircosoft AZure)
  type: http
  server: xx.com
  port: 443
  username: xx
  password: xx
  tls: true
  skip-cert-verify: true
```

Server:

```
Distributor ID: Ubuntu
Description:    Ubuntu 22.04.3 LTS
Release:        22.04
Codename:       jammy
```
 
Help!!

**Comment by zedifen** [comment]
There have been [several discussions on this issue](https://github.com/klzgrad/naiveproxy/issues?q=is%3Aissue+reset). If these logs comes with no trouble for you usage, I think it's okay to just ignore them. Or please feel free to check those discussions for details.

**Comment by bluemiaomiao** [comment]
In fact, there is a problem. Clash does not support Http2, but NaiveProxy will use Http2, which causes the link to be closed prematurely before transmitting data, making the proxy unable to function properly. 

A feasible approach is to start NaiveProxy locally on the client and implement the Socks protocol to listen on localhost, and then configure Clash to localhost. However, such a link will become longer, resulting in a delay of 60ms for ICMP Ping, 50ms for TCP Ping, and 131ms for HTTP URL Test. 

However, using ShadowRocket directly for iOS does not have that much delay.

@zedifen

**Comment by zedifen** [comment]
Fair enough. This should be an Clash issue, not of naiveproxy's. Currently it does seems to be no easy-to-go GUI clients in comply with naiveproxy except for Shadowrocket, and I'd like to see new apps for this in the future. @bluemiaomiao If these logs are causing you trouble and you'd like to keep using Clash, should there be no updates on Clash's side, maybe considering some other server software with HTTP proxy configured is better.

**Comment by bluemiaomiao** [comment]
@zedifen   Yes, I am developing a cross platform NaiveProxy client, but I am afraid of things like Clash. Currently, this project is private, and I believe that supporting only the English language is a good approach. I am a trader working in overseas financial markets, and I need to read a lot of Bloomberg information. 

Payment can also filter out some unreasonable users, but it may go against the original intention of open source. The remedy is to use these fees for donations to other open source projects. As is well known, Babel (a JavaScript library) died in bankruptcy.

**Comment by bluemiaomiao** [comment]
@Chilledheart The shadow of Clash has not disappeared, it exists in various software, such as Stash. Clash's design philosophy is advanced, but the disadvantage is that it does not support HTTP/2 very well. I hope to quickly access domestic and foreign financial websites, rather than redirecting all traffic to foreign countries.

**Comment by Chilledheart** [comment]
I am little interested about the dead things. I have my own naiveproxy client (both CLI and GUI) and supports english and simplified chinese. I have full control on this project which meets all my needs of accessing internet. Although this project is not perfect, I don't worry about the dead things at all.

Programatically, if you are talking about some features such as rule-based traffic, I did some investigation at the platform apis such as Windows' `GetTcpTable2`  call where you can get pid-tcp-connection mapping and then pid-program-name mapping. For this point of view, you can do it easily in your own code or naiveproxy. It is a piece of cake.

**Comment by klzgrad** [comment]
You are supported to not log Caddy forwardproxy traffic because logging is bad for your privacy!

No support is planned for Clash.
