### ISSUE TITLE
How enable prometheus metrics and access logging?

### ISSUE THREAD

**Issue by bluemiaomiao** [klzgrad/naiveproxy#595]
```nginx
{
  servers {
    metrics
  }
}

:443 {
  log {
    output file /var/log/naive/access.log
  }
}
```

When I set these configurations, Naive can successfully start without any error prompts, but the client's Naiveproxy can also connect successfully, but the proxy did not succeed.

**Comment by klzgrad** [comment]
Logging with Caddy forwardproxy is not recommended or supported.
