### ISSUE TITLE
How to compile naiveproxy for android?

### ISSUE THREAD

**Issue by vahidx4r4x** [klzgrad/naiveproxy#596]
Hi, 
I want to compile the latest version of naiveproxy for android from source. the nekobox and sagernet repos are not up-to-date.
Can someone help me?

**Comment by XiaoanHi** [comment]
You can refer to this：https://github.com/SagerNet/SagerNet/pull/588#issuecomment-1339026057,Or you can just use the compiled file from my fork

**Comment by vahidx4r4x** [comment]
> You can refer to this：[SagerNet/SagerNet#588 (comment)](https://github.com/SagerNet/SagerNet/pull/588#issuecomment-1339026057) you can just use the compiled file from my fork

i dont understand. shouldnt i use android studio to compile it?

**Comment by XiaoanHi** [comment]
> > You can refer to this：[SagerNet/SagerNet#588 (comment)](https://github.com/SagerNet/SagerNet/pull/588#issuecomment-1339026057) you can just use the compiled file from my fork
> 
> i dont understand. shouldnt i use android studio to compile it?

SagerNet provides Actions that are automatically compiled using the online environment. No need to use Android Studio.

**Comment by vahidx4r4x** [comment]
> > > You can refer to this：[SagerNet/SagerNet#588 (comment)](https://github.com/SagerNet/SagerNet/pull/588#issuecomment-1339026057) you can just use the compiled file from my fork
> > 
> > 
> > i dont understand. shouldnt i use android studio to compile it?
> 
> SagerNet provides Actions that are automatically compiled using the online environment. No need to use Android Studio.

Aha.
Can you tell me how to compile it? I mean step by step if it is possible for you? I never compiled before.

**Comment by klzgrad** [comment]
The code is available. Technical support is not available.

**Comment by zedifen** [comment]
This project provides naiveproxy as a command-line application. To run it on Android, you probably needs some setup, or call it from other GUI apps via JNI.

Fortunately it looks like the maintainer are testing the Android-plugin build (NekoBox compatible, since SagerNet's repo is now archived). You can find APK in the latest pre-release (i.e. [v120.0.6099.43-2](https://github.com/klzgrad/naiveproxy/releases/tag/v120.0.6099.43-2)).
