### ISSUE TITLE
[Naive Request] Integrate the naive client into naive caddy server as a single executable, reuse port 443 as source port, to build a private network similar to Tailscale

### ISSUE THREAD

**Issue by diyism** [klzgrad/naiveproxy#598]
I've verified that a modified naive caddy server can be connected behind some NAT,
just by sending some welcome udp packets:
https://github.com/caddyserver/caddy/compare/master...diyism:caddy:master

If we can integrate the naive client into naive caddy server as a single executable,
and reuse port 443 as source port, we can build a private mesh network similar to Tailscale.

**Comment by diyism** [comment]
@5l2, tailscale isn't stable in china sometimes, so I'm dreaming a single bundle version of naive-caddy and naive-client with the function of private mesh network and a tailscale-like machines list management page.

**Comment by klzgrad** [comment]
> as a single executable

But why? You can easily create a self-extracting and executing archive containing any number of binaries.
