### ISSUE TITLE
macos官方版太简陋，希望添加几个小功能

### ISSUE THREAD

**Issue by tudoubocai** [klzgrad/naiveproxy#599]
1、config.json文件能填入socks参数
2、能自动打开socks代理，关闭程序能自动关闭socks代理

小白，没技术，只能自己写两个脚本。一个开启socks同时运行naive，一个关闭socks。

**Comment by tudoubocai** [comment]
> NaiveProxy支持SOCKS。> 你的描述不清楚。macos的官方客户端，不能自动打开Mac的socks设置，退出时不能自动关闭socks设置。所以每次使用的时候除了终端运行./naive程序以外，还要手动到系统便好设置中打开socks代理。才能让mac上所有的软件访问代理网络。关闭naiveproxy代理后，又要手动关闭socks代理，mac才能正常上网。
我用shuttle编辑了快捷菜单来处理这个

**Comment by ArcCal** [comment]
你这个需求在这里肯定不会得到满足

**Comment by ArcCal** [comment]
既然自己有动手能力，就自己搞定吧

**Comment by klzgrad** [comment]
Out of scope.
