### ISSUE TITLE
怎么配置未认证用户看到的页面？

### ISSUE THREAD

**Issue by netheril96** [klzgrad/naiveproxy#60]
我想让未认证的用户看到别的页面，比如登录我的私有云的页面，这样流量看起来才不可疑。Trojan可以直接设定`remote_addr`, `remote_port`，那naiveproxy能设置吗？

**Comment by AttorneyFan** [comment]
you can specified what unauthenticated visitors can see in caddyfile, like this:

domain.example
**### root /var/www/html**
tls myemail@example.com
forwardproxy {
  basicauth user pass
  hide_ip
  hide_via
  probe_resistance secret.localhost
  upstream http://127.0.0.1:8080
}

**Comment by tomac4t** [comment]
这一部分是 caddy forwardproxy 插件处理的，要隐藏服务器是代理服务的事实需要使用 `probe_resistance` 指令（默认不启用），具体文档见：https://github.com/caddyserver/forwardproxy#security

这个抗探针指令是否启用区别在于：
- 不启用，密码验证错误，服务器返回 HTTP 407 Proxy Authentication Required
- 启用后，密码验证错误，服务器返回 HTTP 404 Not Found，以此达到抗探针的效果。

用 curl 可以在本地环境简单验证：
```bash
curl -v https://www.microsoft.com/robots.txt -x http://user:pass@127.0.0.1:2015
curl -v https://www.microsoft.com/robots.txt -x http://user:wrong@127.0.0.1:2015
```

> Trojan可以直接设定remote_addr, remote_port，那naiveproxy能设置吗？

forwardproxy 使用的是 HTTPS 代理，但 Trojan 不是标准 HTTPS 代理，前者区分是否是代理的方式是是否使用 HTTP CONNECT 建立链接的，所以不需要像 Trojan 那样有额外的 `remote_addr` 设置。直接放上页面就行。

**Comment by netheril96** [comment]
明白了
