### ISSUE TITLE
TLS handshake error 请作者帮忙

### ISSUE THREAD

**Issue by jiangnanan** [klzgrad/naiveproxy#602]
服务端提示 
{"level":"debug","ts":1702099533.5925567,"logger":"http.stdlib","msg":"http: TLS handshake error from 212.33.236.251:43736: read tcp 122.222.112.111:443->212.33.236.251::43736: read: connection reset by peer"}
偶尔可以偶尔不可以，客户端  [Naive] [1209/132504.736793:ERROR:ssl_client_socket_impl.cc(992)] handshake failed; returned -1, SSL error code 1, net_error -101

我确定我的443端口正常 ping.pe我验证过
也是偶尔可以偶尔不可以   刚申请的域名  namesilo里申请的，然后我用DNSPOD做解析，我试过用公用名 (CN)	R3
组织 (O)	Let's Encrypt 来申请证书，也会这样，然后我换成腾讯云的TrustAsia TLS RSA CA（1年）证书，也是这样，我试过用小火箭 用IP的话是可以的，但是用域名的话就是不行，访问google 提示ERR_CONNECTION_CLOSED ，服务器是centos7 的  所以我也搞不懂是哪里的问题，电脑端的话 时而行时而不行，电脑端用的是V2ray 大家有遇到这样情况的，都是怎么解决的谢谢

**Comment by klzgrad** [comment]
net_error -101是TCP RST
用wireshark看一下，reset是什么样子

**Comment by jiangnanan** [comment]
wireshark 截图如下

**Comment by jiangnanan** [comment]
wireshark 截图如下

**Comment by lp123sun** [comment]
移动的网络吧？我在移动网络也是这样，换联通网络就正常了。

**Comment by jiangnanan** [comment]
@lp123sun 电信网络感觉又像是被检测到，所以不知道什么情况，时而可以时而不可以

**Comment by jiangnanan** [comment]
@klzgrad ![44](https://github.com/klzgrad/naiveproxy/assets/71580782/545676e3-2a74-450e-ba0b-1ed890e47aa7)
这是截图请 是哪里出了问题吗

**Comment by jiangnanan** [comment]
@5l2 改成哪个域名，有推荐个吗谢谢

**Comment by jiangnanan** [comment]
@5l2 换了几个域名了，一直这样，但是小火箭直接用IP进行连接确很确定。。就是V2ray  nave 在CMD运行 就是不稳定。。以前不会这样的。。时而可以时而不可以，电信线路，联通线路 ，移动线路全试过了。。

**Comment by klzgrad** [comment]
65534是个什么端口，跟你特定的环境有关吧

**Comment by jiangnanan** [comment]
@klzgrad  65534 是我用 iptables -t nat -A PREROUTING -p tcp --dport 65534  -j REDIRECT --to-ports 443  转发的 为了防443，之前一直很正常用了几年都是这样操作所以和我的环境应该没有关系
