### ISSUE TITLE
use alternative http/https port and add multiple auth accounts

### ISSUE THREAD

**Issue by monkey-jsun** [klzgrad/naiveproxy#605]
I followed the readme.md file and got everything up and running.  Great!  Thanks!

I like to venture to tweak a couple of things, but I'm having troubles.  

The first challenge is to use alternative http/https ports(8080/8443).  I added the following directives to the Caddyfile and caddy starts up fine with the designated high ports.  However, when I open URL at http://<caddy.server>:8080, the browser redirects to https://<caddy.server>:443, instead of https://<caddy.server>:8443.   How do I achieve this?

```
{
        order forward_proxy before file_server
        https_port 8443
        http_port 8080
}
:8443, vpn.my.net {
        tls admin@my.net
        forward_proxy {
                basic_auth user password
                hide_ip
                hide_via
                probe_resistance
        }
        file_server {
                root /var/www/html
        }
}
```

My second challenge is to add multiple user accounts.  How do I do that?

BTW, I googled Caddyfile format and it seems quite different from what is used here.  For example, forward_proxy would become forwardproxy, and basic_auth becomes basicauth.  I'm quite lost.

**Comment by monkey-jsun** [comment]
Thanks for the pointer.  Do you know why the official Caddy document looks similar but not exactly the same?  For example, in your example we use "basic_auth", but in [the official Caddyfile document ](https://caddyserver.com/docs/caddyfile/directives)it uses "basicauth", which supports multiple users.  

There are others that also fall into this strange "similar but different" category, such as forward_proxy vs forwardproxy.

**Comment by klzgrad** [comment]
Multiple auth is fixed here https://github.com/klzgrad/forwardproxy/releases/tag/v2.7.6-naive
