### ISSUE TITLE
Blocked by reddit web site

### ISSUE THREAD

**Issue by Chilledheart** [klzgrad/naiveproxy#607]
While visiting the [reddit web site][reddit] in pc, I got blocked. I am using the old naiveproxy v114.0.5735.91-3 and chrome  120.0.6099.109 on linux.

![Screenshot from 2023-12-15 11-00-32](https://github.com/klzgrad/naiveproxy/assets/54673341/9362071a-92f4-45e9-9425-88dd3d8596ac)

[reddit]: https://www.reddit.com/r/rpcs3/comments/tqt1ko/clearing_up_some_avx512_misinformation_and_how_to/

**Comment by Chilledheart** [comment]
It's wired. I tried both of my servers (one of which is running on Azure) but no luck. It is probably related to the server's network but I don't have the chance to verify it. I am okay if others can verify it and close this issue.

**Comment by klzgrad** [comment]
Reddit seems to have increased ip blocking in recent days. Not related to naiveproxy.
