### ISSUE TITLE
打不开某些域名

### ISSUE THREAD

**Issue by noahge0923** [klzgrad/naiveproxy#609]
路由器上直接用passwall2连的naive，google，youtube正常，docs.gitlab.com、auth.docker.io等一些域名怎么都访问不了，分流中将这些域名设为直连，就能正常打开，但是在我的理解里，无论是直连还是代理应该都能打开，排查好几天了？能帮忙分析下有可能是哪里的问题吗？感谢🙏

**Comment by noahge0923** [comment]
passwall的日志我看了，确实走向代理了，但是解析出来的youtube ip就正常连接并且能打开，但是docs.gitlab.com的ip就打不开，这我十分不解。

**Comment by noahge0923** [comment]
服务器版本forward proxy 264，客户端版本openwrt的x64 119版本。

**Comment by noahge0923** [comment]
问题找到了，vps上没关ipv6。

**Comment by Ngwind** [comment]
> 问题找到了，vps上没关ipv6。

请问为什么要关ipv6呢。
