### ISSUE TITLE
有多個naiveproxy節點，HAPROXY的設定

### ISSUE THREAD

**Issue by kousyougi** [klzgrad/naiveproxy#61]
我最近把navieproxy搭配HAPROXY，照下面的接法。速度變得非常快。
但是HAPROXY只會檢查client端的socks是不是還活著，不知道naiveproxy_server還能不能連。所以有時候會莫名的卡住。

> naiveproxy_server_1:443--|gfw|--naiveproxy_client_1:1081(SOCKS)─┐
naiveproxy_server_2:443--|gfw|--naiveproxy_client_2:1082(SOCKS)─┤
naiveproxy_server_3:443--|gfw|--naiveproxy_client_3:1083(SOCKS)─┼─ HAPROXY:1079(SOCKS)
naiveproxy_server_4:443--|gfw|--naiveproxy_client_4:1084(SOCKS)─┘

請問有沒有辦法實現像下面這種接法

> naiveproxy_server_1:443--|gfw|─┐
naiveproxy_server_2:443--|gfw|─┤
naiveproxy_server_3:443--|gfw|─┼─ HAPROXY--naiveproxy_client:1080(SOCKS)
naiveproxy_server_4:443--|gfw|─┘

讓HAPROXY檢查naiveproxy_server是不是還活著？

**Comment by rampageX** [comment]
所有 naiveproxy_server 的 `user:pass` 全部一样就可以，haproxy 连接各个 naiveproxy_server，naiveproxy_client 连接 haproxy 的监听端口，之前 ss/ssr 负载均衡不都是这么做的。

**Comment by kousyougi** [comment]
我照下面的設定沒有辦法連，請問這樣看得出是哪裡出問題嗎？

naive的config.json
> {
  "listen": "socks://0.0.0.0:1079",
  "proxy": "https://user:password@127.0.0.1":1078,
  "padding": true
}

haproxy.cfg設定
> listen naive
        bind 0.0.0.0:1078
        mode    tcp
        balance roundrobin
		 server t1 a.server.com:443 check inter 1000 weight 1
		 server t2 b.server.com:443 check inter 1000 weight 1
		 server t3 c.server.com:443 check inter 1000 weight 1
		 server t4 d.server.com:443 check inter 1000 weight 1
		 server t5 e.server.com:443 check inter 1000 weight 1

**Comment by rampageX** [comment]
haproxy 开 status 看服务器是不是都是健康在线，再看 haproxy 和 naiveproxy 的 log.

**Comment by kousyougi** [comment]
haproxy的status大部分都是綠色的。
naiveproxy一直跳出下面的信息。

> ERR_PROXY_CONNECTION_FAILED
[0419/220043.367:ERROR:ssl_client_socket_impl.cc(941)] handshake failed; returned -1, SSL error code 1, net_error -107
[0419/220043.367:INFO:naive_proxy.cc(164)] Connection 67 closed: ERR_PROXY_CONNECTION_FAILED
[0419/220043.406:ERROR:ssl_client_socket_impl.cc(941)] handshake failed; returned -1, SSL error code 1, net_error -107
[0419/220043.406:INFO:naive_proxy.cc(164)] Connection 58 closed: ERR_PROXY_CONNECTION_FAILED

**Comment by tomac4t** [comment]
握手失败，很显然你的 HAProxy 没有 SSL，请自行修改本地端 naive 的配置文件。

**Comment by klzgrad** [comment]
虽然这个107错误并不是证书错误，但不测试也不清楚是什么错误。只肉眼看会发现

`"proxy": "https://user:password@127.0.0.1:1078"`

这里的域名与服务器返回证书的域名不符。

你在config.json加上
```
"host-resolver-rules": "MAP server.com:443 127.0.0.1:1078",
"proxy": "https://user:password@server.com",
```
这样还是有server.com跟a.server.com证书不符的问题。所以你几个服务器上的证书得用同一个域名，证书可以不同，域名要一样。这种约束就是运行在HTTPS之上的代价。

但是，在提出解决方案之前，能不能先解释一下需求？你只是要简单的负载平衡？因为我的理解中这种负载平衡跟“快”没有必然联系，你也可能被平衡到一个慢速服务器上。

**Comment by kousyougi** [comment]
我測試這邊的牆，同一個navieproxy大概用三五分鐘之後就會變非常慢。如果馬上切換到別的naiveproxy點，又可以連三五分鐘。我猜牆把不是白名單的境外IP，超出流量後故意做出這些干擾。
我台灣家用的NAS也是傳一定傳輸量就會被斷線，處於無法傳檔的狀態。

不用為了我這個需求作修改。覺得即使修改之後，牆只要調整一下干擾的策略，我這邊肯定又還是一下能上一下不能上。慘

謝謝

**Comment by Loyalsoldier** [comment]
Finally you will find out that the last and biggest problem is global QoS on ISP networks in China Mainland.
