### ISSUE TITLE
Other clients not shown in the readme

### ISSUE THREAD

**Issue by U201413497** [klzgrad/naiveproxy#611]
https://github.com/KevinSHIT/NaiveSharp

https://github.com/topoge/NgX

https://github.com/ali322/Nave

https://github.com/Qv2ray/QvPlugin-NaiveProxy

https://github.com/ExcitedCodes/NaiveGUI

https://github.com/Dobiec/NaiveproxyForAndroid

https://github.com/MatsuriDayo/Matsuri

**Comment by klzgrad** [comment]
They were in https://github.com/klzgrad/naiveproxy/issues/158.

None of them are actively maintained.
