### ISSUE TITLE
Chrome 121 is going to release

### ISSUE THREAD

**Issue by Chilledheart** [klzgrad/naiveproxy#613]
https://chromereleases.googleblog.com/2024/01/early-stable-for-desktop.html

From the Chrome Release Blog, Early Stable Release has updated to 121.0.6167.75 for Windows along with Android and iOS.

**Comment by klzgrad** [comment]
I use the version tracker linked in https://github.com/klzgrad/naiveproxy/wiki.

**Comment by Chilledheart** [comment]
Branch 122 is cut. [Stable Cut](https://chromium.googlesource.com/chromium/src.git/+/main/docs/process/release_cycle.md#stable-cut)
