### ISSUE TITLE
About provide Android binary

### ISSUE THREAD

**Issue by kvmb** [klzgrad/naiveproxy#615]
Hi, I found that there is no Android binary since v120.0.6099.43-2, I have been using it on Termux, can you provide it again in release ? I will be very grateful to you, thanks.

**Comment by klzgrad** [comment]
```
unzip naiveproxy-plugin-v121.0.6167.71-1-x86_64.apk lib/x86_64/libnaive.so
chmod +x lib/x86_64/libnaive.so
./lib/x86_64/libnaive.so --version
```
