### ISSUE TITLE
Naiveproxy Client-> transit server-> Naiveproxy Server ?

### ISSUE THREAD

**Issue by RqqZy** [klzgrad/naiveproxy#616]
如何多层代理naiveproxy, 像 Naiveproxy Client ->中转服务器 - > Naiveproxy Server

**Comment by klzgrad** [comment]
为什么？

**Comment by RqqZy** [comment]
> 为什么？
感谢回复 
我想搞个国内中转 现在用的 gost 用ss协议代理到Naiveproxy Client 在到Naiveproxy Server了 但是不知道为什么gost到naive client在内网不行只能在公网生效

**Comment by klzgrad** [comment]
NAT + iptables REDIRECT can work.
