### ISSUE TITLE
请问 naiveproxy 如何设置 dns 解锁网飞之类？

### ISSUE THREAD

**Issue by NeedforGit** [klzgrad/naiveproxy#618]
大家好，请问 naiveproxy 如何设置 dns 解锁网飞之类？

我把 vps 的系统 dns 改为解锁 dns 之后，naiveproxy 还是解锁不了网飞之类，换其他程序 如sing-box 解锁就没有问题。

这个问题一直困扰着我，求助大家，感谢！

**Comment by NeedforGit** [comment]
> Containerized service? You lack information and ask a question in the wrong place.

使用的是 openwrt 上的 passwall

**Comment by klzgrad** [comment]
https://github.com/klzgrad/naiveproxy/issues/577
