### ISSUE TITLE
Adding MIPS/MIPS64 release binaries?

### ISSUE THREAD

**Issue by KaraRyougi** [klzgrad/naiveproxy#62]
EdgeRouter 4 runs on Linux kernel 4.9 with a MIPS64 CPU. It also supports standard Debian repository packages. I would assume it can run naiveproxy smoothly. Can I ask for a binary release for MIPS or MIPS64 architecture? Thanks.

**Comment by klzgrad** [comment]
I would love to but unfortunately big-endian platforms are all unsupported by Chromium.
