### ISSUE TITLE
开启naive，并做配置多域名问题

### ISSUE THREAD

**Issue by Angel0726** [klzgrad/naiveproxy#620]
```
{ 
  order forward_proxy before reverse_proxy 
  order forward_proxy before file_server
}
aaa.com :443 { 
  tls sfddsf.com
  route { 
    forward_proxy { 
      basic_auth admin password 
      hide_ip 
      hide_via 
      probe_resistance 
      upstream socks5://127.0.0.1:1008
    } 
    file_server 
     { 
       root /srv 
     } 
  } 
}
bbb.com { 
  tls sfddsf.com
  reverse_proxy http://127.0.0.1:1080 
}
```
网站aaa.com、bbb.com都能打开，但是naiveproxy代理失效。

**Comment by Angel0726** [comment]
> > 但是naiveproxy代理失效
> What does that mean?
> I have deployed naiveproxy and websites on the server. Now, I not only hope to proxy naiveproxy according to the domain name of port 443, but also hope to access different websites according to different domain names of port 443.

> What have you done for debugging?
> Here are my config
```
{ 
  order forward_proxy before reverse_proxy 
  order forward_proxy before file_server
}
aaa.com :443 { 
  tls sfddsf.com
  route { 
    forward_proxy { 
      basic_auth admin password 
      hide_ip 
      hide_via 
      probe_resistance 
      upstream socks5://127.0.0.1:1008
    } 
    file_server 
     { 
       root /srv 
     } 
  } 
}
bbb.com { 
  tls sfddsf.com
  reverse_proxy http://127.0.0.1:1080 
}
```
> Where are the verbose level logs?
Logs will be uploaded later.

**Comment by Angel0726** [comment]
```
aaa.com :443 
tls sfddsf.com
route { 
  forward_proxy { 
    basic_auth admin password 
    hide_ip 
    hide_via 
    probe_resistance 
    upstream socks5://127.0.0.1:1008
  } 
  file_server 
  { 
       root /srv 
  }  
}
```

**Comment by yingziwu** [comment]
你的配置存在问题。

> ```
> { 
>   order forward_proxy before reverse_proxy 
>   order forward_proxy before file_server
> }
> aaa.com :443 { 
>   tls sfddsf.com
>   route { 
>     forward_proxy { 
>       basic_auth admin password 
>       hide_ip 
>       hide_via 
>       probe_resistance 
>       upstream socks5://127.0.0.1:1008
>     } 
>     file_server 
>      { 
>        root /srv 
>      } 
>   } 
> }
> bbb.com { 
>   tls sfddsf.com
>   reverse_proxy http://127.0.0.1:1080 
> }
> ```

并不是有效的 Caddyfile 文件。

通过 `caddy adapt` 可以发现至少两个明显的问题：
- `Error: Unexpected '{' on a new line; did you mean to place the '{' on the previous line?, at t.conf:16`
- `Error: parsing caddyfile tokens for 'tls': single argument must either be 'internal' or an email address, at t.conf:6`

修正上述错误后的配置文件如下：

```
{
	order forward_proxy before reverse_proxy
	order forward_proxy before file_server
}
aaa.com :443 {
	tls i@example.com
	route {
		forward_proxy {
			basic_auth admin password
			hide_ip
			hide_via
			probe_resistance
			upstream socks5://127.0.0.1:1008
		}
		file_server {
			root /srv
		}
	}
}
bbb.com {
	tls i@example.com
	reverse_proxy http://127.0.0.1:1080
}
```

其对应的 json 文件如下：

```json
{
  "apps": {
    "http": {
      "servers": {
        "srv0": {
          "listen": [
            ":443"
          ],
          "routes": [
            {
              "match": [
                {
                  "host": [
                    "bbb.com"
                  ]
                }
              ],
              "handle": [
                {
                  "handler": "subroute",
                  "routes": [
                    {
                      "handle": [
                        {
                          "handler": "reverse_proxy",
                          "upstreams": [
                            {
                              "dial": "127.0.0.1:1080"
                            }
                          ]
                        }
                      ]
                    }
                  ]
                }
              ],
              "terminal": true
            },
            {
              "handle": [
                {
                  "handler": "subroute",
                  "routes": [
                    {
                      "handle": [
                        {
                          "handler": "subroute",
                          "routes": [
                            {
                              "handle": [
                                {
                                  "auth_pass_deprecated": "password",
                                  "auth_user_deprecated": "admin",
                                  "handler": "forward_proxy",
                                  "hide_ip": true,
                                  "hide_via": true,
                                  "probe_resistance": {},
                                  "upstream": "socks5://127.0.0.1:1008"
                                },
                                {
                                  "handler": "file_server",
                                  "hide": [
                                    "./t.conf"
                                  ],
                                  "root": "/srv"
                                }
                              ]
                            }
                          ]
                        }
                      ]
                    }
                  ]
                }
              ],
              "terminal": true
            }
          ]
        }
      }
    },
    "tls": {
      "certificates": {
        "automate": [
          "aaa.com"
        ]
      },
      "automation": {
        "policies": [
          {
            "subjects": [
              "bbb.com",
              "aaa.com"
            ],
            "issuers": [
              {
                "email": "i@example.com",
                "module": "acme"
              },
              {
                "email": "i@example.com",
                "module": "zerossl"
              }
            ]
          }
        ]
      }
    }
  }
}
```

从解析后的 json 配置来看，naiveproxy Caddy 配置应该是没有问题的。

但注意到你使用了 `upstream`  参数，想问一下你是否配置好了相应的上游代理？如果未设置上游代理或上游代理无法正常工作，也将导致 naiveproxy 客户端无法正常运行。
建议移除  `upstream`  参数。

> I have deployed naiveproxy and websites on the server. Now, I not only hope to proxy naiveproxy according to the domain name of port 443, but also hope to access different websites according to different domain names of port 443.

根据你的目的，更加优雅一些的配置文件如下：

```json
{
  "apps": {
    "http": {
      "servers": {
        "srv0": {
          "listen": [":443"],
          "routes": [
            {
              "handle": [
                {
                  "auth_pass_deprecated": "password",
                  "auth_user_deprecated": "admin",
                  "handler": "forward_proxy",
                  "hide_ip": true,
                  "hide_via": true,
                  "probe_resistance": {}
                }
              ]
            },
            {
              "match": [
                {
                  "host": ["bbb.com"]
                }
              ],
              "handle": [
                {
                  "handler": "subroute",
                  "routes": [
                    {
                      "handle": [
                        {
                          "handler": "reverse_proxy",
                          "upstreams": [
                            {
                              "dial": "127.0.0.1:1080"
                            }
                          ]
                        }
                      ]
                    }
                  ]
                }
              ],
              "terminal": true
            },
            {
              "match": [
                {
                  "host": ["aaa.com"]
                }
              ],
              "handle": [
                {
                  "handler": "subroute",
                  "routes": [
                    {
                      "handle": [
                        {
                          "handler": "file_server",
                          "hide": ["./t.conf"],
                          "root": "/srv"
                        }
                      ]
                    }
                  ]
                }
              ],
              "terminal": true
            }
          ]
        }
      }
    },
    "tls": {
      "automation": {
        "policies": [
          {
            "subjects": ["bbb.com", "aaa.com"],
            "issuers": [
              {
                "email": "i@example.com",
                "module": "acme"
              },
              {
                "email": "i@example.com",
                "module": "zerossl"
              }
            ]
          }
        ]
      }
    }
  }
}
```

编写配置文件有几点需要注意：
1. forward_proxy handler 外不能有 match host。
2. 不能开启 [strict_sni_host](https://caddyserver.com/docs/json/apps/http/servers/#strict_sni_host)。

**Comment by Angel0726** [comment]
这个可以用

```
aaa.com :443 
tls sfddsf.com
route { 
  forward_proxy { 
    basic_auth admin password 
    hide_ip 
    hide_via 
    probe_resistance 
    upstream socks5://127.0.0.1:1008
  } 
  file_server 
  { 
       root /srv 
  }  
}
```
但是
```
{ 
  order forward_proxy before reverse_proxy 
  order forward_proxy before file_server
}
aaa.com :443 { 
  tls sfddsf.com
  route { 
    forward_proxy { 
      basic_auth admin password 
      hide_ip 
      hide_via 
      probe_resistance 
      upstream socks5://127.0.0.1:1008
    } 
    file_server 
     { 
       root /srv 
     } 
  } 
}
bbb.com { 
  tls sfddsf.com
  reverse_proxy http://127.0.0.1:1080 
}```

**Comment by Angel0726** [comment]
我测试了下面的配置不可以
```
{ 
  order forward_proxy before reverse_proxy 
  order forward_proxy before file_server
}
aaa.com :443 { 
  tls sfddsf.com
  route { 
    forward_proxy { 
      basic_auth admin password 
      hide_ip 
      hide_via 
      probe_resistance 
      upstream socks5://127.0.0.1:1008
    } 
    file_server 
     { 
       root /srv 
     } 
  } 
}
bbb.com { 
  tls sfddsf.com
  reverse_proxy http://127.0.0.1:1080 
}
```

**Comment by Angel0726** [comment]
> 你的配置存在问题。
> 
> > ```
> > { 
> >   order forward_proxy before reverse_proxy 
> >   order forward_proxy before file_server
> > }
> > aaa.com :443 { 
> >   tls sfddsf.com
> >   route { 
> >     forward_proxy { 
> >       basic_auth admin password 
> >       hide_ip 
> >       hide_via 
> >       probe_resistance 
> >       upstream socks5://127.0.0.1:1008
> >     } 
> >     file_server 
> >      { 
> >        root /srv 
> >      } 
> >   } 
> > }
> > bbb.com { 
> >   tls sfddsf.com
> >   reverse_proxy http://127.0.0.1:1080 
> > }
> > ```
> 
> 并不是有效的 Caddyfile 文件。
> 
> 通过 `caddy adapt` 可以发现至少两个明显的问题：
> - `Error: Unexpected '{' on a new line; did you mean to place the '{' on the previous line?, at t.conf:16`
> - `Error: parsing caddyfile tokens for 'tls': single argument must either be 'internal' or an email address, at t.conf:6`
> 
> 修正上述错误后的配置文件如下：
> 
> ```
> {
> 	order forward_proxy before reverse_proxy
> 	order forward_proxy before file_server
> }
> aaa.com :443 {
> 	tls i@example.com
> 	route {
> 		forward_proxy {
> 			basic_auth admin password
> 			hide_ip
> 			hide_via
> 			probe_resistance
> 			upstream socks5://127.0.0.1:1008
> 		}
> 		file_server {
> 			root /srv
> 		}
> 	}
> }
> bbb.com {
> 	tls i@example.com
> 	reverse_proxy http://127.0.0.1:1080
> }
> ```
> 
> 其对应的 json 文件如下：
> 
> ```json
> {
>   "apps": {
>     "http": {
>       "servers": {
>         "srv0": {
>           "listen": [
>             ":443"
>           ],
>           "routes": [
>             {
>               "match": [
>                 {
>                   "host": [
>                     "bbb.com"
>                   ]
>                 }
>               ],
>               "handle": [
>                 {
>                   "handler": "subroute",
>                   "routes": [
>                     {
>                       "handle": [
>                         {
>                           "handler": "reverse_proxy",
>                           "upstreams": [
>                             {
>                               "dial": "127.0.0.1:1080"
>                             }
>                           ]
>                         }
>                       ]
>                     }
>                   ]
>                 }
>               ],
>               "terminal": true
>             },
>             {
>               "handle": [
>                 {
>                   "handler": "subroute",
>                   "routes": [
>                     {
>                       "handle": [
>                         {
>                           "handler": "subroute",
>                           "routes": [
>                             {
>                               "handle": [
>                                 {
>                                   "auth_pass_deprecated": "password",
>                                   "auth_user_deprecated": "admin",
>                                   "handler": "forward_proxy",
>                                   "hide_ip": true,
>                                   "hide_via": true,
>                                   "probe_resistance": {},
>                                   "upstream": "socks5://127.0.0.1:1008"
>                                 },
>                                 {
>                                   "handler": "file_server",
>                                   "hide": [
>                                     "./t.conf"
>                                   ],
>                                   "root": "/srv"
>                                 }
>                               ]
>                             }
>                           ]
>                         }
>                       ]
>                     }
>                   ]
>                 }
>               ],
>               "terminal": true
>             }
>           ]
>         }
>       }
>     },
>     "tls": {
>       "certificates": {
>         "automate": [
>           "aaa.com"
>         ]
>       },
>       "automation": {
>         "policies": [
>           {
>             "subjects": [
>               "bbb.com",
>               "aaa.com"
>             ],
>             "issuers": [
>               {
>                 "email": "i@example.com",
>                 "module": "acme"
>               },
>               {
>                 "email": "i@example.com",
>                 "module": "zerossl"
>               }
>             ]
>           }
>         ]
>       }
>     }
>   }
> }
> ```
> 
> 从解析后的 json 配置来看，naiveproxy Caddy 配置应该是没有问题的。
> 
> 但注意到你使用了 `upstream`  参数，想问一下你是否配置好了相应的上游代理？如果未设置上游代理或上游代理无法正常工作，也将导致 naiveproxy 客户端无法正常运行。
> 建议移除  `upstream`  参数。
> 
> > I have deployed naiveproxy and websites on the server. Now, I not only hope to proxy naiveproxy according to the domain name of port 443, but also hope to access different websites according to different domain names of port 443.
> 
> 根据你的目的，更加优雅一些的配置文件如下：
> 
> ```json
> {
>   "apps": {
>     "http": {
>       "servers": {
>         "srv0": {
>           "listen": [":443"],
>           "routes": [
>             {
>               "handle": [
>                 {
>                   "auth_pass_deprecated": "password",
>                   "auth_user_deprecated": "admin",
>                   "handler": "forward_proxy",
>                   "hide_ip": true,
>                   "hide_via": true,
>                   "probe_resistance": {}
>                 }
>               ]
>             },
>             {
>               "match": [
>                 {
>                   "host": ["bbb.com"]
>                 }
>               ],
>               "handle": [
>                 {
>                   "handler": "subroute",
>                   "routes": [
>                     {
>                       "handle": [
>                         {
>                           "handler": "reverse_proxy",
>                           "upstreams": [
>                             {
>                               "dial": "127.0.0.1:1080"
>                             }
>                           ]
>                         }
>                       ]
>                     }
>                   ]
>                 }
>               ],
>               "terminal": true
>             },
>             {
>               "match": [
>                 {
>                   "host": ["aaa.com"]
>                 }
>               ],
>               "handle": [
>                 {
>                   "handler": "subroute",
>                   "routes": [
>                     {
>                       "handle": [
>                         {
>                           "handler": "file_server",
>                           "hide": ["./t.conf"],
>                           "root": "/srv"
>                         }
>                       ]
>                     }
>                   ]
>                 }
>               ],
>               "terminal": true
>             }
>           ]
>         }
>       }
>     },
>     "tls": {
>       "automation": {
>         "policies": [
>           {
>             "subjects": ["bbb.com", "aaa.com"],
>             "issuers": [
>               {
>                 "email": "i@example.com",
>                 "module": "acme"
>               },
>               {
>                 "email": "i@example.com",
>                 "module": "zerossl"
>               }
>             ]
>           }
>         ]
>       }
>     }
>   }
> }
> ```
> 
> 编写配置文件有几点需要注意：
> 1. forward_proxy handler 外不能有 match host。
> 2. 不能开启 [strict_sni_host](https://caddyserver.com/docs/json/apps/http/servers/#strict_sni_host)。

upstream后边用v2ray做了分流。你可以看我上面的介绍，不做域名代理是可以使用的

**Comment by Angel0726** [comment]
是不是没有办法开启naive并使用多域名

**Comment by klzgrad** [comment]
A question for Caddy

**Comment by android1122** [comment]
> 你的配置存在问题。
> 
> > ```
> > { 
> >   order forward_proxy before reverse_proxy 
> >   order forward_proxy before file_server
> > }
> > aaa.com :443 { 
> >   tls sfddsf.com
> >   route { 
> >     forward_proxy { 
> >       basic_auth admin password 
> >       hide_ip 
> >       hide_via 
> >       probe_resistance 
> >       upstream socks5://127.0.0.1:1008
> >     } 
> >     file_server 
> >      { 
> >        root /srv 
> >      } 
> >   } 
> > }
> > bbb.com { 
> >   tls sfddsf.com
> >   reverse_proxy http://127.0.0.1:1080 
> > }
> > ```
> 
> 并不是有效的 Caddyfile 文件。
> 
> 通过 `caddy adapt` 可以发现至少两个明显的问题：
> 
> * `Error: Unexpected '{' on a new line; did you mean to place the '{' on the previous line?, at t.conf:16`
> * `Error: parsing caddyfile tokens for 'tls': single argument must either be 'internal' or an email address, at t.conf:6`
> 
> 修正上述错误后的配置文件如下：
> 
> ```
> {
> 	order forward_proxy before reverse_proxy
> 	order forward_proxy before file_server
> }
> aaa.com :443 {
> 	tls i@example.com
> 	route {
> 		forward_proxy {
> 			basic_auth admin password
> 			hide_ip
> 			hide_via
> 			probe_resistance
> 			upstream socks5://127.0.0.1:1008
> 		}
> 		file_server {
> 			root /srv
> 		}
> 	}
> }
> bbb.com {
> 	tls i@example.com
> 	reverse_proxy http://127.0.0.1:1080
> }
> ```
> 
> 其对应的 json 文件如下：
> 
> {
>   "apps": {
>     "http": {
>       "servers": {
>         "srv0": {
>           "listen": [
>             ":443"
>           ],
>           "routes": [
>             {
>               "match": [
>                 {
>                   "host": [
>                     "bbb.com"
>                   ]
>                 }
>               ],
>               "handle": [
>                 {
>                   "handler": "subroute",
>                   "routes": [
>                     {
>                       "handle": [
>                         {
>                           "handler": "reverse_proxy",
>                           "upstreams": [
>                             {
>                               "dial": "127.0.0.1:1080"
>                             }
>                           ]
>                         }
>                       ]
>                     }
>                   ]
>                 }
>               ],
>               "terminal": true
>             },
>             {
>               "handle": [
>                 {
>                   "handler": "subroute",
>                   "routes": [
>                     {
>                       "handle": [
>                         {
>                           "handler": "subroute",
>                           "routes": [
>                             {
>                               "handle": [
>                                 {
>                                   "auth_pass_deprecated": "password",
>                                   "auth_user_deprecated": "admin",
>                                   "handler": "forward_proxy",
>                                   "hide_ip": true,
>                                   "hide_via": true,
>                                   "probe_resistance": {},
>                                   "upstream": "socks5://127.0.0.1:1008"
>                                 },
>                                 {
>                                   "handler": "file_server",
>                                   "hide": [
>                                     "./t.conf"
>                                   ],
>                                   "root": "/srv"
>                                 }
>                               ]
>                             }
>                           ]
>                         }
>                       ]
>                     }
>                   ]
>                 }
>               ],
>               "terminal": true
>             }
>           ]
>         }
>       }
>     },
>     "tls": {
>       "certificates": {
>         "automate": [
>           "aaa.com"
>         ]
>       },
>       "automation": {
>         "policies": [
>           {
>             "subjects": [
>               "bbb.com",
>               "aaa.com"
>             ],
>             "issuers": [
>               {
>                 "email": "i@example.com",
>                 "module": "acme"
>               },
>               {
>                 "email": "i@example.com",
>                 "module": "zerossl"
>               }
>             ]
>           }
>         ]
>       }
>     }
>   }
> }
> 从解析后的 json 配置来看，naiveproxy Caddy 配置应该是没有问题的。
> 
> 但注意到你使用了 `upstream` 参数，想问一下你是否配置好了相应的上游代理？如果未设置上游代理或上游代理无法正常工作，也将导致 naiveproxy 客户端无法正常运行。 建议移除 `upstream` 参数。
> 
> > I have deployed naiveproxy and websites on the server. Now, I not only hope to proxy naiveproxy according to the domain name of port 443, but also hope to access different websites according to different domain names of port 443.
> 
> 根据你的目的，更加优雅一些的配置文件如下：
> 
> {
>   "apps": {
>     "http": {
>       "servers": {
>         "srv0": {
>           "listen": [":443"],
>           "routes": [
>             {
>               "handle": [
>                 {
>                   "auth_pass_deprecated": "password",
>                   "auth_user_deprecated": "admin",
>                   "handler": "forward_proxy",
>                   "hide_ip": true,
>                   "hide_via": true,
>                   "probe_resistance": {}
>                 }
>               ]
>             },
>             {
>               "match": [
>                 {
>                   "host": ["bbb.com"]
>                 }
>               ],
>               "handle": [
>                 {
>                   "handler": "subroute",
>                   "routes": [
>                     {
>                       "handle": [
>                         {
>                           "handler": "reverse_proxy",
>                           "upstreams": [
>                             {
>                               "dial": "127.0.0.1:1080"
>                             }
>                           ]
>                         }
>                       ]
>                     }
>                   ]
>                 }
>               ],
>               "terminal": true
>             },
>             {
>               "match": [
>                 {
>                   "host": ["aaa.com"]
>                 }
>               ],
>               "handle": [
>                 {
>                   "handler": "subroute",
>                   "routes": [
>                     {
>                       "handle": [
>                         {
>                           "handler": "file_server",
>                           "hide": ["./t.conf"],
>                           "root": "/srv"
>                         }
>                       ]
>                     }
>                   ]
>                 }
>               ],
>               "terminal": true
>             }
>           ]
>         }
>       }
>     },
>     "tls": {
>       "automation": {
>         "policies": [
>           {
>             "subjects": ["bbb.com", "aaa.com"],
>             "issuers": [
>               {
>                 "email": "i@example.com",
>                 "module": "acme"
>               },
>               {
>                 "email": "i@example.com",
>                 "module": "zerossl"
>               }
>             ]
>           }
>         ]
>       }
>     }
>   }
> }
> 编写配置文件有几点需要注意：
> 
> 1. forward_proxy handler 外不能有 match host。
> 2. 不能开启 [strict_sni_host](https://caddyserver.com/docs/json/apps/http/servers/#strict_sni_host)。

你好，大佬，现在我遇见的问题跟这个类似。
我用有一台服务器，上面有多个域名，我用的json配置，然后在routes下面配置match，配置其中一个host匹配时才会去执行
              "handle": [
                {
                  "auth_pass_deprecated": "password",
                  "auth_user_deprecated": "admin",
                  "handler": "forward_proxy",
                  "hide_ip": true,
                  "hide_via": true,
                  "probe_resistance": {}
                }
              ]
然后我看了你的回复之后：
1. forward_proxy handler 外不能有 match host。
2. 不能开启 [strict_sni_host](https://caddyserver.com/docs/json/apps/http/servers/#strict_sni_host)
我现在就是卡在1上面，目前这个host下的网站可以正常访问，但是foward_proxy无法访问，请问我这个只能就是，将fowad_proxy放在match之上是吧，那不是意味着所有的这台服务器的域名都可以使用？
