### ISSUE TITLE
NaïveProxy plugin for NB4 does not connect if use Domain as server address

### ISSUE THREAD

**Issue by privatesupport** [klzgrad/naiveproxy#621]
Hi
I`m using NekoBox For Android 1.3.0 with NaïveProxy plugin v121.
When I use Domain (same as sni) as server address it will not connect but when I use IP (assigned to that domain) as server address it connects successfully.
In settings for "Domain Strategy for Server address" I set "prefer ipv4" but not working too.
And there is no helpful logs in logs menu.
Is it bug ? or excepted behavior?
I'm not sure if it is related to plugin or NekoBox For Android itself... so, sorry if it's not related.

**Comment by klzgrad** [comment]
Cannot reproduce.
