### ISSUE TITLE
被GFW识别了吗？为啥经常会突然的访问不了

### ISSUE THREAD

**Issue by opser-gavin** [klzgrad/naiveproxy#624]
被GFW识别了吗？为啥今天经常会突然的用不了，但是我的同节点所在的网站是可以正常访问的
：我用的一个日本aws节点做的caddy，然后用naiveproxy代理+chrome插件科学上网（大家应该都是这样的吧？）

今天遇到很多次，很频繁，google/youtube/github访问不了，但是访问我这个aws节点上的web站点就可以。
这是怎么回事？是被GFW识别到了过滤限制了吗？有知道的大佬吗

**Comment by irgfw** [comment]
It is "gray-listed" on IranGFW. very bad connection and high jitter. mostly blocked on some ISPs in Iran.

**Comment by tripodsun** [comment]
我今天也突然连不上，服务器本身是可以连的

**Comment by Angel0726** [comment]
一样的问题，请问你们解决了吗

**Comment by lp123sun** [comment]
eu.org域名被封了

**Comment by beaglezeng** [comment]
> eu.org域名被封了

我用eu.org域名的，也是无法访问

**Comment by openips** [comment]
花钱买个域名吧 我这没事

**Comment by woshichenghaibo** [comment]
不能直接用吗？非要用浏览器插件吗？不能用小蓝猫是吗？

**Comment by Chilledheart** [comment]
TLS协议访问指定域名，除非是用了ECH，否则域名是明文的出现的，这个最好封

**Comment by Ngwind** [comment]
eu.org 这个域名 国内不太行了。自己花钱买个其他的便宜域名吧

**Comment by ArcCal** [comment]
弄个看上去正常点的域名，比如.com, .org的，也花不了几个钱 会省去很多烦恼

**Comment by daoistyoudao** [comment]
我前两天更新最新release后出现手机连接不上，我以为是手机客户端的问题。。。
昨天晚上电脑上原生client也连不上了，今天早上又好了。看来确实不太稳
手机上用小火箭开启fragment后也能用了
