### ISSUE TITLE
新版的forwardproxy的caddy配置文件和老版的不兼容，通过脚本更新服务就挂掉了（forwardproxy没地方发，就发这来了）

### ISSUE THREAD

**Issue by kennykong** [klzgrad/naiveproxy#626]
报错：
loading new config: loading http app module: provision http: server srv0: setting up route handlers: route 0: loading handler modules: position 0: loading module 'subroute': provision http.handlers.subroute: setting up subroutes: route 0: loading handler modules: position 0: loading module 'forward_proxy': decoding module config: http.handlers.forward_proxy: json: unknown field "auth_pass_deprecated"

很多人用的是这个脚本：
https://github.com/imajeason/nas_tools/blob/main/NaiveProxy/naive.sh

**Comment by kennykong** [comment]
就是forwardproxy（v2.7.6-naive）这一版，之前都好的

**Comment by klzgrad** [comment]
auth_pass_deprecated

已经预告了deprecated，没有义务要兼容

**Comment by jiaczh** [comment]
@klzgrad 问下 那这个参数要改成什么样的呢? 搜了下没搜到。。。 谢谢

**Comment by zedifen** [comment]
I think rather than "finding an alternative/solution for a deprecation", it would be better and easier to find out about things' that are currently available and figure out what to do with them.
