### ISSUE TITLE
go version 1.22.0編譯,json參數無法識別

### ISSUE THREAD

**Issue by sophauer** [klzgrad/naiveproxy#627]
環境
centos 7.9
go version 1.22.0

編譯:
go install github.com/caddyserver/xcaddy/cmd/xcaddy@latest
/root/work/bin/xcaddy build --with github.com/caddyserver/forwardproxy@caddy2=github.com/klzgrad/forwardproxy@naive
mv caddy /usr/local/bin/

執行
/usr/local/bin/caddy run --environ --config /etc/naive.json

報錯;
forward_proxy: json: unknown field "auth_user_deprecated"

**Comment by klzgrad** [comment]
auth_pass_deprecated被移除了

**Comment by jiaczh** [comment]
@sophauer , 问下参数怎么修改呀? 感谢

**Comment by jiaczh** [comment]
> > @sophauer , 问下参数怎么修改呀? 感谢
> 
> 用auth_credentials替代,具体方法你可以去caddy官网搜下

搜了下官网里没有关于auth_credentials的东西呀。。 可以分享下在哪里找到的么。 感谢!!

**Comment by zedifen** [comment]
@jiaczh Have you checked [`forwardproxy`'s README](https://github.com/klzgrad/forwardproxy) by any chance?
