### ISSUE TITLE
bug,密码包含@会报错

### ISSUE THREAD

**Issue by sophauer** [klzgrad/naiveproxy#628]
举例,用户跟密码,分别是user  456@abc
client side 的json:
{
  "listen": "socks://0.0.0.0:1082",
  "proxy": "https://user:456@abc@exsamople.com:443"
}

navie client.json
报错
Invalid proxy URL

包含#!*&这些特殊字元都会报同样错误

**Comment by zedifen** [comment]
Have you tried URL-encoding your password? 

https://url.spec.whatwg.org/#set-the-password

I modify the code to make it print proxy password out, and this is the output be-like:

```
./out/Release/naive --proxy='https://user:456%40abc@exsamople.com:443'
Proxy password is: 456@abc
```
