### ISSUE TITLE
是否支持单端口复用?

### ISSUE THREAD

**Issue by sophauer** [klzgrad/naiveproxy#629]
我想把旁路由的CPU效能发挥起来,每个Core执行一个naiveproxy线程,全listen在同一个1080端口
但貌似naiveproxy的usage文档里找不到关于port reuse的描述

请问是否不支持单端口复用?
如果是,有没有其他路线可以实现?

**Comment by ArcCal** [comment]
软件需要用户去干预用几个核或者哪几个核心吗

**Comment by klzgrad** [comment]
https://github.com/klzgrad/naiveproxy/releases/tag/v122.0.6261.43-2

**Comment by ArcCal** [comment]
> https://github.com/klzgrad/naiveproxy/releases/tag/v122.0.6261.43-2

那这个版本咋用呢

**Comment by klzgrad** [comment]
Run 8 workers for port 1080:
```
for i in $(seq 8); do
  ./naive --listen=socks://0.0.0.0:1080 &
done
```

**Comment by Chilledheart** [comment]
It might be better if you pin the process to a specific core such as:

```
for i in $(seq 8); do
  taskset -c $i ./naive --listen=socks://0.0.0.0:1080 &
done
```
Ref: https://stackoverflow.com/questions/33994983/assigning-a-cpu-core-to-a-process-linux

**Comment by zedifen** [comment]
I'm wondering if it would be better (or possible) to harness multiple CPU core by multi-threading within naiveproxy?
