### ISSUE TITLE
Add support for Synology DSM?

### ISSUE THREAD

**Issue by KaraRyougi** [klzgrad/naiveproxy#63]
Synology DSM is basically customized Debian that does not use dpkg as package manager. The problem is it has legacy version of `libnss3` (and `libnss3-nssdb`). I can successfully run naiveproxy after copy&paste all the necessary libraries from Ubuntu repository (which means messing around with Synology's own versions of libraries). I think it's better to have statically linked libraries compiled into the program, just like what has been done for OpenWRT. Thanks!

**Comment by klzgrad** [comment]
I can't find the source of Synology DSM and I don't know how to build it. There is no static linking for OpenWrt builds.

**Comment by klzgrad** [comment]
I'll consider this issue abandoned.
