### ISSUE TITLE
version v122.0.6261.43-2 won't work at arm 64 platform

### ISSUE THREAD

**Issue by sophauer** [klzgrad/naiveproxy#630]
hi
just downloaded naiveproxy-v122.0.6261.43-2-linux-arm.tar.xz for ARM 64 platform
file info:
naive: ELF 32-bit LSB pie executable, ARM, EABI5 version 1 (SYSV), dynamically linked, interpreter /lib/ld-linux-armhf.so.3, for GNU/Linux 3.2.0, BuildID[sha1]=9443e5efe0015d20a809e3a903a7f120c133ffb8, not stripped

runas root. naive naive.json
bash: naive: cannot execute: required file not found

maybe need arm64 binary?

**Comment by klzgrad** [comment]
You answer it yourself.

**Comment by ArcCal** [comment]
😄

**Comment by ArcCal** [comment]
是你自己不会用，不是软件的问题 


把配置文件改名为config.json

或

naive -c /path/to/config.json

就好了
