### ISSUE TITLE
这个是什么问题 ~/go/bin/xcaddy build --with github.com/caddyserver/forwardproxy@caddy2=github.com/klzgrad/forwardproxy@naive 运行这个命令的报错

### ISSUE THREAD

**Issue by zzduci** [klzgrad/naiveproxy#634]
go: added golang.org/x/mod v0.11.0
go: added golang.org/x/net v0.17.0
go: added golang.org/x/sys v0.14.0
go: added golang.org/x/term v0.13.0
go: added golang.org/x/text v0.13.0
go: added golang.org/x/tools v0.10.0
go: added google.golang.org/protobuf v1.31.0
2024/03/30 04:55:08 [INFO] exec (timeout=0s): /usr/bin/go get -d -v  
go: downloading github.com/klauspost/compress v1.17.0
caddy imports
        github.com/caddyserver/caddy/v2/modules/standard imports
        github.com/caddyserver/caddy/v2/modules/caddyhttp/standard imports
        github.com/caddyserver/caddy/v2/modules/caddyhttp/encode/gzip imports
        github.com/klauspost/compress/gzip: github.com/klauspost/compress@v1.17.0: reading https://proxy.golang.org/github.com/klauspost/compress/@v/v1.17.0.zip: 403 Forbidden
caddy imports
        github.com/caddyserver/caddy/v2/modules/standard imports
        github.com/caddyserver/caddy/v2/modules/caddyhttp/standard imports
        github.com/caddyserver/caddy/v2/modules/caddyhttp/encode/zstd imports
        github.com/klauspost/compress/zstd: github.com/klauspost/compress@v1.17.0: reading https://proxy.golang.org/github.com/klauspost/compress/@v/v1.17.0.zip: 403 Forbidden
caddy imports
        github.com/caddyserver/caddy/v2/modules/standard imports
        github.com/caddyserver/caddy/v2/modules/caddypki/acmeserver imports
        github.com/smallstep/certificates/acme imports
        github.com/smallstep/go-attestation/attest imports
        github.com/google/go-tpm/legacy/tpm2/credactivation imports
        crypto/ecdh: package crypto/ecdh is not in GOROOT (/usr/lib/go-1.19/src/crypto/ecdh)
2024/03/30 04:55:22 [FATAL] exit status 1

**Comment by klzgrad** [comment]
https://github.com/klzgrad/naiveproxy/commit/2a2ff37f5201ea4bbda29413998f736edb296a16

**Comment by zzduci** [comment]
> [2a2ff37](https://github.com/klzgrad/naiveproxy/commit/2a2ff37f5201ea4bbda29413998f736edb296a16)

没有明白是怎么解决这个问题

**Comment by zzduci** [comment]
> [2a2ff37](https://github.com/klzgrad/naiveproxy/commit/2a2ff37f5201ea4bbda29413998f736edb296a16)

可以详细一点吗，谢谢

**Comment by zedifen** [comment]
@zzduci The `forwardproxy` changed their main branch several months ago, so did the naiveproxy's fork. However, it seems that the build instructions on project's README are outdated. It's fixed now via the commit mentioned by the author. Run the updated command again to see if things works.

**Comment by zzduci** [comment]
> @zzduci The `forwardproxy` changed their main branch several months ago, so did the naiveproxy's fork. However, it seems that the build instructions on project's README are outdated. It's fixed now via the commit mentioned by the author. Run the updated command again to see if things works.

thanks for your help,you are a kind man,i try another way ,it is working now
