### ISSUE TITLE
The writing issue with probe resistance requiring authentication in the JSON of forwardproxy v2.7.6-naive. （forwardproxy   v2.7.6-naive的josn中probe resistance requires authentication写法问题)

### ISSUE THREAD

**Issue by Trinoe** [klzgrad/naiveproxy#636]
在新版的naiveproxy的服务端forwardproxy插件  v2.7.6-naive 中
旧版的身份验证写法“auth_user_deprecated”和“auth_pass_deprecated”已经无法识别
因该用什么替代？
In the new version of the NaiveProxy server's ForwardProxy plugin v2.7.6-naive, the old authentication syntax "auth_user_deprecated" and "auth_pass_deprecated" are no longer recognized. 
What should be used as replacements?

我尝试了"auth_user" 和"auth_pass"但仍是错误的
I tried "auth_user" and "auth_pass", but it still doesn't work.

![Snipaste_2024-04-04_18-08-55](https://github.com/klzgrad/naiveproxy/assets/139218234/f022a399-0e09-453c-b3cc-44bc6ffbdcfc)

**Comment by Trinoe** [comment]
Thank you very much for helping me resolve this issue! I am truly grateful for your assistance!

**Comment by gili-gili** [comment]
In linux
`printf 'user:pass' | base64 | tr --delete '\n' | base64`

In powershell
`[System.Convert]::ToBase64String([System.Text.Encoding]::UTF8.GetBytes([System.Convert]::ToBase64String([System.Text.Encoding]::UTF8.GetBytes("username:password"))))`
