### ISSUE TITLE
请问现在iOS上没有支持naive的了吗

### ISSUE THREAD

**Issue by daoistyoudao** [klzgrad/naiveproxy#645]
从最新release更新quic后，除了sing-box还能继续用naive，其它都用不了了，window上v2rayn用xray内核已经连不上了，iOS上目前好像就真的没办法用了。

**Comment by Chilledheart** [comment]
sing-box doesn't use quic support, that's why it still works.

for quic fix see #640

**Comment by klzgrad** [comment]
不知道你在问什么问题
