### ISSUE TITLE
how to deploy naiveproxy server side without caddy?

### ISSUE THREAD

**Issue by yunfan** [klzgrad/naiveproxy#652]
hi, in the file `USAGE.txt` , it said 

```
It works as both a proxy client and a proxy server or together.
```

so i am very interesting of how to deploy it to works as a proxy server?
since the document only shows how to use a caddy plugin for server side, i 
cant find any text about the topic, so i commit this issue, i am sorry if its abuse

**Comment by klzgrad** [comment]
https://github.com/klzgrad/naiveproxy/wiki/HAProxy-Setup

**Comment by yunfan** [comment]
> https://github.com/klzgrad/naiveproxy/wiki/HAProxy-Setup

thanks, i had checked that article, but still misunderstand

in that article you had a tinyproxy which listen on 8888 while you had a naive server listen on 8080, and neither of your haproxy and tinyproxy 's configuration do not has any section about forwarding incoming request to 8080 port which naive listened

also is it possible to use nginx as the front entry? and naive as the backend of nginx?

**Comment by klzgrad** [comment]
> You can also use NaiveProxy as the forward proxy

tinyproxy or naive server is either or. HAProxy is a reverse proxy that forwards to either tinyproxy or naive server.

> nginx

Nginx isn't capable of HTTP/2 reverse proxying. No.
