### ISSUE TITLE
Feature request: proxy chain

### ISSUE THREAD

**Issue by Zephor5** [klzgrad/naiveproxy#654]
I want to use naiveproxy in an environment that I have to use a normal http proxy to connect to my caddy server, how can I get this done?

my pc -> naiveproxy -> normal http proxy (out of my control) -> my caddy server -> net

**Comment by klzgrad** [comment]
It is in the realm of the possible, but you have to prove why your use request is necessary without easy workaround and is general enough for not just your own use case.

**Comment by Zephor5** [comment]
@klzgrad There are companies which have internal work network and prevent staff from connecting internal by default, and provide unified proxy to connect. That's the case. It's relatively niche.
I'm reading the source code but I don't familiar with c++, if you don't have time to do this recently, can you give me some hint about the source code where I can try to sovle this.

**Comment by Zephor5** [comment]
@5l2 I don't think ProxyChains will handle the case.

**Comment by ArcCal** [comment]
小火箭的Proxy Pass功能不就可以达到这个目的？

**Comment by klzgrad** [comment]
Chrome supports proxy chains.

The request is to expose it in naiveproxy.

**Comment by klzgrad** [comment]
https://github.com/klzgrad/naiveproxy/releases/tag/v126.0.6478.40-2

?

**Comment by Zephor5** [comment]
It worked
