### ISSUE TITLE
to review caddy-tailscale HTTP3?

### ISSUE THREAD

**Issue by diyism** [klzgrad/naiveproxy#655]
@klzgrad,

https://github.com/tailscale/caddy-tailscale/issues/33

三周前作者说支持http3, 但是不支持 disguise traffic,
有办法让 caddy-tailscale HTTP3的流量包含naive proxy的padding及multiplexing 功能么?

如果能支持disguise traffic, 用开源的 https://github.com/juanfont/headscale 就可以很方便可靠地
跟国内组建不被GFW封锁的私人网络了

**Comment by klzgrad** [comment]
quic本身就是multiplexing

quic是否有padding对流量分析的影响现在不清楚，你可以试一试没有padding的quic用起来怎么样

naive的padding很简单，但是给其他软件添加类似功能需要你自己实现

**Comment by klzgrad** [comment]
[Maybenot: A Framework for Traffic Analysis Defenses](https://dl.acm.org/doi/abs/10.1145/3603216.3624953) 
[Website Fingerprinting in the Age of QUIC](https://petsymposium.org/popets/2021/popets-2021-0017.php)
[Evaluating practical QUIC website fingerprinting defenses for the masses](https://petsymposium.org/popets/2023/popets-2023-0099.php)
