### ISSUE TITLE
Please help me use naiveproxy on openwrt

### ISSUE THREAD

**Issue by dgp970** [klzgrad/naiveproxy#656]
I have run naive on openwrt.

# ./naive
Proxying via HTTPS domain:443
Listening on socks://127.0.0.1:1080

But can not access the network. I have only done this step, but it seems that still need to redirect the traffic?
By googling I created related iptalbes rules but it doesn't work.
I would appreciate if anyone could tell me what else I need to configure besides running naive.

**Comment by Zephor5** [comment]
try use ssrplus + naiveproxy  or passwall(2) + naiveproxy

**Comment by Zephor5** [comment]
try use ssrplus + naiveproxy  or passwall(2) + naiveproxy

**Comment by dgp970** [comment]
I am used to only installing naiveproxy on openwrt. Can anyone tell me what to do next in the command line? Thank you.

**Comment by shNanChen** [comment]
1. ### [server-setup](https://github.com/klzgrad/naiveproxy?tab=readme-ov-file#server-setup)
2. ### [client-setup](https://github.com/klzgrad/naiveproxy?tab=readme-ov-file#client-setup)

**Comment by dgp970** [comment]
> 1. ### [server-setup](https://github.com/klzgrad/naiveproxy?tab=readme-ov-file#server-setup)
> 
>     2. ### [client-setup](https://github.com/klzgrad/naiveproxy?tab=readme-ov-file#client-setup)

According to usage.txt, I changed the configuration.
for naive: listen=redir://0.0.0.0:1080
for iptables:
iptables -t nat -A PREROUTING -p udp -j REDIRECT --to-ports 1080
iptables -t nat -A PREROUTING -p tcp -j REDIRECT --to-ports 1080
iptables -t nat -A OUTPUT -d server_ip -j RETURN
iptables -t nat -A OUTPUT -p udp -j REDIRECT --to-ports 1080
iptables -t nat -A OUTPUT -p tcp -j REDIRECT --to-ports 1080

The DNS leaks, how to  configure it correctly, thank for the reply.
