### ISSUE TITLE
发现客户端使用 QUIC 传输时一个连接协商 BUG。 

### ISSUE THREAD

**Issue by lxhao61** [klzgrad/naiveproxy#657]
[由一个网友报告](https://github.com/lxhao61/integrated-examples/discussions/210)：当客户端使用 QUIC 传输时按照官方配置连接不成功，但服务器端 TLS 中添加 ``alpn h3 h2 http/1.1`` （Caddyfile 配置）后连接问题解决。

**Comment by klzgrad** [comment]
naive v126以后quic://根本没有发出proxy-authorization header

**Comment by lxhao61** [comment]
哦，JSON 配置由 Caddyfile 转化来的，应该无差异呀。
不明白 nelog，怎么弄的？

**Comment by lxhao61** [comment]
> > 不明白 netlog，怎么弄的？
> 
> 请参考文档 USAGE.txt.

明白了，谢谢！ 我之前一直使用路由器上 PassWall 客户端。

**Comment by lxhao61** [comment]
> 使用默认的Caddyfile没有重现
> 
> 你应该保存netlog看一下问题

没加 ``alpn h3 h2 http/1.1`` 配置的 netLog
[netLog1.zip](https://github.com/user-attachments/files/16199996/netLog1.zip)

加 ``alpn h3 h2 http/1.1`` 配置的 netLog
[netLog2.zip](https://github.com/user-attachments/files/16199999/netLog2.zip)

**Comment by klzgrad** [comment]
这两个netlog里面都正常使用quic，没看出异常

**Comment by lxhao61** [comment]
我的网络环境无网友情况极端，加 ``alpn h3 h2 http/1.1`` 配置仅可以让 QUIC 协议连接成功率得到了改善。已跟网友沟通，过几天提交他情况的 netlog 。

**Comment by klzgrad** [comment]
把有问题的netlog发出来才有参考意义
