### ISSUE TITLE
The latest version of naive naiveproxy-v127.0.6533.64-1-linux-x64.tar.xz doesn't support glibc 2.27 anymore

### ISSUE THREAD

**Issue by pnf500** [klzgrad/naiveproxy#660]
Just upgrade naive to the latest version v127.0.6533.64-1 on both ubuntu 18.04 and 24.04. But it failed to start on ubuntu 18.04 due to error GLIBC_2.28 not found. The version of GLIBC ships with ubuntu 18.04 is GLIBC 2.27. oh, what a pity.
I'm running both ubuntu 18.04 and 24.04. But I like 18.04. It's smaller and faster. KLZGRAD, would you please keep the latest version of naive to run on GLIB 2.27?

**Comment by klzgrad** [comment]
https://github.com/klzgrad/naiveproxy/releases/tag/v127.0.6533.64-2

**Comment by Chilledheart** [comment]
See upstream change merged in main branch and m129 branch aka "Reintroduce support for Ubuntu 18.04"

https://chromium.googlesource.com/chromium/src/+/df14ef63b2bc8
https://chromium.googlesource.com/chromium/src/+/58ab871cb6ab

They reintroduced the build support for ubuntu 18.04 in main and m129 (not found in m128 yet). I think it is better to do the same thing for naive's m128 release and furthur (no patch required for m129 or later)

**Comment by Chilledheart** [comment]
See issue tracker from chromium https://issues.chromium.org/issues/361375791#comment3:

> Reopening. We have decided to reintroduce support for Ubuntu 18.04, based on an offline discussion.

Ubuntu 18.04 is marked as obsolete linux distribution through. (https://issues.chromium.org/issues/361375791#comment9)
