### ISSUE TITLE
chrome浏览器特征加域名中有敏感词是否可能会被针对

### ISSUE THREAD

**Issue by bash99** [klzgrad/naiveproxy#67]
刚刚碰到个奇特的情况，将之前的tls over https代理升级了naiveproxy padding模式的代理。

其他域名都正常。但是某个域名里面有 1984的字符串，结果马上被封锁了，80和443端口都连不上。过了几分钟后解封，测试了几遍都是这样。

之前是用meow的https代理支持访问，反而一直正常。

**Comment by tomac4t** [comment]
是什么域名？测试了冰岛主机托管商的 [1984hosting.com](https://1984hosting.com/) 和 [1984.is](https://1984.is/) 网站在使用代理和不使用代理的情况下都是正常的，无法复现，1984 不是什么敏感词。此外，HTTPS 代理的 Host header 里有[被代理的域名](https://bugzilla.mozilla.org/show_bug.cgi?id=1017769)，但它被包裹在 TLS 里，第三方是无法观察到代理所访问的域名的。

**Comment by bash99** [comment]
类似1984.is的域名，只不过1984在二级，比如 1984.xxxx.com 这样，这个域名是用来做代理服务器的，而不是被访问的域名，所以在没做域名前置情况下，应该在sni阶段就出现了。

**Comment by bash99** [comment]
域名换了，把1984去掉换成另外的域名，指向同一个ip，访问正常。

**Comment by tomac4t** [comment]
既然这个域名是代理服务器的域名，那么你标题的论点是否可以理解为 Chrome 浏览器访问含有敏感词的域名会“被针对”——这本身是真命题，不然不叫敏感词了。但我不能被说服 `1984` 是关键词。当然你可以自己打开 Chrome 访问试一试，结果会一目了然，证书等配置错误还是真的触发了审查。

**Comment by klzgrad** [comment]
不可能
