### ISSUE TITLE
请确认BUG

### ISSUE THREAD

**Issue by frostnotfall** [klzgrad/naiveproxy#670]
naive版本：128.0.6613.40
caddy：v2.7.6-naive2
本地系统：win10 22h2

现象：
本地使用 curl 代理方式访问 https://ios.chat.openai.com/public-api/mobile/server_status/v1 提示握手失败：
curl: (35) schannel: failed to receive handshake, SSL/TLS connection failed

截图：
![image](https://github.com/user-attachments/assets/d7bb8fcf-220c-4afd-b9bf-c2f48716f17b)

是不是这个接口本来就不通？不。

服务端截图：
![image](https://github.com/user-attachments/assets/33e74f82-78ca-4c72-bd5b-4889307acdea)

dns解析不一样？
![image](https://github.com/user-attachments/assets/7b2d20f8-c35a-47dc-854e-5f6e22e175d8)

本地域名绑hosts，与服务端解析的ip一致。当然为了展示更清晰，curl 手动绑 IP
![image](https://github.com/user-attachments/assets/17cdc0ad-2d9e-41db-9d57-1d1c2f0c8eff)

日志：
也没别的，访问该域名之后紧接着就是一个 Connection X closed: OK
![image](https://github.com/user-attachments/assets/e3caf6e8-304f-4d0b-b95a-4997174a91ee)

这是否属于BUG？

**Comment by orangeByte** [comment]
参考 #577
