### ISSUE TITLE
运行naive客户端失败用户名和密码有 逗号

### ISSUE THREAD

**Issue by Ngwind** [klzgrad/naiveproxy#671]
现象：
运行客户端打印"Illegal instruction"后退出了， 相同的config.json配置文件，在debian12 x64系统中可以正常运行。
![image](https://github.com/user-attachments/assets/3aa263cd-e202-4a52-bb3c-a81f64eabcfd)

系统信息：
```text
root@OpenWrt:~# cat /etc/os-release
NAME="OpenWrt"
VERSION="23.05.4"
ID="openwrt"
ID_LIKE="lede openwrt"
PRETTY_NAME="OpenWrt 23.05.4"
VERSION_ID="23.05.4"
HOME_URL="https://openwrt.org/"
BUG_URL="https://bugs.openwrt.org/"
SUPPORT_URL="https://forum.openwrt.org/"
BUILD_ID="r24012-d8dd03c46f"
OPENWRT_BOARD="bcm27xx/bcm2711"
OPENWRT_ARCH="aarch64_cortex-a72"
OPENWRT_TAINTS=""
OPENWRT_DEVICE_MANUFACTURER="OpenWrt"
OPENWRT_DEVICE_MANUFACTURER_URL="https://openwrt.org/"
OPENWRT_DEVICE_PRODUCT="Generic"
OPENWRT_DEVICE_REVISION="v0"
OPENWRT_RELEASE="OpenWrt 23.05.4 r24012-d8dd03c46f"

```

(从release页面下载的）naive二进制版本：
naiveproxy-v123.0.6312.40-1-openwrt-aarch64_cortex-a72-static
naiveproxy-v128.0.6613.40-1-openwrt-aarch64_cortex-a72-static
naiveproxy-v128.0.6613.40-1-openwrt-aarch64_cortex-a72

客户端config.json配置文件：
```json
{
  "listen": "socks://127.0.0.1:1082",
  "proxy": "https://******:******@***.***.top:443",
  "log": "./naive.log"
}

```

请问是什么原因呢？有没有进一步排查的手动和建议? 谢谢！

**Comment by klzgrad** [comment]
用gdb看一下哪个instruction是illegal，来判断是否有指令集不匹配的情况

**Comment by Chilledheart** [comment]
根据 https://openwrt.org/toh/raspberry_pi_foundation/raspberry_pi wiki 上最接近4b的openwrt 目标应该是 _bcm27xx/bcm2711_，你也许可以试试 [arm_arm1176jzf-s_vfp](https://github.com/klzgrad/naiveproxy/releases/download/v129.0.6668.81-1/naiveproxy-v129.0.6668.81-1-openwrt-arm_arm1176jzf-s_vfp.tar.xz) (_bcm27xx/bcm2708_) 而不是cortex a72

**Comment by Chilledheart** [comment]
<img width="484" alt="截屏2024-10-07 10 55 20" src="https://github.com/user-attachments/assets/5ef425d7-8124-4284-86e6-beda2336c55a">

**Comment by Chilledheart** [comment]
<img width="411" alt="截屏2024-10-07 10 56 09" src="https://github.com/user-attachments/assets/177fb8f5-e26c-41ba-9988-22a905721108">

**Comment by hisuwj** [comment]
在openwrt-mips32el和ubuntu-x64，v126.0.6478.40-2版本以及以后的版本会有Illegal instruction提示。windows也是v126.0.6478.40-2版本以及以后的版本会自动退出，之前的版本都是正常的。

**Comment by klzgrad** [comment]
> openwrt-mips32el和ubuntu-x64

无法重现，需要coredump

**Comment by hisuwj** [comment]
> > openwrt-mips32el和ubuntu-x64
> 
> 无法重现，需要coredump

我自己分析了coredump，终于找到原因了，原因是因为用户名和密码有  逗号  和  点  。用户名、密码使用逗号和点在v126.0.6478.40-2之前是可以的，v126.0.6478.40-2之后就会提示Illegal instruction

**Comment by klzgrad** [comment]
https://github.com/klzgrad/naiveproxy/releases/tag/v130.0.6723.40-2

**Comment by Chilledheart** [comment]
<img width="966" alt="截屏2024-10-18 23 09 53" src="https://github.com/user-attachments/assets/156c900a-806d-45a2-8579-7f638124debe">

std::string::back()是带assertions的。如果能提供一个带assertions的版本，这种内存问题很容易抓的。

一般看挂掉的日志就可以了，会详细打印断言的函数和具体触发断言的原因。

最简单，跑一遍debug 版本也足够了。

**Comment by Chilledheart** [comment]
<img width="733" alt="截屏2024-10-18 23 31 11" src="https://github.com/user-attachments/assets/cf3e02eb-4428-441f-84b7-28babf0fd82d">
<img width="687" alt="截屏2024-10-18 23 33 49" src="https://github.com/user-attachments/assets/32d88a00-f24b-49e2-9d6a-81dbb01b7286">



提一嘴 chromium 项目里有一个叫 libcxx_hardening 的profile，是默认启用的，可以引入就会默认启用STL的断言。你可以看看为什么是中了断言崩掉了，还是这个profile压根没起作用。

**Comment by Chilledheart** [comment]
<img width="800" alt="截屏2024-10-18 23 37 09" src="https://github.com/user-attachments/assets/22533d7e-4a44-4fcc-8e80-54250e15401e">

vs

<img width="640" alt="截屏2024-10-18 23 37 29" src="https://github.com/user-attachments/assets/41971583-385b-4fda-8124-2380f14162b2">

**Comment by Chilledheart** [comment]
https://source.chromium.org/chromium/chromium/src/+/main:buildtools/third_party/libc++/__assertion_handler?q=_LIBCPP_ASSERTION_HANDLER&ss=chromium

https://github.com/klzgrad/naiveproxy/blob/89e03e4b2b04061dc40ddebd4f28c182abdd7844/src/buildtools/third_party/libc%2B%2B/__assertion_handler
