### ISSUE TITLE
能否原生支持一下分流

### ISSUE THREAD

**Issue by yangyangkeai** [klzgrad/naiveproxy#672]
考虑到在服务器端需要分流openai到warp以实现解锁chatgpt客户端,  目前使用的方案是naive->xray->warp/direct.  
naive->xray监听本地socks速度损耗非常大,  只使用naive速度可以跑满200Mbps ,  用上xray分流速度就只剩下30->40Mbps(未走warp的流量, 分到warp的流量速度只有不到20Mbps).

后来尝试了sing-box, 他支持naive且自带分流功能,   这个就可以跑满带宽.

**Comment by Bryan2333** [comment]
naiveproxy使用了caddy的forwardproxy模块，在caddy模块上面实现分流不太可能，更现实的解决方法是给forwardproxy模块的upstream添加unix domain socket的支持。

**Comment by klzgrad** [comment]
不能，naive是单协议，不做协议集成
