### ISSUE TITLE
能否支持aarch64_cortex-a53_neon-vfpv4

### ISSUE THREAD

**Issue by tiancaiV** [klzgrad/naiveproxy#673]
或者我该选哪个版本，我在编译naiveproxy时，总是报md5或256错误
我使用的是https://github.com/kenzok8/small软件源，又或者编译需要特殊工具譬如golang版本？

**Comment by tiancaiV** [comment]
make[2]: Entering directory '/home/openwrt/zuixin-gl/wlan-ap/openwrt/feeds/small/naiveproxy'
mkdir -p /home/openwrt/zuixin-gl/wlan-ap/openwrt/dl
SHELL= flock /home/openwrt/zuixin-gl/wlan-ap/openwrt/tmp/.naiveproxy-v128.0.6613.40-1-openwrt-aarch64_cortex-a53_neon-vfpv4.tar.xz.flock -c '  	/home/openwrt/zuixin-gl/wlan-ap/openwrt/scripts/download.pl "/home/openwrt/zuixin-gl/wlan-ap/openwrt/dl" "naiveproxy-v128.0.6613.40-1-openwrt-aarch64_cortex-a53_neon-vfpv4.tar.xz" "dummy" "" "https://github.com/klzgrad/naiveproxy/releases/download/v128.0.6613.40-1/"    '
Cannot find appropriate hash command, ensure the provided hash is either a MD5 or SHA256 checksum.
make[2]: *** [Makefile:109: /home/openwrt/zuixin-gl/wlan-ap/openwrt/dl/naiveproxy-v128.0.6613.40-1-openwrt-aarch64_cortex-a53_neon-vfpv4.tar.xz] Error 255
make[2]: Leaving directory '/home/openwrt/zuixin-gl/wlan-ap/openwrt/feeds/small/naiveproxy'
time: package/feeds/small/naiveproxy/compile#0.15#0.10#0.26
    ERROR: package/feeds/small/naiveproxy failed to build.
make[1]: *** [package/Makefile:118: package/feeds/small/naiveproxy/compile] Error 1
make[1]: Leaving directory '/home/openwrt/zuixin-gl/wlan-ap/openwrt'
make: *** [/home/openwrt/zuixin-gl/wlan-ap/openwrt/include/toplevel.mk:230：package/luci-app-ssr-plus/compile] 错误 2

**Comment by klzgrad** [comment]
aarch64_cortex-a53_neon-vfpv4 不是一个有效的 OpenWrt 指令集。
