### ISSUE TITLE
Feature Request for Naive Extension in Hiddify-Next (NekoBox for Android / nekoray Alternative)

### ISSUE THREAD

**Issue by privatesupport** [klzgrad/naiveproxy#675]
Dear Naive Team,
I am writing to bring to your attention the [hiddify-next](https://github.com/hiddify/hiddify-next) project, a multi-platform auto-proxy client that supports various protocols including Sing-box, X-ray, TUIC, Hysteria, Reality, Trojan, and SSH. This project is open-source, secure, and ad-free.
In the latest release of [hiddify-core](https://github.com/hiddify/hiddify-core), a feature called [Extensions](https://github.com/hiddify/hiddify-core?tab=readme-ov-file#extension) has been introduced. Unfortunately, as I am not a Go or JS developer, I am unable to implement the Naive extension myself.
I would like to request that you consider integrating this program as an alternative to NekoRay/Box. Hiddify-next has received more frequent updates and offers better support, functioning effectively in both China and Iran. It would be greatly appreciated if we could also utilize the Naive extension within this application.
Thank you for considering my request.
Best regards.

**Comment by klzgrad** [comment]
You can consider integrating naiveproxy-plugin.apk as a plugin to your program the same way SagerNet and NekoBox did it successfully.
