### ISSUE TITLE
openwrt上naiveproxy配置问题

### ISSUE THREAD

**Issue by maxbole** [klzgrad/naiveproxy#676]
我的服务器只支持ipv6连接，由于wifi不支持ipv6，于是我进行了中转。在安卓Nekobox上填写中转服务器地址，端口，用户名和密码后，无法连接。在"服务器名称指示"那一栏填写原服务器ipv6地址绑定的域名后，连接成功。但是我在openwrt上安装naiveproxy插件后发现没有"服务器名称指示"这一填写栏，真心希望大佬能加上这一选项!🙏

**Comment by klzgrad** [comment]
本项目不提供openwrt的naiveproxy“插件”，只提供二进制
