### ISSUE TITLE
OpenWrt builds incompatible with older OpenWrt versions

### ISSUE THREAD

**Issue by klzgrad** [klzgrad/naiveproxy#679]
> > > If I remove
> > 
> > 
> > The point of this discussion is that the user should be able to download easily usable binaries without having to build from source.
> > The static builds exist because some users have legacy non-OpenWrt embedded distros that do not work with the musl dependency requirement.
> > What is your distro, and why do you need a static build? @hisuwj
> 
> My system version is openwrt-21.02.7. The support for musl time64 started after the openwrt-22.03.0 version. Therefore, the versions prior to openwrt-21.02.7 do not support musl time64, so I can only choose the static version.

The musl version in openwrt-21.02.7 is 1.1.24, and support for time64 began only after musl 1.2.0.

_Originally posted by @hisuwj in https://github.com/klzgrad/naiveproxy/issues/664#issuecomment-2423705887_

**Comment by klzgrad** [comment]
OpenWrt 18, 19, 21 vs 22, 23
```diff
--- naive.21.dsyms	2024-10-19 19:26:44.317190638 +0800
+++ naive.22.dsyms	2024-10-19 19:26:40.085167466 +0800
@@ -5,11 +5,13 @@
          U __atomic_fetch_or_8@LIBATOMIC_1.0
          U __atomic_load_8@LIBATOMIC_1.0
          U __atomic_store_8@LIBATOMIC_1.0
+         U __clock_gettime64
          U __ctype_get_mb_cur_max
          U __cxa_atexit
          U __divdf3@GCC_3.0
          U __divdi3@GLIBC_2.0
          U __divsf3@GCC_3.0
+         U __dlsym_time64
          U __eqdf2@GCC_3.0
          U __eqsf2@GCC_3.0
          U __errno_location
@@ -30,22 +32,34 @@
          U __floatundisf@GCC_4.2.0
          U __floatunsidf@GCC_4.2.0
          U __floatunsisf@GCC_4.2.0
+         U __fstat_time64
+         U __fstatat_time64
          U __gedf2@GCC_3.0
+         U __gettimeofday_time64
+         U __gmtime64_r
          U __gtdf2@GCC_3.0
          U __gtsf2@GCC_3.0
          U __ledf2@GCC_3.0
          U __libc_start_main
+         U __localtime64_r
+         U __lstat_time64
          U __ltdf2@GCC_3.0
          U __ltsf2@GCC_3.0
+         U __mktime64
          U __moddi3@GLIBC_2.0
          U __muldf3@GCC_3.0
          U __mulsf3@GCC_3.0
+         U __nanosleep_time64
          U __nedf2@GCC_3.0
+         U __pthread_cond_timedwait_time64
          U __sched_cpucount
          U __stack_chk_fail
          U __stack_chk_guard
+         U __stat_time64
          U __subdf3@GCC_3.0
          U __subsf3@GCC_3.0
+         U __time64
+         U __timegm_time64
          U __tls_get_addr
          U __truncdfsf2@GCC_3.0
          U __udivdi3@GLIBC_2.0
@@ -64,11 +78,9 @@
          U cbrt
          U ceil
          U ceilf
-         U clock_gettime
          U closedir
          U connect
          U creat
-         U dlsym
          U epoll_create1
          U epoll_ctl
          U epoll_wait
@@ -97,8 +109,6 @@
          U freelocale
          U frexp
          U fseek
-         U fstat
-         U fstatat
          U ftruncate
          U fwrite
          U gai_strerror
@@ -113,9 +123,7 @@
          U getrlimit
          U getsockname
          U getsockopt
-         U gettimeofday
          U getwc
-         U gmtime_r
          U htonl
          U htons
          U inet_ntop
@@ -131,10 +139,8 @@
          U listen
          U llround
          U llroundf
-         U localtime_r
          U log
          U lseek
-         U lstat
          U madvise
          U mbrlen
          U mbrtowc
@@ -148,12 +154,10 @@
          U memset
          U mkdir
          U mkstemp
-         U mktime
          U mmap
          U mprotect
          U munmap
          U nan
-         U nanosleep
          U newlocale
          U ntohs
          U open
@@ -172,7 +176,6 @@
          U pthread_cond_destroy
          U pthread_cond_init
          U pthread_cond_signal
-         U pthread_cond_timedwait
          U pthread_cond_wait
          U pthread_condattr_destroy
          U pthread_condattr_init
@@ -222,7 +225,6 @@
          U snprintf
          U socket
          U sscanf
-         U stat
          U statfs
          U statvfs
          U stderr
@@ -244,8 +246,6 @@
          U strtoull
          U syscall
          U sysconf
-         U time
-         U timegm
          U tolower
          U toupper
          U uname
```

**Comment by klzgrad** [comment]
https://github.com/klzgrad/naiveproxy/releases/tag/v130.0.6723.40-4

**Comment by Chilledheart** [comment]
Actually you can still build against newer musl without 64-bit time_t support by -U_REDIR_TIME64.

**Comment by Chilledheart** [comment]
Continued. This macro is defined in alltypes.h for every 32-bit architecture. See https://git.musl-libc.org/cgit/musl/commit/?id=38143339646a4ccce8afe298c34467767c899f51. I didnt test it but you undefined this macro to link musl with the old ABI.

And static builds dont require the new ABI.

**Comment by klzgrad** [comment]
I tried to build with new musl without _REDIR_TIME64 but the binary crashed somewhere else.

Static builds would do better with newer musl libc in principle, at least in the malloc case it seems to release memory faster.

**Comment by Chilledheart** [comment]
Yes, I also tried with undefining _REDIR_TIME64 but it turns out it crashes with overflowed time_t. You need to override the definition of time_t as well because musl doesn't redefine time_t as 32-bit even _REDIR_TIME64 is undefined:

![image](https://github.com/user-attachments/assets/83d4d87e-523d-4247-8d28-5830d2b0fcd0)

https://git.musl-libc.org/cgit/musl/diff/arch/arm/bits/alltypes.h.in?id=38143339646a4ccce8afe298c34467767c899f51

Both of your changes (undefining _REDIR_TIME64 and change of time_t)  must be done in `bits/alltypes.h` header. I re-run the built binary and it is okay now.

Anyway, changing sdk header is evil and the more clean way is to use static build which calls 32-bit time_t syscall as fallback of 64-bit time_t syscall (Yes, I checked every related of source code, just to make sure the newer static musl build can run on old kernel).

**Comment by Chilledheart** [comment]
Actually you should use _time32_t_ defined in _compat/time32/time32.h_ if  `_REDIR_TIME64` is undefined. Clearly, musl doesn't do that for free.
