### ISSUE TITLE
[Need help] How to set quic udp MTU for naive client?

### ISSUE THREAD

**Issue by diyism** [klzgrad/naiveproxy#682]
$ ip a | grep tailscale0
5: tailscale0: <POINTOPOINT,MULTICAST,NOARP,UP,LOWER_UP> mtu 1280 qdisc fq_codel state UNKNOWN group default qlen 500
    inet 100.1.1.100/32 scope global tailscale0
    
$ strace naive --listen=socks://100.1.1.100:3209 --proxy=quic://user:pass@mydomain.com --host-resolver-rules="MAP mydomain.com 100.1.1.101"
...
connect(9, {sa_family=AF_INET, sin_port=htons(443), sin_addr=inet_addr("100.1.1.100")}, 16) = 0
setsockopt(9, SOL_SOCKET, SO_RCVBUF, [1048576], 4) = 0
setsockopt(9, SOL_IP, IP_MTU_DISCOVER, [2], 4) = 0
setsockopt(9, SOL_SOCKET, SO_SNDBUF, [29040], 4) = 0
getsockname(9, {sa_family=AF_INET, sin_port=htons(41960), sin_addr=inet_addr("100.1.1.100")}, [128 => 16]) = 0
recvmsg(9, {msg_namelen=128}, 0)        = -1 EAGAIN (Resource temporarily unavailable)
epoll_ctl(3, EPOLL_CTL_ADD, 9, {events=EPOLLIN, data={u32=7416072, u64=64905553193224}}) = 0
sendto(9, "\310\0\0\0\1\10}\3111{\210\231V\253\0\0E4\377\222lTd\232\203\326\t\277\372\244\n\356"..., 1350, 0, NULL, 0) = -1 EMSGSIZE (Message too long)
sendto(9, "\313\0\0\0\1\10}\3111{\210\231V\253\0\0E4\35\276\232\253\276\344\223\372S\t\n\236\331b"..., 1350, 0, NULL, 0) = -1 EMSGSIZE (Message too long)

If I add a socat(100.1.1.100:443) between the naive client and the caddy naive server(100.1.1.101:443), everything is ok:
$ naive --listen=socks://100.1.1.100:3209 --proxy=quic://user:pass@mydomain.com --host-resolver-rules="MAP mydomain.com 100.1.1.100"
$ socat -T20 udp-listen:443,bind=100.1.1.100,fork,reuseaddr udp4:100.1.1.101:443
But maybe it will degrade performance.

I try to modify the naive client myself, and found: https://github.com/klzgrad/naiveproxy/blob/def98703a81e99fa1f42f0220efd7b698036641c/src/net/quic/quic_chromium_client_session.cc#L1101
But it's too difficult for me.

**Comment by klzgrad** [comment]
Is it necessary to layer naiveproxy over tailscale?

Why is tailscale limited to 1280 mtu? QUIC requires "UDP payloads of at least 1200 bytes".

**Comment by diyism** [comment]
I asked claude.ai, it says "Tailscale enforces a maximum Transmission Unit (MTU) of 1280 bytes for its network interface primarily to accommodate the additional headers introduced by the encapsulation process used in its underlying technology, WireGuard. This MTU limitation is particularly significant in scenarios involving relayed traffic and helps avoid issues related to Path Maximum Transmission Unit Discovery (PMTUD)."

I have some containers that I want to use as relay servers to load-balance naive proxy traffic to the target caddy naive server. These containers don't have WAN ports(maybe Port Restricted Cone), but tailscale/wireguard can establish direct connections between the naive client and these containers without tailscale relay server:

naive client (--insecure-concurrency=N) -----> iptables nth mode ---> tailscale interface---> N relay servers ----direct internet----> caddy naive server

So I think I've turned the "insecure-concurrency" into "secure concurrency" because the iptables nth mode dispatches only 1 connection between naive client and every relay server, am I wrong?

**Comment by diyism** [comment]
I did a weird test:
After tailscale established connections, I modified the tailscale0 mtu:
sudo ifconfig tailscale0 mtu 1350
And get rid of socat, now naive client can connect the relay servers directly without EMSGSIZE too long error. It seems everything is ok now.
