### ISSUE TITLE
I hope to provide a distribution for the mipsel_74kc architecture.

### ISSUE THREAD

**Issue by lwb1978** [klzgrad/naiveproxy#683]
Currently, the releases lack binary files for the mipsel_74kc architecture. I hope they can be added. Thank you. The relevant SDK is: https://archive.openwrt.org/releases/23.05.5/targets/ramips/rt3883/openwrt-sdk-23.05.5-ramips-rt3883_gcc-12.3.0_musl.Linux-x86_64.tar.xz

**Comment by klzgrad** [comment]
https://github.com/klzgrad/naiveproxy/releases/tag/v107.0.5304.87-1

OpenWrt mipsel architectures (24kc, 74kc) are merged under the name mipsel_24kc without the specific tuning because Clang does not support -mtune for mipsel.

**Comment by lwb1978** [comment]
Thank you
