### ISSUE TITLE
寻求帮助，在OpenWrt上使用naiveproxy

### ISSUE THREAD

**Issue by dgp970** [klzgrad/naiveproxy#686]
naive开启的是 redir://0.0.0.0:1080
连接WIFI

仅设置了iptables规则：
iptables -t nat -A PREROUTING -p tcp --dport 22 -j ACCEPT
iptables -t nat -A PREROUTING -p tcp -j REDIRECT --to-ports 1080

请教作者给出iptables完整语句让远程服务器进行DNS查询。
本人尝试过在'PREROUTING'或'OUTPUT’链重定向udp但依旧无法访问被墙的网站，故特来寻求帮助。
就当是补充OpenWrt上iptables的相关规则吧，感谢作者付出！

**Comment by klzgrad** [comment]
你可以尝试在openwrt上面运行一个dnsmasq或者其他带缓存的dns转发器，把dns请求转发到tcp://8.8.8.8:53，然后这个请求会通过redir://0.0.0.0:1080转发到远程

**Comment by dgp970** [comment]
> 你可以尝试在openwrt上面运行一个dnsmasq或者其他带缓存的dns转发器，把dns请求转发到tcp://8.8.8.8:53，然后这个请求会通过redir://0.0.0.0:1080转发到远程

自身能力不够，没有实现...
