### ISSUE TITLE
关于naiveproxy在部分地区dns污染导致被封的上报

### ISSUE THREAD

**Issue by U201413497** [klzgrad/naiveproxy#688]
时间：2024年11月28日下午14时许，突然不能使用。

电脑使用ping指令查询 ping 域名，回复是127.0.0.1

解决办法。修改电脑是host，域名和IP进行绑定，已恢复。

继续检查，itdog.cn进行查询，使用   域名:443,测试，显示我当地联通和移动，反馈都是127.0.0.1，电信正常，但是我手机是电信网络，已经不通。

判断是dns污染了。因此不能使用了。

**Comment by U201413497** [comment]
更新，上述被封的为主域名，123.xyz这种，经过检查，a.123.xyz这样的二级域名正常。

**Comment by ArcCal** [comment]
/naive --host-resolver-rules="MAP www.gooooooooooogle.com 152.67.249.33" --listen=socks://0.0.0.0:1080 --proxy=https://user:pass@www.gooooooooooogle.com --log

**Comment by ArcCal** [comment]
> /naive --host-resolver-rules="MAP [www.gooooooooooogle.com](http://www.gooooooooooogle.com) ip.ip.ip.ip" --listen=socks://0.0.0.0:1080 --proxy=https://user:pass@www.gooooooooooogle.com --log

可以完全不依赖dns 也不用改host

**Comment by U201413497** [comment]
> > /naive --host-resolver-rules="MAP [www.gooooooooooogle.com](http://www.gooooooooooogle.com) ip.ip.ip.ip" --listen=socks://0.0.0.0:1080 --proxy=https://user:pass@www.gooooooooooogle.com --log
> 
> 可以完全不依赖dns 也不用改host

感谢你的回复，根据你提供的办法，可以正常使用了。不用修改dns和host。

**Comment by zedifen** [comment]
@NeedforGit It's that as long as you pass MAP rules to naiveproxy client, whether via command line option `--host-resolver-rules`, or the JSON equivalent, you don't need to touch DNS or computer's hosts settings to make naiveproxy connect to the correct sever IP.

**Comment by ArcCal** [comment]
> > > /naive --host-resolver-rules="MAP [www.gooooooooooogle.com](http://www.gooooooooooogle.com) ip.ip.ip.ip" --listen=socks://0.0.0.0:1080 --proxy=https://user:pass@www.gooooooooooogle.com --log
> > 
> > 
> > 可以完全不依赖dns 也不用改host
> 
> 你好，请问这条命令是要加到哪里啊？

直接加在naive命令后面 作为传递给naive的参数
