### ISSUE TITLE
Adding Openwrt arm 32 release binaries?

### ISSUE THREAD

**Issue by crysislinux** [klzgrad/naiveproxy#69]
Thanks for this lovely project.

From the release page, OpenWrt arm64 is supported, but OpenWrt arm32 is not.

![image](https://user-images.githubusercontent.com/5404597/82152040-5a3f5000-9891-11ea-8297-a8d2cfb833de.png)

Many routers are still using 32-bit processors, even for high-end models such as Netgear 7800

There was an issue for this: https://github.com/klzgrad/naiveproxy/issues/53

Armv7 is still a 32-bit processor.

> Armv7 is too broad a concept.

That's right, but a generic arm 32-bit build should work for many arm processors out there.

v2ray support those and it even has an armv7 build (slightly smaller and more performant than the generic one) beside the generic 32-bit build.

I guess they don't build it for a specific CPU but for an instruction set.

Sorry to just ask for help but not trying myself, it's just a bit hard for me to set it up from scratch.

**Comment by klzgrad** [comment]
Requests for openwrt builds must specify a target listed in here https://openwrt.org/docs/techref/targets/start.

**Comment by crysislinux** [comment]
@klzgrad 

The target for Netgear 7800 is `ipq806x` on the list according to https://openwrt.org/toh/netgear/r7800.

Hope that the build could also work for other targets that use the same instruction set.

**Comment by klzgrad** [comment]
[naive.zip](https://github.com/klzgrad/naiveproxy/files/4651440/naive.zip)

See if this binary works

**Comment by crysislinux** [comment]
@klzgrad It's somehow running.

I guess I need to upgrade my openwrt(it's 18.06.0 now) as you pointed out in other issues. I will give an update when it's done. Thanks.

![image](https://user-images.githubusercontent.com/5404597/82395025-29bc0980-9a7d-11ea-8bb6-6117b5aed39c.png)

**Comment by crysislinux** [comment]
@klzgrad 

It works great after upgrading to `OpenWrt 19.07` and installing `libnss`.

**Comment by klzgrad** [comment]
Formally released as openwrt arm_cortex-a15_neon-vfpv4.

**Comment by crysislinux** [comment]
It works great. Thanks.
