### ISSUE TITLE
probe_resistance for HAProxy?

### ISSUE THREAD

**Issue by gili-gili** [klzgrad/naiveproxy#690]
caddy有个功能叫做probe_resistance，可以在验证无效的时候正常返回网页，请问haproxy可不可以这样？我用的是haproxy做判断，如果是http connect方法就转到Naiveproxy/Tinyproxy，因为用host判断不行，很奇怪
如果不行的话，我使用haproxy配合caddy可以吗？我之前这样做不行，haproxy一直抱错，caddy也没有受到请求，caddy是关闭tls的

**Comment by gili-gili** [comment]
补充一下，我现在用的方法是wiki给的，在haproxy验证，验证好了转给naiveproxy。
然后haproxy转发给caddy那个方法，验证设置在caddy那里

**Comment by klzgrad** [comment]
wiki里面写的就是haproxy的probe resistance。只有front application才需要probe resistance。

没用过haproxy后面串联caddy的用法，也不知道为什么要这样用，没必要。haproxy目前只测试过后面串联naive server的用法。

**Comment by gili-gili** [comment]
因为我之前naiveproxy是配合caddy使用的也不知道naiveproxy可以作为服务端。想使用caddy的其他功能，这样只需要haproxy+caddy。
caddy如果没有开tls，处理haproxy的naiveproxy请求会出错。
