### ISSUE TITLE
OpenAI Login Page: Unexpected token '<', "<!DOCTYPE "... is not valid JSON

### ISSUE THREAD

**Issue by muiyu** [klzgrad/naiveproxy#694]
今天第一次使用 naive，访问 Google 没有问题，但是在我尝试登录 OpenAI 账号时页面出现 Unexpected token '<', "<!DOCTYPE "... is not valid JSON 字样。改为其他代理方式能够正常登录。目前还没有发现访问其他服务会出现这个问题。

<center>
<img src=https://github.com/user-attachments/assets/b7edac76-0dcf-4310-8c74-12dcd4fd78d8>
<img src=https://github.com/user-attachments/assets/19659357-76d9-4de0-bf84-78cc59ba974d>
</center>

我自己也会尝试继续排错，并将提供更多信息，不过我是第一次使用 Caddy，可能需要一些时间。如您有其他需要了解的信息或能够加速我进行日志查询的方法，请在下方回应！

感谢！

**Comment by muiyu** [comment]
经过一段时间之后恢复正常，登录成功，但是并未发现原因，我也没有进行任何配置改动。

**Comment by zedifen** [comment]
This is probably not a naiveproxy issue. 

ChatGPT uses Cloudflare (but it's same for others if they are using some kind of WAF). When a request is blocked by WAF, it probably returns a HTML like this, starting with `<!DOCTYPE...`.

If the frontend JavaScript code expects a JSON response but actually got an unfortunate HTML, and it starts de-serializing anyway without checking if it's valid JSON, things will break. Worse, if it doesn't handle the error but directly throw the message out, end users will get a confusing report like this.
