### ISSUE TITLE
Padding is not  working

### ISSUE THREAD

**Issue by emacsenli** [klzgrad/naiveproxy#78]
I have setup 2 naive clients (both released binary not compiled myself) on my local machine. one is listening on port  1080 with padding on while the other is on port 8080 without padding 

while on VPS ,if caddyfile just remove upstream section as README.md said , naive worked fine.

but if I try "padding" mode , command  curl -x socks5://127.0.0.1:1080 https://www.google.com just returned error "SSL_ERROR_SYSCALL" . and tcpdump localmachine 1080 ,show that with a ClientHello then no ServerHello back from google, and tcpdump of  local machine to  VPS  stage ,there is nothing wrong,https stream works fine. so the problem is from stage between   VPS and google. 
and tcpdump of this  stage  shows that  after 3 handshakes there is not a ClientHello but an unkown record ,and google return a Fatal Alert and RST immediately .

compare both tcpdump of localhost 1080 and VPS to google ,localhost has a ClientHello of payload length 585 in socks protocol ,but VPS to google is of  payload length  880.
so this is problem I think

**Comment by darhwa** [comment]
Have you enabled padding for both your naive client and the naive server behind caddy?

**Comment by emacsenli** [comment]
> Have you enabled padding for both your naive client and the naive server behind caddy?

ok let me put configurations on :

**local machine**

> config.json for naive

> {
>   "listen": "socks://127.0.0.1:1080",
>   "proxy": "https://user:passwd@myDomain",
>   //"log": ,
>   "padding":true
> }
>

**Comment by darhwa** [comment]
In the naive server, you have to config it to listen on http://*** instead of socks5://*** to make the padding work correctly.

I agree that this is error-prone for users.

**Comment by tomac4t** [comment]
> 客户端的listen只支持socks
> 
> 服务端的listen只支持http
> 
> 客户端listen http再加padding就是这样 ([#51 (comment)](https://github.com/klzgrad/naiveproxy/issues/51#issuecomment-599488476))

**Comment by emacsenli** [comment]
Yes correct...Finally Done ,thanks

**Comment by KevinZonda** [comment]
@klzgrad It can be closed.

**Comment by klzgrad** [comment]
Padding support is now auto-configured.
