### ISSUE TITLE
Are there any way to use navie proxy with apache2?

### ISSUE THREAD

**Issue by Edelwiess** [klzgrad/naiveproxy#79]
Thanks

**Comment by tomac4t** [comment]
Duplicate of #52

**Comment by klzgrad** [comment]
The ultimate reason most regular HTTP/2 servers can't be used and only H/2 reverse proxies can is that the kind of traffic you're generating here is much more interactive than the kind normally served by a static H/2 server. Only using reverse proxies will keep your plausible deniability.

**Comment by Stevemoretz** [comment]
> The ultimate reason most regular HTTP/2 servers can't be used and only H/2 reverse proxies can is that the kind of traffic you're generating here is much more interactive than the kind normally served by a static H/2 server. Only using reverse proxies will keep your plausible deniability.

I was searching for naiveproxy apache reverse proxy that I got here, can naiveproxy be used behind apache? Apache has a reverse proxy feature which I use for websocket but I have no idea how it can support naiveproxy?
