### ISSUE TITLE
Parroting DNS requests?

### ISSUE THREAD

**Issue by henrypijames** [klzgrad/naiveproxy#80]
I was just re-reading the Parrot paper and was reminded that "real" browser traffic is typically accompanied by a lot of DNS requests. So, if NP tries to parrot Chrome, doesn't the client have to generate some believable DNS requests as well?

Scenario 1: User is using PA along with unencrypted DNS. The walls sees a stream of DNS requests, but no traffic going to the servers that these DNS addresses resolve to. Ergo, it knows something's up.

Scenario 2: User is using PA along with DNS-over-HTTPS in browser. The wall sees a lot of HTTPS traffic to the server, but no DNS requests - not even DoH to the default servers, because those requests are all channeled through PA now. Again, it knows something is up.

Scenario 3: User is using PA along with a separate encrypted DNS client. The wall sees the encrypted DNS requests and thinks to itself, whoever uses (dedicated) encrypted DNS is also likely to climb the wall, so let's take a closer look at that HTTPS server, shall we?

Scenario 4: PA client forces user to use either DoH or separate encrypted DNS, and uses its Chrome stack to generate random DNS requests to Chrome's default DoH servers. In principle, this would look much less suspicious, but it requires really good parroting of genuine DNS requests, or these fake DNS requests themselves become a fingerprint.

Scenario 5: PA client offers its own encrypted DNS subsystem and forces user to use it. It then proxy those DNS requests to Chrome's default DoH servers. The wall now see a Chrome user who has turned on DoH (may even become default in some Chromium-based browsers). The only thing suspicious now is that there's just HTTPS traffic to one single server, and no other servers. This is probably the least suspicious picture we can paint.

Am I missing something here?

**Comment by klzgrad** [comment]
> "real" browser traffic is typically accompanied by a lot of DNS requests

No, it's not.

**Comment by henrypijames** [comment]
> No, it's not.

Care to elaborate?

> Also, you did miss the fact that SOCKS5 can proxy traffic without name resolution.

I don't understand what you mean by this, either.

**Comment by tomac4t** [comment]
> User is using PA along with unencrypted DNS. The walls sees a stream of DNS requests, but no traffic going to the servers that these DNS addresses resolve to.

The firewall may not be able to observe all DNS traffic from you. Because the Authoritative or Recursive DNS can within the Firewall. Thinking a situation when you are using ISP DNS or DNSPod.

> > Also, you did miss the fact that SOCKS5 can proxy traffic without name resolution.
> 
> I don't understand what you mean by this, either.

Socks5 can resolve the hostname remotely, it isn't a rare situation if the browser doesn't have too many DNS requests.

**Comment by henrypijames** [comment]
> The firewall may not be able to observe all DNS traffic from you. Because the Authoritative or Recursive DNS can within the Firewall. Thinking a situation when you are using ISP DNS or DNSPod.

You're right - unless the GFW is deployed at the ISP itself.

> Socks5 can resolve the hostname remotely, it isn't a rare situation if the browser doesn't have too many DNS requests.

Like I've said, if the wall knows (or suspects) that you're using SOCKS5 (or dedicated encrypted DNS), you've already lost half the battle, because most SOCKS5 users are wall climbers.

> I don't think NaiveProxy is parrot something. It is "run the actual protocol" as the author recommended.

No, it's really not. "Run the actual protocol", or the stenographic approach, means you have to have real HTTPS traffic on that connection, and hide your fake HTTPS traffic inside it. And the real traffic has to be vastly outnumber the fake one, because steno only works if the hidden data is significantly smaller in volume than the cover data. PA give you no real traffic at all, so while the connection itself may be perfectly legit looking, the *behavior* of that connection is different. The lack of outgoing DNS requests are just one example.

**Comment by tomac4t** [comment]
> Like I've said, if the wall knows (or suspects) that you're using SOCKS5 (or dedicated encrypted DNS), you've already lost half the battle, because most SOCKS5 users are wall climbers.

But how? 

> "A  session  of  a  given  protocol  may  trigger other protocols. For example, an HTTP request often triggers multiple DNS queries." 

(1) "Often" isn't "must", It's possible a website without any third-party resource. (2) Can't obverse DNS traffic doesn't represent a user using encrypted DNS or something. (3) Basically, NaiveProxy and other circumvent tools are not socks5 proxies, they just provide a socks5 interface on local.

**Comment by henrypijames** [comment]
I wasn't suggesting that the wall knows you're using SOCKS5 - you said a lack of observable DNS requests could simply mean SOCKS5, and I was responding to that, saying that that assumption doesn't make things better for us.

You don't think it would be very, very unusual for a "normal" Internet user, who isn't climbing the wall and who isn't using advanced networking tools like encrypted DNS and SOCKS5 (because if you are using those tools, you're immediately a suspected wall climber, no additional evidence needed), to have an extensive (both in duration and in data volume) HTTPS connection to a single server, but no observable DNS request (or very little - other programs on the system could still be requesting DNS, but not nearly as much as a browser) and no other significant web traffic apart from this one HTTPS connection?

Is there a plausible scenario for this? Yes, there is. You could have a personal cloud office (like OwnCloud) on your server be using that all this time (in fact, I've been considering deploying a NextCloud on my VPS just for this purpose). But plausible doesn't mean common - it still sticks out like a sore thumb. Remember, the wall doesn't have to *proof* you're climbing it, it only needs to suspect it. And you need more than plausible deniability - you need to blend in. PA without observable DNS is not blending in.

**Comment by tomac4t** [comment]
@henrypijames 不知道您是否使用了机器翻译，表达了我从未说过的且相悖的内容。关于最后一点，我强烈建议您先使用 caddy forwardproxy 插件并了解原理后再来评价，您就会知道 DNS 请求在这里是毫无必要的。

**Comment by henrypijames** [comment]
I am writing my own words, and I've never used machine translation (for English). I also do know Caddy ForwardProxy and have used it for at least two years now (don't remember exactly). What part of "Your camouflage is plausible but still attention-drawing" is hard to understand?

**Comment by henrypijames** [comment]
> Instead of just raising proposals, try to come up with a practical design that reflects your ideas (without even implementing it), and see how practical it turns out.

It's exactly what I did in my initial post: The scenario 5 was precisely a "practical design that reflects [my] ideas (without even implementing it)".
