### ISSUE TITLE
Pedding not work & there are lots of ERR_INVALID_ARGUMENT

### ISSUE THREAD

**Issue by KevinZonda** [klzgrad/naiveproxy#81]
I tried naive with padding:

Server ->
```
./naive --listen=http://127.0.0.1:8080 --log --padding
```

Client ->
```
.\naive --proxy=xx:xx@xxx.com --listen=http://127.0.0.1:1080 --log --padding
```

Caddyfile ->
```
xxx.com
root /var/www/html
tls a@a.com
forwardproxy {
  basicauth aaa bbb
  hide_ip
  hide_via
  probe_resistance secret.localhost
  upstream http://127.0.0.1:8080
}
```

Server logs ->
![image](https://user-images.githubusercontent.com/33132228/83959472-d08f0b00-a8af-11ea-85ce-a87d0b1a00e3.png)

Client logs ->
![image](https://user-images.githubusercontent.com/33132228/83959459-a1789980-a8af-11ea-8684-26c44cd462d2.png)

I tried to open website, but my browser give me `ERR_SSL_PROTOCOL_ERROR`.

![image](https://user-images.githubusercontent.com/33132228/83959480-e8ff2580-a8af-11ea-8a11-3d39cd2f7ced.png)

I think this issue is related to https://github.com/klzgrad/naiveproxy/issues/78 , but the fix not work.

BTW, there are **lots of** `ERR_INVALID_ARGUMENT` in no-padding mode, is it normal??

**Comment by tomac4t** [comment]
> 客户端的listen只支持socks
> 
> 服务端的listen只支持http
> 
> 客户端listen http再加padding就是这样 ([#51 (comment)](https://github.com/klzgrad/naiveproxy/issues/51#issuecomment-599488476))

**Comment by KevinZonda** [comment]
> > 客户端的listen只支持socks
> > 服务端的listen只支持http
> > 客户端listen http再加padding就是这样 ([#51 (comment)](https://github.com/klzgrad/naiveproxy/issues/51#issuecomment-599488476))

I will give a try. Thanks a lot.

**Comment by tomac4t** [comment]
You mentioned on the other issue https://github.com/ExcitedCodes/NaiveGUI/issues/1: 

> Windows can only accept HTTP proxy.

It's not right. Windows also support socks5 proxy. Here is link about how to configure the socks5 proxy on Windows: https://techcommunity.microsoft.com/t5/discussions/add-socks5-authentication-support-to-edge-insider-browser/m-p/908994

**Comment by KevinZonda** [comment]
> You mentioned on the other issue [ExcitedCodes/NaiveGUI#1](https://github.com/ExcitedCodes/NaiveGUI/issues/1):
> 
> > Windows can only accept HTTP proxy.
> 
> It's not right. Windows also support socks5 proxy. Here is a link about how to configure the socks5 proxy on Windows: https://techcommunity.microsoft.com/t5/discussions/add-socks5-authentication-support-to-edge-insider-browser/m-p/908994

Not for Edge, but for WinNet. See more at https://github.com/KevinZonda/NaiveSharp and https://github.com/KevinZonda/NaiveSharp/blob/master/NaiveSharp/Module/Proxy.cs

**Comment by KevinZonda** [comment]
> > 客户端的listen只支持socks
> > 服务端的listen只支持http
> > 客户端listen http再加padding就是这样 ([#51 (comment)](https://github.com/klzgrad/naiveproxy/issues/51#issuecomment-599488476))

It works, and I ported to my client too. https://github.com/KevinZonda/NaiveSharp/blob/bf32a0817ea86c662d4024b5bec8d40a75522d16/NaiveSharp/Module/Operation.cs#L26-L35 , Thanks a lot!
