### ISSUE TITLE
maybe some Strange behaviors of Naive client-----immediate [tcp-Fin]  after sending Change Cipher spec

### ISSUE THREAD

**Issue by emacsenli** [klzgrad/naiveproxy#82]
I have tcpdump several naiveproxy tcp flows and find something strange .the average time of tcp flows  only last for 1.5 seconds, sometimes less then 1 second.this is the main strange behavior
below  is the 2 examples refer to this behavior.
 
**for the first example**

> TCP 3 handshakes seem to be normal 
> 
> and then Client Hello ,Server Hello both are OK and ServerHello fragmented  in 3 packets ,with lengths of 1456,1456,686 
> 
> and then Naive Client  sends Change Cipher Spec .
> 
> then comes the problem :in about 0.2 ms naive Client send a [fin,ack] and terminated the flow.
> 

**for the second example**

> TCP 3 handshakes seem to be nomal
> 
> and then Client Hello  and then Server Hello packet  (length 454 , no more fragments like expample 1 ) ,naive send client Change Cipher Spec  ,and immediately sends [Fin,Ack] in about 0.23 ms  which terminates the TCP flow. with incoming TLS  flow from server ,client return RST as expected 

 
I am not familiar with TCP and have no knowledge of TLS ,so I am not sure that these phenomenons  are normal or there is a risk of probations of both Server and Client  (such as Fin after ClientHello)

**the second behavior** is that naiveclient makes TLS connections itself but not proxy incoming connections  going out, I have also captured local socks5 port which naive client is listening and 'netstat -napc' for processes and ports log , during  the same period ,and find almost  no  incoming request from ff browser or curl to naive client but client itself generated TLS request in a burst ,raise  8 or 10 connections to naive server in one or two minutes and clients  terminates  these connections all then .

and **the last behavior** is ,by capturing local socks port data ,there is active Fin from navie client  to close connections from applications.but the client should always be listening or transporting data out to server ,right?

**Comment by klzgrad** [comment]
https://www.chromium.org/developers/design-documents/network-stack/preconnect
