### ISSUE TITLE
Consider Adding SIP003 Support

### ISSUE THREAD

**Issue by DuckSoft** [klzgrad/naiveproxy#84]
It will be very nice to have naiveproxy as a pluggable transportation layer in Shadowsocks, and also in other censorship circumvention techniques. 

Shadowsocks SIP003 Specs: http://shadowsocks.org/en/spec/Plugin.html

---
cc @studentmain

**Comment by klzgrad** [comment]
I would be open to porting Chrome net stack for third party use. But I disagree with SIP003's design in principle.
