### ISSUE TITLE
NaiveProxy URI Specification

### ISSUE THREAD

**Issue by DuckSoft** [klzgrad/naiveproxy#86]
Recently I managed to port `naiveproxy` to [Qv2ray](https://github.com/Qv2ray), working as a [plugin](https://github.com/Qv2ray/QvPlugin-NaiveProxy), when I came up the following uri draft. NaiveProxy is so exciting that I even ported it to Arch Linux CN. Hopefully this will contribute to the development of NaiveProxy.

### Basic
* NaiveProxy URIs should be standard URIs, not something using JSON and Base64 encoding, etc.
* `https` / `quic` schemes shouldn't be used directly, since they can be confusing with the real protocols.

### Rules
* schema := `naive+https` | `naive+quic`
* username, password := basic auth info. when there's no auth, omit both.
* host := target host
* port can be omitted if it's 443, or specify it explicitly
* queries:
   * `padding` := 'true' | 'false' - whether to use padding or not. when omitted, use 'false' as default.
   * ... to be added
* fragment: used to place descriptive texts

### Examples
* `naive+https://what:happened@test.someone.cf?padding=false#Naive!`
* `naive+https://some.public.rs?padding=True#Public-01`
* `naive+quic://manhole:114514@quic.test.me`

### Application
Launchers simply strip `naive+` from the scheme part, strip and parse the url queries for extra arguments, and strip fragment as optional descriptive text. Afterwards, he/she can directly pass this stripped uri following `--proxy=` in NaiveProxy argument list. After adding extra arguments like `--padding` and `--extra-headers`, NaiveProxy is ready to go.

This URI can also be used in subscriptions, when mixed with other protocols, this scheme is easily distinguishable since we have a prefix `naive+`. This allows further parsing of the subscribed hosts.

**Comment by klzgrad** [comment]
Where is this used?

**Comment by DuckSoft** [comment]
> Where is this used?

Used for sharing/distributing proxies. Also in client software.
![图片](https://user-images.githubusercontent.com/7822648/84560120-6e347f80-ad73-11ea-9c5c-babedcadac76.png)

**Comment by klzgrad** [comment]
So naiveproxy is the object that is being shared? Then I have no say in the way you want to share it. I think this is out of scope for me.

**Comment by DuckSoft** [comment]
Fine.

**Comment by KevinZonda** [comment]
LGTM. I will use it in https://github.com/KevinZonda/NaiveSharp
