### ISSUE TITLE
Network stall in redir mode

### ISSUE THREAD

**Issue by nutinshell** [klzgrad/naiveproxy#87]
When running sometime later, the connections will be very very slow, kill and relaunch could fix it temporarily. Any suggestion?

**Comment by klzgrad** [comment]
> Any suggestion?

Give me something to work with, anything.

**Comment by nutinshell** [comment]
> > Any suggestion?
> 
> Give me something to work with, anything.

I want, but I can't... it runs from ver 72, maybe you can reproduce very easily.

**Comment by klzgrad** [comment]
Have you tried version 83?

**Comment by nutinshell** [comment]
yes, v83.0.4103.61-2

**Comment by klzgrad** [comment]
I use redir mode quite often and never saw this. The only thing that might cause problems is if you use the builtin fake dns resolver, which might return wrong results (but very unlikely though) after wrap around. If you use your own dns resolver this should be impossible. Any log can demostrate what exactly you mean by "connections will be very very slow"

**Comment by nutinshell** [comment]
you said "often", do you mean that setting it up and all devices in LAN depended on it? I am using my own dns resolver, I saw no any log in stdout when connections stall, twitter feed refresh taking a long time, youtube only 240p... netstat | wc -l about ~70

**Comment by klzgrad** [comment]
What can I do with this? I can't reproduce and there's nothing for me to work with.

There are two things  you can do. You can test it like a black box with tcpdump: do inbound socks connections with naiveproxy work ok? Do outbound https connections from naiveproxy work ok?

Then naiveproxy has a flag `--log-net-log` that saves more detailed internal log. You can send the dumps and logs to kizdiv@gmail.com if you're concerned with private info.

**Comment by NetHeritage** [comment]
发现一个现象，redir模式下，Windows客户机上所有程序都可以正常富强，唯独Dropbox一直提示无法建立安全连接。iOS设备所有的软件（包括Dropbox）也都没问题

**Comment by klzgrad** [comment]
我在Windows上让Steam被redir代理也有一点卡顿。你应该使用Wireshark跟踪一下Dropbox的收发情况。也许Dropbox需要UDP。

**Comment by NetHeritage** [comment]
@klzgrad 请教您两个问题
一是，下面这段话，您想表达什么意思（来自usage.txt）
Also activates a DNS resolver on the same UDP port. Similar iptables
      rules can redirect DNS queries to this resolver. The resolver returns
      artificial addresses that are translated back to the original domain
      names in proxy requests and then resolved remotely.

      The artificial results are not saved for privacy, so restarting the
      resolver may cause downstream to cache stale results.

另一个问题是，网关上NaiveProxy以redir模式运行，本机设置firefox强制使用内置的Cloudflare DNS over HTTPS服务器且不能fallback（trr mode 值为3)，有时会出现www.google.com疑似被解析到twitter或者Facebook的IP，firefox提示因为Google启用了HSTS，证书不匹配，所以无法访问Google。firefox使用阿里云的doh服务器也会有这种现象。而不使用redir模式、本机运行NaiveProxy，从没出现过这种现象。这种现象为何发生，该怎么解决呢。
非常感谢！

**Comment by frankang** [comment]
I got the same stall problem when running naiveproxy (latest release version) on openwrt, it happens both in the socks mode and redir mode after some time (may be there is a certain traffic/connection threshold?), restarting naiveproxy can fix that. I'll try to collect the net-log.
