### ISSUE TITLE
Does it support udp?

### ISSUE THREAD

**Issue by yingyue2008** [klzgrad/naiveproxy#89]
Does it support udp when use socks5 or redir ?

**Comment by klzgrad** [comment]
No. I don't see the point of running udp over socks5.

**Comment by hdid** [comment]
@Meteorite Can you help about this as you did for [Chisel](https://github.com/jpillora/chisel/pull/250)? Thank you

**Comment by Meteorite** [comment]
@hdid 
This project seems to be very different from chisel and to tell the truth, I see it for the first time. So, I'm afraid, I will not be able to do it easily, and I have no motivation to invest many time into it, at least for now.

**Comment by klzgrad** [comment]
Now duplicate of #617.
