### ISSUE TITLE
naive.exe flash back

### ISSUE THREAD

**Issue by wyw1018** [klzgrad/naiveproxy#90]
Hi yesterday I downloaded v83.0.4103.61-3 without noticing "TEST ONLY. End users do not use". When I double clicked naive.exe the DOS window flashed back. After I deleted it and downloaded the old release the problem still persisted. Other types of exe files didn't have such problem. The old release worked well before I downloaded the test release. How can I fix this issue?

**Comment by klzgrad** [comment]
you should run naive.exe inside cmd.exe and see the output

**Comment by wyw1018** [comment]
the output shows "Error reading config.json: (1003) File doesn't exist." but I do have config.son in the same directory with the folllowing content:
{
"listen": "socks://127.0.0.1:1080",
"proxy": "https://wyw####:cnlaLvvY#####@na####.##",
"padding": true,
"log": ""
}

**Comment by klzgrad** [comment]
I just tried and couldn't reproduce this.

**Comment by klzgrad** [comment]
Not reproducible.
