### ISSUE TITLE
windows版上行速度很慢

### ISSUE THREAD

**Issue by baraja** [klzgrad/naiveproxy#92]
40M的上行带宽只能跑到十几M
而ubuntu下测试似乎是可以跑满的
测试环境是speedtest.net，反复测试了很多遍都是如此

**Comment by klzgrad** [comment]
我知道上行会比下行慢，这是HTTP/2服务器的接收窗口的默认参数导致的，默认参数认为上传小、下传大。如果打开`logging`就会在上传堵塞的时候看到许多"STALL"的消息。但是一般人不会去改这个参数，如果擅自改了就很突兀。

windows上传速率比ubuntu的上传速率慢，这个没有明显的问题所在，要解决是个费时费力的事情。你可以论证一下这个事情有多大的价值，值得让我去研究。

**Comment by baraja** [comment]
了解了，测试了一下vmess的h2，上传速度也跑不满
那可以用http1.1吗？

**Comment by darhwa** [comment]
golang的h2默认接收窗口是1MB，而且每收到一个DATA帧都会回一个WINDOW_UPDATE。简单计算一下，只要带宽延迟积不超过接收窗口两倍，h2就不会卡上传带宽。带宽延迟积2MB，带宽只有十几Mbps？那你一个RTT要800~1600毫秒？所以我要怀疑一下你的结果。这个上限到底是h2卡的，还是ISP卡的？

我不太确定使用speedtest.net测试速度是什么意思。测出来的是你到自己主机的带宽，还是到就近speedtest服务器的带宽呢？如果是后者，那么你到不同服务器的上传带宽不同完全是可能的。

**Comment by baraja** [comment]
ISP上行40m，v2ray ws tls能跑满，trojan也能
VPS是日本的，连日本的speedtest服务器测试

**Comment by darhwa** [comment]
那就确实是golang默认接收窗口偏小的问题，这个不太好改。如果你愿意折腾，可以试试haproxy，然后在global里设置tune.h2.initial-window-size参数。

**Comment by baraja** [comment]
没事，上行用不太到，下行速度能跑满就很知足了。np为我们多提供了一种选择，感谢大佬们付出！

**Comment by klzgrad** [comment]
Works as designed.
