### ISSUE TITLE
naiveproxy as a library

### ISSUE THREAD

**Issue by simon-on-gh** [klzgrad/naiveproxy#94]
I am thinking about the feasibility to use naiveproxy as a HTTP or TCP library instead of a standalone proxy program.
Traditional proxy tools like v2ray implement their own protocol with websocket and they can benefit from naiveproxy by replacing their websocket implementation. 
https://github.com/v2ray/discussion/issues/754
https://github.com/v2ray/v2ray-core/issues/2098

**Comment by klzgrad** [comment]
Library, yes. Integrate with whom? With what interface?

**Comment by simon-on-gh** [comment]
How about something that mimics the WebSocket API in JavaScript
https://developer.mozilla.org/en-US/docs/Web/API/WebSockets_API

WebSocket is better supported by CDNs and load-balancing systems,  compared to HTTP proxy protocol. 

Also, with CDN you can distribute your traffic into many IPs, which makes them look like normal browsing behavior. I think it's a very appealing feature, since the header and traffic shaped by naiveproxy is very Chrome already.

**Comment by klzgrad** [comment]
Websocket and CDN fronting are two approaches that this project is designed against.

If someone is prepared to integrate such a library into certain apps I can help him, otherwise I'm not very motivated to work on this in a vacuum.

**Comment by simon-on-gh** [comment]
I tried making a v2ray websocket relay in Electron, which uses nodejs as a Websocket server, and Chrome for frowarding everything a regular v2ray server. It's pretty slow and it doesn't work on platforms where electron is not supported, especially mobile phones and routers. 

I also tried to make something similar using https://github.com/klzgrad/naiveproxy/blob/f51cbff6e3bac4b15d92ca03157824467446e38d/src/net/websockets/websocket_stream_test.cc in your code base, but I get lost quickly

**Comment by klzgrad** [comment]
There is no actual commitment to working on a library split from naive proxy.
