### ISSUE TITLE
Could you please providing a compiled version of Caddy v2 with naïve fork of forwardproxy?

### ISSUE THREAD

**Issue by koolwiki** [klzgrad/naiveproxy#96]
Could you please providing a compiled version of Caddy v2 with naïve fork of forwardproxy? I cann't succesfully compile it. Thank you.

**Comment by klzgrad** [comment]
What was the problem compiling?

**Comment by koolwiki** [comment]
root@myPC:~$ go get -u github.com/caddyserver/xcaddy/cmd/xcaddy
# runtime/internal/sys
/usr/lib/go-1.14/src/runtime/internal/sys/stubs.go:16:30: undefined: StackGuardMultiplierDefault
root@myPC:~$

**Comment by klzgrad** [comment]
```
$ cat /usr/share/go-1.14/src/runtime/internal/sys/zversion.go
// Code generated by go tool dist; DO NOT EDIT.

package sys

const TheVersion = `go1.14.2`
const Goexperiment = ``
const StackGuardMultiplierDefault = 1
```
Your go was probably not installed correctly.

**Comment by koolwiki** [comment]
Thank you. After reinstalling the go, it works now.

**Comment by NetHeritage** [comment]
root@naiveproxy-caddy2:~# ~/go/bin/xcaddy build --with github.com/caddyserver/forwardproxy=./forwardproxy
2020/07/18 04:08:06 [INFO] Temporary folder: /tmp/buildenv_2020-07-18-0408.627660925
2020/07/18 04:08:06 [INFO] Writing main module: /tmp/buildenv_2020-07-18-0408.627660925/main.go
2020/07/18 04:08:06 [INFO] Initializing Go module
2020/07/18 04:08:06 [INFO] exec (timeout=10s): /usr/bin/go mod init caddy
go: creating new go.mod: module caddy
2020/07/18 04:08:06 [INFO] Replace github.com/caddyserver/forwardproxy => ./forwardproxy
2020/07/18 04:08:06 [INFO] exec (timeout=10s): /usr/bin/go mod edit -replace github.com/caddyserver/forwardproxy=./forwardproxy
2020/07/18 04:08:06 [INFO] Pinning versions
2020/07/18 04:08:06 [INFO] exec (timeout=0s): /usr/bin/go get -d -v github.com/caddyserver/caddy/v2
2020/07/18 04:08:07 [INFO] Build environment ready
2020/07/18 04:08:07 [INFO] Building Caddy
2020/07/18 04:08:07 [INFO] exec (timeout=0s): /usr/bin/go build -o /root/caddy -ldflags -w -s -trimpath
go: finding github.com/caddyserver/forwardproxy latest
build caddy: cannot load github.com/caddyserver/forwardproxy: module github.com/caddyserver/forwardproxy@latest found (v0.0.0-20191002195248-247c0bafaabd, replaced by ./forwardproxy), but does not contain package github.com/caddyserver/forwardproxy
2020/07/18 04:08:08 [INFO] Cleaning up temporary folder: /tmp/buildenv_2020-07-18-0408.627660925
2020/07/18 04:08:08 [FATAL] exit status 1

**Comment by koolwiki** [comment]
Use this command: ~/go/bin/xcaddy build --with github.com/caddyserver/forwardproxy=/home/Your usename/forwardproxy

**Comment by NetHeritage** [comment]
好像依然不行
root@naiveproxy-caddy2:~# ~/go/bin/xcaddy build --with github.com/caddyserver/forwardproxy=/home/root/forwardproxy
2020/07/18 11:18:07 [INFO] Temporary folder: /tmp/buildenv_2020-07-18-1118.949389648
2020/07/18 11:18:07 [INFO] Writing main module: /tmp/buildenv_2020-07-18-1118.949389648/main.go
2020/07/18 11:18:07 [INFO] Initializing Go module
2020/07/18 11:18:07 [INFO] exec (timeout=10s): /usr/bin/go mod init caddy
go: creating new go.mod: module caddy
2020/07/18 11:18:07 [INFO] Replace github.com/caddyserver/forwardproxy => /home/root/forwardproxy
2020/07/18 11:18:07 [INFO] exec (timeout=10s): /usr/bin/go mod edit -replace github.com/caddyserver/forwardproxy=/home/root/forwardproxy
2020/07/18 11:18:07 [INFO] Pinning versions
2020/07/18 11:18:07 [INFO] exec (timeout=0s): /usr/bin/go get -d -v github.com/caddyserver/caddy/v2
2020/07/18 11:18:08 [INFO] Build environment ready
2020/07/18 11:18:08 [INFO] Building Caddy
2020/07/18 11:18:08 [INFO] exec (timeout=0s): /usr/bin/go build -o /root/caddy -ldflags -w -s -trimpath
go: finding github.com/caddyserver/forwardproxy latest
build caddy: cannot load github.com/caddyserver/forwardproxy: module github.com/caddyserver/forwardproxy@latest found (v0.0.0-20191002195248-247c0bafaabd, replaced by /home/root/forwardproxy), but does not contain package github.com/caddyserver/forwardproxy
2020/07/18 11:18:09 [INFO] Cleaning up temporary folder: /tmp/buildenv_2020-07-18-1118.949389648
2020/07/18 11:18:09 [FATAL] exit status 1

**Comment by klzgrad** [comment]
Use ~/go/bin/xcaddy build --with github.com/caddyserver/forwardproxy=**$PWD**/forwardproxy.
