### ISSUE TITLE
caddy.json 参考配置存在探测风险

### ISSUE THREAD

**Issue by seauiohruo** [klzgrad/naiveproxy#97]
现在 README 给出的参考配置 `caddy.json` 开启了 forwardproxy 插件的 `probe_resistance` 功能以隐藏 407 状态码。（参见 #60 ）

参考配置以 `secret.localhost` 作为代理验证页面，而 README 中并没有给出有关风险提示。（只有[wiki这里](https://github.com/klzgrad/naiveproxy/wiki/Caddy-Proxy-HOWTO#use-the-proxy)算有一点提示？）
如果照抄参考配置，可能会被主动探测。

比如
`curl -v https://example.naive/ -H "Host: secret.localhost"`
服务器返回 Hidden Proxy Page ，即可断定存在代理服务器。

建议在 README.md 中加入明显的提示，或者进一步修改 forwardproxy 插件，彻底隐藏 407 页面。

**Comment by klzgrad** [comment]
`secret`这个不算提示吗？

**Comment by NetHeritage** [comment]
真的会有人照抄的

**Comment by seauiohruo** [comment]
> `secret`这个不算提示吗？

secret 这个，我认为比较隐晦，至少我是没多想。还以为是固定写法。

我是（无聊）翻看 forwardproxy 的说明才意识到，probe_resistance 的参数的意义。第一次搭建时，我并没有修改这个参数。

@klzgrad  你认为这里有提示，如果你不想改，那就别改了，可能这个项目不需要对小白那么友好（

> 真的会有人照抄的

有的，比如我（

**Comment by klzgrad** [comment]
加了防呆

**Comment by me1ting** [comment]
naiveproxy的安装已经很傻瓜化了，对于手动安装的人来说，大部分人都会第一时间修改用户名和密码。
但是`probe_resistance`参数如果不查询文档，很多人是难以明白它的功能，并修改为一个自定义值。

因此在README.md中显式提醒修改该值（甚至user pass），从而提升安全性，更符合该项目的理念。
