### ISSUE TITLE
最新的84.0.4147.89-1版本服务器端 ~/go/bin/xcaddy build 时出错

### ISSUE THREAD

**Issue by ysbreh** [klzgrad/naiveproxy#98]
root@naiveproxy-caddy2:~# ~/go/bin/xcaddy build --with github.com/caddyserver/forwardproxy=./forwardproxy
2020/07/18 04:08:06 [INFO] Temporary folder: /tmp/buildenv_2020-07-18-0408.627660925
2020/07/18 04:08:06 [INFO] Writing main module: /tmp/buildenv_2020-07-18-0408.627660925/main.go
2020/07/18 04:08:06 [INFO] Initializing Go module
2020/07/18 04:08:06 [INFO] exec (timeout=10s): /usr/bin/go mod init caddy
go: creating new go.mod: module caddy
2020/07/18 04:08:06 [INFO] Replace github.com/caddyserver/forwardproxy => ./forwardproxy
2020/07/18 04:08:06 [INFO] exec (timeout=10s): /usr/bin/go mod edit -replace github.com/caddyserver/forwardproxy=./forwardproxy
2020/07/18 04:08:06 [INFO] Pinning versions
2020/07/18 04:08:06 [INFO] exec (timeout=0s): /usr/bin/go get -d -v github.com/caddyserver/caddy/v2
2020/07/18 04:08:07 [INFO] Build environment ready
2020/07/18 04:08:07 [INFO] Building Caddy
2020/07/18 04:08:07 [INFO] exec (timeout=0s): /usr/bin/go build -o /root/caddy -ldflags -w -s -trimpath
go: finding github.com/caddyserver/forwardproxy latest
build caddy: cannot load github.com/caddyserver/forwardproxy: module github.com/caddyserver/forwardproxy@latest found (v0.0.0-20191002195248-247c0bafaabd, replaced by ./forwardproxy), but does not contain package github.com/caddyserver/forwardproxy
2020/07/18 04:08:08 [INFO] Cleaning up temporary folder: /tmp/buildenv_2020-07-18-0408.627660925
2020/07/18 04:08:08 [FATAL] exit status 1

_Originally posted by @NetHeritage in https://github.com/klzgrad/naiveproxy/issues/96#issuecomment-660420920_

**Comment by NetHeritage** [comment]
root@naiveproxy-caddy2:~# ~/go/bin/xcaddy build --with github.com/caddyserver/forwardproxy=./forwardproxy
2020/07/18 12:38:26 [INFO] Temporary folder: /tmp/buildenv_2020-07-18-1238.495330201
2020/07/18 12:38:26 [INFO] Writing main module: /tmp/buildenv_2020-07-18-1238.495330201/main.go
2020/07/18 12:38:26 [INFO] Initializing Go module
2020/07/18 12:38:26 [INFO] exec (timeout=10s): &{Path:/usr/bin/go Args:[go mod init caddy] Env:[] Dir:/tmp/buildenv_2020-07-18-1238.495330201 Stdin:<nil> Stdout:0xc00000e020 Stderr:0xc00000e028 ExtraFiles:[] SysProcAttr:<nil> Process:<nil> ProcessState:<nil> ctx:<nil> lookPathErr:<nil> finished:false childFiles:[] closeAfterStart:[] closeAfterWait:[] goroutine:[] errch:<nil> waitDone:<nil>}
go: creating new go.mod: module caddy
2020/07/18 12:38:26 [INFO] Replace github.com/caddyserver/forwardproxy => ./forwardproxy
2020/07/18 12:38:26 [INFO] exec (timeout=10s): &{Path:/usr/bin/go Args:[go mod edit -replace github.com/caddyserver/forwardproxy=./forwardproxy] Env:[] Dir:/tmp/buildenv_2020-07-18-1238.495330201 Stdin:<nil> Stdout:0xc00000e020 Stderr:0xc00000e028 ExtraFiles:[] SysProcAttr:<nil> Process:<nil> ProcessState:<nil> ctx:<nil> lookPathErr:<nil> finished:false childFiles:[] closeAfterStart:[] closeAfterWait:[] goroutine:[] errch:<nil> waitDone:<nil>}
2020/07/18 12:38:26 [INFO] Pinning versions
2020/07/18 12:38:26 [INFO] exec (timeout=0s): &{Path:/usr/bin/go Args:[go get -d -v github.com/caddyserver/caddy/v2] Env:[] Dir:/tmp/buildenv_2020-07-18-1238.495330201 Stdin:<nil> Stdout:0xc00000e020 Stderr:0xc00000e028 ExtraFiles:[] SysProcAttr:<nil> Process:<nil> ProcessState:<nil> ctx:<nil> lookPathErr:<nil> finished:false childFiles:[] closeAfterStart:[] closeAfterWait:[] goroutine:[] errch:<nil> waitDone:<nil>}
2020/07/18 12:38:27 [INFO] Build environment ready
2020/07/18 12:38:27 [INFO] Building Caddy
2020/07/18 12:38:27 [INFO] exec (timeout=0s): &{Path:/usr/bin/go Args:[go build -o /root/caddy -ldflags -w -s -trimpath] Env:[SHELL=/bin/bash PWD=/root LOGNAME=root XDG_SESSION_TYPE=tty MOTD_SHOWN=pam HOME=/root LANG=en_US.UTF-8 LS_COLORS=rs=0:di=01;34:ln=01;36:mh=00:pi=40;33:so=01;35:do=01;35:bd=40;33;01:cd=40;33;01:or=40;31;01:mi=00:su=37;41:sg=30;43:ca=30;41:tw=30;42:ow=34;42:st=37;44:ex=01;32:*.tar=01;31:*.tgz=01;31:*.arc=01;31:*.arj=01;31:*.taz=01;31:*.lha=01;31:*.lz4=01;31:*.lzh=01;31:*.lzma=01;31:*.tlz=01;31:*.txz=01;31:*.tzo=01;31:*.t7z=01;31:*.zip=01;31:*.z=01;31:*.dz=01;31:*.gz=01;31:*.lrz=01;31:*.lz=01;31:*.lzo=01;31:*.xz=01;31:*.zst=01;31:*.tzst=01;31:*.bz2=01;31:*.bz=01;31:*.tbz=01;31:*.tbz2=01;31:*.tz=01;31:*.deb=01;31:*.rpm=01;31:*.jar=01;31:*.war=01;31:*.ear=01;31:*.sar=01;31:*.rar=01;31:*.alz=01;31:*.ace=01;31:*.zoo=01;31:*.cpio=01;31:*.7z=01;31:*.rz=01;31:*.cab=01;31:*.wim=01;31:*.swm=01;31:*.dwm=01;31:*.esd=01;31:*.jpg=01;35:*.jpeg=01;35:*.mjpg=01;35:*.mjpeg=01;35:*.gif=01;35:*.bmp=01;35:*.pbm=01;35:*.pgm=01;35:*.ppm=01;35:*.tga=01;35:*.xbm=01;35:*.xpm=01;35:*.tif=01;35:*.tiff=01;35:*.png=01;35:*.svg=01;35:*.svgz=01;35:*.mng=01;35:*.pcx=01;35:*.mov=01;35:*.mpg=01;35:*.mpeg=01;35:*.m2v=01;35:*.mkv=01;35:*.webm=01;35:*.ogm=01;35:*.mp4=01;35:*.m4v=01;35:*.mp4v=01;35:*.vob=01;35:*.qt=01;35:*.nuv=01;35:*.wmv=01;35:*.asf=01;35:*.rm=01;35:*.rmvb=01;35:*.flc=01;35:*.avi=01;35:*.fli=01;35:*.flv=01;35:*.gl=01;35:*.dl=01;35:*.xcf=01;35:*.xwd=01;35:*.yuv=01;35:*.cgm=01;35:*.emf=01;35:*.ogv=01;35:*.ogx=01;35:*.aac=00;36:*.au=00;36:*.flac=00;36:*.m4a=00;36:*.mid=00;36:*.midi=00;36:*.mka=00;36:*.mp3=00;36:*.mpc=00;36:*.ogg=00;36:*.ra=00;36:*.wav=00;36:*.oga=00;36:*.opus=00;36:*.spx=00;36:*.xspf=00;36: SSH_CONNECTION=34.85.108.48 55210 45.77.191.174 22 LESSCLOSE=/usr/bin/lesspipe %s %s XDG_SESSION_CLASS=user TERM=xterm LESSOPEN=| /usr/bin/lesspipe %s USER=root SHLVL=1 XDG_SESSION_ID=1 XDG_RUNTIME_DIR=/run/user/0 SSH_CLIENT=34.85.108.48 55210 22 XDG_DATA_DIRS=/usr/local/share:/usr/share:/var/lib/snapd/desktop PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin DBUS_SESSION_BUS_ADDRESS=unix:path=/run/user/0/bus SSH_TTY=/dev/pts/0 _=/root/go/bin/xcaddy GOOS= GOARCH= GOARM= CGO_ENABLED=0] Dir:/tmp/buildenv_2020-07-18-1238.495330201 Stdin:<nil> Stdout:0xc00000e020 Stderr:0xc00000e028 ExtraFiles:[] SysProcAttr:<nil> Process:<nil> ProcessState:<nil> ctx:<nil> lookPathErr:<nil> finished:false childFiles:[] closeAfterStart:[] closeAfterWait:[] goroutine:[] errch:<nil> waitDone:<nil>}
flag provided but not defined: -trimpath
usage: go build [-o output] [-i] [build flags] [packages]
Run 'go help build' for details.
2020/07/18 12:38:27 [INFO] Cleaning up temporary folder: /tmp/buildenv_2020-07-18-1238.495330201
2020/07/18 12:38:27 [FATAL] exit status 2

**Comment by NetHeritage** [comment]
root@naiveproxy-caddy2:~# ~/go/bin/xcaddy build --with github.com/caddyserver/forwardproxy=/home/root/forwardproxy
2020/07/18 11:18:07 [INFO] Temporary folder: /tmp/buildenv_2020-07-18-1118.949389648
2020/07/18 11:18:07 [INFO] Writing main module: /tmp/buildenv_2020-07-18-1118.949389648/main.go
2020/07/18 11:18:07 [INFO] Initializing Go module
2020/07/18 11:18:07 [INFO] exec (timeout=10s): /usr/bin/go mod init caddy
go: creating new go.mod: module caddy
2020/07/18 11:18:07 [INFO] Replace github.com/caddyserver/forwardproxy => /home/root/forwardproxy
2020/07/18 11:18:07 [INFO] exec (timeout=10s): /usr/bin/go mod edit -replace github.com/caddyserver/forwardproxy=/home/root/forwardproxy
2020/07/18 11:18:07 [INFO] Pinning versions
2020/07/18 11:18:07 [INFO] exec (timeout=0s): /usr/bin/go get -d -v github.com/caddyserver/caddy/v2
2020/07/18 11:18:08 [INFO] Build environment ready
2020/07/18 11:18:08 [INFO] Building Caddy
2020/07/18 11:18:08 [INFO] exec (timeout=0s): /usr/bin/go build -o /root/caddy -ldflags -w -s -trimpath
go: finding github.com/caddyserver/forwardproxy latest
build caddy: cannot load github.com/caddyserver/forwardproxy: module github.com/caddyserver/forwardproxy@latest found (v0.0.0-20191002195248-247c0bafaabd, replaced by /home/root/forwardproxy), but does not contain package github.com/caddyserver/forwardproxy
2020/07/18 11:18:09 [INFO] Cleaning up temporary folder: /tmp/buildenv_2020-07-18-1118.949389648
2020/07/18 11:18:09 [FATAL] exit status 1

**Comment by klzgrad** [comment]
Use ~/go/bin/xcaddy build --with github.com/caddyserver/forwardproxy=**$PWD**/forwardproxy.
