### ISSUE TITLE
fail to setup latest version

### ISSUE THREAD

**Issue by emiyalee1005** [klzgrad/naiveproxy#99]
I got following error when running "~/go/bin/xcaddy build --with github.com/caddyserver/forwardproxy=./forwardproxy"
The path ./forwardproxy does exist. I don't know what is going wrong

root@hi:~# ~/go/bin/xcaddy build --with github.com/caddyserver/forwardproxy=./forwardproxy
2020/07/19 05:52:41 [INFO] Temporary folder: /tmp/buildenv_2020-07-19-0552.343089064
2020/07/19 05:52:41 [INFO] Writing main module: /tmp/buildenv_2020-07-19-0552.343089064/main.go
2020/07/19 05:52:41 [INFO] Initializing Go module
2020/07/19 05:52:41 [INFO] exec (timeout=10s): /usr/bin/go mod init caddy 
go: creating new go.mod: module caddy
2020/07/19 05:52:41 [INFO] Replace github.com/caddyserver/forwardproxy => ./forwardproxy
2020/07/19 05:52:41 [INFO] exec (timeout=10s): /usr/bin/go mod edit -replace github.com/caddyserver/forwardproxy=./forwardproxy 
2020/07/19 05:52:41 [INFO] Pinning versions
2020/07/19 05:52:41 [INFO] exec (timeout=0s): /usr/bin/go get -d -v github.com/caddyserver/caddy/v2 
2020/07/19 05:52:44 [INFO] Build environment ready
2020/07/19 05:52:44 [INFO] Building Caddy
2020/07/19 05:52:44 [INFO] exec (timeout=0s): /usr/bin/go build -o /root/caddy -ldflags -w -s -trimpath 
go: finding github.com/caddyserver/forwardproxy latest
build caddy: cannot load github.com/caddyserver/forwardproxy: module github.com/caddyserver/forwardproxy@latest found (v0.0.0-20191002195248-247c0bafaabd, replaced by ./forwardproxy), but does not contain package github.com/caddyserver/forwardproxy
2020/07/19 05:52:45 [INFO] Cleaning up temporary folder: /tmp/buildenv_2020-07-19-0552.343089064
2020/07/19 05:52:45 [FATAL] exit status 1

**Comment by klzgrad** [comment]
Use ~/go/bin/xcaddy build --with github.com/caddyserver/forwardproxy=**$PWD**/forwardproxy. I fixed the README.
